### ISSUE TITLE
[NONLTO_X] "dangling-pointer" warnings in mkfitcore

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#43380] opened 2023-11-24 10:55 UTC
GCC emits dangling-pointer warnings in NONLTO builds (as well as LTO builds for ppc64le, but not for x86 or aarch64):

```
In file included from /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.cc:476:
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc: In function 'void parsAndErrPropFromPathL_impl(const Tf&, const Ti&, TfLL1&, const float*, const Tf1&, TfLLL&, int, int, int, const mkfit::PropagationFlags&) [with Tf = Matriplex::Matriplex<float, 6, 1, 4>; Ti = Matriplex::Matriplex<int, 1, 1, 4>; TfLL1 = Matriplex::Matriplex<float, 6, 1, 4>; TfLLL = Matriplex::Matriplex<float, 6, 6, 4>; Tf1 = Matriplex::Matriplex<float, 1, 1, 4>]':
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:250:34: warning: dangling pointer to 'cosPin.299' may be used [-Wdangling-pointer=]
   250 |     jacCCS2Curv(n, 3, 1) = cosPin[n - nmin];
      |                            ~~~~~~^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:72:9: note: 'cosPin.299' declared here
   72 |   float cosPin[nmax - nmin];
      |         ^~~~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:98:29: warning: dangling pointer to 'cosPin.299' may be used [-Wdangling-pointer=]
    98 |     const float t11 = cosPin[n - nmin] * sinT[n - nmin];
      |                       ~~~~~~^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:72:9: note: 'cosPin.299' declared here
   72 |   float cosPin[nmax - nmin];
      |         ^~~~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:81:22: warning: dangling pointer to 'cosPin.299' may be used [-Wdangling-pointer=]
    81 |     cosPin[n - nmin] = std::cos(inPar(n, 4, 0));
      |     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:72:9: note: 'cosPin.299' declared here
   72 |   float cosPin[nmax - nmin];
      |         ^~~~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:249:35: warning: dangling pointer to 'sinPin.300' may be used [-Wdangling-pointer=]
   249 |     jacCCS2Curv(n, 3, 0) = -sinPin[n - nmin];
      |                             ~~~~~~^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:73:9: note: 'sinPin.300' declared here
   73 |   float sinPin[nmax - nmin];
      |         ^~~~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:99:29: warning: dangling pointer to 'sinPin.300' may be used [-Wdangling-pointer=]
    99 |     const float t12 = sinPin[n - nmin] * sinT[n - nmin];
      |                       ~~~~~~^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:73:9: note: 'sinPin.300' declared here
   73 |   float sinPin[nmax - nmin];
      |         ^~~~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:82:22: warning: dangling pointer to 'sinPin.300' may be used [-Wdangling-pointer=]
    82 |     sinPin[n - nmin] = std::sin(inPar(n, 4, 0));
      |     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:73:9: note: 'sinPin.300' declared here
   73 |   float sinPin[nmax - nmin];
      |         ^~~~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:266:53: warning: dangling pointer to 'cosPout.301' may be used [-Wdangling-pointer=]
   266 |     jacCurv2CCS(n, 0, 4) = -cosT[n - nmin] * cosPout[n - nmin];
      |                                              ~~~~~~~^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:74:9: note: 'cosPout.301' declared here
   74 |   float cosPout[nmax - nmin];
      |         ^~~~~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:100:30: warning: dangling pointer to 'cosPout.301' may be used [-Wdangling-pointer=]
   100 |     const float t21 = cosPout[n - nmin] * sinT[n - nmin];
      |                       ~~~~~~~^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:74:9: note: 'cosPout.301' declared here
   74 |   float cosPout[nmax - nmin];
      |         ^~~~~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:83:23: warning: dangling pointer to 'cosPout.301' may be used [-Wdangling-pointer=]
    83 |     cosPout[n - nmin] = std::cos(outPar(n, 4, 0));
      |     ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:74:9: note: 'cosPout.301' declared here
   74 |   float cosPout[nmax - nmin];
      |         ^~~~~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:265:36: warning: dangling pointer to 'sinPout.302' may be used [-Wdangling-pointer=]
   265 |     jacCurv2CCS(n, 0, 3) = -sinPout[n - nmin];
      |                             ~~~~~~~^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:75:9: note: 'sinPout.302' declared here
   75 |   float sinPout[nmax - nmin];
      |         ^~~~~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:101:30: warning: dangling pointer to 'sinPout.302' may be used [-Wdangling-pointer=]
   101 |     const float t22 = sinPout[n - nmin] * sinT[n - nmin];
      |                       ~~~~~~~^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:75:9: note: 'sinPout.302' declared here
   75 |   float sinPout[nmax - nmin];
      |         ^~~~~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:84:23: warning: dangling pointer to 'sinPout.302' may be used [-Wdangling-pointer=]
    84 |     sinPout[n - nmin] = std::sin(outPar(n, 4, 0));
      |     ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:75:9: note: 'sinPout.302' declared here
   75 |   float sinPout[nmax - nmin];
      |         ^~~~~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:266:33: warning: dangling pointer to 'cosT.303' may be used [-Wdangling-pointer=]
   266 |     jacCurv2CCS(n, 0, 4) = -cosT[n - nmin] * cosPout[n - nmin];
      |                             ~~~~^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:76:9: note: 'cosT.303' declared here
   76 |   float cosT[nmax - nmin];
      |         ^~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:246:49: warning: dangling pointer to 'cosT.303' may be used [-Wdangling-pointer=]
   246 |     jacCCS2Curv(n, 0, 5) = inChg(n, 0, 0) * cosT[n - nmin] * inPar(n, 3, 0);
      |                                             ~~~~^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:76:9: note: 'cosT.303' declared here
   76 |   float cosT[nmax - nmin];
      |         ^~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:121:28: warning: dangling pointer to 'cosT.303' may be used [-Wdangling-pointer=]
   121 |     const float v11 = -cosT[n - nmin] * u12;
      |                        ~~~~^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:76:9: note: 'cosT.303' declared here
   76 |   float cosT[nmax - nmin];
      |         ^~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:85:20: warning: dangling pointer to 'cosT.303' may be used [-Wdangling-pointer=]
    85 |     cosT[n - nmin] = std::cos(inPar(n, 5, 0));
      |     ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:76:9: note: 'cosT.303' declared here
   76 |   float cosT[nmax - nmin];
      |         ^~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:269:32: warning: dangling pointer to 'sinT.304' may be used [-Wdangling-pointer=]
   269 |     jacCurv2CCS(n, 2, 4) = sinT[n - nmin];
      |                            ~~~~^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:77:9: note: 'sinT.304' declared here
   77 |   float sinT[nmax - nmin];
      |         ^~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:245:49: warning: dangling pointer to 'sinT.304' may be used [-Wdangling-pointer=]
   245 |     jacCCS2Curv(n, 0, 3) = inChg(n, 0, 0) * sinT[n - nmin];
      |                                             ~~~~^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:77:9: note: 'sinT.304' declared here
   77 |   float sinT[nmax - nmin];
      |         ^~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:95:44: warning: dangling pointer to 'sinT.304' may be used [-Wdangling-pointer=]
    95 |     const float qbp = inChg(n, 0, 0) * sinT[n - nmin] * inPar(n, 3, 0);
      |                                        ~~~~^
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:77:9: note: 'sinT.304' declared here
   77 |   float sinT[nmax - nmin];
      |         ^~~~
  /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:86:20: warning: dangling pointer to 'sinT.304' may be used [-Wdangling-pointer=]
    86 |     sinT[n - nmin] = std::sin(inPar(n, 5, 0));
      |     ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/e1e0e062aff59b3bd39ce61ae5cef897/opt/cmssw/el8_amd64_gcc12/cms/cmssw/CMSSW_14_0_NONLTO_X_2023-11-23-2300/src/RecoTracker/MkFitCore/src/PropagationMPlex.icc:77:9: note: 'sinT.304' declared here
   77 |   float sinT[nmax - nmin];
      |         ^~~~
```

[full log](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_14_0_NONLTO_X_2023-11-23-2300/RecoTracker/MkFitCore).

The warning is described in GCC source code as "The use is one of a dangling pointer if a clobber of the variable [the pointer points to] has not been found before the function exit point".  In this case it seems to be false-positive, but worth checking anyway.

**Comment by slava77** [comment] 2023-11-24 17:06
type tracking

**Comment by slava77** [comment] 2023-11-24 17:06
@osschar

**Comment by slava77** [comment] 2023-11-24 17:09
@iarspider 
just to be sure, is this recent? 
When it was last not seen and was CMSSW_14_0_NONLTO_X_2023-11-23-2300 the first time this appeared?

**Comment by iarspider** [comment] 2023-11-24 17:14
@slava77 [this](https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/el8_amd64_gcc12/CMSSW_14_0_NONLTO_X_2023-11-19-0000/RecoTracker/MkFitCore) seems to be the earliest occurrence.

**Comment by slava77** [comment] 2023-11-24 17:19
OK, if 11-19-0000 is the first, #43146 would be the reason (merged Nov 18)

**Comment by osschar** [comment] 2023-11-25 23:37
Yeah, I saw those when building ... and they make no sense, well, at least to me :) @gartung @makortel do you have any insight on this?

**Comment by smuzaffar** [comment] 2023-11-26 18:09
Dropping `static` from https://github.com/cms-sw/cmssw/blob/master/RecoTracker/MkFitCore/src/PropagationMPlex.icc#L58  (`static inline void helixAtRFromIterativeCCS_impl(...`) fixes the compilation warning. No idea what is the difference between `static inline` and `inline` in this case.

**Comment by makortel** [comment] 2023-11-26 20:04
> No idea what is the difference between `static inline` and `inline` in this case.

As these are standalone functions, the difference _should_ be that
* `inline`: the definition of the function is allowed to exist in multiple object files, and the linker effectively picks one of those definitions (in addition it gives a hint to the compiler about actual inlining)
* `static`:  each object file gets a separate definition of the function (and with `inline` there is again a hint for the compiler)

Why that would make a difference for this warning, I have no idea (also the `PropagationMPlex.icc` seems to be `#include`d only from one file, so the practical impact of `static` should be negligible). Maybe somehow related to how GCC implements `static` functions?

**Comment by osschar** [comment] 2023-11-27 21:23
Thank you everybody! Should I replace static with a unnamed namespace and make a PR? Or just remove static?

What do I do with the other 3 static inline function templates in the same file that don't produce this warning?

**Comment by osschar** [comment] 2023-11-27 21:40
Duh, anon namespace produces the same error.

**Comment by makortel** [comment] 2023-11-27 22:31
I'd remove the static.

Given the strange behavior of GCC, if someone would be willing to do the work, I think it could be worth it to try to craft a small reproducer and open a ticket with GCC. (perhaps already going for smaller reproducer could reveal something)

**Comment by smuzaffar** [comment] 2023-12-08 10:16
I have opened https://github.com/cms-sw/cmssw/issues/43380 to fix this

**Closed** 2023-12-08 17:25 UTC
Labels: reconstruction-pending, pending-signatures, tracking
