### ISSUE TITLE
testGetPayloadData (getPayloadData.py) unit failure  

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#34512] opened 2021-07-16 03:13 UTC
**There is a unit failure In CMSSW_12_0_X_2021-07-15-2300**
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-07-15-2300/unitTestLogs/CondCore/Utilities#/181-181
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'cond::BasicPayload'
getPayloadData.py --discover test not passed... found no entries
---> test testGetPayloadData had ERRORS

**This can also be reproduced locally:**
 cmsrel CMSSW_12_0_X_2021-07-15-2300
 cd CMSSW_12_0_X_2021-07-15-2300/src
 cmsenv
 git cms-addpkg CondCore/Utilities
 cd CondCore/Utilities/test/
 source test_getPayloadData.sh

**Comment by qliphy** [comment] 2021-07-16 03:14
assign db

**Comment by qliphy** [comment] 2021-07-16 03:14
@mmusich  Please have a look. Thanks!

**Comment by mmusich** [comment] 2021-07-16 08:05
@qliphy just about the second part of your report, that's not correct

> The issue was not there in previous IB. However, there are other errors seem not to be reported in IB:
(I have tested both CMSSW_12_0_X_2021-07-15-1100 and CMSSW_12_0_X_2021-07-14-1100 )
---> Passed test of 'getPayloadData.py --plugin pluginBasicPayload_PayloadInspector --plot plot_BasicPayload_data0_withInput --tag BasicPayload_v0 --input_params {"Factor":"1","Offset":"2","Scale":"3"} --time_type Run --iovs {"start_iov": "1", "end_iov": "101"} --db Prod --test'
Traceback (most recent call last):
File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-07-14-1100/bin/slc7_amd64_gcc900/getPayloadData.py", line 278, in
result = deserialize_iovs(args.db, args.plugin, args.plot, tags, args.time_type, input_params)
File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-07-14-1100/bin/slc7_amd64_gcc900/getPayloadData.py", line 48, in decorated
result = f( *fargs, **fkwargs )
File "/cvmfs/cms-ib.cern.ch/week1/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-07-14-1100/bin/slc7_amd64_gcc900/getPayloadData.py", line 106, in deserialize_iovs
success = plot.process(db_name, tags)
RuntimeError: An exception of category 'ConditionDatabase' occurred.
Exception Message:
Tag "BasicPayload" has not been found in the database. from IOVProxy::load

This is actually expected, because the test is checking for failures when being passed wrong input:
https://github.com/cms-sw/cmssw/blob/11928c0272ed5b3750ef43723ece1056e14ea5cc/CondCore/Utilities/test/test_getPayloadData.sh#L63-L73

Please remove that part from the report, because it's very confusing!

**Comment by qliphy** [comment] 2021-07-16 08:09
@mmusich ok, thanks.  I will remove that part.

**Comment by mmusich** [comment] 2021-07-16 08:17
About the issue in the last IB, I think I understand the cause.
In general, if there are no changes in any of the plugins to be "discovered" (as it has been the case until now) the script will look for *all* the plugins available, see e.g. here:

 https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-07-15-1100/unitTestLogs/CondCore/Utilities#/172.

But specifically in `CMSSW_12_0_X_2021-07-15-2300` two PRs changing plugins in `CondCore/SiPixelPlugins` have been merged (#34375 and #34457), and as a consequence the script only discovers the plugins in that folder, see:

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-07-15-2300/unitTestLogs/CondCore/Utilities#/172

as a result the specific plugin used for the test is missing and the test fails.
I suspect that the test will restart to work at the next IB, but again every time someone updates the plugins it will fail again.
I think this is a by-product of the behavior introduced in https://github.com/cms-sw/cmssw/pull/34257/.
I'll try to think how to avoid that, but suggestions are welcome.

**Comment by mmusich** [comment] 2021-07-16 10:07
see https://github.com/cms-sw/cmssw/pull/34515

**Closed** 2021-07-18 11:13 UTC
Labels: db-pending, pending-signatures
