### ISSUE TITLE
SonicTriton test failures in GPU IBs

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#34547] opened 2021-07-19 13:11 UTC
The SonicTriton tests have been failing in GPU IBs at least since CMSSW_12_0_GPU_X_2021-07-12-2300 with
```
%MSG-i TritonService:  AfterModConstruction 19-Jul-2021 01:07:23 UTC pre-events
cmsTriton -P -1 -p 6853 -v -n triton_server_instance_d3efd696-cd2d-475e-8e51-23ac1f50bc1b -m /cvmfs/cms-ib.cern.ch/nweek-02690/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_GPU_X_2021-07-18-2300/external/slc7_amd64_gcc900/data/HeterogeneousCore/SonicTriton/data/models/gat_test/config.pbtxt -t /pool/condor/dir_17213/1c95b347-fce9-487f-a68b-dc9f5a9f4ae9 start
%MSG
%MSG-i TritonService:  AfterModConstruction 19-Jul-2021 01:07:26 UTC pre-events
CMS_TRITON_GRPC_PORT: 8001
ERROR:   container cleanup failed: no instance found with name triton_server_instance_d3efd696-cd2d-475e-8e51-23ac1f50bc1b
FATAL:   container creation failed: unable to add /pool/condor/dir_17213/1c95b347-fce9-487f-a68b-dc9f5a9f4ae9/-B to mount list: destination must be an absolute path

FATAL:   failed to start instance: while running /usr/libexec/singularity/bin/starter: exit status 255
Error for command "stop": no instance found

Usage:
  singularity [global options...] instance stop [stop options...] [instance]

Run 'singularity --help' for more detailed usage information.
mv: cannot stat 'log_triton_server_instance_d3efd696-cd2d-475e-8e51-23ac1f50bc1b.log': No such file or directory
Retrying after container issue...
ERROR:   container cleanup failed: no instance found with name triton_server_instance_d3efd696-cd2d-475e-8e51-23ac1f50bc1b
FATAL:   container creation failed: unable to add /pool/condor/dir_17213/1c95b347-fce9-487f-a68b-dc9f5a9f4ae9/-B to mount list: destination must be an absolute path

FATAL:   failed to start instance: while running /usr/libexec/singularity/bin/starter: exit status 255
Error for command "stop": no instance found

Usage:
  singularity [global options...] instance stop [stop options...] [instance]

Run 'singularity --help' for more detailed usage information.
mv: cannot stat 'log_triton_server_instance_d3efd696-cd2d-475e-8e51-23ac1f50bc1b.log': No such file or directory
Retrying after container issue...
ERROR:   container cleanup failed: no instance found with name triton_server_instance_d3efd696-cd2d-475e-8e51-23ac1f50bc1b
FATAL:   container creation failed: unable to add /pool/condor/dir_17213/1c95b347-fce9-487f-a68b-dc9f5a9f4ae9/-B to mount list: destination must be an absolute path

FATAL:   failed to start instance: while running /usr/libexec/singularity/bin/starter: exit status 255
Error for command "stop": no instance found

Usage:
  singularity [global options...] instance stop [stop options...] [instance]

Run 'singularity --help' for more detailed usage information.
mv: cannot stat 'log_triton_server_instance_d3efd696-cd2d-475e-8e51-23ac1f50bc1b.log': No such file or directory
Retrying after container issue...
Error from Singularity

%MSG
----- Begin Fatal Exception 19-Jul-2021 01:07:26 UTC-----------------------
An exception of category 'FallbackFailed' occurred while
   [0] Calling beginJob
Exception Message:
Starting the fallback server failed with exit code 65280
----- End Fatal Exception -------------------------------------------------

---> test TestHeterogeneousCoreSonicTritonProducerCPU had ERRORS
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_GPU_X_2021-07-18-2300/unitTestLogs/HeterogeneousCore/SonicTriton#/

**Comment by makortel** [comment] 2021-07-19 13:11
assign heterogeneous

**Comment by makortel** [comment] 2021-07-19 13:11
@kpedro88 please take a look

**Comment by kpedro88** [comment] 2021-07-20 21:01
@makortel I see this in `CMSSW_12_0_GPU_X_2021-07-18-2300`, but not in `CMSSW_12_0_GPU_X_2021-07-19-2300`. So it may have been incidentally fixed by #34508, but I'm not sure how.

`CMSSW_12_0_GPU_X_2021-07-19-2300` has a different failure in the GPU test, though:
```
unable to register CUDA shared memory region: 26489_input5: failed to register CUDA shared memory region '26489_input5'
```

However, I can't reproduce the failures from either IB locally, so it's hard for me to debug further. Is there a way to access a machine equivalent to the one that runs the GPU IB tests?

**Comment by makortel** [comment] 2021-07-28 21:38
CMSSW_12_0_GPU_X_2021-07-27-2300 reports only the following without any clear prior printouts what could be going on
```
===== Test "TestHeterogeneousCoreSonicTritonProducerGPU" ====
GPU 0: Tesla V100S-PCIE-32GB (UUID: GPU-85a4a9af-34fa-d34e-ff49-a574a53d2c85)
has GPU
has singularity
has unprivileged user namespace support
GPU 0: Tesla V100S-PCIE-32GB (UUID: GPU-85a4a9af-34fa-d34e-ff49-a574a53d2c85)
%MSG-i TritonService:  (NoModuleName) 28-Jul-2021 01:05:47 UTC pre-events
...
%MSG-i TritonGraphProducer:  TritonGraphProducer:TritonGraphProducerGRPC  28-Jul-2021 01:06:01 UTC Run: 1 Event: 1
produce() time: 463
%MSG
----- Begin Fatal Exception 28-Jul-2021 01:06:01 UTC-----------------------
An exception of category 'TritonFailure' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'p'
   [2] Calling method for module TritonGraphProducer/'TritonGraphProducer'
Exception Message:
unable to register CUDA shared memory region: 8831_input3: failed to register CUDA shared memory region '8831_input3'
----- End Fatal Exception -------------------------------------------------

=============================================
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_GPU_X_2021-07-27-2300/unitTestLogs/HeterogeneousCore/SonicTriton#/

One warning
```
%MSG-i TritonService:  AfterModConstruction 28-Jul-2021 01:06:01 UTC pre-events
CMS_TRITON_GRPC_PORT: 8004
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (493) bind mounts

INFO:    instance started successfully
server is ready!

%MSG
```
stood out but I don't know how relevant it is.

**Comment by kpedro88** [comment] 2021-07-28 22:19
@makortel yes, I noted this failure in my [previous comment](https://github.com/cms-sw/cmssw/issues/34547#issuecomment-883705746), in which I also said:
> However, I can't reproduce the failures from either IB locally, so it's hard for me to debug further. Is there a way to access a machine equivalent to the one that runs the GPU IB tests?

The warning from Singularity can be ignored.

**Comment by kpedro88** [comment] 2021-09-17 23:29
Updates on this issue: I was given instructions to access the GPU machines used for IB tests (requesting a GPU worker node on lxplus condor and then using `condor_ssh_to_job`).

If I try to run on the bare metal worker node, I get this message:
```
ERROR: This container was built for NVIDIA Driver Release 465.19 or later, but
       version 460.27.04 was detected and compatibility mode is UNAVAILABLE.

       [[CUDA Driver UNAVAILABLE (compatibility check timed out)]]
```

I tried on two different nodes, a T4 and a V100 (both datacenter GPUs). They both had the noted driver version which corresponds to CUDA 11.2, while CMSSW is on CUDA 11.4.2. Datacenter GPUs have forward compatibility for CUDA, but not for the drivers (at least, this is my current understanding).

My first idea to address driver incompatibilities: just add another check for a recent-enough driver version in the test script, and skip the GPU test if it isn't available. This isn't too difficult to implement.

In the longer term, we need to think more about the strategy for dealing with old driver versions on the grid. (It may involve manually building server images for different driver versions.)

However, all of this is actually secondary to the real problem. When I run the tests inside Singularity, starting the container with `cmssw-cc7 --nv`, I instead get:
```
WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use Docker with NVIDIA Container Toolkit to start this container; see
   https://github.com/NVIDIA/nvidia-docker.
```

This explains the observed failure mentioned above: GPU shared memory can't be accessed if the server doesn't know how to access the GPU.

The problem here seems to be that the Nvidia libraries are not mounted inside the container by Singularity. The container entrypoint checks this to determine if the GPU is available: https://github.com/triton-inference-server/server/blob/v2.11.0/nvidia_entrypoint.sh#L46, and indeed there is no file matching `libcuda.so*` inside the container. Luckily, our friendly neighborhood Singularity expert just came up with a workaround for this the other day: https://github.com/hpcng/singularity/issues/5759#issuecomment-919523970

**Comment by kpedro88** [comment] 2021-09-17 23:30
See: #35328

**Comment by fwyzard** [comment] 2021-09-18 05:37
Datacenter GPUs do have forward compatibility for the NVIDIA drivers; this
is already being properly set up and used by the CMSSW environment.

**Closed** 2021-09-24 09:43 UTC
Labels: pending-signatures, heterogeneous-pending
