### ISSUE TITLE
Problem with edmConfigDump on reco step

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23116] opened 2018-05-02 15:11 UTC
While checking for a Tier0 crash, I realized that the edmConfigDump expansion of the provided PSet.py for prompt reco (CMSSW_10_1_2_patch2) is unrunnable:

edmConfigDump PSet.py > ! full.py ; cmsRun full.py 

----- Begin Fatal Exception 02-May-2018 16:53:19 CEST-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named full.py
Exception Message:
python encountered the error: <type 'exceptions.NameError'>
name 'inf' is not defined
----- End Fatal Exception -------------------------------------------------

This issue is present also in the expansion of regular configurations produced through cmsDriver.py in recent releases.

I have tracked this as due to the expansion of the fragment

https://github.com/cms-sw/cmssw/blob/master/RecoEgamma/ElectronIdentification/python/Identification/mvaElectronID_Fall17_iso_V1_cff.py

specifically for the PSet clipLower and clipUpper, where several inf and -inf are put in the output, and cause the configuration to become unrunnable.

**Comment by fabiocos** [comment] 2018-05-02 15:11
@slava77 @perrotta FYI

**Comment by slava77** [comment] 2018-05-02 15:57
assign core

as we discussed in the skype call, the problem is lack of support for syntax like ```float('Inf')``` in the config dump. Ideally, the configDump should produce it back instead of a plain text ```inf```, which is not recognized by the parser

**Comment by Dr15Jones** [comment] 2018-05-03 17:55
fixed by #23133

**Comment by fabiocos** [comment] 2018-05-04 14:45
@Dr15Jones thank you Chris, I confirm that with this PR now the classical step3 configuration is executable again:

`process.mvaEleID_Fall17_iso_V1_producer_config = cms.PSet(
    beamSpot = cms.InputTag("offlineBeamSpot"),
    clipLower = cms.vdouble(
        -float('inf'), -float('inf'), -1.0, -float('inf'), -float('inf'), 
        -float('inf'), -float('inf'), -float('inf'), -float('inf'), -float('inf'), 
        -1.0, -float('inf'), -float('inf'), -float('inf'), -float('inf'), 
        -float('inf'), -float('inf'), -0.06, -0.6, -0.2, 
        -float('inf'), -float('inf'), -float('inf'), -float('inf'), -float('inf')
    ),
    clipUpper = cms.vdouble(
        float('inf'), float('inf'), 2.0, 5.0, float('inf'), 
        float('inf'), float('inf'), float('inf'), 10.0, 200.0, 
        float('inf'), float('inf'), float('inf'), float('inf'), 20.0, 
        20.0, float('inf'), 0.06, 0.6, 0.2, 
        float('inf'), float('inf'), float('inf'), float('inf'), float('inf')
    ),
`

**Closed** 2018-05-04 14:45 UTC
Labels: core-pending, pending-signatures
