### ISSUE TITLE
Unit test failing in FWCore/TFWLiteSelector in ROOT6 IB (ROOT master)

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#32162] opened 2020-11-17 16:23 UTC
There is a consistent failure in ROOT master IB

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_ROOT6_X_2020-11-16-2300/unitTestLogs/FWCore/TFWLiteSelector#/255-255

where a ROOT macro is creating a tmp file and it's not always properly created.
It's either 
https://github.com/cms-sw/cmssw/blob/master/FWCore/TFWLiteSelector/test/proof_thing2_sel.C
or 
https://github.com/cms-sw/cmssw/blob/master/FWCore/TFWLiteSelector/test/proof_thing_sel.C

Lets have it as an issue

**Comment by makortel** [comment] 2020-11-17 17:24
assign core

**Comment by dan131riley** [comment] 2020-11-17 18:12
I'm guessing that the files are getting overwritten by different processes.  Different builds are supposed to use different temporary directories, but there's a trivial bug that prevents this from actually happening.  Fix is in #32166

**Closed** 2020-11-18 00:30 UTC
Labels: core-pending, pending-signatures

**Comment by makortel** [comment] 2020-11-24 15:15
Following comment https://github.com/cms-sw/cmssw/pull/32166#issuecomment-731852649 this issue could be re-opened

On the other hand it appears to be a duplicate of https://github.com/cms-sw/cmssw/issues/31233 so maybe it is best to move further discussion there.
