### ISSUE TITLE
MVA xml file reading in createGBRForest is longest time in initializing PAT job

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#38089] opened 2022-05-25 18:25 UTC
Profiling workflow 11834.21 step 4 showed that `createGBRForest` was the largest contributor to the time it takes to startup the job.

```
            2.1  .........       1.14 / 1.19         PhotonMVAEstimator::PhotonMVAEstimator(edm::ParameterSet const&) [464]
            8.3  .........       4.54 / 4.54         ElectronMVAEstimatorRun2::init(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) [102]
[50]       12.4       6.84       0.00 / 6.84       createGBRForest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)
```

In other cases ( #34908 ) this was solved by converting the xml files into ROOT files. It looks like it would be good to do the same for the Electron and Photon ID (?) cases as well.

**Comment by Dr15Jones** [comment] 2022-05-25 18:25
assign reconstruction

**Comment by makortel** [comment] 2022-05-25 18:39
Does this issue have any overlap with #37867?

**Comment by jpata** [comment] 2022-06-13 11:29
-reconstruction
- duplicate of https://github.com/cms-sw/cmssw/issues/37867

**Comment by makortel** [comment] 2023-05-02 16:40
@cmsbuild, please close

**Closed** 2023-05-02 16:40 UTC
Labels: reconstruction-rejected, pending-signatures
