### ISSUE TITLE
JetFlavourClustering throws an unknown exception

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#21668] opened 2017-12-08 14:24 UTC
In the integration build CMSSW_10_0_X_2017-12-07-1100 for workflow 1326.0 on step3, the job failed with the log message
```
----- Begin Fatal Exception 07-Dec-2017 19:24:43 CET-----------------------
An exception of category 'Unknown' occurred while
   [0] Processing  Event run: 1 lumi: 2 event: 101 stream: 2
   [1] Running path 'MINIAODSIMoutput_step'
   [2] Prefetching for module PoolOutputModule/'MINIAODSIMoutput'
   [3] Prefetching for module PATJetSlimmer/'slimmedJetsPuppi'
   [4] Prefetching for module PATJetSelector/'selectedPatJetsPuppi'
   [5] Prefetching for module PATJetProducer/'patJetsPuppi'
   [6] Calling method for module JetFlavourClustering/'patJetFlavourAssociationPuppi'
Exception Message:
An exception of unknown type was thrown.
----- End Fatal Exception -------------------------------------------------
```
That message happens if a module throws an exception which inherits from neither `std::exception` or `cms::Exception`.

**Comment by Dr15Jones** [comment] 2017-12-08 14:25
assign analysis, reconstruction

**Comment by slava77** [comment] 2017-12-08 14:41
"nice"
now it has popped up in relvals
and is getting out of the private thread addressing an issue in 
https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/4626.html

@arizzi @ferencek 

For the case in 94X I've spent at least half a day trying to make it crash but I couldn't.

@Dr15Jones do you have a reproducible case here or is it a single report?

**Comment by Dr15Jones** [comment] 2017-12-08 15:01
It only failed that once and subsequent IBs have run fine.

**Comment by Dr15Jones** [comment] 2017-12-08 15:09
I did a quick grep through fastjet code for `throw`. Turns out it throws its own `Error` class as its exception:
https://github.com/cms-externals/fastjet/blob/master/include/fastjet/Error.hh

That class does not inherit from `std::exception`. So it looks like `JetFlavourClustering` should try to catch exceptions of type `fastjet::Error` and convert it to a `cms::Exception` so we can see the message.

**Comment by arizzi** [comment] 2017-12-12 16:07
anyhow the additonal information circulated in the other thread was that the printout is :+1: 
<pre>
fastjet::Error:  *** CRITICAL INTERNAL FASTJET ERROR *** CONTACT THE
AUTHORS *** trying to recomine an object that has previsously been
recombined

</pre>

(given that we cannot reproduce I suspect there is something not threadsafe in fastjet... and I've no clue how to debug that)

**Comment by Dr15Jones** [comment] 2017-12-12 16:09
How I'd start to look at a thread-safety issue would be to find where in fastjet that printout is done and then checking to see if there is a global or static variable used as part of that calculation.

**Comment by slava77** [comment] 2017-12-12 16:25
On 12/12/17 8:09 AM, Chris Jones wrote:
> How I'd start to look at a thread-safety issue would be to find where in
> fastjet that printout is done and then checking to see if there is a
> global or static variable used as part of that calculation.

Can the static analyzer be run on it?

.. perhaps this is something to be done for all compiled externals

**Comment by arizzi** [comment] 2017-12-12 16:30
it seems to be printout in ClusterSequence.cc and at a quick glance it seems there is a datamember (_history) that is modified by several functions and in a particular call it finds in there something unexpected.

How are we sure that we have no two threads calling ClusterSequence at the same time acting on the same _history datamember?

**Comment by Dr15Jones** [comment] 2017-12-12 16:38
> How are we sure that we have no two threads calling ClusterSequence at the same time acting on the same _history datamember?

The check would be to trace back all constructions of ClusterSequence to see if they are associated with a global or static. Unfortunately, doing a search on github often misses many matches.

**Comment by Dr15Jones** [comment] 2017-12-12 16:43
Looks like
https://github.com/cms-externals/fastjet/blob/77e18236f42023d23f6493a5c2d023f3f5f22be0/include/fastjet/ClusterSequence.hh#L759

should be changed to `std::atomic<bool> _first_time;` However, that seems extremely unlikely to have caused this problem.

**Comment by arizzi** [comment] 2017-12-12 16:44
it seems ClusterSequence is not even reused across events... so nothing
obviously bad..

**Comment by slava77** [comment] 2017-12-12 16:50
On 12/12/17 8:43 AM, Chris Jones wrote:
> Looks like
> https://github.com/cms-externals/fastjet/blob/77e18236f42023d23f6493a5c2d023f3f5f22be0/include/fastjet/ClusterSequence.hh#L759
> 

IIUC, CMSSW distribution is using this version
https://github.com/cms-externals/fastjet/blob/cms/v3.1.0/include/fastjet/ClusterSequence.hh#L769

**Comment by Dr15Jones** [comment] 2017-12-12 17:56
Looking at the module code, I do not see why this needs to be `new`ed nor why fjClusterSeq_ is a member data:

https://github.com/cms-sw/cmssw/blob/a1a699103d53ed00ae87f2a2578dd7e4b6bd0b5b/PhysicsTools/JetMCAlgos/plugins/JetFlavourClustering.cc#L328

If this problem is because of a memory overwrite (instead of thread-safety issue in fastjet) making the object on the stack might avoid the problem.

**Comment by Dr15Jones** [comment] 2017-12-12 18:03
So the comment just before the throw
https://github.com/cms-externals/fastjet/blob/cms/v3.1.0/src/ClusterSequence.cc#L1503

seems to imply that this failure is expected under normal operation and is dependent on the strategy used.

**Comment by slava77** [comment] 2017-12-12 18:14
On 12/12/17 10:03 AM, Chris Jones wrote:
> So the comment just before the throw
> https://github.com/cms-externals/fastjet/blob/cms/v3.1.0/src/ClusterSequence.cc#L1503
> 
> seems to imply that this failure is expected under normal operation and
> is dependent on the strategy used.
> 

I guess you are suggesting to catch this.
Is that so?

**Comment by Dr15Jones** [comment] 2017-12-12 19:27
My only suggestion is this may not be a thread-safety or memory related problem, but be intrinsic with the strategy being used by fastjet.

**Comment by arizzi** [comment] 2017-12-12 19:42
well but why it is not reproducible then?

Il 12 dic 2017 8:28 PM, "Chris Jones" <notifications@github.com> ha scritto:

**Comment by Dr15Jones** [comment] 2017-12-12 19:57
Are there any random numbers used by fastjet or by algorithms feeding data into fastjet?

**Comment by ferencek** [comment] 2017-12-13 14:37
As far as I know, there shouldn't be any random numbers involved here. A collection of particles is fed into FastJet and then clustered.

**Comment by rappoccio** [comment] 2017-12-14 18:21
Sorry for the delay, catching up here. There is some random numbers thrown for the area calculation, but we set the seed deterministically so it should be reproducible in that case.

**Comment by ferencek** [comment] 2017-12-14 21:52
@rappoccio, but there is no jet area calculation in this case. Ghost partons are formed "by hand" by taking their momentum and scaling it down by a large factors. These ghosts are then clustered together with jet contituents so there is no randomness in this procedure.

Are there any random numbers involved in the Puppi algorithm? Naively I would not expect any.

**Comment by rappoccio** [comment] 2017-12-15 02:36
Good point. I'm not sure then... may then be threading.

**Comment by arizzi** [comment] 2017-12-15 07:23
could it be some numerical instability due to the ghost procedure? did anyone report to the fastjet authors? (even if we do not have a recipe to reproduce they may have some ideas..)

**Comment by ferencek** [comment] 2017-12-15 10:53
One possible hint is that it only happens with Puppi jets or at least I haven't heard of any non-Puppi cases. So possibly some feature in the momenta of Puppi candidates triggers a problem in FastJet.

**Comment by rappoccio** [comment] 2017-12-15 14:14
It would probably be best to find a reproducible (or close to) test case before bugging the fastjet authors. They may also not help here, we have patched fastjet for multithreading on our own so it may very well be our problem.

**Comment by slava77** [comment] 2017-12-21 23:04
assign core

**Comment by slava77** [comment] 2017-12-21 23:34
[this may be just a part of the problem, but this part is apparently related to the core, either a RefVector or elements inside of it are not thread safe]

I tried to investigate this using the original issue input file from MC processing
This was in 940patch1 using /store/mc/RunIIFall17DRStdmix/QCD_Pt_80to120_TuneCP5_13TeV_pythia8/AODSIM/NoPU_94X_mc2017_realistic_v10-v2/70000/6692DC82-C0D5-E711-B2ED-0025905A60CE.root

I managed to derive from that and have a reasonably easily crashing setup
/afs/cern.ch/user/s/slava77/public/py/task_BTV-RunIIFall17DRStdmix-00003/pat/step1_PAT_nFlavor.py
this has O(100) clones of patJetFlavourAssociationPuppi created and added to the miniAOD task and the job is running nThreads >> nStreams. A typical run crashes after less than 200-300 events, usually in different places.

With some printouts added, the most suspicious part is in loading of partons (a GenParticlesRefVector) at https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/JetMCAlgos/plugins/JetFlavourClustering.cc#L322, which executes a fairly simple loop 
(Here the vector is O(1000) in size) at https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/JetMCAlgos/plugins/JetFlavourClustering.cc#L491-L501. 
I see that inside the loop different instances of JetFlavourClustering see different values of pt() for the same indices of the vector (the keys are consistently the same).
I also made a reference from a single thread run to confirm that identical counts come out of this loop.
The "other" values of pt() for items with the same keys as the reference appear to be sensible and even have matching values  in the same large vector of partons (at least in a few cases that I have checked).
It looks like a simultaneous read of a RefVector leads to different objects.


Another note about the "partons" vector is that there are typically a few % of identical p4-vectors in it (same for the original GenParticles). I think that's not a very healthy input for fastjet, but it's apparently not leading to problems at least in the tested events with single core execution.

**Comment by Dr15Jones** [comment] 2017-12-22 00:42
Is the GenParticlesRefVector generated in the job or is it coming from storage?

**Comment by slava77** [comment] 2017-12-22 00:47
On 12/21/17 4:42 PM, Chris Jones wrote:
> Is the GenParticlesRefVector generated in the job or is it coming from
> storage?

The refVector is generated (process.patJetPartons =
cms.EDProducer("HadronAndPartonSelector",)

The genParticles come from storage.

**Comment by Dr15Jones** [comment] 2017-12-22 00:56
Which of the collections from HadronAndPartonSelector is being used by the loop in JetFlavourClustering?

**Comment by Dr15Jones** [comment] 2017-12-22 00:59
Are the GenParticles set for earlyDelete?

**Comment by slava77** [comment] 2017-12-22 01:19
On 12/21/17 4:56 PM, Chris Jones wrote:
> Which of the collections from HadronAndPartonSelector is being used by
> the loop in JetFlavourClustering?
> 

patJetPartons_physicsPartons

these are not on the early delete list

**Comment by Dr15Jones** [comment] 2017-12-22 01:19
Since the collection was read back from storage and then used to fill the GenParticlesRefVector, the `push_back` done in `HadronAndPartonSelector` would call 
https://github.com/cms-sw/cmssw/blob/master/DataFormats/Common/interface/RefVectorBase.h#L86

and therefore get the pointer to the object in the original collection. 

The iterator over the collection ultimately calls RefVector::operator()[]
https://github.com/cms-sw/cmssw/blob/master/DataFormats/Common/interface/RefVector.h#L75

which has a bug on line 80! Before applying 'clang tidy' line 80 was correct as
`RefCore newCore(core);` but was incorrectly changed to `const RefCore& newCore(core);` by clang. The change would explain the behavior you are seeing.

**Comment by slava77** [comment] 2017-12-22 01:28
On 12/21/17 5:19 PM, Chris Jones wrote:
> Since the collection was read back from storage and then used to fill
> the GenParticlesRefVector, the |push_back| done in
> |HadronAndPartonSelector| would call
> https://github.com/cms-sw/cmssw/blob/master/DataFormats/Common/interface/RefVectorBase.h#L86
> 
> and therefore get the pointer to the object in the original collection.
> 
> The iterator over the collection ultimately calls RefVector::operator()[]
> https://github.com/cms-sw/cmssw/blob/master/DataFormats/Common/interface/RefVector.h#L75
> 
> which has a bug on line 80! Before applying 'clang tidy' line 80 was
> correct as
> |RefCore newCore(core);| but was incorrectly changed to |const RefCore&
> newCore(core);| by clang. The change would explain the behavior you are
> seeing.

interesting.

This is indeed in 940, as can be seen in the last commit for this file
in 940
https://github.com/cms-sw/cmssw/commit/908b4dbce52f9cf0b5a9834d6a7fbd17990334dd#diff-1c35e7722c1cce2720b091259b713001R80

**Comment by slava77** [comment] 2017-12-22 01:30
It's worth to double-check what else may have gone bad in #20789

**Comment by Dr15Jones** [comment] 2017-12-22 01:37
Fix is in #21772

**Comment by slava77** [comment] 2017-12-22 01:43
> Fix is in #21772

my guess is that the test will require a full release recompilation.
Perhaps I better wait for an IB with this and then check the JetFlavourClustering there

**Comment by Dr15Jones** [comment] 2017-12-22 01:46
Probably just rebuilding JetFlavourClustering would be enough to quickly test to see if that solved the problem (since it is only in reading the RefVector).

**Comment by slava77** [comment] 2017-12-22 02:56
> Probably just rebuilding JetFlavourClustering would be enough

it looks like it did the job
- all 142 instances of JetFlavourClustering are reading the same count of partons with pt>0.
- there are no exceptions from fastjet in my (modified) version of JetFlavourClustering

**Comment by perrotta** [comment] 2018-02-28 11:06
@Dr15Jones @slava77 : I think this has been solved already, and it can be closed. Correct?

**Comment by slava77** [comment] 2018-02-28 13:55
- fixed in the master from 10_0_0
- fixed in 9_4_X from CMSSW_9_4_X_2018-02-18-0000 (after 9_4_4), not in a production build yet (the PR was available since Dec 21).

The effect of missing this in production is that simultaneous dereferencing from a RefVector in multithreaded environment will lead to random values, still more often from the right collection than from a random place in memory that would lead to a crash.
@Dr15Jones please correct me if I'm wrong.

@fabozzi @GurpreetSinghChahal @prebello 
you may want to take this in account for upcoming production requests to advance as soon as possible to a build with a fix.
@fabiocos

**Comment by slava77** [comment] 2018-02-28 13:56
> @Dr15Jones @slava77 : I think this has been solved already, and it can be closed. Correct?

I'd rather keep it open until the fix is in the essential 9_4_X production builds

**Comment by fabozzi** [comment] 2018-02-28 14:07
OK, this means that all 94X campaigns (Fall17, EOYREReco2017, NanoAOD) should move to the new release when available
Is the fix entered also in 94X_MAOD branch?

**Comment by slava77** [comment] 2018-02-28 14:19
>  Is the fix entered also in 94X_MAOD branch?

yes

**Comment by slava77** [comment] 2018-04-16 15:22
+1

the fix is available in 94X production since CMSSW_9_4_5

**Comment by smuzaffar** [comment] 2020-05-29 15:56
This has been fixed.

**Closed by smuzaffar** 2020-05-29 15:56 UTC
Labels: analysis-pending, core-pending, pending-signatures, reconstruction-approved
