### ISSUE TITLE
DAS queries of workflows 29696.0 and  29700.0 fail

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#45532] opened 2024-07-23 13:47 UTC
Workflows 29696.0 and  29700.0 fail in PR and IB tests with DAS error (since a long time).

**Comment by makortel** [comment] 2024-07-23 13:47
assign pdmv, upgrade

**Comment by iarspider** [comment] 2024-07-23 13:52
Duplicate of https://github.com/cms-sw/cmssw/issues/45371

**Comment by makortel** [comment] 2024-07-23 13:54
Tbanks

**Comment by srimanob** [comment] 2024-07-31 23:52
+Upgrade

**Comment by AdrianoDee** [comment] 2024-09-05 08:59
+pdmv

**Closed** 2024-09-05 14:35 UTC
Labels: fully-signed, pdmv-approved, upgrade-approved
