### ISSUE TITLE
Fix user-floats that changed after updating SonicTriton service in #40814

### ISSUE THREAD

**Issue by rappoccio** [cms-sw/cmssw#40938] opened 2023-03-02 18:25 UTC
There is an unknown knock-on effect from #40814 that changed slimmed pat photons in the single gamma workflow 10805.31 as pointed out [here](https://github.com/cms-sw/cmssw/pull/40814#issuecomment-1452228434). This urgently needs to be fixed before 13_1_0_pre2.

**Comment by rappoccio** [comment] 2023-03-02 18:25
urgent

**Comment by rappoccio** [comment] 2023-03-02 18:31
assign reconstruction

**Comment by perrotta** [comment] 2023-03-02 19:00
@kpedro88

**Comment by kpedro88** [comment] 2023-03-02 20:16
see https://github.com/cms-data/RecoEgamma-EgammaPhotonProducers/pull/3

**Comment by perrotta** [comment] 2023-03-31 09:16
This looks like having been fixed by https://github.com/cms-data/RecoEgamma-EgammaPhotonProducers/pull/3 (thank you Kevin).
That fix surfaced another inherent non reproducibility in the outputs of `photonDRN` from SonicTriton, see https://github.com/cms-sw/cmssw/issues/41060. However, that is independent from this issue, which can be then closed.

**Closed by perrotta** 2023-03-31 09:16 UTC
Labels: reconstruction-pending, pending-signatures, urgent
