### ISSUE TITLE
trackingOnly workflows broken in latests IBs 

### ISSUE THREAD

**Issue by JanFSchulte** [cms-sw/cmssw#31743] opened 2020-10-10 17:38 UTC
Running trackingOnly workflows in the latest IBs (last two days at least) fails with a `ProductNotFound` error when writing the RECOSIM output:

`Begin processing the 1st record. Run 1, Event 1, LumiSection 1 on stream 0 at 10-Oct-2020 19:35:18.571 CEST

----- Begin Fatal Exception 10-Oct-2020 19:35:57 CEST-----------------------

An exception of category 'ProductNotFound' occurred while

   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0

   [1] Running path 'RECOSIMoutput_step'

   [2] Prefetching for module PoolOutputModule/'RECOSIMoutput'

   [3] Calling method for module PFClusterProducer/'particleFlowClusterHGCalFromMultiCl'

Exception Message:

Principal::getByToken: Found zero products matching all criteria

Looking for type: std::vector<reco::HGCalMultiCluster>

Looking for module label: ticlMultiClustersFromTrackstersMerge

Looking for productInstanceName: `

Can be reproduced in `CMSSW_11_2_X_2020-10-10-1100` by running `runTheMatrix.py -l 23234.1 -w upgrade`

**Comment by slava77** [comment] 2020-10-10 17:41
assign reconstruction,upgrade

**Comment by JanFSchulte** [comment] 2020-10-10 17:44
I should mention that full workflows that run the whole RECO work fine.

**Comment by JanFSchulte** [comment] 2020-10-11 18:16
Turns out this problem is already present it pre7 and apparently caused by this PR https://github.com/cms-sw/cmssw/pull/31527

Tested by making sure the trackingOnly workflows still worked in pre6 but fail when applying #31527 on top of it.

**Comment by slava77** [comment] 2020-10-11 18:42
`particleFlowClusterHGCalFromMultiCl` is a part of `hgcalLocalRecoTask` and that PR added `ticlMultiClustersFromTrackstersMerge` to the inputs , which drags in dependence of generalTracks.
So, violates the factorization of local reco.


For a temporary manual solution, try to `process.hgcalLocalRecoTask.remove(process.particleFlowClusterHGCalFromMultiCl)` and (just in case) `process.reconstruction_trackingOnly.remove(process.particleFlowClusterHGCalFromMultiCl)` to see if this helps locally.
The other option is not to write `particleFlowClusterHGCalFromMultiCl`, `process.RECOSIMoutput.outputCommands.append('drop *_particleFlowClusterHGCalFromMultiCl_*_*')`

@SohamBhattacharya @rovere @felicepantaleo 
we need some refactoring of `hgcalLocalRecoTask` re dependence of `particleFlowClusterHGCalFromMultiCl` on tracks.

**Comment by JanFSchulte** [comment] 2020-10-11 18:48
@slava77 Thanks for the suggestion, the workaround works and I can continue my work until a more permanent fix is found.

**Comment by rovere** [comment] 2020-10-13 07:19
Ciao @slava77 , all,
indeed I see the problem and some factorization is needed. In this specific case, I'm not sure why the `particleFlowClusterHGCalFromMultiCl` product is needed in a `TrackingOnly` scenario. I think that, independently of the factorization that is needed, we should not include products in a `TrackingOnly` scenario that are not strictly needed.

**Comment by slava77** [comment] 2020-10-13 12:05
> Ciao @slava77 , all,
> indeed I see the problem and some factorization is needed. In this specific case, I'm not sure why the `particleFlowClusterHGCalFromMultiCl` product is needed in a `TrackingOnly` scenario. I think that, independently of the factorization that is needed, we should not include products in a `TrackingOnly` scenario that are not strictly needed.

trackingOnly still includes jetCore, which requires calorimeter local reco; that's nor phase-2 though.
`particleFlowClusterHGCalFromMultiCl` is a part of calo local.

**Comment by rovere** [comment] 2020-10-18 09:52
> > Ciao @slava77 , all,
> > indeed I see the problem and some factorization is needed. In this specific case, I'm not sure why the `particleFlowClusterHGCalFromMultiCl` product is needed in a `TrackingOnly` scenario. I think that, independently of the factorization that is needed, we should not include products in a `TrackingOnly` scenario that are not strictly needed.
> 
> trackingOnly still includes jetCore, which requires calorimeter local reco; that's nor phase-2 though.
> `particleFlowClusterHGCalFromMultiCl` is a part of calo local.

Ciao @slava77 ,
`jetCore` is not part of `Phase2` reconstruction. Dropping the "missing" product is a viable temporary fix. Having a functional factorization is a long term goal that will be delivered together with a solid Phase2 reconstruction.

**Comment by slava77** [comment] 2020-10-18 16:00
> Ciao @slava77 ,
> `jetCore` is not part of `Phase2` reconstruction. 

after looking closely, apparently the problem is worse than just jetCore.
CaloJets are used in PV sorting and none of the HGCAL inputs are used.
It's still probably making it for just a suboptimal performance rather than a bug for vertexing in phase2.
@mtosi @vmariani @hatakeyamak @bendavid

**Comment by slava77** [comment] 2020-10-20 00:52
I have a fix in #31844

**Comment by slava77** [comment] 2020-10-20 18:38
+1

> I have a fix in #31844

this was now merged and should appear in 11_2_0_pre8 and in IBs starting from 10-20-2300.

**Comment by JanFSchulte** [comment] 2020-10-20 18:39
Thanks for taking care of it!

**Comment by kpedro88** [comment] 2020-10-20 19:30
+upgrade

**Closed** 2020-10-21 00:14 UTC
Labels: fully-signed, reconstruction-approved, upgrade-approved
