### ISSUE TITLE
DQM Physics sequence missing input collections

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#22996] opened 2018-04-18 12:22 UTC
The DQM Physics sequence is throwing exceptions in the express configuration due to the lack of an input jet corrector collection. A quick protection has been made available in #22992 / #22993 to prevent on the very short term express crashes even if the collection is missing, but this is just a temporary workaround.

A proper solution implies fixing the DQM Physics sequence, in a similar way as the DQM JetMET sequence, so as to pass correctly the collection. 

Two solution have been checked to solve the problem in the express configuration:

- adding the ak4PFCHSL1FastL2L3CorrectorChain sequence at the beginning of the dqmPhysics sequence;

- move the name of the collection to the clone dqmAk4PFCHSL1FastL2L3CorrectorChain, used by the DQM JetMET sequence, in the top physics modules requiring it. 

A proper solution should be deplyed, making the protection in #22992 not necessary, but it should be verified to work in all possible scenarios.

**Comment by fabiocos** [comment] 2018-04-18 12:33
assign dqm

**Comment by fabiocos** [comment] 2019-10-15 09:31
@jfernan2 is your revision of DQM sequences thought to address also this issue?

**Comment by jfernan2** [comment] 2019-10-15 10:04
@fabiocos  it was not but I am adding it now to the list
Are 1001.2,1040.1 workflows still good to test this?
Thanks

**Comment by jfernan2** [comment] 2019-10-15 10:50
BTW: I am not sure why 'assign dqm' is retrieving an old list of DQM L2 people since cms-bot categories.py file has the right list.... 
Where can I fix that? Sorry I failed to find it on github...

**Comment by davidlange6** [comment] 2019-10-15 11:08
presumably the dqm group hasn't kept it up to date - to do so, make a PR for

https://github.com/cms-sw/cms-bot/blob/308056b21a7832caf8adfd127bc728d7a2473b07/categories.py#L25

**Comment by jfernan2** [comment] 2019-10-15 11:26
@davidlange6  as I said in my comment, the categories.py file is up to date in what dqm concerns since a long time, just search for @vazzolini,@vanbesien,@dmitrijus there, they are not there but the comment by cmsbuild triggered by "assign dqm" command took a wrong list

**Comment by davidlange6** [comment] 2019-10-15 11:40
Sorry misunderstood. Maybe we have an obsolete version of the cmsbot repo someplace in Jenkins

David


On 15 Oct 2019, at 13:26, jfernan2 <notifications@github.com> wrote:

﻿

@davidlange6<https://github.com/davidlange6> as I said in my comment, the categories.py file is up to date in what dqm concerns since a long time, just search for @vazzolini<https://github.com/vazzolini>,@vanbesien<https://github.com/vanbesien>,@dmitrijus<https://github.com/dmitrijus> there, they are not there but the comment by cmsbuild triggered by "assign dqm" command took a wrong list

**Comment by fabiocos** [comment] 2019-10-15 11:42
@jfernan2 @davidlange6 please note that the issue itself is quite old, open since April last year...

**Comment by fabiocos** [comment] 2019-10-15 11:43
As now @jfernan2 is going through the sequence cleaning process, I think it is a good idea to check back all the issues that were temporarily hidden during data taking by protections

**Comment by jfernan2** [comment] 2019-10-15 11:44
> @jfernan2 @davidlange6 please note that the issue itself is quite old, open since April last year...

you are right... my fault then

**Comment by jfernan2** [comment] 2019-10-15 11:45
@fabiocos  the point is how to check at present if the fix works, 1001.2,1040.1 workflows  do not show this problem with runTheMatrix.py as far as I can tell from the logs..

**Comment by fabiocos** [comment] 2019-10-15 11:47
@jfernan2 this goes back to the problem of defining a proper express-like test suitable for recent runs. Configuration/DataProcessing can provide a tool to help here.

**Comment by jfernan2** [comment] 2019-10-16 09:37
@fabiocos I have fixed the issue in the last commit of https://github.com/cms-sw/cmssw/pull/28156 
I used the second solution proposed in the issue since it seems more CPU economic...
I have tested it offline and works, but I am afraid it will change again for Express Run3 if Puppy Jets are finally adopted
On the other side  don't really know how to introduce a test for this/Express in github/Jenkins...

**Comment by fabiocos** [comment] 2019-10-16 13:35
@jfernan2 thank you, defining a test workflow to mimic the latest express configuration is something we should consider, as discussed multiple times

**Comment by jfernan2** [comment] 2020-03-11 18:40
This issue should be closed

**Comment by fabiocos** [comment] 2020-03-12 09:14
@jfernan2 @silviodonato do we have evidence that all the issues (i.e. error messages induced by protections) have gone? And was the express workflow tested in some way?

**Comment by silviodonato** [comment] 2020-03-12 11:31
Good point @fabiocos . I tried to look for the error messages related to the protection in the IB tests of old releases without success. @jfernan2, do you know how to reproduce the old error related to `topSingleMuonMediumDQM`, `topSingleElectronMediumDQM`, `singleTopMuonMediumDQM`, `singleTopElectronMediumDQM`?

**Comment by jfernan2** [comment] 2020-03-12 11:40
@silviodonato I guess that reverting the PR i made up there, right?

**Comment by silviodonato** [comment] 2020-03-12 12:52
I looked at the IB test of CMSSW_11_0_X [1] because they should not include  #28156
[1] https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_11_0/2020-03-11-2300?selectedArchs=slc7_amd64_gcc820&selectedFlavors=X&selectedFlavors=X&selectedStatus=failed&selectedStatus=known_failed&selectedStatus=passed

**Comment by jfernan2** [comment] 2020-03-12 15:01
Sorry @silviodonato I do not understand: the link you point out is from IB of today while #28156 was merged in 11_0_X around October 2019
I am sorry but I do not follow what you mean

**Comment by silviodonato** [comment] 2020-03-12 16:17
You are right. I wanted to say CMSSW_10_6_X. For instance, I don't see any special error in
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/raw/slc7_amd64_gcc700/CMSSW_10_6_X_2020-03-12-1100/pyRelValMatrixLogs/run/136.8391_RunExpressPhy2017F+RunExpressPhy2017F+HLTDR2_2017+RECODR2_2017reHLTSiPixelCalZeroBias_Prompt+HARVEST2017/step3_RunExpressPhy2017F+RunExpressPhy2017F+HLTDR2_2017+RECODR2_2017reHLTSiPixelCalZeroBias_Prompt+HARVEST2017.log
This means we cannot use wf 136.8391 from IB test to validate the fix.

**Comment by jfernan2** [comment] 2020-03-12 17:41
I see... @fabiocos  spotted this in real Express sequence at Tier0 if I understand correctly. 136.8391 is using DQM:@standardDQM+@ExtraHLT+@miniAODDQM so the issue should be hidden there since all the JetCorrections are loaded

@schneiml  has been trying to get the actual config file and cmsRun environment at T0: 
https://its.cern.ch/jira/browse/CMSTZ-427
But no success yet. 

Nevertheless, I have tested DQM/Physics/test/topDQM_production_cfg.py which is the closest test file to the TOP modules, and since the Jet correctors are loaded in the JetMET DQM module the problem should be gone now even in real express...

**Comment by fabiocos** [comment] 2021-05-12 09:19
@jfernan2 @silviodonato @qliphy not sure which kind of updates are available nowadays, some cleaning was ongoing already when I left the release manager task. Probably this issue should be closed and something newer opened in case there are residual problems are present, please provide comments and suggestions.

**Comment by silviodonato** [comment] 2021-05-12 16:16
I agree, I think we can close this issue. @jfernan2 ?

**Comment by jfernan2** [comment] 2021-05-12 16:18
Yes, fine from my side

**Closed** 2021-05-12 16:26 UTC
Labels: dqm-pending, pending-signatures
