### ISSUE TITLE
EOS data access issue in CMSSW

### ISSUE THREAD

**Issue by stlammel** [cms-sw/cmssw#31657] opened 2020-10-02 18:53 UTC
T2_AT_Vienna moved to a new EOS-based storage system. About 90% of
HammerCloud jobs running at the site to check things are working properly
fail with interrupted data reads.
An EOS issue report was submitted and EOS developers believe the access
issue/bug is within CMSSW.
https://eos-community.web.cern.ch/t/fst-marked-as-offline-and-spurious-mgm-failovers/511
Strangely, EOS is used at CERN since years without CMSSW access issue
reports. However, the EOS team received a similar report from CERN recently.
EOS configuration is probably different at Vienna nd CERN. Also behaviour might
have changed in recent versions.
The issue needs to be investigated and corrected.

**Comment by makortel** [comment] 2020-10-02 18:59
assign core

**Comment by makortel** [comment] 2020-10-02 18:59
@bbockelm Would you be able to take a look?

**Comment by bbockelm** [comment] 2020-10-02 19:19
The file-open patterns is not a bug, just the behavior of CMSSW.  I suspect it's a false lead.

Without access to the logfiles (all the links I saw pointed to SAM and the links are now dead), I can't really speculate as to what's going wrong at Vienna.

Does Vienna deploy any Xrootd client plugins that might be hijacking the code paths?

**Comment by bbockelm** [comment] 2020-10-02 20:55
@stlammel pointed me at a few logs.  Here's what I see:

```
== CMSSW: R__unzipLZMA: error 9 in lzma_code
== CMSSW: ----- Begin Fatal Exception 02-Oct-2020 00:01:44 UTC-----------------------
== CMSSW: An exception of category 'FileReadError' occurred while
== CMSSW:    [0] Rethrowing an exception that happened on a different thread.
== CMSSW:    [1] Reading branch EcalRecHitsSorted_reducedEcalRecHitsEE__RECO.
== CMSSW:    Additional Info:
== CMSSW:       [a] Fatal Root Error: @SUB=TBasket::ReadBasketBuffers
== CMSSW: fNbytes = 76661, fKeylen = 128, fObjlen = 130264, noutot = 0, nout=0, nin=76533, nbuf=130264
```

```
== CMSSW: ----- Begin Fatal Exception 02-Oct-2020 00:32:34 UTC-----------------------
== CMSSW: An exception of category 'FileReadError' occurred while
== CMSSW:    [0] Calling InputSource::readEvent_
== CMSSW:    [1] Reading branch BranchListIndexes
== CMSSW:    Additional Info:
== CMSSW:       [a] Fatal Root Error: @SUB=TBasket::Streamer
== CMSSW: The value of fObjlen is incorrect (-262554878) ; trying to recover by setting it to zero
```

```
== CMSSW:    Additional Info:
== CMSSW:       [a] Fatal Root Error: @SUB=TBasket::Streamer
== CMSSW: The value of fKeylen is incorrect (-22264) ; trying to recover by setting it to zero
```

Those look like real corruptions and I don't see much to do with the multi-source work.  The incorrect bytes are getting into the root layers.

**Comment by stlammel** [comment] 2020-10-02 21:09
@bbockelm Hallo Brian,
we ask the Vienna admins to verify the checksum as very first step and
files don't seem to be corrupted on EOS. SAM SE-style xrootd tests read
blocks from each SAM test file from a server at CERN and compare the
checksum. We don't observe any errors/corruption there too.
- Stephan

**Comment by bbockelm** [comment] 2020-10-03 16:13
Yup, I completely believe that the files on disk aren't corrupted - I think the admins mentioned that on the EOS thread.

The question is, why are corrupt bytes getting to the root layer?  I noticed they are using erasure coding instead of replication - I wonder if that possibly could cause the issue?

**Comment by esindril** [comment] 2020-11-03 08:48
The issue mentioned in this ticket has been identified and fixed in the EOS project. I believe this can be closed.

**Comment by makortel** [comment] 2020-11-03 13:25
Thanks @esindril!

**Comment by makortel** [comment] 2020-11-03 13:25
+1

**Closed** 2020-11-03 13:31 UTC
Labels: core-approved, fully-signed
