### ISSUE TITLE
Problem in the 94X backport of HcalDetId protections for calibration events

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#23744] opened 2018-07-04 16:27 UTC
The merge of #23688 has caused a list of reproducible failures in 2016 workflows in CMSSW_9_4_X_2018-07-03-2300 , within DQM with the exception

----- Begin Fatal Exception 04-Jul-2018 10:09:31 CEST-----------------------
An exception of category 'Conditions not found' occurred while
[0] Processing Event run: 283877 lumi: 17 event: 27631378 stream: 1
[1] Running path 'dqmoffline_step'
[2] Calling method for module DigiTask/'digiTask'
Exception Message:
Unavailable Conditions of type HcalQIEData for cell (0x4e280440) (CastorRadFacility 1 / 2 / 0)
----- End Fatal Exception -------------------------------------------------

triggered from

https://cmssdt.cern.ch/lxr/source/CondFormats/CastorObjects/interface/CastorCondObjectContainer.h#0090

as used in the module https://cmssdt.cern.ch/lxr/source/DQM/HcalTasks/python/DigiTask.py for what I can see.

**Comment by fabiocos** [comment] 2018-07-04 16:32
@bsunanda FYI The failing workflows are not present in 8_0_X, are we sure that the problem does not affect also that release?

**Comment by bsunanda** [comment] 2018-07-04 18:37
I shall take a look and let you know. I thought it was tested for the failed lump blocks
________________________________

**Comment by abdoulline** [comment] 2018-07-05 15:41
@fabiocos, 
(Cc @bsunanda, @DryRun, @deguio) 

I guess that DetId  _fix_ may have "provoked" something (undesirable consequence) which until now was kind of hidden behind improper treatment of Calib.channels  Id  and it _may_ need a fix in HCAL DQM as well. 
We didn't have HcalDQMData  (neither any other conditions) for CRF channels (which are present in e-map = unpacked, though). So I take it "offline" to internal HCAL discussion for the moment...

**Comment by DryRun** [comment] 2018-07-09 18:59
Hi @fabiocos , could I ask specifically which workflows are failing? I tried a few (2016 data), but they apparently ran successfully.

**Comment by fabiocos** [comment] 2018-07-11 08:58
@abdoulline @DryRun please see https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/relVal/CMSSW_9_4/2018-07-04-1100?selectedArchs=slc7_amd64_gcc630&selectedArchs=slc6_amd64_gcc630&selectedFlavors=X&selectedFlavors=MAOD_X&selectedFlavors=AN_X&selectedStatus=failed

136.769, 136.77, 136.771, 136.772, ...

**Comment by abdoulline** [comment] 2018-07-11 11:05
@fabiocos   Thank you, Fabio.  

Unfortunately in my case (lxplus) all the tests you've listed, like 
runTheMatrix.py -l 136.769 &

failed at the step2 with similar file access errors: 
Failed to open file at URL root://eoscms.cern.ch:1094//eos/cms/store/data/Run2016H/DoubleEG/RAW/v1/000/283/877/00000/00B1E52F-889B-E611-B4B9-FA163EA8BEB3.root.

And I don't see RAW for the aforementioned sample:  
eos ls /eos/cms/store/data/Run2016H/DoubleEG
MINIAOD

Hopefully David (@DryRun) will have a better chance...

**Comment by DryRun** [comment] 2018-07-11 11:35
Thanks @abdoulline and @fabiocos. 136.731 and 136.7611 were the ones I tried successfully previously, and unfortunately I see the same file access errors as @abdoulline for most of the others. On EOS, I do see something for `eos ls /eos/cms/store/data/Run2016H/ZeroBias/RAW`, so perhaps 136.778 will work... trying that now.

**Comment by abdoulline** [comment] 2018-07-11 15:16
CMSSW_9_4_X_2018-07-08-0000 + 136.778 = OK...

136.778_RunZeroBias2016H+RunZeroBias2016H+HLTDR2_2016+RECODR2_2016reHLT_Prompt+H
ARVESTDR2 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED  - time date Wed J
ul 11 16:45:10 2018-date Wed Jul 11 13:39:38 2018; exit: 0 0 0 0
1 1 1 1 tests passed, 0 0 0 0 failed

**Comment by fabiocos** [comment] 2018-07-11 16:12
@abdoulline indeed, I reverted the crashing PR in CMSSW_9_4_X_2018-07-04-2300 as you can see in the IB history, so an earlier build should be used. Alternatively just merge #23688 on top of todays' IB an try...

**Comment by abdoulline** [comment] 2018-07-11 20:13
@fabiocos  admittedly I've overlooked the reverting... 
So for @DryRun  it should be easy now to reproduce the issue with earlier  (e.g.) 
CMSSW_9_4_X_2018-07-03-2300 + 136.778

**Comment by DryRun** [comment] 2018-07-12 19:41
Thanks for the suggestions. I was using CMSSW_9_4_X_2018-07-03-2300, but it was crashing yesterday due to the cvmfs issues. 

It works today, and I was able to locate the crash. I think the crash can be fixed with c3cdccbb3cb57fa622cff03295b2d9115a0276c7 (requires subdet==HcalEndcap for QIE11 digis; also,  f8aeac9086a41dc160e997be433fe5f2091ea48f could be included, which does the same thing for HBHE digis. See https://github.com/cms-sw/cmssw/commits/8d539d44ecea86fea7f16929f65101103fb077d4/DQM/HcalTasks/plugins/DigiTask.cc).

However, there are 7 commits to DigiTask.cc in between 9_4_X and c3cdccbb3cb57fa622cff03295b2d9115a0276c7. Could we cherry-pick just the relevant commits, or do we have to take all the commits in order?

**Comment by abdoulline** [comment] 2018-07-12 20:38
David,   the two fixing snippets you've linked - they are just several lines of code. So I'd suggest you to submit this "minimum-minimorum" fix to 94X _without_ any other back-porting...

**Comment by abdoulline** [comment] 2018-07-17 05:19
@DryRun   David?

**Comment by DryRun** [comment] 2018-07-17 09:49
Hi @abdoulline, thanks for the reminder. I made a backport of the two commits at https://github.com/cms-sw/cmssw/pull/23808, which should fix this crash.

**Comment by abdoulline** [comment] 2018-07-17 10:52
Thank you, David.

Then, after it, Sunanda's PR #23688 (reverted) can be re-included again...

**Comment by fabiocos** [comment] 2018-08-02 08:38
The problem looks fixed now

**Closed** 2018-08-02 08:38 UTC
Labels: pending-assignment
