### ISSUE TITLE
crash in HLT DQM HLTBTagPerformanceAnalyzer/hltbTagValidation observed in singleElectron 1TeV gun in 103X

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#24522] opened 2018-09-12 18:31 UTC
in CMSSW_10_3_0_pre4

```runTheMatrix.py -l 10803.0 -w upgrade --useInput all --command="-n 400"``` (my test was specifically on 1K events; the crash is on event 334)

```
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 7 event: 335 stream: 0
   [1] Calling method for module HLTBTagPerformanceAnalyzer/'hltbTagValidation'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::ShallowTagInfo>
Looking for module label: hltDeepCombinedSecondaryVertexBJetTagsInfos
Looking for productInstanceName:

```

**Comment by slava77** [comment] 2018-09-12 18:32
assign dqm

**Comment by slava77** [comment] 2018-09-12 19:42
@smuzaffar 
is the bot asleep? 
I do not see the standard receipt message or any labels assigned.

**Comment by slava77** [comment] 2018-09-12 19:43
>  is the bot asleep?

apparently it is, now that I read the note about this on the HN

**Comment by zhenhu** [comment] 2018-09-12 20:12
Same error observed in pre3 relvals.  Several workflows affected: 
ADDMonoJet, TenTau, ZpTT, SingleElectronPt1000, TenE, WpToENu, HSCPstop, DisplacedSUSY_stopToBottom
We lost roughly 10% statistics due to this error

**Comment by smuzaffar** [comment] 2018-09-12 21:04
ping cms-bot

**Comment by slava77** [comment] 2018-09-12 23:05
In case it helps with relvals: I managed to run through completion by effectively disabling the module with ```--customise_command="process.hltbTagValidation.TriggerResults = \"\"\n"```

**Comment by fabiocos** [comment] 2018-09-13 12:46
@slava77 @zhenhu thank you for the report. It is likely related to #24316 added in pre3.

@jfernan2 @andrius-k @schneiml is already somebody looking into this?

**Comment by fabiocos** [comment] 2018-09-25 12:17
@jfernan2 @andrius-k @schneiml there was any follow-up of this issue?

**Comment by schneiml** [comment] 2018-09-25 12:36
Sorry @fabiocos , this got lost somewhere, I just hear about it now. We'll have a look.

**Comment by fabiocos** [comment] 2018-09-26 15:32
@schneiml @slava77 I tried to reproduce this both in 10_3_0_pre4 and in the latest IB, running on 1000 events workflow 10803.0, but I could not

**Comment by zhenhu** [comment] 2018-09-26 16:14
Hi @fabiocos , some error logs here FYI
https://cms-unified.web.cern.ch/cms-unified/report/asikdar_RVCMSSW_10_3_0_pre4ZpTT_1500_13_180918_210231_5742
https://cms-unified.web.cern.ch/cms-unified/report/asikdar_RVCMSSW_10_3_0_pre4TenTau_15_500_180918_205913_6200
https://cms-unified.web.cern.ch/cms-unified/report/zhenhu_RVCMSSW_10_3_0_pre4ADDMonoJet_d3MD3_13_180917_130459_3766

**Comment by schneiml** [comment] 2018-09-27 13:53
Quick update: to me, right now, everything seems about correct: The crash happens at the first event that this module selects. The object that it looks for seems to be available: `edmEventSize` says it is in the file, and the HLT config in use `keeps` the collection. 

So, I don't see what is wrong here so far.

**Comment by fabiocos** [comment] 2018-09-27 14:11
@schneiml not sure that the crash is at the first event looking at the reports. Anyway so far I have been unable to produce a crash, I am trying with a larger sample. I have cooked a protection for this anyway

**Comment by Dr15Jones** [comment] 2018-09-27 14:18
@schneiml One thing to keep in mind, even if `edmEventSize` shows there is a branch in the file, it does not mean there is an entry for every event.

**Comment by schneiml** [comment] 2018-09-27 14:31
@fabiocos I meant "the first event where this product is read". The module seems to do some very restrictive filtering and ignores most events.

Is there a (easy) way to check if a product is available for a given event?

**Comment by schneiml** [comment] 2018-09-27 14:34
Also: `runTheMatrix.py -l 10803.0 -w upgrade --useInput all --command="-n 400" --ibeos -t 8` works reliably for me. The `-t 8` is for speed, also works (crashes) when run single threaded.

**Comment by Dr15Jones** [comment] 2018-09-27 15:34
>Is there a (easy) way to check if a product is available for a given event?

If you do a `Events->Scan(...)` of the branch in question in ROOT and look for a `false` value in the `.present` sub-branch.

**Comment by jfernan2** [comment] 2019-06-21 13:58
Since #24682 was merged, should this issue be closed?

**Closed** 2019-07-05 08:57 UTC
Labels: dqm-pending, pending-signatures
