### ISSUE TITLE
HLT crash in run 359998: Unavailable Conditions of type HcalChannelQuality 

### ISSUE THREAD

**Issue by trtomei** [cms-sw/cmssw#39693] opened 2022-10-11 01:28 UTC
Crash in Run 359998 
http://cmsonline.cern.ch/cms-elog/1159020
 
with following message:
```
[2] Calling method for module CaloTowersCreator/'hltTowerMakerForAll'
Exception Message:
Unavailable Conditions of type HcalChannelQuality for cell (0x0) 
```

Unfortunately not reproducible yet. The file reconverted to ROOT is
`/nfshome0/hltpro/hilton_c2e36_35_04/hltpro/thiagoScratch/run359998_ls0335.root`,
and the relevant configurations are:

- CMSSW_12_4_9
- GT: 124X_dataRun3_HLT_v4
- /cdaq/physics/Run2022/2e34/v1.4.0/HLT/V10

A copy of the configuration file is available in /nfshome0/hltpro/hilton_c2e36_35_04/hltpro/thiagoScratch/hlt.py

**Comment by missirol** [comment] 2022-10-11 08:35
FYI: @cms-sw/hlt-l2 @silviodonato

**Comment by missirol** [comment] 2022-10-11 08:45
For the record, this online crash happened more than once (and it does not seem to be reproducible offline). Affected runs (afaik):
```
357898
359998
```

**Comment by trtomei** [comment] 2022-10-13 03:10
Hi @wang-hui The files are available in `/afs/cern.ch/user/t/tomei/public/issue39693` now!

**Comment by silviodonato** [comment] 2022-10-13 07:49
Hello @cms-sw/hcal-dpg-l2 @cms-sw/alca-l2 , this crash happened again this night in run [360295](https://cmsoms.cern.ch/cms/runs/report?cms_run=360295). HLT was using `CMSSW_12_4_10`.
The crash happened 5 times (2022-10-13):
- 1 time at 09:16:07 (`fu-c2b03-33-01`)
- 1 time at 08:27:12 (`fu-c2b03-12-01`)
- 3 time around 05:40
   - 05:39:07 (`fu-c2b03-33-01`)
   - 05:41:26 (`fu-c2b03-30-01`)
   - 05:44:57 (`fu-c2b02-03-01`)

**Comment by silviodonato** [comment] 2022-10-14 07:24
In Run 360330
```
   [2] Calling method for module CaloTowersCreator/'hltStoppedHSCPTowerMakerForAll'
Exception Message:
Requested conditions of type HcalChannelQuality for cell (0x45104408) (HE -17,8,1) got conditions for cell (0x0)
```

**Comment by mariadalfonso** [comment] 2022-10-14 11:18
> Hi @wang-hui The files are available in `/afs/cern.ch/user/t/tomei/public/issue39693` now!

this particular event was investigated by @wang-hui
offline-cpu code give the following warning
```
[1] %MSG-w HBHEDigi:  HBHEPhase1Reconstructor:hltHbherecoLegacy  13-Oct-2022 21:36:29 CEST Run: 359998 Event: 538274608
 bad SOI/maxTS in cell (HB 10,47,3)
 expect maxTS >= 3 && soi > 0 && soi < maxTS - 1
 got maxTS = 8, SOI = -1
```

see here https://github.com/cms-sw/cmssw/blob/master/RecoLocalCalo/HcalRecProducers/src/HBHEPhase1Reconstructor.cc#L520

There is a shift in the SOI, I do not see this condition in the the hlt-gpu code so that's why crash on this.
I will implement some fix today so that HLT will not crash.

Of course we need why the electronics thinks this rec-hit is shifted of 25ns !

**Comment by mariadalfonso** [comment] 2022-10-14 11:19
> Hello @cms-sw/hcal-dpg-l2 @cms-sw/alca-l2 , this crash happened again this night in run [360295](https://cmsoms.cern.ch/cms/runs/report?cms_run=360295). HLT was using `CMSSW_12_4_10`. The crash happened 5 times (2022-10-13):
> 
> * 1 time at 09:16:07 (`fu-c2b03-33-01`)
> * 1 time at 08:27:12 (`fu-c2b03-12-01`)
> * 3 time around 05:40
>   
>   * 05:39:07 (`fu-c2b03-33-01`)
>   * 05:41:26 (`fu-c2b03-30-01`)
>   * 05:44:57 (`fu-c2b02-03-01`)
> 
> [f3mon_logtable_2022-10-13T07_53_34.976Z.txt](https://github.com/cms-sw/cmssw/files/9772156/f3mon_logtable_2022-10-13T07_53_34.976Z.txt)
> 
> List of runs with the crashes:
> 
> ```
> 357898
> 359998
> 360295
> ```

Hi where I can find the events here ?
would be good to have these events copied somewhere so that we can classify all these exceptions.

**Comment by missirol** [comment] 2022-10-14 11:32
> where I can find the events here ?

They are available on the online GPU machines, e.g. ` gpu-c2a02-35-01.cms `, at

`/store/error_stream/run{357898,359998,360295}/*raw`

For an example of how to rerun HLT directly on `*.raw` files, see https://github.com/cms-sw/cmssw/issues/39045#issuecomment-1214193410.

> I do not see this condition in the the hlt-gpu code so that's why crash on this.

FYI: @cms-sw/heterogeneous-l2

**Comment by fwyzard** [comment] 2022-10-14 15:02
Seems to be happening a lot more frequently in recent runs:

> [720 crashes in run 360330 ](https://cmsonline.cern.ch/webcenter/portal/cmsonline/Common/Elog?_piref683379043.strutsAction=%2FviewMessageDetails.do%3FmsgId%3D1160049)
> 
> Run number: 360330
> L1/HLT key: collisions2022/v249
> HLT Menu: /cdaq/physics/Run2022/2e34/v1.4.3/HLT/V1
> CMSSW version: CMSSW_12_4_10
> ```
> Most (if not all) of the crashes have the message: 
> [2] Calling method for module CaloTowersCreator/'hltTowerMakerForAll'
> Exception Message:
> Requested conditions of type HcalChannelQuality for cell (0x45104407) (HE -17,7,1) got conditions for cell (0x0)
> ```

**Comment by fwyzard** [comment] 2022-10-14 15:02
assign heterogeneous

**Comment by francescobrivio** [comment] 2022-10-14 15:11
> Seems to be happening a lot more frequently in recent runs:
> 
> > [720 crashes in run 360330 ](https://cmsonline.cern.ch/webcenter/portal/cmsonline/Common/Elog?_piref683379043.strutsAction=%2FviewMessageDetails.do%3FmsgId%3D1160049)
> > Run number: 360330
> > L1/HLT key: collisions2022/v249
> > HLT Menu: /cdaq/physics/Run2022/2e34/v1.4.3/HLT/V1
> > CMSSW version: CMSSW_12_4_10
> > ```
> > Most (if not all) of the crashes have the message: 
> > [2] Calling method for module CaloTowersCreator/'hltTowerMakerForAll'
> > Exception Message:
> > Requested conditions of type HcalChannelQuality for cell (0x45104407) (HE -17,7,1) got conditions for cell (0x0)
> > ```

Just to add a bit of information on "recent runs":
this morning there was the update of the HCAL conditions that caused some trobules exactly in the run range `360329–360333` (as described in [this CMSTalk post](https://cms-talk.web.cern.ch/t/hlt-express-prompt-hcal-conditions-update/16263)) and which consequently caused some processing issues in Tier0 (see [this CMSTalk post](https://cms-talk.web.cern.ch/t/segmentation-fault-in-express-jobs/16261)).

Since the crashes reported in this GH issue pre-date the errors I just described, I think the two thing might be un-related, but I just wanted to add the information for completeness.

**Comment by fwyzard** [comment] 2022-10-14 15:43
One thing that I can reproduce is that the `soi` (what is it ?) computed on GPU is "wrong" for the same event as for the CPU:
```
Begin processing the 18th record. Run 359998, Event 538274608, LumiSection 335 on stream 0 at 14-Oct-2022 17:38:13.244 CEST
%MSG-w HBHEDigi:  HBHEPhase1Reconstructor:hltHbherecoLegacy  14-Oct-2022 17:38:13 CEST Run: 359998 Event: 538274608
 bad SOI/maxTS in cell (HB 10,47,3)
 expect maxTS >= 3 && soi > 0 && soi < maxTS - 1
 got maxTS = 8, SOI = -1
%MSG
```
and
```
Begin processing the 18th record. Run 359998, Event 538274608, LumiSection 335 on stream 0 at 14-Oct-2022 17:39:00.806 CEST
gch: 6861, nchannelsf01HE: 4265, nchannelsf015: 4265, soi: -85
gch: 6861, nchannelsf01HE: 4265, nchannelsf015: 4265, soi: -85
gch: 6861, nchannelsf01HE: 4265, nchannelsf015: 4265, soi: -85
gch: 6861, nchannelsf01HE: 4265, nchannelsf015: 4265, soi: -85
gch: 6861, nchannelsf01HE: 4265, nchannelsf015: 4265, soi: -85
gch: 6861, nchannelsf01HE: 4265, nchannelsf015: 4265, soi: -85
gch: 6861, nchannelsf01HE: 4265, nchannelsf015: 4265, soi: -85
gch: 6861, nchannelsf01HE: 4265, nchannelsf015: 4265, soi: -85
----- Begin Fatal Exception 14-Oct-2022 17:39:00 CEST-----------------------
An exception of category 'Conditions not found' occurred while
   [0] Processing  Event run: 359998 lumi: 335 event: 538274608 stream: 0
   [1] Running path 'Path'
   [2] Calling method for module CaloTowersCreator/'hltTowerMakerForAll'
Exception Message:
Unavailable Conditions of type HcalChannelQuality for cell (0x0) 
----- End Fatal Exception -------------------------------------------------
```

**Comment by fwyzard** [comment] 2022-10-14 16:06
Looking at the legacy code in `RecoLocalCalo/HcalRecProducers/src/HBHEPhase1Reconstructor.cc`
  - if the `soi` is bad, it prints a warning and sets a `badSOI` flag:
    ```c++
        const int soi = tsFromDB_ ? properties.paramTs->firstSample() : frame.presamples();
        const bool badSOI = !(maxTS >= 3 && soi > 0 && soi < maxTS - 1);
        if (badSOI) {
          edm::LogWarning("HBHEDigi") << " bad SOI/maxTS in cell " << cell
                                      << "\n expect maxTS >= 3 && soi > 0 && soi < maxTS - 1"
                                      << "\n got maxTS = " << maxTS << ", SOI = " << soi;
        }
    ```
  - the `badSOI` flag is set in the `channelInfo`:
    ```c++
        channelInfo->setChannelInfo(cell,
                                    pulseShapeID,
                                    nTSToCopy,
                                    fitSoi,
                                    soiCapid,
                                    darkCurrent,
                                    fcByPE,
                                    lambda,
                                    noisecorr,
                                    hwerr.first,
                                    hwerr.second,
                                    properties.taggedBadByDb || dropByZS || badSOI);
    ```
  - the last argument of `setChannelInfo` sets the `dropped_` flag, which is read via the `bool isDropped()` method
  - which in turn makes the producer skip this channel:
    ```c++
        // If needed, add the channel info to the output collection
        const bool makeThisRechit = !channelInfo->isDropped();
        [...]
    
        // Reconstruct the rechit
        if (rechits && makeThisRechit) {
            [...]
    ```

Now the question is - how do we skip a "bad" channel in the GPU reconstruction ?

**Comment by fwyzard** [comment] 2022-10-14 16:49
By the way, a source of problems is that `soiSamples` was uninitialised, henve the random value `-87`.

**Comment by fwyzard** [comment] 2022-10-14 18:30
OK.

In the meantime, I've prepared what I think is a fix to skip the channels affected by this problem, trying to follow the same approach used in the legacy rechit reconstruction: https://github.com/cms-sw/cmssw/pull/39738 .

**Comment by fwyzard** [comment] 2022-10-14 18:34
+heterogeneous

**Comment by fwyzard** [comment] 2022-10-15 08:46
The same error has been reported in [runs 360393 and 360400](https://cmsonline.cern.ch/webcenter/portal/cmsonline/Common/Elog?_piref683379043.strutsAction=%2FviewMessageDetails.do%3FmsgId%3D1160178).

Running with the candidate fix from #39740 lets all HLT jobs complete, with some HCAL-related messages:
```
%MSG-w HBHEDigi:  HBHEPhase1Reconstructor:hltHbherecoLegacy  15-Oct-2022 10:42:05 CEST Run: 360400 Event: 26202582
 bad SOI/maxTS in cell (HB -12,28,1)
 expect maxTS >= 3 && soi > 0 && soi < maxTS - 1
 got maxTS = 8, SOI = -1
%MSG
```
```
%MSG-w Invalid Data:  HcalRawToDigi:hltHcalDigis 15-Oct-2022 10:42:45 CEST  Run: 360400 Event: 44480955
The default QIE11 Collection has 8 samples per digi, while the current data has 17!  This data cannot be included with the default collection.
In order to store this data in the event, it must have a unique tag.  To accomplish this, provide two lists to HcalRawToDigi 
1) that specifies the number of samples and 2) that gives tags with which these data are saved.
For example in this case you might add 
process.hcalDigis.saveQIE11DataNSamples = cms.untracked.vint32( 17) 
process.hcalDigis.saveQIE11DataTags = cms.untracked.vstring( "MYDATA" )
%MSG
```
```
%MSG-w HBHEDigi:  HBHEPhase1Reconstructor:hltHbherecoLegacy  15-Oct-2022 10:43:04 CEST Run: 360400 Event: 136235629
 bad SOI/maxTS in cell (HB 11,27,1)
 expect maxTS >= 3 && soi > 0 && soi < maxTS - 1
 got maxTS = 8, SOI = -1
%MSG
%MSG-w HBHEDigi:  HBHEPhase1Reconstructor:hltHbherecoLegacy  15-Oct-2022 10:43:04 CEST Run: 360400 Event: 136235629
 bad SOI/maxTS in cell (HB -9,30,3)
 expect maxTS >= 3 && soi > 0 && soi < maxTS - 1
 got maxTS = 8, SOI = -1
%MSG
```

**Comment by mmusich** [comment] 2022-10-24 09:31
@cms-sw/hcal-dpg-l2 please consider signing this issue.
@trtomei please consider closing this issue (as per [today's joint ops document](https://docs.google.com/document/d/1mDdCUu8PxEeWPLzG1SnKFQMFcxPR5bfGNMAQdJ1pG1s/edit#heading=h.ujw8h4xet7es) no more issues of this type were noticed in recent runs)

**Comment by wang-hui** [comment] 2022-10-24 12:23
Hi @mmusich the patch of this issue has been merged in #39738.
We HCAL DPG are happy with the patch.

**Comment by mmusich** [comment] 2022-10-24 12:27
@wang-hui then please sign-off this issue. 
Thanks.

**Comment by missirol** [comment] 2022-10-24 12:35
please close

**Closed** 2022-10-24 12:35 UTC
Labels: fully-signed, heterogeneous-approved, hcal-dpg-approved
