### ISSUE TITLE
POG approved photon id log warnings

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#20915] opened 2017-10-13 11:46 UTC
can these selectors be either disabled or POG approved?

%MSG
%MSG-w IdInformation:  VersionedPhotonIdProducer:egmPhotonIDs@ctor  13-Oct-2017 13:39:53 CEST pre-events
Instantiated ID: cutBasedPhotonID-Spring16-V2p2-loose
with MD5 hash: d6ce6a4f3476294bf0a3261e00170daf
This ID is not POG approved and likely under development!!!
Please make sure to report your progress with this ID at the next relevant POG meeting.

%MSG
%MSG-w IdInformation:  VersionedPhotonIdProducer:egmPhotonIDs@ctor  13-Oct-2017 13:39:53 CEST pre-events
Instantiated ID: cutBasedPhotonID-Spring16-V2p2-medium
with MD5 hash: c739cfd0b6287b8586da187c06d4053f
This ID is not POG approved and likely under development!!!
Please make sure to report your progress with this ID at the next relevant POG meeting.

%MSG
%MSG-w IdInformation:  VersionedPhotonIdProducer:egmPhotonIDs@ctor  13-Oct-2017 13:39:53 CEST pre-events
Instantiated ID: cutBasedPhotonID-Spring16-V2p2-tight
with MD5 hash: bdb623bdb1a15c13545020a919dd9530
This ID is not POG approved and likely under development!!!
Please make sure to report your progress with this ID at the next relevant POG meeting.

**Comment by davidlange6** [comment] 2017-10-13 11:47
assign reconstruction

**Comment by davidlange6** [comment] 2017-10-13 11:47
assign analysis

**Comment by slava77** [comment] 2017-10-13 13:23
@davidlange6 please clarify which release and workflow (and also the machine) where this was observed (in the past there was an instance where these warnings were dependent on local node setup)

@Sam-Harper @lgray 
please take a look

this may be a duplicate of 
https://github.com/cms-sw/cmssw/issues/19799

**Comment by slava77** [comment] 2017-10-13 13:24
@davidlange6 
please edit the issue title "pop" -> "POG" and perhaps add that there is a logWarning

**Comment by davidlange6** [comment] 2017-10-13 13:30
this was 9_2_13 workflow 148.0 that I happened to be looking at.

**Comment by Sam-Harper** [comment] 2017-10-13 13:34
Yes I dont think we backported https://github.com/cms-sw/cmssw/issues/19799, would you like us to?

**Comment by slava77** [comment] 2017-10-13 13:35
+1

since it's fixed in 93X (since July), I think it's fine as is, no backports necessary.

**Comment by davidlange6** [comment] 2017-10-13 13:39
i agree - thanks for the instant followup.

**Closed** 2017-10-16 06:49 UTC
Labels: analysis-pending, pending-signatures, reconstruction-approved
