### ISSUE TITLE
Error message on ForwardDiskSectorBuilderFromDet

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#39296] opened 2022-09-03 02:30 UTC
I see this error message appears in 2018 and 2021/22 PR test workflows,
```
%MSG-e TkDetLayers:   TrackerRecoGeometryESProducer:TrackerRecoGeometryESProducer@callESModule  02-Sep-2022 20:18:29 CEST Run: 1 Stream: 0
 ForwardDiskSectorBuilderFromDet: Trying to build Petal Wedge from Dets at different z positions !! Delta_z = -0.951241
%MSG
```
I assume it is known and can be ignored. If that is the case, should this message be cleaned up or we would like to keep this LogError?
https://github.com/cms-sw/cmssw/blob/master/RecoTracker/TkDetLayers/src/ForwardDiskSectorBuilderFromDet.cc

**Comment by makortel** [comment] 2022-09-03 13:56
assign geometry

**Comment by makortel** [comment] 2022-09-03 13:56
FYI @cms-sw/trk-dpg-l2

**Comment by mmusich** [comment] 2022-09-03 15:54
Duplicate of https://github.com/cms-sw/cmssw/issues/34476, please close.

**Closed** 2023-02-28 18:16 UTC
Labels: geometry-pending, pending-signatures
