### ISSUE TITLE
PVFitter leaks memory

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#19003] opened 2017-05-30 01:15 UTC
PVFitter calls `new` but does not delete those items. To fix

-change `hPVx` and `hPVy` to be `std::unique_ptr<TH2F>` and call `SetDirectory(nullptr)` on them to make sure they are not attached to the global directory
-Do not call `new` to create `FcnBeamSpotFitPV`. Instead, just create them on the stack.

**Comment by Dr15Jones** [comment] 2017-05-30 01:16
assign reconstruction,alca

**Comment by Dr15Jones** [comment] 2017-05-30 01:17
This will leak every LuminosityBlock

**Comment by VinInn** [comment] 2017-06-16 17:10
is this fixed?

**Comment by slava77** [comment] 2017-06-16 17:16
On 6/16/17 10:10 AM, Vincenzo Innocente wrote:
> is this fixed?

not that I'm aware (in a PR form).
May I ask you to add "@" for the PVFitter developers.
Thank you.

**Comment by VinInn** [comment] 2017-06-17 05:32
TRK-POG will take care at the some time of reducing the its memory footprint once the dust is settle...

**Comment by slava77** [comment] 2018-10-20 15:44
@VinInn @JanFSchulte @mtosi 
was this issue resolved?

**Comment by smuzaffar** [comment] 2019-11-18 21:06
looks like the leak is still there? Can some one please provide a fix?

**Comment by christopheralanwest** [comment] 2019-11-19 22:49
@francescobrivio @sarafiorendi Could you address the memory leaks in PVFitter? Thanks.

**Comment by francescobrivio** [comment] 2019-11-20 08:38
Hi @christopheralanwest , sorry we were not aware of this issue.
We will provide a PR to address this.

**Comment by francescobrivio** [comment] 2019-11-21 13:58
hi @christopheralanwest and @smuzaffar 
we have prepared a fix for this issue, you can preliminarily find it here:
https://github.com/MilanoBicocca-pix/cmssw/commit/28c5211ba906c51152db8616adb69f63d8582e74
Before opening a PR I would like to test if this solves the problem you mention, since in the last years we run with this code without incurring in any problem. 
Could you provide use a way to reproduce the memory leak?

**Comment by christopheralanwest** [comment] 2019-12-03 22:22
+1

This has been resolved by PR #28509.

**Comment by perrotta** [comment] 2019-12-27 09:02
+1
- Fixed by #28509

**Closed** 2020-01-16 17:54 UTC
Labels: alca-approved, fully-signed, reconstruction-approved
