### ISSUE TITLE
In `PixelBaryCentreAnalyzer`, `SiPixelQuality` is not updated when changing run

### ISSUE THREAD

**Issue by amecca** [cms-sw/cmssw#38812] opened 2022-07-21 11:36 UTC
When adding in [Alignment/OfflineValidation/plugins/PixelBaryCentreAnalyzer.cc:L302](https://github.com/cms-sw/cmssw/blob/master/Alignment/OfflineValidation/plugins/PixelBaryCentreAnalyzer.cc#L302) the following:
```c++
std::cout << usePixelQuality_ << '\t' << run_ << '\t' << badPixelInfo->BadModuleNumber() << std::endl;
```
Running with a run range:
```
$ cmsRun PixelBaryCentreAnalyzer_cfg.py firstRun=345747 lastRun=345863
Begin processing the 1st record. Run 345747, Event 1, LumiSection 1 on stream 0 at 21-Jul-2022 13:24:20.614 CEST
1	345747	66
0	345747	66
1	345863	66
0	345863	66
...
```
but with only one run:
```
$ cmsRun PixelBaryCentreAnalyzer_cfg.py firstRun=345863 lastRun=345863
1	345863	68
0	345863	68
...
```
So it seems that the `SiPixelQuality` object returned from `EventSetup::getData()` is not updated.

Note that you may have to make [SiPixelQuality::BadModuleNumber()](https://cmsdoxygen.web.cern.ch/cmsdoxygen/CMSSW_12_4_3/doc/html/d5/d0d/classSiPixelQuality.html#a483e7b8623775c731b6e586ee10a1e23) const.

**Comment by tvami** [comment] 2022-07-21 12:43
assign alca

**Comment by tvami** [comment] 2022-07-21 12:45
Shouldnt this
https://github.com/cms-sw/cmssw/blob/master/Alignment/OfflineValidation/plugins/PixelBaryCentreAnalyzer.cc#L129
watch for lumisections?

**Comment by tvami** [comment] 2022-07-21 12:53
i.e.
siPixelQualityToken_(esConsumes<SiPixelQuality, SiPixelQualityFromDbRcd>()),
-->
siPixelQualityToken_(esConsumes<SiPixelQuality, SiPixelQualityFromDbRcd, edm::Transition::BeginLuminosityBlock>()),
or
siPixelQualityToken_(esConsumes<SiPixelQuality, SiPixelQualityFromDbRcd, edm::Transition::EndRun>()),
not really sure if you need to transition really at the lumi block, or the end run, you problably are fine at the end run. But can you try both and see the diff? @amecca

**Comment by mmusich** [comment] 2022-07-21 12:55
the call is done at `analyze`:

https://github.com/cms-sw/cmssw/blob/d7e416cc8b5654e29c68d406d6aecd52a80561e9/Alignment/OfflineValidation/plugins/PixelBaryCentreAnalyzer.cc#L218

so the `esConsumes` statement is correct. 
IF one wants to watch for LS it should be done in the `beginLuminosityBlock` transition (this analyzer doesn't have the method). Also it would beg the question of which LS to take since the analysis is done per run.

**Comment by tvami** [comment] 2022-07-21 12:58
@mmusich ok, what about the end run transition then? Could that solve the issue?

**Comment by mmusich** [comment] 2022-07-21 13:02
> , what about the end run transition then? Could that solve the issue?

I think the problem is a bit "ill-defined" as there is no "per-Run"  pixel quality.

**Comment by amecca** [comment] 2022-07-21 15:05
Indeed, since the call to `EventSetup::getData()` is done in the `analyze()` method, changing the token's initialization to 
```
siPixelQualityToken_(esConsumes<SiPixelQuality, SiPixelQualityFromDbRcd, edm::Transition::BeginLuminosityBlock>()),
```
causes an error [1] at runtime.

Just to be clear, this tool needs per-IOV pixel quality, so the original author used an ESWatcher to monitor the TrackerAlignmentRcd and fetch the SiPixelQuality only when it changes.
We are aware that this might not be the optimal solution.

One solution could be to modify the `esConsume` statement and fetch the pixel quality in `beginRun()`.
Another one would be to change the plugin type from EDAnalyzer to something more appropriate.

Which one would you suggest @tvami?

<details>
<summary>[1]</summary>
Begin processing the 1st record. Run 345747, Event 1, LumiSection 1 on stream 0 at 21-Jul-2022 16:18:04.486 CEST<br>
----- Begin Fatal Exception 21-Jul-2022 16:18:04 CEST-----------------------<br>
An exception of category 'ESGetTokenWrongTransition' occurred while<br>
   [0] Processing  Event run: 345747 lumi: 1 event: 1 stream: 0<br>
   [1] Running path 'p'<br>
   [2] Calling method for module PixelBaryCentreAnalyzer/'PixelBaryCentreAnalyzerWithPixelQuality'<br>
Exception Message:<br>
The transition ID stored in the ESGetToken does not match the<br>
transition where the token is being used. The associated record<br>
type is: SiPixelQualityFromDbRcd<br>
For producers, filters and analyzers this transition ID is<br>
set as a template parameter to the call to the esConsumes<br>
function that creates the token. Event is the default transition.<br>
Other possibilities are BeginRun, EndRun, BeginLuminosityBlock,<br>
or EndLuminosityBlock. You may need multiple tokens if you want to<br>
get the same data in multiple transitions. The transition ID has a<br>
different meaning in ESProducers. For ESProducers, the transition<br>
ID identifies the function that produces the EventSetup data (often<br>
there is one function named produce but there can be multiple<br>
functions with different names). For ESProducers, the ESGetToken<br>
must be used in the function associated with the ESConsumesCollector<br>
returned by the setWhatProduced function.<br>
----- End Fatal Exception -------------------------------------------------  
</details>

**Comment by makortel** [comment] 2022-07-21 18:08
The `SiPixelQuality` in `SiPixelQualityFromDbRcd` record comes directly from the conditions database, right? I suppose further investigations would need a recipe to reproduce the described behavior.

**Comment by mmusich** [comment] 2022-07-21 18:37
> The `SiPixelQuality` in `SiPixelQualityFromDbRcd` record comes directly from the conditions database, right? 

Yes, even though it would be probably better to fetch it from `SiPixelQualityRcd`, which  comes from an `ESProducer` (this would need an aside follow-up)

>  I suppose further investigations would need a recipe to reproduce the described behavior.

I think the issue description gives a way to reproduce, including the exact commands.
Though this

> Note that you may have to make [SiPixelQuality::BadModuleNumber()](https://cmsdoxygen.web.cern.ch/cmsdoxygen/CMSSW_12_4_3/doc/html/d5/d0d/classSiPixelQuality.html#a483e7b8623775c731b6e586ee10a1e23) const.

is not really needed,  one can just print: 

```
std::cout << usePixelQuality_ << '\t' << run_ << '\t' << badPixelInfo->getBadComponentList().size() << std::endl;
```

**Comment by makortel** [comment] 2022-07-21 19:25
Thanks @mmusich. In 12_5_0_pre3 I get consistently 68 for both runs (345747 and 345863, when run together or separately).

If I interpret the output of `conddb list SiPixelQuality_v07_offline` correctly, both of these runs are covered with the same IOV (`[345747:1, 346169:1[`), so the value should be the same for those runs.

Is the problem then why in one case it gave (or still gives?) 66 and in other case 68 even if they should be the same?

**Comment by mmusich** [comment] 2022-07-21 19:36
> Is the problem then why in one case it gave (or still gives?) 66 and in other case 68 even if they should be the same?

I think so, though @amecca should clarify better. 
On a side note the configuration is using an `EmptySource`  with 1 event per run in the first LS:

https://github.com/cms-sw/cmssw/blob/3366348d820fac30187461f83eac3ca20e010840/Alignment/OfflineValidation/test/PixelBaryCentreAnalyzer_cfg.py#L47-L53

I don't know if this plots a role.

**Comment by amecca** [comment] 2022-07-21 19:58
> Thanks @mmusich. In 12_5_0_pre3 I get consistently 68 for both runs (345747 and 345863, when run together or separately).
I forgot that I had changed the GlobalTag in the config from `"auto:run2_data"` to `"124X_dataRun3_v9"`.
This is the exact recipe to reproduce the issue.


> Is the problem then why in one case it gave (or still gives?) 66 and in other case 68 even if they should be the same?

**Comment by makortel** [comment] 2022-07-21 20:15
> > In 12_5_0_pre3 I get consistently 68 for both runs (345747 and 345863, when run together or separately).
> 
> I forgot that I had changed the GlobalTag in the config from `"auto:run2_data"` to `"124X_dataRun3_v9"`. This is the exact recipe to reproduce the issue.

Thanks. With `124X_dataRun3_v9` I was able to reproduce the issue, i.e. 345747 alone gives consistently 66, 345863 alone gives consistently 68, and together they give 66. I see `124X_dataRun3_v9` has the same tag `SiPixelQuality_v07_offline` as `124X_dataRun2_v2`, so the IOV structure is the same, which explains why framework does not update anything in `SiPixelQualityFromDbRcd` between those runs.

As of why `PoolDBESSource` in some situations gives a `SiPixelQuality` object giving 66 and in some other cases 68, I have no idea (at the moment).

**Comment by mmusich** [comment] 2022-07-21 20:18
> As of why PoolDBESSource in some situations gives a SiPixelQuality object giving 66 and in some other cases 68, I have no idea (at the moment).

As I have already discussed with @amecca it's not a good idea to use `124X_dataRun3_v9` when analyzing ~recent runs because it has a snapshot and the framework will not deliver IoVs inserted in the DB more recently than the snapshot.

**Comment by Dr15Jones** [comment] 2022-07-22 13:33
@mmusich it appears that when using a snapshot, if someone requests data for a run beyond the end of the snapshot they are given the last IOV instead. Instead, would it be possible to not return a data product at all in the cases where one is requesting data for a run off the end of the snapshot?

**Comment by mmusich** [comment] 2022-07-22 14:33
@Dr15Jones 

> it appears that when using a snapshot, if someone requests data for a run beyond the end of the snapshot they are given the last IOV instead.

Yes, this is the original design from when we moved to CondDB version2.

> Instead, would it be possible to not return a data product at all in the cases where one is requesting data for a run off the end of the snapshot?

I think the technical part of the question pertains to @cms-sw/db-l2. 
From a consumer perspective, changing the behavior in the suggested way might be useful in certain situations to spot "buggy" configurations, on the other hand, it would need some careful consideration because I suspect that there are many users relying on the feature "implicitly" when applied correctly, and should certainly be widely announced.

**Comment by tvami** [comment] 2022-07-22 14:40
> I think the technical part of the question pertains to https://github.com/orgs/cms-sw/teams/db-l2.

Giacomo is on vacation, so it will take some time to get an answer from him

**Comment by tvami** [comment] 2022-07-27 19:28
+alca
 * the problem reported in the issue is solved by using the correct GT
 * after discussing the getData functionality with snapshots with @ggovi and @cms-sw/alca-l2 the decision is that this is a feature and thus it's category `wontfix`

**Comment by ggovi** [comment] 2022-07-28 07:56
Hello,
the feature under discussion is implemented by selecting the iovs inserted before the 'freezing' timestamp. This implementation replaces the condbv1 solution, that was based on dedicated snapshot databases exported on demand by the DBAs.  The final behaviour is the same, as it depends only on the 'open iov' approach, that has been adopted in CMS since the early phases. 
On the other hand, @Dr15Jones  has a point. If this is the desired behaviour, the implementation should be not too complex.

**Comment by mmusich** [comment] 2022-07-28 10:07
@ggovi 

> . If this is the desired behaviour, the implementation should be not too complex.

Out of curiosity could such a mechanism be implemented "on demand", such that it throws if no data is found when a certain "strict" flag is demanded, but the default is not changed?

**Comment by ggovi** [comment] 2022-07-28 14:17
@mmusich Yes it could be possibly on demand, we need to define properly the usage and the policy.

**Comment by amecca** [comment] 2022-08-02 14:03
@ggovi should we open another issue to request the implementation of such mechanism?

**Comment by mmusich** [comment] 2022-08-02 14:13
This is issue is fully signed, can it be closed? @amecca

**Comment by amecca** [comment] 2022-08-02 14:22
Thanks. Yes, this issue can be closed

**Comment by mmusich** [comment] 2022-08-02 14:26
@amecca, since you own it, feel free to close it. Thx

**Closed** 2022-08-02 14:31 UTC
Labels: alca-approved, fully-signed
