### ISSUE TITLE
Two versions of class TrackQuality

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#32895] opened 2021-02-12 14:24 UTC
We have two separate classes both named TrackQuality:
https://github.com/cms-sw/cmssw/blob/master/SimTracker/TrackHistory/interface/TrackQuality.h
https://github.com/cms-sw/cmssw/blob/master/L1Trigger/TrackTrigger/interface/TrackQuality.h

both live in the global namespace. The L1Trigger one was added in December of 2020 and should be moved to a namespace (e.g. l1trigger).

**Comment by Dr15Jones** [comment] 2021-02-12 14:24
assign simulation, l1

**Comment by davidlange6** [comment] 2021-02-12 14:28
Perhaps related to #32894

**Comment by makortel** [comment] 2021-02-23 13:33
@cms-sw/l1-l2 (also @cms-sw/simulation-l2) Could you please take a look?

**Comment by civanch** [comment] 2021-02-23 14:14
@cms-sw/l1-l2 , because L1 class was introduced just recently, it would be natural, that it is renamed and not very old class from Sim. Of course, if this is not possible we will rename.

**Comment by civanch** [comment] 2021-09-13 11:30
@rekovic, @jmduarte, @cecilecaillol, is this issue already fixed?

**Comment by civanch** [comment] 2021-12-05 07:24
@cecilecaillol, @rekovic can we address this?

**Comment by cecilecaillol** [comment] 2022-04-11 15:02
The issue is addressed in https://github.com/cms-sw/cmssw/pull/37495 and can be closed

**Closed** 2022-04-11 15:04 UTC
Labels: simulation-pending, l1-approved, pending-signatures
