### ISSUE TITLE
[ROOT626] A list is accessing an object already deleted

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#43887] opened 2024-02-07 10:44 UTC
Unit test TrackPropagation/Geant4e/testG4Refitter [failed](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_1_ROOT626_X_2024-02-06-2300/unitTestLogs/TrackPropagation/Geant4e#/7662-7662) in CMSSW_14_1_ROOT626_X_2024-02-06-2300:

```
===== Test "testG4Refitter" ====
%MSG-i AlpakaService:  (NoModuleName) 07-Feb-2024 08:25:04 CET pre-events
AlpakaServiceSerialSync succesfully initialised.
Found 1 device:
  - Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz
%MSG
07-Feb-2024 08:25:11 CET  Initiating request to open file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_14_0_0_pre2/RelValSingleMuPt10/GEN-SIM-RECO/133X_mcRun3_2023_realistic_v3_STD-v2/2590000/da5cf255-2d65-41ec-ac89-45daf33c66d3.root
07-Feb-2024 08:25:18 CET  Initiating request to open file root://cms-xrd-global.cern.ch//eos/cms/store/relval/CMSSW_14_0_0_pre2/RelValSingleMuPt10/GEN-SIM-RECO/133X_mcRun3_2023_realistic_v3_STD-v2/2590000/da5cf255-2d65-41ec-ac89-45daf33c66d3.root
07-Feb-2024 08:25:20 CET  Initiating request to open file root://xrootd-cms.infn.it//store/relval/CMSSW_14_0_0_pre2/RelValSingleMuPt10/GEN-SIM-RECO/133X_mcRun3_2023_realistic_v3_STD-v2/2590000/da5cf255-2d65-41ec-ac89-45daf33c66d3.root
%MSG-w RootInputFileSequence:  file_open 07-Feb-2024 08:25:22 CET pre-events
Input file root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_14_0_0_pre2/RelValSingleMuPt10/GEN-SIM-RECO/133X_mcRun3_2023_realistic_v3_STD-v2/2590000/da5cf255-2d65-41ec-ac89-45daf33c66d3.root could not be opened, and fallback was attempted.
Additional information:
  [a] Fatal Root Error: @SUB=TList::Clear
A list is accessing an object (0x14e7f1235ae0) already deleted (list name = TList)

Input file root://cms-xrd-global.cern.ch//eos/cms/store/relval/CMSSW_14_0_0_pre2/RelValSingleMuPt10/GEN-SIM-RECO/133X_mcRun3_2023_realistic_v3_STD-v2/2590000/da5cf255-2d65-41ec-ac89-45daf33c66d3.root could not be opened, and fallback was attempted.
Additional information:
  [a] Fatal Root Error: @SUB=TList::Clear
A list is accessing an object (0x14e7f0b91c80) already deleted (list name = TList)


%MSG
----- Begin Fatal Exception 07-Feb-2024 08:25:22 CET-----------------------
An exception of category 'FallbackFileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   Additional Info:
      [a] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://cms-xrd-global.cern.ch//eos/cms/store/relval/CMSSW_14_0_0_pre2/RelValSingleMuPt10/GEN-SIM-RECO/133X_mcRun3_2023_realistic_v3_STD-v2/2590000/da5cf255-2d65-41ec-ac89-45daf33c66d3.root
      [b] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://eoscms.cern.ch//eos/cms/store/user/cmsbuild/store/relval/CMSSW_14_0_0_pre2/RelValSingleMuPt10/GEN-SIM-RECO/133X_mcRun3_2023_realistic_v3_STD-v2/2590000/da5cf255-2d65-41ec-ac89-45daf33c66d3.root
      [c] Input file root://xrootd-cms.infn.it//store/relval/CMSSW_14_0_0_pre2/RelValSingleMuPt10/GEN-SIM-RECO/133X_mcRun3_2023_realistic_v3_STD-v2/2590000/da5cf255-2d65-41ec-ac89-45daf33c66d3.root could not be opened.
      [d] Fatal Root Error: @SUB=TList::Clear
A list is accessing an object (0x14e7dcd0fa40) already deleted (list name = TList)

----- End Fatal Exception -------------------------------------------------

---> test testG4Refitter had ERRORS
TestTime:26
^^^^ End Test testG4Refitter ^^^^
```

**Comment by iarspider** [comment] 2024-02-07 10:44
assign TrackPropagation/Geant4e

**Comment by smuzaffar** [comment] 2024-02-07 10:56
@iarspider , I think this is related to https://github.com/cms-sw/cmssw/issues/43882 . ROOT fix https://github.com/root-project/root/pull/12845 has already been back ported to earlier root releases. Please update root 6.26 for 14.1.X root626 branch

**Comment by makortel** [comment] 2024-02-07 14:18
Right, this issue is a duplicate of https://github.com/cms-sw/cmssw/issues/43882

**Closed** 2024-02-07 15:10 UTC
Labels: simulation-pending, pending-signatures, tracking
