### ISSUE TITLE
GPU tests are failing after moving to GCC12

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#42997] opened 2023-10-12 06:37 UTC
RelVals/unittests are failing for GPU IBs after moving to GCC12. Looks like the `cuda-compatible-runtime` does not find any supported cuda device [a]. Looks like cuda driver version 12.1 and our runtime cuda 12.2 are not compatible.

FYI @fwyzard 

[a]
```
Singularity> nvidia-smi
Thu Oct 12 08:28:20 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-PCIE-40GB           Off| 00000000:00:06.0 Off |                    0 |
| N/A   29C    P0               37W / 250W|      2MiB / 40960MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
Singularity> /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02806/el8_amd64_gcc12/external/cuda-compatible-runtime/1.0-e595d828442cc07b078b61d178cb6872/test/cuda-compatible-runtime -k -v
CUDA driver version 12.1
CUDA runtime version 12.2
None of the CUDA devices supports launching and running a CUDA kernel.
```

**Comment by fwyzard** [comment] 2023-10-12 07:33
@smuzaffar where can I find a machine with CUDA 12.1 / 530.30.02 ?

**Comment by smuzaffar** [comment] 2023-10-12 07:53
@fwyzard , CERN HTCondor gpu nodes have cuda 12.1. I will send you the instructions to access one of these nodes

**Comment by fwyzard** [comment] 2023-10-18 07:35
Unfortunately, it looks like this is the expected behaviour, according to NVIDIA.

CUDA 12.x requires the 525.x (or later) drivers:
![image](https://github.com/cms-sw/cmssw/assets/4069793/a6e3c58f-d79c-4b1f-b625-9ced3bf36539)

Or it requires the 450.x/470.x drivers, with the compatibility layer (that we include in CMSSW):
![image](https://github.com/cms-sw/cmssw/assets/4069793/3c252153-603c-40e5-b420-e430de0ef8c8)

**Comment by fwyzard** [comment] 2023-10-18 07:36
However, this explains why the tests fail on machines with CUDA 11.8 .

The tests _should_ work on machines with CUDA 12.1 .

**Comment by smuzaffar** [comment] 2023-10-18 08:07
@fwyzard , following runs on node with cuda 12.1
```
/cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02807/el8_amd64_gcc12/external/cuda-compatible-runtime/1.0-e595d828442cc07b078b61d178cb6872/test/cuda-compatible-runtime  && echo OK
12.2
OK
```

but it fails when `-k (If there are any CUDA devices, check that at least one supports launching a CUDA kernel)` option is used 
```
Singularity> /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02807/el8_amd64_gcc12/external/cuda-compatible-runtime/1.0-e595d828442cc07b078b61d178cb6872/test/cuda-compatible-runtime  -k && echo OK
12.2
```

**Comment by smuzaffar** [comment] 2023-10-18 08:13
ok htcondor nodes we have `NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1` but looks like `530.30.02` is not compatible with compatibility layer we have in cmssw

**Comment by fwyzard** [comment] 2023-10-18 08:19
Mhm, with 530.x we should _not_ need the compatibility layer, CUDA 12.2.x should work out of the box.

**Comment by fwyzard** [comment] 2023-10-18 08:21
```
fwyzard@devfu-c2b03-44-01.cms:~$ nvidia-smi
Wed Oct 18 10:20:46 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                        On | 00000000:23:00.0 Off |                    0 |
| N/A   36C    P8               11W /  70W|      2MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla T4                        On | 00000000:E2:00.0 Off |                    0 |
| N/A   39C    P8               11W /  70W|      2MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

fwyzard@devfu-c2b03-44-01.cms:~$ /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02807/el8_amd64_gcc12/external/cuda-compatible-runtime/1.0-e595d828442cc07b078b61d178cb6872/test/cuda-compatible-runtime -k && echo OK
12.2
OK
```

**Comment by fwyzard** [comment] 2023-10-18 08:21
Maybe there is a problem with the container image ?

**Comment by fwyzard** [comment] 2023-10-18 08:27
It works also inside the container:
```
fwyzard@devfu-c2b03-44-01.cms:~$ cmssw-el8 --nv
Singularity> nvidia-smi
Wed Oct 18 10:26:35 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                        On | 00000000:23:00.0 Off |                    0 |
| N/A   36C    P8               12W /  70W|      2MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla T4                        On | 00000000:E2:00.0 Off |                    0 |
| N/A   39C    P8               12W /  70W|      2MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
Singularity> /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02807/el8_amd64_gcc12/external/cuda-compatible-runtime/1.0-e595d828442cc07b078b61d178cb6872/test/cuda-compatible-runtime -k && echo OK
12.2
OK
Singularity> cd /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02807/el8_amd64_gcc12/cms/cmssw/CMSSW_13_3_X_2023-10-17-2300
Singularity> cmsenv
Singularity> cudaComputeCapabilities 
   0     7.5    Tesla T4
   1     7.5    Tesla T4
```

**Comment by smuzaffar** [comment] 2023-10-18 08:28
then could it be the problem with A100 GPU? on htcondor I see we have `NVIDIA A100-PCIE-40GB`  while you are testing  `Tesla T4`

**Comment by fwyzard** [comment] 2023-10-18 08:30
I would need to check locally.
Can you remind me how to use a condor node ?

**Comment by smuzaffar** [comment] 2023-10-18 08:37
To use one of the htcondior node please do (from lxplus)
```
> ~cmsbuild/public/lxplus
> export _CONDOR_SCHEDD_HOST=bigbird21.cern.ch
> export _CONDOR_CREDD_HOST=bigbird21.cern.ch
> condor_ssh_to_job -auto-retry 230323.0
```

this node is available for next 5 hours and then it will be deleted.

**Comment by smuzaffar** [comment] 2023-10-18 08:40
may be for A100, we need to build for `sm_80/compute_80` ( https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_13_3_X/master/cuda-flags.file#L7 )?

**Comment by smuzaffar** [comment] 2023-10-18 08:50
by the way, gpu tests for 13.2.X work

**Comment by fwyzard** [comment] 2023-10-18 08:54
OK, I see the problem between gcc 11 / cuda 11.8 and gcc 12 / cuda 12.2:
```
bash-4.2$ /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02807/el8_amd64_gcc11/external/cuda-compatible-runtime/1.0-ca249f5e31a49bcfe53fea771aa4a1dc/test/cuda-compatible-runtime -k && echo OK
11.8
OK
```
vs
```
bash-4.2$ /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02807/el8_amd64_gcc12/external/cuda-compatible-runtime/1.0-e595d828442cc07b078b61d178cb6872/test/cuda-compatible-runtime -k && echo OK
12.2
```

**Comment by fwyzard** [comment] 2023-10-18 09:25
If that is the reason, https://github.com/cms-sw/cmsdist/pull/8767 might fix the problem.

**Comment by makortel** [comment] 2023-10-23 15:19
The tests are now working, so I think we can close this issue

**Closed** 2023-10-23 15:20 UTC
Labels: core-approved, fully-signed, heterogeneous-approved

**Comment by iarspider** [comment] 2023-10-24 08:46
There is still a failing GPU test: https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_13_3_GPU_X_2023-10-23-2300/unitTestLogs/PhysicsTools/TensorFlow#/154-154

@fwyzard could you please take a look?

**Comment by smuzaffar** [comment] 2023-10-24 08:49
@iarspider , we should fix this test to not run as TF for GCC12/CUDA12  is not built with CUDA support

**Comment by fwyzard** [comment] 2023-10-24 09:02
> There is still a failing GPU test: https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_13_3_GPU_X_2023-10-23-2300/unitTestLogs/PhysicsTools/TensorFlow#/154-154
> 
> @fwyzard could you please take a look?

See https://github.com/cms-sw/cmssw/issues/42883 .

**Comment by fwyzard** [comment] 2023-10-24 09:05
@iarspider I think you were looking in it yourself with https://github.com/cms-sw/cmsdist/pull/8732 ?
