### ISSUE TITLE
Use a dict to specify how to change subvalues of a PSet

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#13210] opened 2016-02-06 23:38 UTC
In the module `clone` method and in the `Modifier.toModify` method one sometimes needs to modify methods which are found down a chain of PSets. The present method is unwieldy and error prone

```python
myMod.clone(foo = myMod.foo.clone(
                bar= myMod.foo.bar.clone(
                    giin=5, 
                    fib=6.2)
                ),
            sab = myMod.sab.clone(
                ren = "qik")
            )
```

Instead, we could accept a python dictionary to specify the subvalue to change
```python
myMod.clone(foo = {"bar": {"giin":5, 
                           "fib": 6.2}},
            sab = {"ren": "qik"})
```
or one can even use the standard python `dict` function to write
```python
myMod.clone(foo = dict( bar = dict(giin=5, 
                                   fib = 6.2)),
            sab = dict( ren = "qik"))
```

**Comment by Dr15Jones** [comment] 2016-02-06 23:39
@makortel I think this might make some of the modifications simpler

**Comment by Dr15Jones** [comment] 2016-02-06 23:39
assign core

**Comment by makortel** [comment] 2016-02-08 08:50
@Dr15Jones Indeed it would, thanks. Is this issue a duplicate of #13167? (I like the syntax of this issue more, especially the `dict` variant that avoids quotes).

**Comment by Dr15Jones** [comment] 2016-02-08 19:37
#13224

**Comment by Dr15Jones** [comment] 2016-02-08 19:38
+1

**Closed** 2016-04-14 09:17 UTC
Labels: core-approved, fully-signed
