### ISSUE TITLE
DeepTauId module throws exception returning nan

### ISSUE THREAD

**Issue by peruzzim** [cms-sw/cmssw#28358] opened 2019-11-07 13:02 UTC
The DeepTauId producer has thrown this exception:

https://github.com/cms-sw/cmssw/blob/619b1aa756a2181a5d946f22b4bba8c96c57b84d/RecoTauTag/RecoTau/plugins/DeepTauId.cc#L1008-L1009

in a NanoAODv6 production workflow:
`invalid prediction = -nan for tau_index = 0, pred_index = 0`

Please see https://its.cern.ch/jira/browse/CMSCOMPPR-10135 for details.
@rmanzoni @roger-wolf can you please follow up?

@pgunnell

**Comment by peruzzim** [comment] 2019-11-07 13:06
assign reconstruction

**Comment by slava77** [comment] 2019-11-07 13:24
IMHO, there should be no throw; we are generally not throwing on FPEs.
The data should be flagged appropriately (LogWarning or LogError depending on perceived importance) and the job should continue.

**Comment by peruzzim** [comment] 2019-11-07 13:35
A small request in case you touch this: would be preferrable to avoid having nan in Mini/NanoAOD for people using this in trainings or other selections. If you deem it ok, it would be better to put a background-like value such as -1 in case there is no value to put.

**Comment by rmanzoni** [comment] 2019-11-07 14:27
@mbluj @swozniewski @kandrosov 
please have a look at this issue.

I don't see anything wrong with @peruzzim's proposal to return -1 rather than NaN.
And turning this into a LogWarning (certainly not an Error imo) as @slava77 suggests wouldn't be bad either.

**Comment by rmanzoni** [comment] 2019-11-07 14:30
there's a few more `throw` in DeepTauId.cc, I think they could use the same treatment, in principle

**Comment by kandrosov** [comment] 2019-11-07 16:15
In DeepTau implementation there are protections against having NaN as the output. It should never happen. For that reason, the exception is thrown if the check is not passed. If it happens, I would consider it a strong indication that there is some significant bug and in the presence of such bug, I would do not trust also the results where output is not a NaN. In the private productions done by tau POG and other analysis groups, this exception was never raised... With which CMSSW release are you having this error?  Could it be related to this PR https://github.com/cms-sw/cmssw/pull/28128 ?

**Comment by peruzzim** [comment] 2019-11-07 16:18
@kandrosov please check the link above for all informations on the release, the cmsRun command, the input file etc.

**Comment by kandrosov** [comment] 2019-11-07 17:21
@peruzzim Thanks!  Hm... I don't succeed to reproduce the error. I ran the following commands:
```sh
cmsrel CMSSW_10_2_18
cd CMSSW_10_2_18/src
cmsenv
wget https://cms-unified.web.cern.ch/cms-unified//joblogs/pgunnell_Run2017C-31Mar2018-v1-HighMultiplicityEOF3-Nano25Oct2019_10218_191031_170638_7952/8001/DataProcessing/e7606528-7e28-4359-a2aa-a4cb5c6b546d-46-0-logArchive/job/WMTaskSpace/cmsRun1/PSet.py
wget https://cms-unified.web.cern.ch/cms-unified//joblogs/pgunnell_Run2017C-31Mar2018-v1-HighMultiplicityEOF3-Nano25Oct2019_10218_191031_170638_7952/8001/DataProcessing/e7606528-7e28-4359-a2aa-a4cb5c6b546d-46-0-logArchive/job/WMTaskSpace/cmsRun1/PSet.pkl
cmsRun  -j FrameworkJobReport.xml PSet.py
```
Could you, please, confirm that these steps should lead to the same output as the crashed job [1]? 
If yes, a non-reproducibility could mean some problem with the setup on the machine where the job ran,   or some thread safety issue in the DeepTau producer.

[1] http://cern.ch/go/7grD

**Comment by peruzzim** [comment] 2019-11-13 09:34
Can you please follow up with PdmV in the JIRA ticket mentioned above?

**Comment by pgunnell** [comment] 2019-11-14 09:09
Dear all, I confirm that this might be to a site problem (MIT) in production. We ask computing to resubmit the failing jobs. Thanks a lot for all your effort, there was no hint that this error could come from a site issue and not from the code.

@kandrosov @peruzzim

**Comment by davidlange6** [comment] 2019-11-14 09:15
What sort of “site problem”? Corrupt cvmfs cache? Or is this more of a guess?

On Nov 14, 2019, at 10:09 AM, pgunnell <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear all, I confirm that this might be to a site problem (MIT) in production. We ask computing to resubmit the failing jobs. Thanks a lot for all your effort, there was no hint that this error could come from a site issue and not from the code.

@kandrosov<https://github.com/kandrosov> @peruzzim<https://github.com/peruzzim>

**Comment by pgunnell** [comment] 2019-11-14 14:52
it's a guess but we had 5 wf failures in computing all running at MIT. The error is what you see in the jira ticket (https://its.cern.ch/jira/browse/CMSCOMPPR-10135). I suspect it was a glitch on reading the input file of DeepTau but not sure how to check that.

**Comment by srimanob** [comment] 2019-11-21 10:42
Maybe this issue can be closed as the conclusion is about the site, and re-open if need.

**Comment by perrotta** [comment] 2019-11-21 10:48
Were the failing jobs resubmitted, as requested/anticipated in https://github.com/cms-sw/cmssw/issues/28358#issuecomment-553794615?
Did the re-submissions complete without errors?

**Comment by peruzzim** [comment] 2019-12-09 14:15
@pgunnell do we have news about the resubmitted jobs? Would be good to be sure that it was indeed not a code problem, in view of future productions.

**Comment by pgunnell** [comment] 2019-12-09 16:29
I confirm @peruzzim . For the resubmitted jobs, there was no problem.

**Comment by peruzzim** [comment] 2019-12-11 16:44
thanks, then I think this can be closed

**Comment by slava77** [comment] 2020-09-05 01:55
+1

based on earlier comments, this issue was apparently transient and there were no issues found with the code logic

**Closed** 2020-09-05 02:11 UTC
Labels: fully-signed, reconstruction-approved

**Comment by VinInn** [comment] 2023-02-09 18:18
it would be useful to have full details of the Hardware were the error occurred.
If there is a real hardware issue and nothing specifically related to the code used by DeepTau it could affect many other parts of any kind of job running there.

We may have to develop and deploy some sort of ad-hoc test or just ask site to regularly run memory-checks.

**Comment by VinInn** [comment] 2023-02-09 18:22
I am not at all convinced that there is a proved evidence of hardware failure.
I think we need to make controlled experiments on machines where the problem occur and find the cause (not just the symptoms)

**Comment by kandrosov** [comment] 2023-02-10 15:12
I agree that there is no evidence so far whatever memory corruption occurs due to software or hardware issue. We did not succeed yet to reproduce it in the controlled environment that would allow to have a detailed debugging.

> Most of the time it is NOT memory corruption: it is just reading uninitialized memory

I'm not sure if reading uninitialized memory is more plausible than memory corruption. In the cases that I am aware of, such condition occurs only after some running period, i.e. for the first events DeepTau score is computed correctly. All inputs are screened against "unexpected NaNs". So we have a NN evaluation on finite inputs that starts to give NaNs after some "breaking point".

**Comment by VinInn** [comment] 2023-02-10 16:41
I have a logfile where it happens in the first event of a thread

**Comment by VinInn** [comment] 2023-02-11 14:35
cross posting:
My understanding is that TensorFlow is used in DeepTauId.
TnsorFlow is a fat library: uses different code on different hardware: I wonder if there has been any test to compare its result on a sse only machine, avx, avx2 and axv512.
If yes, which SSE-only machine has been used?
