### ISSUE TITLE
Failed to open the file 'PromptCalibProdSiStripGains_A.root'

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#33059] opened 2021-03-03 17:22 UTC
Two unit tests are failing in `CalibTracker/SiStripChannelGain`
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_11_3_X_2021-03-03-1100/unitTestLogs/CalibTracker/SiStripChannelGain#/
```
===== Test "testSSTGainPCL_fromRECO" ====
argument 0: testSSTGainPCL_fromRECO
argument 1: /bin/bash
argument 2: CalibTracker/SiStripChannelGain/test
argument 3: testSSTGain_PCL_FromRECO.sh
shell is: /bin/bash
Current directory is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100
topdir is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100
testdir is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/src/CalibTracker/SiStripChannelGain/test
tmpdir is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/tmp/slc7_amd64_gcc900
testbin is: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/test/slc7_amd64_gcc900
Running script: /data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_11_3_X_2021-03-03-1100/src/CalibTracker/SiStripChannelGain/test/testSSTGain_PCL_FromRECO.sh
03-Mar-2021 13:33:17 CET  Initiating request to open file file:PromptCalibProdSiStripGains_A.root
----- Begin Fatal Exception 03-Mar-2021 13:33:17 CET-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootInputFileSequence::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling File::sysopen()
Exception Message:
Failed to open the file 'PromptCalibProdSiStripGains_A.root'
   Additional Info:
      [a] Input file file:PromptCalibProdSiStripGains_A.root could not be opened.
      [b] open() failed with system error 'No such file or directory' (error code 2)
----- End Fatal Exception -------------------------------------------------
Failure running cmsRun testSSTGain_HARVEST_FromRECO.py 0: status 84
status = 21504

---> test testSSTGainPCL_fromRECO had ERRORS
 
^^^^ End Test testSSTGainPCL_fromRECO ^^^^
 
===== Test "checkMultiRunHarvestingOutput" ====
Error in <TFile::TFile>: file DQM_V0001_R000999999__Express__PCLTest__ALCAPROMPT.root does not exist
checkMultiRunHarvesting: ERROR. Could not find the file: DQM_V0001_R000999999__Express__PCLTest__ALCAPROMPT.root

---> test checkMultiRunHarvestingOutput had ERRORS
 
^^^^ End Test checkMultiRunHarvestingOutput ^^^^
>> Tests for package CalibTracker/SiStripChannelGain ran.

```

**Comment by silviodonato** [comment] 2021-03-03 17:22
assign alca

**Comment by silviodonato** [comment] 2021-03-03 17:23
I see the error appeared also in `CMSSW_11_2_X_2021-03-03-1100` even without merging any PRs https://cmssdt.cern.ch/SDT/html/cmssdt-ib/#/ib/CMSSW_11_2_X 
so it sounds like a transient problem

**Comment by makortel** [comment] 2021-03-03 17:30
Duplicate of #33055

**Closed** 2021-03-03 18:00 UTC
Labels: alca-pending, pending-signatures
