### ISSUE TITLE
C++ Modules support (based on Clang)

### ISSUE THREAD

**Issue by davidlt** [cms-sw/cmssw#15248] opened 2016-07-21 09:41 UTC
The current very basic draft exist here: https://github.com/davidlt/cmssw/tree/cpp-modules
It can only be used with DEVEL IBs as it requires Clang pre-3.9. We will be updating Clang as needed in DEVEL IBs.

How to use it?

```
scram p CMSSW_8_1_DEVEL_X_2016-07-19-1100
cmsenv
git cms-merge-topic davidlt:cpp-modules
rm -rf $CMSSW_BASE/cppmodulescache
mkdir -p $CMSSW_BASE/cppmodulescache

# Modify $CMSSW_BASE/config/BuildFile.xml
vim $CMSSW_BASE/config/BuildFile.xml

# Add the following line:
#
#   <flags INCLUDE="$(LOCALTOP)/src/FWCore/GNUCppStandardLibrary/interface"/>
#
# after:
#
#   <classpath path="+Project/LCG+SubSystem/+Package/tests+binary"/>
#

USER_CXXFLAGS="-fmodules -fmodules-cache-path=$CMSSW_BASE/cppmodulescache" scram b -v -j 1 COMPILER=llvm 2>&1 | tee b.log

# Alternative command:
USER_CXXFLAGS="-fmodules -Xclang -fmodules-local-submodule-visibility -fmodules-cache-path=$CMSSW_BASE/cppmodulescache" scram b -v -j 1 COMPILER=llvm 2>&1 | tee b.log
```

**Comment by davidlt** [comment] 2016-07-21 09:42
@vgvassilev: iostream.h -> iostream

**Comment by davidlt** [comment] 2016-07-21 13:45
@vgvassilev if we use `-Xclang -fmodules-local-submodule-visibility` we get:
```
>> Compiling  /mnt/build/davidlt/cppmodules/CMSSW_8_1_DEVEL_X_2016-07-17-2300/src/FWCore/MessageService/bin/Standalone.cpp
/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/llvm/3.8.99/bin/clang++ -c -DGNU_GCC -D_GNU_SOURCE -DCMSSW_GIT_HASH="CMSSW_8_1_DEVEL_X_2016-07-17-2300" -DPROJECT_NAME="CMSSW" -DPROJECT_VERSION="CMSSW_8_1_DEVEL_X_2016-07-17-2300" -DBOOST_SPIRIT_THREADSAFE -DPHOENIX_THREADSAFE -I/mnt/build/davidlt/cppmodules/CMSSW_8_1_DEVEL_X_2016-07-17-2300/src/FWCore/GNUCppStandardLibrary/interface -I/mnt/build/davidlt/cppmodules/CMSSW_8_1_DEVEL_X_2016-07-17-2300/src -I/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_DEVEL_X_2016-07-17-2300/src -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/lcg/root/6.06.04-agcabg/include -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/boost/1.57.0-giojec/include -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/pcre/8.37/include -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/bz2lib/1.0.6/include -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/libuuid/2.22.2/include -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/python/2.7.11-giojec/include/python2.7 -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/tbb/44_20151115oss/include -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/zlib/1.2.8/include -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/tinyxml/2.5.3/include -O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -std=c++14 -ftree-vectorize -Wstrict-overflow -Werror=array-bounds -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Wa,--compress-debug-sections -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-long-long -Wreturn-type -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=uninitialized -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-c99-extensions -Wno-c++11-narrowing -D__STRICT_ANSI__ -Wno-unused-private-field -Wno-unknown-pragmas -Wno-unused-command-line-argument -ftemplate-depth=512 -Wno-error=potentially-evaluated-expression -DBOOST_DISABLE_ASSERTS -Wno-error=unused-variable -fmodules -fmodules-cache-path=/build/davidlt/cppmodules/CMSSW_8_1_DEVEL_X_2016-07-17-2300/cppmodulescache -fPIC -MMD -MF tmp/slc6_amd64_gcc530/src/FWCore/MessageService/bin/Standalone/Standalone.d /mnt/build/davidlt/cppmodules/CMSSW_8_1_DEVEL_X_2016-07-17-2300/src/FWCore/MessageService/bin/Standalone.cpp -o tmp/slc6_amd64_gcc530/src/FWCore/MessageService/bin/Standalone/Standalone.o
In file included from /mnt/build/davidlt/cppmodules/CMSSW_8_1_DEVEL_X_2016-07-17-2300/src/FWCore/MessageService/bin/Standalone.cpp:21:
In file included from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_DEVEL_X_2016-07-17-2300/src/FWCore/PluginManager/interface/PresenceFactory.h:5:
In file included from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_DEVEL_X_2016-07-17-2300/src/FWCore/PluginManager/interface/PluginFactory.h:26:
In file included from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_DEVEL_X_2016-07-17-2300/src/FWCore/PluginManager/interface/PluginFactoryBase.h:32:
In file included from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_1_DEVEL_X_2016-07-17-2300/src/FWCore/PluginManager/interface/PluginInfo.h:22:
In file included from /cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/boost/1.57.0-giojec/include/boost/filesystem/path.hpp:29:
In file included from /cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/boost/1.57.0-giojec/include/boost/shared_ptr.hpp:17:
In file included from /cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/boost/1.57.0-giojec/include/boost/smart_ptr/shared_ptr.hpp:28:
/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/boost/1.57.0-giojec/include/boost/smart_ptr/detail/shared_count.hpp:417:33: error: declaration of 'unique_ptr' must be imported from module 'GNU_CPP_STL.FWCore/GNUCppStandardLibrary/interface/condition_variable' before it is required
    explicit shared_count( std::unique_ptr<Y, D> & r ): pi_( 0 )
                                ^
/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/gcc/5.3.0/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../include/c++/5.3.0/bits/unique_ptr.h:129:11: note: previous declaration is here
    class unique_ptr
          ^
1 error generated.
config/SCRAM/GMake/Makefile.rules:1917: recipe for target 'tmp/slc6_amd64_gcc530/src/FWCore/MessageService/bin/Standalone/Standalone.o' failed
gmake: *** [tmp/slc6_amd64_gcc530/src/FWCore/MessageService/bin/Standalone/Standalone.o] Error 1
```

**Comment by davidlt** [comment] 2016-07-21 14:00
Correction, same happens even if I don't use `-Xclang -fmodules-local-submodule-visibility`. I have seen similar happening with `std::shared_ptr` and others. We also have seen issues with redefinitions of every type in `pthread.h` which I couldn't reproduce again for now.

**Comment by davidlt** [comment] 2016-07-25 14:18
You can find `care` binary here http://davidlt.web.cern.ch/davidlt/vault/proot/care

I have used it with the failing command:
```
./care -o partial_rootfs.tar.gz /cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/llvm/3.8.99/bin/clang++ -c -DGNU_GCC -D_GNU_SOURCE -DCMSSW_GIT_HASH="CMSSW_8_1_DEVEL_X_2016-07-19-1100" -DPROJECT_NAME="CMSSW" -DPROJECT_VERSION="CMSSW_8_1_DEVEL_X_2016-07-19-1100" -DBOOST_SPIRIT_THREADSAFE -DPHOENIX_THREADSAFE -I/mnt/build/davidlt/cppmodules/CMSSW_8_1_DEVEL_X_2016-07-19-1100/src/FWCore/GNUCppStandardLibrary/interface -I/mnt/build/davidlt/cppmodules/CMSSW_8_1_DEVEL_X_2016-07-19-1100/src -I/mnt/build/davidlt/cppmodules/CMSSW_8_1_DEVEL_X_2016-07-19-1100/poison -I/cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_DEVEL_X_2016-07-19-1100/src -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/lcg/root/6.06.04-agcabg/include -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/boost/1.57.0-giojec/include -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/pcre/8.37/include -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/bz2lib/1.0.6/include -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/libuuid/2.22.2/include -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/python/2.7.11-giojec/include/python2.7 -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/tbb/44_20151115oss/include -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/zlib/1.2.8/include -I/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/tinyxml/2.5.3/include -O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -std=c++14 -ftree-vectorize -Wstrict-overflow -Werror=array-bounds -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -Wa,--compress-debug-sections -msse3 -felide-constructors -fmessage-length=0 -Wall -Wno-long-long -Wreturn-type -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=strict-aliasing -Werror=narrowing -Werror=uninitialized -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wno-attributes -Wno-c99-extensions -Wno-c++11-narrowing -D__STRICT_ANSI__ -Wno-unused-private-field -Wno-unknown-pragmas -Wno-unused-command-line-argument -ftemplate-depth=512 -Wno-error=potentially-evaluated-expression -DBOOST_DISABLE_ASSERTS -Wno-error=unused-variable -fmodules -fmodules-cache-path=/mnt/build/davidlt/cppmodules/CMSSW_8_1_DEVEL_X_2016-07-19-1100/cppmodulescache -fPIC -MMD -MF tmp/slc6_amd64_gcc530/src/FWCore/MessageService/bin/Standalone/Standalone.d /mnt/build/davidlt/cppmodules/CMSSW_8_1_DEVEL_X_2016-07-19-1100/src/FWCore/MessageService/bin/Standalone.cpp -o tmp/slc6_amd64_gcc530/src/FWCore/MessageService/bin/Standalone/Standalone.o
```

Output
```
care info: concealed path: $HOME /afs/cern.ch/user/d/davidlt
care info: concealed path: /tmp
care info: revealed path: $PWD /mnt/build/davidlt/cppmodules/CMSSW_8_1_DEVEL_X_2016-07-19-1100
care info: revealed path: /cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/llvm/3.8.99/bin/clang-3.9
care info: ----------------------------------------------------------------------
In file included from /mnt/build/davidlt/cppmodules/CMSSW_8_1_DEVEL_X_2016-07-19-1100/src/FWCore/MessageService/bin/Standalone.cpp:21:
In file included from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_DEVEL_X_2016-07-19-1100/src/FWCore/PluginManager/interface/PresenceFactory.h:5:
In file included from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_DEVEL_X_2016-07-19-1100/src/FWCore/PluginManager/interface/PluginFactory.h:26:
In file included from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_DEVEL_X_2016-07-19-1100/src/FWCore/PluginManager/interface/PluginFactoryBase.h:32:
In file included from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc530/cms/cmssw-patch/CMSSW_8_1_DEVEL_X_2016-07-19-1100/src/FWCore/PluginManager/interface/PluginInfo.h:22:
In file included from /cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/boost/1.57.0-giojec/include/boost/filesystem/path.hpp:29:
In file included from /cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/boost/1.57.0-giojec/include/boost/shared_ptr.hpp:17:
In file included from /cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/boost/1.57.0-giojec/include/boost/smart_ptr/shared_ptr.hpp:28:
/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/boost/1.57.0-giojec/include/boost/smart_ptr/detail/shared_count.hpp:417:33: error: declaration of 'unique_ptr' must be imported from module 'GNU_CPP_STL.FWCore/GNUCppStandardLibrary/interface/condition_variable' before it is required
    explicit shared_count( std::unique_ptr<Y, D> & r ): pi_( 0 )
                                ^
/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc530/external/gcc/5.3.0/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../include/c++/5.3.0/bits/unique_ptr.h:129:11: note: previous declaration is here
    class unique_ptr
          ^
1 error generated.
care info: ----------------------------------------------------------------------
care info: Hints:
care info:   - search for "conceal" in `care -h` if the execution didn't go as expected.
care info:   - run `care -x partial_rootfs.tar.gz` to extract the output archive correctly.
```

Got 37M partial rootfs tarball with 1278 files touched in this execution. 483 headers are found in this tarball.

You can grab it from: http://davidlt.web.cern.ch/davidlt/vault/cppmodules_partial_rootfs.tar.gz

**Comment by vgvassilev** [comment] 2016-07-25 15:18
@davidlt yes I can reproduce the issue outside now. Thanks a lot!

**Comment by vgvassilev** [comment] 2016-07-30 10:11
Some debugging aids (suggested by Richard Smith):
  * `-fdiagnostics-show-note-include-stack` will tell you which module a note comes from
  * `#pragma clang __debug dump X` allows you to produce an AST dump from within a source file, so you can see which modules declare a given name
  * `#pragma clang __debug macro M` allows you to dump a macro, which can be useful to see which module(s) export visible include guards for a header

If a name is not visible in a modules build but is visible in a non-modules build, i usually find that's due to one of two things
  * some part of the machinery that provides it depends on macro definitions leaking into a modular header from outside, or
  * there is an include cycle involving a modular header and a non-modular header

**Comment by vgvassilev** [comment] 2016-08-01 12:51
A flavor of the `unique_ptr` issue is in this bug report: https://llvm.org/bugs/show_bug.cgi?id=28794

**Comment by vgvassilev** [comment] 2016-10-18 11:45
It may be worth to give another try as the blocking issue was resolved.

**Comment by Teemperor** [comment] 2017-03-21 10:19
We now have a list of the cyclic dependencies in the headers of CMS master: https://teemperor.de/pub/cms/cycle_report.cycle.html (Should be updated every few seconds). It also contains some debugging help on how to break those cyclic dependencies.

You can run this program to get the same output for your local changes: https://github.com/Teemperor/circle-break

**Comment by Teemperor** [comment] 2017-06-07 06:52
Forgot to link those: 
https://github.com/cms-sw/cmssw/pull/19111
https://github.com/cms-sw/cmssw/pull/19107
https://github.com/cms-sw/cmssw/pull/19108
https://github.com/cms-sw/cmssw/pull/19109

**Comment by Teemperor** [comment] 2017-06-20 10:08
I started to to through my list of headers that are obsolete since a long time or never compiled, so the previous 5 PRs and the next N PRs will be just removing those headers.

**Comment by Teemperor** [comment] 2017-11-30 10:47
With these final PRs nearly all of CMS should compile with C++ modules. The remaining issues are a few very strange issues I couldn't easily solve.

One of them are those two headers that declare the same class but slightly changed:
https://github.com/cms-sw/cmssw/blob/master/CommonTools/UtilAlgos/interface/InputTagDistributor.h
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/UtilAlgos/interface/InputTagDistributor.h

**Comment by vgvassilev** [comment] 2017-11-30 10:51
@Teemperor, great job!

FWIW, the diff between two files is really minimal ([see here](https://www.diffchecker.com/6D03gZTl)).

**Comment by Teemperor** [comment] 2017-11-30 11:08
At the reviewers: If you want multiple PRs merged into one, just comment with what subsystems/packages you want to have merged and I'll create a single PR for them. Thanks.

**Comment by davidlt** [comment] 2017-11-30 13:45
One needs to look back into CVS ( http://cern.ch/cmscvs/cgi/viewvc.cgi/cvsroot/CMSSW/ ) to understand why someone made a copy of `InputTagDistributor`.

**Comment by davidlt** [comment] 2017-11-30 13:51
http://cmscvs.web.cern.ch/cmscvs/cgi/viewvc.cgi/cvsroot/CMSSW/PhysicsTools/UtilAlgos/interface/InputTagDistributor.h?view=log
http://cmscvs.web.cern.ch/cmscvs/cgi/viewvc.cgi/cvsroot/CMSSW/CommonTools/UtilAlgos/interface/InputTagDistributor.h?view=log

Looks like original copy comes from `PhysicsTools`.  Then migrated to `CommonTools`, then removed, then again added back. Commit messages do not explain why this was done. Maybe we should merge to a single copy in `PhysicsTools/UtilAlgos`.  It's bad, because we have duplicate symbols in global namespace now. That's a bug from my point of view.

**Comment by vgvassilev** [comment] 2017-11-30 13:53
@davidlt, thanks for digging. The question is which one should we keep and which one should we remove.

**Comment by davidlt** [comment] 2017-11-30 13:53
There is another similar case in CMSSW: https://github.com/cms-sw/cmssw/issues/21312

**Comment by davidlt** [comment] 2017-11-30 13:54
@vgvassilev ask experts, or propose a PR. I would go with `PhysicsTools/UtilAlgos`, but in needed modifications/extensions into the original class.

**Comment by Dr15Jones** [comment] 2017-11-30 14:38
Which ever one is kept should go in CommonTools/UtilAlgos since that package is the one intended to hold classes shared by reconstruction and analysis.

**Comment by davidlt** [comment] 2017-11-30 14:39
I guess, then we need to copy the one from PhysicsTools/UtilAlgos which has consumes migration done.

**Comment by davidlange6** [comment] 2017-12-04 10:53
these are the biggest of the pcms? (eg the vast majority of the 1.3 GB is small stuff)

**Comment by Teemperor** [comment] 2017-12-04 11:43
Yes, the biggest CMS module is 28MB. The dependencies have bigger modules (e.g. Geant4 is one of the biggest currently with a single 120 MB module) because that's easier/faster to create.

**Comment by Teemperor** [comment] 2017-12-14 10:39
@smuzaffar Here is the tracking issue.

**Comment by Teemperor** [comment] 2018-05-11 13:06
Here is the blacklisted header I never fixed, but that either need to be removed:

https://github.com/Teemperor/scram2cmake/blob/master/scram2cmake.py#L23

**Comment by Teemperor** [comment] 2018-05-11 13:08
@mrodozov here is the tracking issue.

**Comment by mrodozov** [comment] 2018-05-11 14:36
```
module "/build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc630/lcg/root/6.12.07-gnimlf3/root-6.12.07/core/base/v7/inc/ROOT/TDirectory.hxx" { header "/\
build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc630/lcg/root/6.12.07-gnimlf3/root-6.12.07/core/base/v7/inc/ROOT/TDirectory.hxx" export * }
  module "/build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc630/lcg/root/6.12.07-gnimlf3/root-6.12.07/core/base/v7/inc/ROOT/TDirectoryEntry.hxx" { head\
er "/build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc630/lcg/root/6.12.07-gnimlf3/root-6.12.07/core/base/v7/inc/ROOT/TDirectoryEntry.hxx" export * }
  module "/build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc630/lcg/root/6.12.07-gnimlf3/root-6.12.07/core/base/v7/inc/ROOT/TDrawable.hxx" { header "/b\
uild/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc630/lcg/root/6.12.07-gnimlf3/root-6.12.07/core/base/v7/inc/ROOT/TDrawable.hxx" export * }
  module "/build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc630/lcg/root/6.12.07-gnimlf3/root-6.12.07/core/base/v7/inc/ROOT/TIndexIter.hxx" { header "/\
build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc630/lcg/root/6.12.07-gnimlf3/root-6.12.07/core/base/v7/inc/ROOT/TIndexIter.hxx" export * }
  module "/build/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc630/lcg/root/6.12.07-gnimlf3/root-6.12.07/core/base/v7/inc/ROOT/TLogger.hxx" { header "/bui\
ld/cmsbld/jenkins/workspace/build-any-ib/w/BUILD/slc7_amd64_gcc630/lcg/root/6.12.07-gnimlf3/root-6.12.07/core/base/v7/inc/ROOT/TLogger.hxx" export * }
```
Generated wrong module.modulemap paths

**Comment by Teemperor** [comment] 2018-05-14 12:16
This is the boost modulemap that should hopefully work: https://github.com/Teemperor/ClangAutoModules/blob/CMS/inc-cms/boost/module.modulemap

**Comment by makortel** [comment] 2018-05-30 13:04
Let me ask if there is a plan to add this test as part of PR tests? I'm afraid otherwise new problems continue to creep in.

**Comment by vgvassilev** [comment] 2018-05-30 20:08
@makortel, once all headers are fixed we will add a pull request level check.

**Comment by makortel** [comment] 2018-06-11 13:35
@mrodozov Ok. I was thinking whether it would have made sense to add the check as part of PR tests without enforching it (to allow spotting these inconsistencies for new code earlier), but maybe for a ~week time scale it is not worth it.

**Comment by davidlange6** [comment] 2019-12-11 10:20
#28606

**Comment by smuzaffar** [comment] 2021-09-16 10:29
closing this issue. We have CXXMODULE IBs dedicated for this

**Closed by smuzaffar** 2021-09-16 10:29 UTC
Labels: pending-assignment
