### ISSUE TITLE
Problem in Pyquen RelVals

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#21814] opened 2018-01-09 08:47 UTC
The IB RelVals 300 301 and 302 are failing since January 4th, apparently after the integration of the PR 21783 with a configuration problem

%MSG
----- Begin Fatal Exception 05-Jan-2018 05:14:47 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MixingModule label='mix'
Exception Message:
RootEmbeddedFileSequence no input files specified for secondary input source.
----- End Fatal Exception -------------------------------------------------

The release for HI mixing was also updated
I think that these workflows were not explicitly checked, to be fixed

@prebello

**Comment by Dr15Jones** [comment] 2018-01-09 12:53
I believe these are caused by a DAS failure which is causing the query for the MixingModule input to return an empty list.

**Comment by davidlange6** [comment] 2018-01-09 12:59
Not likely an issue with das if it’s happening each day (but wasn’t there a related pr today ?)



On 9 Jan 2018, at 11:54, Chris Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe these are caused by a DAS failure which is causing the query for the MixingModule input to return an empty list.

**Comment by Dr15Jones** [comment] 2018-01-09 13:10
From the log of the failing job
```
the query is file dataset = /RelValHydjetQ_B12_5020GeV_2018/CMSSW_10_0_0_pre2-PU_100X_mc2017_realistic_v1-v1/GEN-SIM
DAS succeeded after 1 attempts 0
found files:  []
```
The DAS query is returning the empty set.

**Comment by davidlange6** [comment] 2018-01-09 16:58
which is not a failure, but rather a feature in this case...anyway, the dataset change was here

https://github.com/cms-sw/cmssw/pull/21783

and the correct dataset appears to be

/RelValHydjetQ_B12_5020GeV_2018/CMSSW_10_0_0_pre2-100X_upgrade2018_realistic_v1-v1/GEN-SIM

rather than

/RelValHydjetQ_B12_5020GeV_2018/CMSSW_10_0_0_pre2-PU_100X_mc2017_realistic_v1-v1/GEN-SIM

@prebello should be able to fix the typo from her PR.

**Comment by prebello** [comment] 2018-01-09 18:00
Hi @fabiocos and @davidlange6,  indeed it is the case and I already tried to fix this typo in PR#21800, testing wfs with PR#21783, without success because base release incompatibility. 
I will make a new PR soon in the newest IB, since 21783 is properly merged. 
Working on it now to be ready for pre4. Thank you

**Comment by prebello** [comment] 2018-01-09 20:05
@fabiocos @davidlange6 please see new PR#21819

**Comment by fabiocos** [comment] 2018-01-10 13:18
@prebello This seems to fix the problem, thanks, I merge it

**Closed** 2018-01-10 13:19 UTC
Labels: pending-assignment
