### ISSUE TITLE
multiple paths causes the dependency loop detection to fail 

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/cmssw#20475] opened 2017-09-12 10:47 UTC
While testing an HLT menu we stumbled upon a job that would be run indefinitely, doing nothing.

Here is a minimal test case to reproduce the issue:
```python
import FWCore.ParameterSet.Config as cms

process = cms.Process( "TEST" )

process.source = cms.Source( "EmptySource" )

process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32( 100 )
)

process.options = cms.untracked.PSet(
    numberOfThreads = cms.untracked.uint32( 1 ),
    numberOfStreams = cms.untracked.uint32( 0 ),
)

process.triggerResultsFilter = cms.EDFilter( "TriggerResultsFilter",
    hltResults = cms.InputTag( "TriggerResults" ),
    l1tResults = cms.InputTag( "" ),
    triggerConditions = cms.vstring( 'L1_ZeroBias' ),
    l1tIgnoreMaskAndPrescale = cms.bool( True ),
    throw = cms.bool( True )
)

process.hltBool = cms.EDFilter( "HLTBool",
    result = cms.bool( True )
)

process.Path1 = cms.Path( process.triggerResultsFilter + process.hltBool )
process.Path2 = cms.Path( process.triggerResultsFilter + process.hltBool )

process.Tracer = cms.Service('Tracer')
```

Running it will produce an output like
```
++ starting: constructing source: EmptySource
++ finished: constructing source: EmptySource
++++ starting: constructing module with label 'TriggerResults' id = 1
++++ finished: constructing module with label 'TriggerResults' id = 1                                                                                                                        
++++ starting: constructing module with label 'Path1' id = 2                                                                                                                                 
++++ finished: constructing module with label 'Path1' id = 2                                                                                                                                 
++++ starting: constructing module with label 'Path2' id = 3                                                                                                                                 
++++ finished: constructing module with label 'Path2' id = 3                                                                                                                                 
++++ starting: constructing module with label 'triggerResultsFilter' id = 4                                                                                                                  
++++ finished: constructing module with label 'triggerResultsFilter' id = 4                                                                                                                  
++++ starting: constructing module with label 'hltBool' id = 5                                                                                                                               
++++ finished: constructing module with label 'hltBool' id = 5                                                                                                                               
++ preallocate: 1 concurrent runs, 1 concurrent luminosity sections, 1 streams                                                                                                               
++ starting: begin job                                                                                                                                                                       
...
++++ finished: begin lumi: stream = 0 run = 1 lumi = 1 time = 1
++++ starting: source event
++++ finished: source event
Begin processing the 1st record. Run 1, Event 1, LumiSection 1 at 12-Sep-2017 12:40:29.629 CEST
++++ starting: processing event : stream = 0 run = 1 lumi = 1 event = 1 time = 5000001
++++++ starting: processing path 'Path2' : stream = 0
++++++++ starting: prefetching before processing event for module: stream = 0 label = 'triggerResultsFilter' id = 4
++++++ starting: processing path 'Path1' : stream = 0
```
and stay there.

I've reproduced the same behaviour both with `CMSSW_9_2_10` and `CMSSW_9_4_X_2017-09-11-1100`.

If I change the configuration removing or commenting out one of the two identical paths, the framework identifies a dependency loop:
```
----- Begin Fatal Exception 12-Sep-2017 12:45:04 CEST-----------------------
An exception of category 'ScheduleExecutionFailure' occurred while
   [0] Calling beginJob
Exception Message:
Unrunnable schedule
Module run order problem found: 
@PathEnded after hltBool [path Path1], hltBool after triggerResultsFilter [path Path1], triggerResultsFilter consumes TriggerResults, TriggerResults consumes @PathEnded
 Running in the threaded framework would lead to indeterminate results.
 Please change order of modules in mentioned Path(s) to avoid inconsistent module ordering.
----- End Fatal Exception -------------------------------------------------
```

So, there are two problems:
1. introducing a second path makes the loop detection fail, and the job gets stuck at a later moment - I assume trying to satisfy an impossible dependency
2. requesting the `TriggerResults` collection in a `Path` should yield the one from the previous job, not the one from the current job

The latter might actually be the intended behaviour, though I think it contradicts what would happens with a normal product ?

The former is clearly a bug.

**Comment by fwyzard** [comment] 2017-09-12 10:48
@degrutto @gennai marco.pieri@cern.ch

**Comment by Dr15Jones** [comment] 2017-09-12 13:42
assign core

**Comment by Dr15Jones** [comment] 2017-09-12 13:49
@fwyzard thanks for reporting the problem and for giving a simple reproducer. Out of curiosity, was the original problem also a case of two identical paths or was it just that two Paths (not EndPaths) had `TriggerResultsFilter`?

> So, there are two problems:
>
>introducing a second path makes the loop detection fail, and the job gets stuck at a later moment - I assume trying to satisfy an impossible dependency

That is definitely a bug

>requesting the TriggerResults collection in a Path should yield the one from the previous job, not the one from the current job
The latter might actually be the intended behaviour, though I think it contradicts what would happens with a normal product ?

The latter is intended behavior and happens also for normal data products. In Run 1 the framework would do the 'fallback if not available' but in Run 2 we also try to get the data product from present process if there is a module that says it produces it. This guarantees that unscheduled and scheduled jobs with the same mix of modules will process the event identically. Also, with Paths running simultaneously and modules needing data from different Paths it is the only way to be consistent. 

Another way to fix the problem is the change the `InputTag` to use `skipCurrentProcess` or to use the process name explicitly.

**Comment by Dr15Jones** [comment] 2017-09-13 13:25
@fwyzard could you put the original full configuration somewhere so I can test that my fix is general enough to catch the full case?

**Comment by Dr15Jones** [comment] 2017-09-13 15:53
With the full configuration, my change catches the circular dependency
```
----- Begin Fatal Exception 13-Sep-2017 10:52:14 CDT-----------------------
An exception of category 'ScheduleExecutionFailure' occurred while
   [0] Calling beginJob
Exception Message:
Unrunnable schedule
Module run order problem found: 
TriggerResults consumes HLT_Physics_part0_v7, HLT_Physics_part0_v7 after hltBoolEnd [path HLT_Physics_part0_v7], hltBoolEnd after hltNominalTrains [path HLT_Physics_part0_v7], hltNominalTrains consumes TriggerResults
 Running in the threaded framework would lead to indeterminate results.
 Please change order of modules in mentioned Path(s) to avoid inconsistent module ordering.
----- End Fatal Exception -------------------------------------------------
```

I'm testing it now on the full `runTheMatrix.py` to double check I didn't cause a false positive.

**Comment by Dr15Jones** [comment] 2017-09-13 16:05
The fix is in #20502

**Comment by fwyzard** [comment] 2017-09-14 05:45
Thanks.
Would you consider a backport to 9.2.x ?
I think the same patch should apply cleanly.

**Comment by Dr15Jones** [comment] 2017-09-14 21:15
Although the patch would apply cleanly, I have already uncovered two sets of circular dependencies in existing CMSSW_9_4 workflows in runTheMatrix.py. It is likely back porting to CMSSW_9_2 will uncover problems in workflows (that just happen to work) in that release as well. So back porting could cause job failures in jobs that "work" now.

[E.g. the circular dependencies I found would only cause a deadlock if an exception caused a specific path to fail, then the module not run on the failed path would lead to a circular dependency between two different paths.]

**Comment by fwyzard** [comment] 2017-09-15 09:59
I see... I would still consider it a bug worth fixing, but I don't know who
should fix the workflows.

By the the way - what was the framework doing, when the bug caused the loop
to be undetected ?
Just wait for the collection to be produced ?

.A

**Comment by Dr15Jones** [comment] 2017-09-15 13:19
> By the the way - what was the framework doing, when the bug caused the loop
to be undetected ?
Just wait for the collection to be produced ?

Yes, it was waiting for the collection to be produced but that couldn't happen because the data it needed ultimately couldn't be made without itself being run.

**Comment by Dr15Jones** [comment] 2017-09-15 13:21
@davidlange6 Andrea has requested that the circular dependency fix be backported to CMSSW_9_2. However, I'm sure it will uncover production configurations which have latent circular dependencies (as it did in CMSSW_9_4). These cycles are bad as they can lead to deadlocks, however modifying production configurations might have unforseen consequences (although I can't see how we would get different results). How would you like to handle this?

**Comment by Dr15Jones** [comment] 2017-09-15 19:51
@fwyzard The backport is #20502

**Comment by fwyzard** [comment] 2017-09-15 20:08
Thanks,
.A

**Comment by makortel** [comment] 2020-05-04 15:36
+1

appears to be fixed

**Closed** 2020-05-04 15:40 UTC
Labels: core-approved, fully-signed
