### ISSUE TITLE
[PowerPC] Unit test testCUDAService fails

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#40616] opened 2023-01-26 09:47 UTC
Failing at least since `CMSSW_13_0_X_2023-01-19-2300`. Log ([link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_ppc64le_gcc11/CMSSW_13_0_X_2023-01-25-2300/unitTestLogs/HeterogeneousCore/CUDAServices#/)):

```
===== Test "testCUDAService" ====

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
testCUDAService is a Catch v2.13.6 host application.
Run with -? for options

-------------------------------------------------------------------------------
Tests of CUDAService
  CUDAService enabled
  Enabled only if there are CUDA capable GPUs
-------------------------------------------------------------------------------
/scratch/cmsbuild/jenkins_a/workspace/build-any-ib/w/tmp/BUILDROOT/6f55c87ee4256a45b80226ccc4e367a5/opt/cmssw/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_0_X_2023-01-25-2300/src/HeterogeneousCore/CUDAServices/test/testCUDAService.cpp:39
...............................................................................

/scratch/cmsbuild/jenkins_a/workspace/build-any-ib/w/tmp/BUILDROOT/6f55c87ee4256a45b80226ccc4e367a5/opt/cmssw/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_0_X_2023-01-25-2300/src/HeterogeneousCore/CUDAServices/test/testCUDAService.cpp:39: FAILED:
due to unexpected exception with message:
  An exception of category 'NotFound' occurred.
  Exception Message:
  No ServiceRegistry has been set for this thread. Tried to ask availability of
  a Service edm::ResourceInformation

-------------------------------------------------------------------------------
Tests of CUDAService
  CUDAService enabled
-------------------------------------------------------------------------------
/scratch/cmsbuild/jenkins_a/workspace/build-any-ib/w/tmp/BUILDROOT/6f55c87ee4256a45b80226ccc4e367a5/opt/cmssw/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_0_X_2023-01-25-2300/src/HeterogeneousCore/CUDAServices/test/testCUDAService.cpp:36
...............................................................................

/scratch/cmsbuild/jenkins_a/workspace/build-any-ib/w/tmp/BUILDROOT/6f55c87ee4256a45b80226ccc4e367a5/opt/cmssw/el8_ppc64le_gcc11/cms/cmssw/CMSSW_13_0_X_2023-01-25-2300/src/HeterogeneousCore/CUDAServices/test/testCUDAService.cpp:36: FAILED:
due to unexpected exception with message:
  An exception of category 'NotFound' occurred.
  Exception Message:
  No ServiceRegistry has been set for this thread. Tried to ask availability of
  a Service edm::ResourceInformation

===============================================================================
test cases: 1 | 1 failed
assertions: 4 | 2 passed | 2 failed


---> test testCUDAService had ERRORS
TestTime:1
^^^^ End Test testCUDAService ^^^^
>> Tests for package HeterogeneousCore/CUDAServices ran.

```

**Comment by iarspider** [comment] 2023-01-26 09:47
assign heterogeneous

**Comment by fwyzard** [comment] 2023-01-26 10:32
I can reproduce the failure on a Power node:
```bash
$ $CMSSW_BASE/test/el8_ppc64le_gcc11/testCUDAService 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
testCUDAService is a Catch v2.13.6 host application.
Run with -? for options

-------------------------------------------------------------------------------
Tests of CUDAService
  CUDAService enabled
  Enabled only if there are CUDA capable GPUs
-------------------------------------------------------------------------------
/data/fwyzard/CMSSW_13_0_X_2023-01-25-2300/src/HeterogeneousCore/CUDAServices/test/testCUDAService.cpp:39
...............................................................................

/data/fwyzard/CMSSW_13_0_X_2023-01-25-2300/src/HeterogeneousCore/CUDAServices/test/testCUDAService.cpp:39: FAILED:
due to unexpected exception with message:
  An exception of category 'NotFound' occurred.
  Exception Message:
  No ServiceRegistry has been set for this thread. Tried to ask availability of
  a Service edm::ResourceInformation

-------------------------------------------------------------------------------
Tests of CUDAService
  CUDAService enabled
-------------------------------------------------------------------------------
/data/fwyzard/CMSSW_13_0_X_2023-01-25-2300/src/HeterogeneousCore/CUDAServices/test/testCUDAService.cpp:36
...............................................................................

/data/fwyzard/CMSSW_13_0_X_2023-01-25-2300/src/HeterogeneousCore/CUDAServices/test/testCUDAService.cpp:36: FAILED:
due to unexpected exception with message:
  An exception of category 'NotFound' occurred.
  Exception Message:
  No ServiceRegistry has been set for this thread. Tried to ask availability of
  a Service edm::ResourceInformation

===============================================================================
test cases: 1 | 1 failed
assertions: 4 | 2 passed | 2 failed
```

However, the `CUDAService` itself seems to be working fine within CMSSW:
```bash
$ cmsRun HeterogeneousCore/CUDAServices/test/testCUDAService.py 
%MSG-i ThreadStreamSetup:  (NoModuleName) 26-Jan-2023 11:31:31 CET pre-events
setting # threads 4
setting # streams 4
%MSG
Disabling gnu++: clang has no __float128 support on this target!
%MSG-i CUDAService:  (NoModuleName) 26-Jan-2023 11:31:32 CET pre-events
NVIDIA driver:    510.47.03
CUDA driver API:  11.6 (compiled with 11.5)
CUDA runtime API: 11.5 (compiled with 11.5)
CUDA runtime successfully initialised, found 4 compute devices.

CUDA device 0: Tesla V100-SXM2-32GB
  compute capability:          7.0 (sm_70)
  streaming multiprocessors:            80
  CUDA cores:                         5120
  single to double performance:        2:1
  compute mode:           default (shared)
  memory:  31434 MB free /  31744 MB total
  constant memory:                   64 kB
  L2 cache size:                   6144 kB
  L1 cache mode:   local and global memory

Other capabilities
  can map host memory into the CUDA address space for use with cudaHostAlloc()/cudaHostGetDevicePointer()
  supports coherently accessing pageable memory without calling cudaHostRegister() on it
  ...

CUDAService fully initialized
%MSG
```

**Comment by fwyzard** [comment] 2023-01-26 10:32
@makortel @Dr15Jones did anything change recently within the framework that could cause the stand alone test to fail ?

**Comment by smuzaffar** [comment] 2023-01-26 10:41
by the way this test also fails for amd64 GPU IBs https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_0_GPU_X_2023-01-25-2300/unitTestLogs/HeterogeneousCore/CUDAServices#/

**Comment by makortel** [comment] 2023-01-26 17:20
I guess this is caused by
https://github.com/cms-sw/cmssw/blob/9607861f39b53236a68cf53c6b8cf64b39473eec/HeterogeneousCore/CUDAServices/src/CUDAService.cc#L365-L366
(added in https://github.com/cms-sw/cmssw/pull/37831). The test failure (because of not initializing the Service system) was likely not noticed in the PR tests, because the `CUDAService` constructor asks for the `ResourceInformation` Service only if a GPU is present.

I'll look into fixing it.

**Comment by makortel** [comment] 2023-01-26 19:59
Fixed in https://github.com/cms-sw/cmssw/pull/40625

**Closed** 2023-01-27 16:42 UTC
Labels: pending-signatures, heterogeneous-pending

**Comment by makortel** [comment] 2023-01-27 16:44
+heterogeneous
