### ISSUE TITLE
Crash related to l1tPFCandidates

### ISSUE THREAD

**Issue by kskovpen** [cms-sw/cmssw#38860] opened 2022-07-26 07:02 UTC
We have spotted a problem when running Phase2 reconstruction sequences in 12_5_0_pre3 on top of the simulation files that were produced in 12_5_0_pre2. The issue may or may not be connected to https://github.com/cms-sw/cmssw/pull/38230. The crash info is appended below and can also be found here: https://cms-unified.web.cern.ch/cms-unified/showlog/?search=CMSSW_12_5_0_pre3__UPSG_Std_2026D88PU200_RECOonly-TTbar_14TeV-00001:

```
Fatal Exception (Exit code: 8001)
An exception of category 'FileReadError' occurred while
[0] Processing Event run: 1 lumi: 1 event: 1 stream: 0
[1] Running path 'prevalidation_step2'
[2] Prefetching for module CSCDigiValidation/'cscDigiValidation'
[3] While reading from source MuonDigiCollection simCscTriggerPrimitiveDigis '' HLT
[4] Rethrowing an exception that happened on a different read request.
[5] Processing Event run: 1 lumi: 1 event: 2 stream: 1
[6] Running path 'FEVTDEBUGHLToutput_step'
[7] Prefetching for module PoolOutputModule/'FEVTDEBUGHLToutput'
[8] While reading from source std::vector l1pfCandidates 'Calo' HLT
[9] Reading branch l1tPFCandidates_l1pfCandidates_Calo_HLT.
Additional Info:
[a] Fatal Root Error: @SUB=TStreamerInfo::BuildOld
Cannot convert l1t::PFCandidate::muonRef_ from type: edm::Ptr to type: edm::Ref,l1t::SAMuon,edm::refhelper::FindUsingAdvance,l1t::SAMuon> >, skip element
```

The issue can be reproduced with https://cms-pdmv.cern.ch/relval/api/relvals/get_cmsdriver/CMSSW_12_5_0_pre3__UPSG_Std_2026D88PU200_RECOonly-TTbar_14TeV-00001.

@bbilin @jmartinb @rappoccio @cms-sw/l1-l2  @cms-sw/upgrade-l2

**Comment by srimanob** [comment] 2022-07-26 07:07
assign upgrade

**Comment by srimanob** [comment] 2022-07-26 07:09
To be clear, the job uses RAW file out from DIGI-HLT step from previous release, to run RECO only, right?
This is not the case of using existing GEN-SIM to rerun DIGI-RECO again, i.e. as in IB test.

**Comment by kskovpen** [comment] 2022-07-26 07:11
> To be clear, the job uses RAW file out from DIGI-HLT step from previous release, to run RECO only, right? This is not the case of using existing GEN-SIM to rerun DIGI-RECO again, i.e. as in IB test.

To be more specific, the failed wf uses dbs:/RelValTTbar_14TeV/CMSSW_12_5_0_pre2-PU_124X_mcRun4_realistic_v4_2026D88PU200-v1/GEN-SIM-DIGI-RAW as input.

**Comment by makortel** [comment] 2022-07-26 13:42
The problem is indeed caused by #38230, more specifically this change in `DataFormats/L1TParticleFlow/interface/PFCandidate.h`
```diff
  class PFCandidate : public L1Candidate {
  public:
-    typedef edm::Ptr<l1t::Muon> MuonRef;
+    typedef l1t::SAMuonRef MuonRef;
```
with `l1t::SAMuonRef` being defined as
https://github.com/cms-sw/cmssw/blob/d274e6059bb2ec56587312eaa188dba33bf2d2e4/DataFormats/L1TMuonPhase2/interface/SAMuon.h#L16-L17

It is not possible to convert `edm::Ptr<X>` to `edm::Ref<Y>` (even if `X == Y`), so this change created a backwards incompatibility.

**Comment by srimanob** [comment] 2022-07-26 13:46
FYI @cecilecaillol @cms-sw/l1-l2

**Comment by srimanob** [comment] 2022-07-26 13:46
assign l1

**Comment by makortel** [comment] 2022-07-26 13:51
The exception message indicates that the `l1tPFCandidates_l1pfCandidates_Calo_HLT` branch was requested by the OutputModule. **If** nothing else needs it in the job, and **if** it is not needed downstream, the problem could be circumvented by dropping the branch on input.

**Comment by srimanob** [comment] 2022-07-26 14:40
Thanks @makortel 
I believe l1tPFCandidates_l1pfCandidates_*_HLT is still needed, at least in the DQM code, i.e. https://github.com/cms-sw/cmssw/blob/master/DQMOffline/L1Trigger/python/L1TPhase2Offline_cfi.py#L89-L100

Running with `--outputCommand "drop l1tPFCandidates_l1pfCandidates_*_HLT"` gives a crash in DQM.
```
----- Begin Fatal Exception 26-Jul-2022 16:36:53 CEST-----------------------
An exception of category 'FileReadError' occurred while
   [0] Processing  Event run: 1 lumi: 71 event: 7001 stream: 1
   [1] Running path 'validation_step9'
   [2] Prefetching for module PFJetDQMAnalyzer/'hgcalPFJetValidation'
   [3] While reading from source std::vector<reco::GenJet> ak4GenJets '' HLT
   [4] Rethrowing an exception that happened on a different read request.
   [5] Processing  Event run: 1 lumi: 71 event: 7001 stream: 1
   [6] Running path 'dqmoffline_7_step'
   [7] Prefetching for module L1TPhase2CorrelatorOffline/'l1tPhase2CorrelatorOfflineDQM'
   [8] While reading from source std::vector<l1t::PFCandidate> l1pfCandidates 'PF' HLT
   [9] Reading branch l1tPFCandidates_l1pfCandidates_PF_HLT.
   Additional Info:
      [a] Fatal Root Error: @SUB=TStreamerInfo::BuildOld
Cannot convert l1t::PFCandidate::muonRef_ from type: edm::Ptr<l1t::Muon> to type: edm::Ref<vector<l1t::SAMuon>,l1t::SAMuon,edm::refhelper::FindUsingAdvance<vector<l1t::SAMuon>,l1t::SAMuon> >, skip element

----- End Fatal Exception -------------------------------------------------
```

**Comment by makortel** [comment] 2022-12-02 15:12
Is there anything to be done for this issue, or can it be closed? (I'd imagine the need to address these specific RelVal workflows is long gone)

**Comment by kskovpen** [comment] 2022-12-02 20:28
I think we can close it - we do not see such issues reoccurring in the recent productions.

**Comment by perrotta** [comment] 2022-12-02 21:49
> I think we can close it - we do not see such issues reoccurring in the recent productions.

If also the submitter (among others) propose to close, let close it

**Closed by perrotta** 2022-12-02 21:49 UTC
Labels: l1-pending, pending-signatures, upgrade-pending
