### ISSUE TITLE
Assertion failure in `testAlcaBeamMonitor`

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#43711] opened 2024-01-14 17:57 UTC
Starting from [CMSSW_14_0_X_2024-01-12-2300](https://github.com/cms-sw/cmssw/compare/CMSSW_14_0_X_2024-01-12-1100...CMSSW_14_0_X_2024-01-12-2300) `testAlcaBeamMonitor` 

https://github.com/cms-sw/cmssw/blob/e8154a2ff2a04ce4431ed5ed83d6ae84913c90c3/DQM/BeamMonitor/test/testAlcaBeamMonitor.cc#L17

 is failing in every IB (in all architectures) with an assertion:

```
===== Test "testAlcaBeamMonitor" ====
testAlcaBeamMonitor: /data/cmsbld/jenkins/workspace/build-any-ib/w/tmp/BUILDROOT/50a1a8dffdd0aca0b3b5e055c82a1c18/opt/cmssw/el8_amd64_gcc12/cms/cmssw-patch/CMSSW_14_0_X_2024-01-12-2300/src/DQMServices/Core/interface/DQMStore.h:687: dqm::implementation::DQMStore::bookTransaction(iFunc, uint64_t, bool)::ModuleIdScope::ModuleIdScope(dqm::implementation::IBooker&, uint64_t, MonitorElementData::Scope, edm::LuminosityBlockID) [with iFunc = DQMOneEDAnalyzer<edm::LuminosityBlockCache<alcabeammonitor::BeamSpotInfo> >::beginRun(const edm::Run&, const edm::EventSetup&)::<lambda(dqm::legacy::DQMStore::IBooker&)>; uint64_t = long unsigned int]: Assertion `newid != 0 || !"moduleID must be set for normal booking transaction"' failed.
```

see e.g. 

https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_14_0_X_2024-01-14-0000/unitTestLogs/DQM/BeamMonitor#/3

**Comment by makortel** [comment] 2024-01-16 14:26
assign DQM/BeamMonitor

**Comment by makortel** [comment] 2024-01-16 14:30
On a cursory look from the many PRs merged in CMSSW_14_0_X_2024-01-12-2300 the possible culprit is not immediately clear.

**Comment by mmusich** [comment] 2024-01-16 20:24
> On a cursory look from the many PRs merged in CMSSW_14_0_X_2024-01-12-2300 the possible culprit is not immediately clear.

apparently reverting https://github.com/cms-sw/cmssw/pull/43683 the unit test succeeds.

**Comment by mmusich** [comment] 2024-01-16 20:24
assign core
   * see https://github.com/cms-sw/cmssw/issues/43711#issuecomment-1894458032

**Comment by makortel** [comment] 2024-01-16 20:30
Thanks @mmusich. @Dr15Jones, could you take a look?

**Comment by Dr15Jones** [comment] 2024-01-16 21:03
The problem is in DQMStore. A module ID of 0 is a valid number according to the framework (the invalid number is the largest possible uint64 number).

**Comment by makortel** [comment] 2024-01-16 21:03
Looking at the function call chain leading to the assertion failure
https://github.com/cms-sw/cmssw/blob/10b8a609a21728eece3889ca8bef0cdf8d9053ba/DQMServices/Core/interface/DQMOneEDAnalyzer.h#L34-L47
https://github.com/cms-sw/cmssw/blob/10b8a609a21728eece3889ca8bef0cdf8d9053ba/DQMServices/Core/interface/DQMStore.h#L697-L699
https://github.com/cms-sw/cmssw/blob/10b8a609a21728eece3889ca8bef0cdf8d9053ba/DQMServices/Core/interface/DQMStore.h#L679-L687
and also
https://github.com/cms-sw/cmssw/blob/10b8a609a21728eece3889ca8bef0cdf8d9053ba/DQMServices/Core/interface/DQMStore.h#L557

it seems to me the `DQMStore` assumes 0 would not be a valid value for `ModuleDescription::id()`. But 0 is a valid value, and the special value for invalid `ModuleDescription` Id is
https://github.com/cms-sw/cmssw/blob/10b8a609a21728eece3889ca8bef0cdf8d9053ba/DataFormats/Provenance/interface/ModuleDescription.h#L65-L66

I could imagine https://github.com/cms-sw/cmssw/pull/43683 changing the module IDs. Maybe in a `TestProcessor` the `AlcaBeamMonitor` now gets legitimately id 0?

**Closed** 2024-01-19 16:35 UTC
Labels: dqm-pending, core-pending, db-pending, pending-signatures, tracking

**Comment by makortel** [comment] 2024-01-19 16:40
+core
