### ISSUE TITLE
Ordering of `globalEndLuminosityBlockProduce`

### ISSUE THREAD

**Issue by schneiml** [cms-sw/cmssw#27291] opened 2019-06-20 14:43 UTC
Dear Framework experts,

The manual [1] promises regarding `globalEndLuminosityBlockProduce`

> This method is guaranteed to be called after `globalEndLuminosityBlockSummary` so that the LuminosityBlock summary object is complete. 

I have reasons to believe that this is a lie.

```
++++ starting: global end lumi: run = 1 lumi = 1 time = 1
++++++ starting: global end lumi for module: label = 'ana1' id = 5
TRACE: /dev/shm/mschneid/CMSSW_11_0_0_pre1/src/DQMServices/Core/interface/DQMEDAnalyzer.h:138(globalEndLuminosityBlockProduce) data 0
TRACE: /dev/shm/mschneid/CMSSW_11_0_0_pre1/src/DQMServices/Core/interface/DQMEDAnalyzer.h:139(globalEndLuminosityBlockProduce) prod 0
TRACE: /dev/shm/mschneid/CMSSW_11_0_0_pre1/src/DQMServices/Core/interface/DQMEDAnalyzer.h:141(globalEndLuminosityBlockProduce) data 0
TRACE: /dev/shm/mschneid/CMSSW_11_0_0_pre1/src/DQMServices/Core/interface/DQMEDAnalyzer.h:142(globalEndLuminosityBlockProduce) prod 0
Returning product:
4
TRACE: /dev/shm/mschneid/CMSSW_11_0_0_pre1/src/DQMServices/Core/interface/DQMEDAnalyzer.h:129(globalEndLuminosityBlockSummary) data 4
TRACE: /dev/shm/mschneid/CMSSW_11_0_0_pre1/src/DQMServices/Core/interface/DQMEDAnalyzer.h:130(globalEndLuminosityBlockSummary) out 0
++++++ finished: global end lumi for module: label = 'ana1' id = 5
++++++ starting: global end lumi for module: label = 'ana2' id = 6
TRACE: /dev/shm/mschneid/CMSSW_11_0_0_pre1/src/DQMServices/Core/interface/DQMEDAnalyzer.h:138(globalEndLuminosityBlockProduce) data 0
TRACE: /dev/shm/mschneid/CMSSW_11_0_0_pre1/src/DQMServices/Core/interface/DQMEDAnalyzer.h:139(globalEndLuminosityBlockProduce) prod 0
TRACE: /dev/shm/mschneid/CMSSW_11_0_0_pre1/src/DQMServices/Core/interface/DQMEDAnalyzer.h:141(globalEndLuminosityBlockProduce) data 0
TRACE: /dev/shm/mschneid/CMSSW_11_0_0_pre1/src/DQMServices/Core/interface/DQMEDAnalyzer.h:142(globalEndLuminosityBlockProduce) prod 0
Returning product:
4
TRACE: /dev/shm/mschneid/CMSSW_11_0_0_pre1/src/DQMServices/Core/interface/DQMEDAnalyzer.h:129(globalEndLuminosityBlockSummary) data 4
TRACE: /dev/shm/mschneid/CMSSW_11_0_0_pre1/src/DQMServices/Core/interface/DQMEDAnalyzer.h:130(globalEndLuminosityBlockSummary) out 0
++++++ finished: global end lumi for module: label = 'ana2' id = 6
```

Reproducer in [2].

Additional questions: Is there a reason to declare `LuminosityBlockSummary` when we don't really need the cache? I used it simply because it matches what we do, but we can also keep all the data in the (`GlobalCache`'d) `DQMStore` until `*produce` and not the summaries at all. Do they signal anything important to the framework?

[1] https://twiki.cern.ch/twiki/bin/view/CMSPublic/FWMultithreadedFrameworkStreamModuleInterface#edm_EndLuminosityBlockProducer

[2] 
```
mkdir /dev/shm/$USER
cd /dev/shm/$USER
cmsrel CMSSW_11_0_0_pre1
cd CMSSW_11_0_0_pre1/src/
cmsenv
git cms-merge-topic schneiml:dqm-new-dqmstore-on-CMSSW_11_0_0_pre1-from-andrius
git checkout 526c63df55a8dd3bd2398fdf7
cd DataFormats/
scram b -j10
cd ../DQMServices/Demo/
scram b -j10
cmsRun test/rundemo_cfg.py
```
Copy&paste into lxplus7 shell, ~4min.

FYI @andrius-k @fioriNTU

**Comment by Dr15Jones** [comment] 2019-06-20 15:13
assign core

**Comment by Dr15Jones** [comment] 2019-06-20 15:15
@makortel could you look into this?

**Comment by makortel** [comment] 2019-06-20 15:19
I'll take a look.

**Comment by makortel** [comment] 2019-06-20 15:43
I can reproduce (thanks for the recipe @schneiml).

**Comment by makortel** [comment] 2019-06-20 17:55
Calls to both `globalEndLuminosityBlockProduce()` and `globalEndLuminosityBlockSummary()` originate from `edm::stream::ProducingModuleAdaptor::doEndLuminosityBlock()`
https://github.com/cms-sw/cmssw/blob/1844a22b8a592316952ccd99e6c3fee085caad54/FWCore/Framework/interface/stream/ProducingModuleAdaptor.h#L189-L193
and the order there is indeed what @schneiml observes.

Digging from the history, the behavior has been like this since the beginning, i.e. #241.

I see the unit test tests only that both functions get called, but not their relative order
https://github.com/cms-sw/cmssw/blob/1844a22b8a592316952ccd99e6c3fee085caad54/FWCore/Framework/test/stream_module_t.cppunit.cc#L448-L460

**Comment by makortel** [comment] 2019-06-20 17:56
@Dr15Jones If you agree, I'll enhance the unit test to test also the order, and switch the order in `ProducingModuleAdaptor`.

**Comment by makortel** [comment] 2019-06-20 18:23
@Dr15Jones global modules seem to have the same issue, calls to both `globalEndLuminosityBlockProduce()` and `globalEndLuminosityBlockSummary()` originate from `edm::global::EDProducerBase::doEndLuminosityBlock()`
https://github.com/cms-sw/cmssw/blob/1844a22b8a592316952ccd99e6c3fee085caad54/FWCore/Framework/src/global/EDProducerBase.cc#L150-L153

**Comment by makortel** [comment] 2019-06-20 18:25
one modules do not have `edm::LuminosityBlockSummaryCache<T>`, so nothing needs to be done there.

**Comment by makortel** [comment] 2019-06-20 18:36
Not surprisingly, limited modules also have the same issue
https://github.com/cms-sw/cmssw/blob/1844a22b8a592316952ccd99e6c3fee085caad54/FWCore/Framework/src/limited/EDProducerBase.cc#L127-L130

**Comment by makortel** [comment] 2019-06-20 19:56
@Dr15Jones By quick look it seems that we have the same issue with `globalEndRunProduce()` and `globalEndRunSummary()` as well

stream
https://github.com/cms-sw/cmssw/blob/1844a22b8a592316952ccd99e6c3fee085caad54/FWCore/Framework/interface/stream/ProducingModuleAdaptor.h#L140-#L144

global
https://github.com/cms-sw/cmssw/blob/1844a22b8a592316952ccd99e6c3fee085caad54/FWCore/Framework/src/global/EDProducerBase.cc#L118-#L120

limited
https://github.com/cms-sw/cmssw/blob/1844a22b8a592316952ccd99e6c3fee085caad54/FWCore/Framework/src/limited/EDProducerBase.cc#L95-#L98

**Comment by Dr15Jones** [comment] 2019-06-20 20:36
@makortel go ahead and make the change.

**Comment by makortel** [comment] 2019-06-21 14:51
Fixed in #27306, thanks @schneiml for reporting.

**Comment by schneiml** [comment] 2019-06-25 15:10
Thanks for the quick fix!

Though that still leaves me with the question whether I *should* use `globalEnd{LuminosityBlock,Run}Summary`. For now I don't, and that seems to be fine [1], but I wonder if the framework has an opinion there. We *do*  take a (per-`globalCache`) lock for a while there. [2] 

[1] Well I am currently debugging a problem where my product's memory gets corrupted, but I hope that is not related... 

[2] https://github.com/cms-sw/cmssw/blob/0cd4bca7aed775df65d999dbb13b813b13fb23ee/DQMServices/Core/interface/DQMEDAnalyzer.h#L140-L152

**Comment by Dr15Jones** [comment] 2019-06-25 15:39
First item, never inherit from an std standard container:
https://github.com/cms-sw/cmssw/blob/0cd4bca7aed775df65d999dbb13b813b13fb23ee/DataFormats/Histograms/interface/MonitorElementCollection.h#L247

Second, why make master_ a shared_ptr instead of just holding an instance of the object?
https://github.com/cms-sw/cmssw/blob/0cd4bca7aed775df65d999dbb13b813b13fb23ee/DQMServices/Core/interface/DQMEDAnalyzer.h#L27

If you switch to using a `EDPutToken` you can do the following:
```C++
static void globalEndRunProduce(...) {
   std::scoped_lock lock{context->global()->lock_ };
   run.emplace(putToken_, context->global()->master_.toProduct(edm::Transition::EndRun, run.run(), edm::invalidLuminosityBlockNumber));
}
```
which avoids unnecessary memory copies.

**Comment by schneiml** [comment] 2019-06-25 16:44
@Dr15Jones 
re inheriting from containers: Any specific reasons? I might be fine with a typedef, but forwarding all the interface is not such a big deal either.

re `shared_ptr`: that one is actually shared (between all the edm::stream copies of the module). Each one also has their private instance, but the coordination of sharing MEs that can be filled concurrently is in the master.

re `EDPutToken`: how could I access `putToken_` from a static context?

**Comment by Dr15Jones** [comment] 2019-06-25 18:48
> re inheriting from containers: Any specific reasons? I might be fine with a typedef, but forwarding all the interface is not such a big deal either.

Inheriting from the std containers is considered very bad form by the world-wide C++ communitee. I'm sure it also violates our new coding guidelines as well. So please do
```C++
using MonitorElementCollection = std::vector<MonitorElementData>
```
A vector is MUCH better to store than a std::set.

>re shared_ptr: that one is actually shared (between all the edm::stream copies of the module). Each one also has their private instance, but the coordination of sharing MEs that can be filled concurrently is in the master.

What is shared is the DQMStoreGroup. There is no reason then to have its members be a `std::shared_ptr`.

>re EDPutToken: how could I access putToken_ from a static context?

Add it to the DQMStoreGroup.

**Closed** 2019-06-25 20:40 UTC
Labels: core-pending, pending-signatures

**Comment by schneiml** [comment] 2019-06-26 08:18
> A vector is MUCH better to store than a std::set.

I agree, but I cannot allow a copy (or even move [1]) constructor in `MonitorElementData`. It contains a mutex and a ROOT object pointer.

What we should use is any collection of `unique_ptr<MonitorElementData>`, but #27277.

Also, having order enforced is a nice thing, but we could also do that on a vector (and the query using the free `std::lower_bound` should work about the same).

> What is shared is the DQMStoreGroup

That is true, but also `DQMStore` does not know about that atm and just has a `shared_ptr` and a pointer to the mutex. Though this does sound like an obvious thing to restructure.

> Add it to the DQMStoreGroup.

Ok. Where should I get it from? the constructor? Can I assume that all `produces` calls return the same token? Leaking things from the constructor into (sort-of) static context is not something I'd do without explicit permission to do so...

[1] Now there is a move constructor, since otherwise it is impossible to initialize it in a set. But that one should dissapear, either into a specialized constructor or entirely.

**Comment by schneiml** [comment] 2019-06-26 10:18
Update: Implemented some of that.

Though the token story is not so simple, I cannot create them in the constructor since I cannot rely on the subsystem subclasses to pass the GlobalCache on to me. So instead I build this hack, which seems to work, but I'd like explicit approval for that (or suggestions for alternatives, as usual).
https://github.com/cms-sw/cmssw/blob/1050b2ee76c948f7270aa5455b5faf6717687c8e/DQMServices/Core/interface/DQMEDAnalyzer.h#L12-L19

**Comment by schneiml** [comment] 2019-06-26 13:39
Update2: I tried to move to a vector-backed version of `MonitorElementCollection`. But, as long as we cannot have products with pointers this is pointless, ROOT (?) requires the elements to be copyable (STL would be fine with moveable, as I understand), and when provided with a copy constructor the vector implementation will also happily call it all the time.

Now, my reason to look into that was that the `std::set` based product (which never copies or moves, since its elements are individual heap objects anyways) returns partially deallocated when I `get` it from the lumi. But I don't have enough evidence yet to open an issue for that...

Really looking forward to #27277 getting fixed.

**Comment by Dr15Jones** [comment] 2019-06-26 14:48
>> What is shared is the DQMStoreGroup

>That is true, but also DQMStore does not know about that atm and just has a shared_ptr and a pointer to the mutex. Though this does sound like an obvious thing to restructure.

I personally wouldn't make `DQMStore` know about `DQMStoreGroup`. Instead, since `DQMStore` is local to a module it is not unreasonable to say that the DQMStore::DQMStoreMaster has to live longer than the `DQMStore`. With that policy, you could just pass a `DQMStore::DQMStoreMaster*` to the `DQMStore`. I personally find setting strict 'ownership' and 'referencing' policies to usually be superior to shared ownership memory models.

>>Add it to the DQMStoreGroup.

>Ok. Where should I get it from? the constructor? Can I assume that all produces calls return the same token? Leaking things from the constructor into (sort-of) static context is not something I'd do without explicit permission to do so...

Let's try a two phased approach. First add the tokens as member data of the `DQMEDAnalyzer` class itself. Then those variables can be set in the constructor. Then in the beginStream call, set the values held in the `DQMEDAnalyzerGlobalCache` as so

```C++
 void beginStream(edm::StreamID id) {
    dqmstore_ = std::make_unique<DQMStore>();
    
    {
        std::scoped_lock lock(globalCache()->master_->lock_);
        if( globalCache()->master_->lumiToken_.isUninitialized()) {
             globalCache()->master_->lumiToken_ = lumiToken_;
             globalCache()->master_->runToken_ = runToken_;
        }
    }
    dqmstore_->setMaster(globalCache()->master_);
  }
```

EDPutTokens are very lightweight since they only hold an unsigned int. Therefore having replicas of them is not too costly.

**Comment by schneiml** [comment] 2019-06-26 15:02
Thanks @Dr15Jones, the two-phased approach seems reasonable.

For the `DQMStoreMaster`, making the `DQMStore` aware of it is worth it, I think, if only to give the mutex a nice place. As far as I see there is no _pointer to thing and a mutex to access it_ type in stl, which is really what I would like there.

Moving to hierarchical ownership is something that came to mind, but if I can guarantee safety with a few less assumptions, I tend to take that, currently. 

On that front, it just appeared to me that we hit another interesting question when using `TH1`s out of a product: what is the lifetime of the product? How would I know that it was discarded, when all I have is a pointer pointing deep into the structure? Can I make a product of `shared_ptr`s and then those elements that are used somewhere else will outlive the product?

The safe path is of course to just copy everything that we need from the product, and we could get away with that in harvesting, but making a copy "just in case" whenever a module looks at a ME seems like a big waste.
