### ISSUE TITLE
Build errors and unit failures in CMSSW_12_0_X_2021-07-09-2300

### ISSUE THREAD

**Issue by qliphy** [cms-sw/cmssw#34438] opened 2021-07-10 15:01 UTC
Since CMSSW_12_0_X_2021-07-09-2300 there are build errors and unit failures in the default ( slc7_amd64_gcc900)

e.g.
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc7_amd64_gcc900/CMSSW_12_0_X_2021-07-09-2300/Validation/HGCalValidation

>> Building  big object file tmp/slc7_amd64_gcc900/src/Validation/HGCalValidation/src/ValidationHGCalValidation/bigobj/ValidationHGCalValidation.obj
/data/cmsbld/jenkins/workspace/build-any-ib/w/slc7_amd64_gcc900/external/gcc/9.3.0/bin/ld -r -z muldefs -o tmp/slc7_amd64_gcc900/src/Validation/HGCalValidation/src/ValidationHGCalValidation/bigobj/ValidationHGCalValidation.obj tmp/slc7_amd64_gcc900/src/Validation/HGCalValidation/src/ValidationHGCalValidation/bigobj/a/ValidationHGCalValidation_xr.cc.o tmp/slc7_amd64_gcc900/src/Validation/HGCalValidation/src/ValidationHGCalValidation/bigobj/HGVHistoProducerAlgo.cc.o
Copying tmp/slc7_amd64_gcc900/src/Validation/HGCalValidation/src/ValidationHGCalValidation/libValidationHGCalValidation.so to productstore area:
>> Checking EDM Class Version for src/Validation/HGCalValidation/src/classes_def.xml in libValidationHGCalValidation.so
/usr/bin/echo >> Skipped running EDM Class Version test
  File "/usr/bin/echo", line 1
  SyntaxError: Non-UTF-8 code starting with '\xff' in file /usr/bin/echo on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
 Suggestion: You can run 'scram build updateclassversion' to generate src/Validation/HGCalValidation/src/classes_def.xml.generated with updated ClassVersion
  gmake: *** [tmp/slc7_amd64_gcc900/src/Validation/HGCalValidation/src/ValidationHGCalValidation/libValidationHGCalValidation.so] Error 1
 Leaving library rule at Validation/HGCalValidation

And
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-07-09-2300/unitTestLogs/DQMOffline/Configuration#/244-244

Task failed.
Traceback (most recent call last):
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-07-09-1100/bin/slc7_amd64_gcc900/cmsswSequenceInfo.py", line 532, in <module>
    processseqs(seqset)
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-07-09-1100/bin/slc7_amd64_gcc900/cmsswSequenceInfo.py", line 288, in processseqs
    for it in t.get(): # should only be one
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/python3/3.8.2-cms/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/python3/3.8.2-cms/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/python3/3.8.2-cms/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-07-09-1100/bin/slc7_amd64_gcc900/cmsswSequenceInfo.py", line 272, in <lambda>
    tasks = [stp.map_async(lambda seq: (seq, inspectsequence(seq)), [seq]) for seq in seqs]
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/cms/cmssw/CMSSW_12_0_X_2021-07-09-1100/bin/slc7_amd64_gcc900/cmsswSequenceInfo.py", line 65, in inspectsequence
    subprocess.check_call(driverargs, cwd=wd, stdout=2) # 2: STDERR
  File "/cvmfs/cms-ib.cern.ch/nweek-02688/slc7_amd64_gcc900/external/python3/3.8.2-cms/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmsDriver.py', 'step3', '--conditions', 'auto:run2_data', '-s', 'VALIDATION', '--process', 'DUMMY', '--eventcontent', 'DQM', '--datatier', 'DQMIO', '--customise_commands', 'process.Tracer = cms.Service("Tracer")', '--filein', 'file:///data/cmsbld/jenkins/workspace/ib-run-qa/CMSSW_12_0_X_2021-07-09-2300/tmp/004D960A-EA4C-E811-A908-FA163ED1F481.root', '-n', '0', '--python_filename', 'cmssw_cfg.py', '--no_exec']' returned non-zero exit status 1.

**Comment by qliphy** [comment] 2021-07-10 15:13
Could it be due to recent python2 -> python3 migration? 

e.g. https://github.com/cms-sw/cmsdist/pull/7106 was merged recently.

**Comment by qliphy** [comment] 2021-07-10 15:14
assign core

**Comment by smuzaffar** [comment] 2021-07-11 09:21
@qliphy , cms-sw/cmsdist#7106 was merged in CMSSW_12_0_X_2021-07-09-1100 IB and unit tests ran fine in that IB. I think unit tests failue are due to one of the PRs merged in CMSSW_12_0_X_2021-07-09-2300 .

For build errors, I see that errors are only in patch IBs. Lets which for last night's 00h00 IB ( which will be a full IB) to see if full re-build has fixed the build issue

**Comment by smuzaffar** [comment] 2021-07-11 09:31
assign dqm
@jfernan2 , could the change in https://github.com/cms-sw/cmssw/pull/34302 now confusing unit tests in DQMOffline/Configuration ?

**Comment by smuzaffar** [comment] 2021-07-11 09:53
I confirm that reverting  #34302  fixes `TestDQMOfflineConfiguration_*` tests ( at least TestDQMOfflineConfiguration_110 ran successfully). So if #34302 contains a valid change then DQMOffline/Configuration also need update

[a]
```
/cvmfs/cms-ib.cern.ch/week0/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-07-10-1100/bin/slc7_amd64_gcc900/edmConfigDump:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Analyzing 10 seqs...
+ sqlite3 sequences110.db
+ grep EDAnalyzer legacymodules-sequences110.db.txt
+ exit 0

---> test TestDQMOfflineConfiguration_110 succeeded
TestTime:440
^^^^ End Test TestDQMOfflineConfiguration_110 ^^^^
```

**Comment by srimanob** [comment] 2021-07-11 13:11
Thanks @smuzaffar 
Could you please let me know how can I make a local test? The https://github.com/cms-sw/cmssw/pull/34302 is just assigning the type workflow properly to data when guessing point to data. Still unclear why it has an effect on DQM. Thanks.

**Comment by smuzaffar** [comment] 2021-07-11 13:15
@srimanob , following should be enough to run the test
```
scram p CMSSW_12_0_X_2021-07-11-0000
cd CMSSW_12_0_X_2021-07-11-0000/
cmsenv
git cms-addpkg DQMOffline/Configuration
scram b runtests_TestDQMOfflineConfiguration_110
```

**Comment by srimanob** [comment] 2021-07-11 16:44
Thanks @smuzaffar 

Looking in the error, I think the issue is the VALIDATION step itself. It runs
`cmsDriver.py step3 --conditions auto:run2_data -s VALIDATION --process DUMMY --eventcontent DQM --datatier DQMIO --customise_commands 'process.Tracer = cms.Service("Tracer")' --filein file:/eos/cms/store/data/Run2018A/EGamma/RAW/v1/000/315/489/00000/004D960A-EA4C-E811-A908-FA163ED1F481.root -n 10 --python_filename cmssw_cfg.py --no_exec`
however it tries pick MC requirement, require mix collection in this case. This is the reason of the error in
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_12_0_X_2021-07-09-2300/unitTestLogs/DQMOffline/Configuration#/242-266

The issue seems to come from
https://github.com/cms-sw/cmssw/blob/master/Configuration/Applications/python/ConfigBuilder.py#L1852-L1856
which seems to apply to all cases (both data and MC).

Clearly, if we run above cmsDriver with --data, it will fail. 

I don't know why we run the test in this way, trying to dump MC sequence on RAW data.

FYI @qliphy @cms-sw/dqm-l2 

For the short time fixing, I propose @qliphy to revert https://github.com/cms-sw/cmssw/pull/34302. And I will make PR to fix for Nano sequence only first.

**Comment by srimanob** [comment] 2021-07-11 17:20
It seems fixing the validation sequence is the right thing to do. Fixing only Nano sequence is just a temporary/dirty way to work. Actually, it is not about Nano-only, but other steps will be the same if CMSSW guesses it is data workflow but it will pick MC customization anyway. Detail is in
https://github.com/cms-sw/cmssw/pull/34302#issuecomment-877834286

After reverting https://github.com/cms-sw/cmssw/pull/34302, I propose to close this issue and open a new one with a specific issue to DQM. I can make it.

**Comment by qliphy** [comment] 2021-07-12 01:09
> After reverting #34302, I propose to close this issue and open a new one with a specific issue to DQM. I can make it.

Ok, thanks @srimanob

**Closed** 2021-07-12 01:10 UTC
Labels: core-pending, dqm-pending, pending-signatures
