### ISSUE TITLE
Tracking clang-format work

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#26082] opened 2019-03-06 11:49 UTC
I thought that I would start an issue to keep track of things we discussed in the core meeting yesterday. @Dr15Jones @smuzaffar @fwyzard @fabiocos

**Comment by davidlange6** [comment] 2019-03-06 11:53
To do item: see what problems come after applying clang-format to the entire repository

I tried this - there is one error (repeating a few times)

>> Compiling  /build/dlange/CMSSW_10_6_X_2019-03-05-2300/src/Alignment/CocoaFit/src/NtupleObjects.cc
In file included from /cvmfs/cms-ib.cern.ch/nweek-02566/slc7_amd64_gcc700/lcg/root/6.12.07-pafccj/include/TObject.h:17:0,
                 from /build/dlange/CMSSW_10_6_X_2019-03-05-2300/src/Alignment/CocoaFit/interface/NtupleObjects.h:11,
                 from /build/dlange/CMSSW_10_6_X_2019-03-05-2300/src/Alignment/CocoaFit/src/NtupleObjects.cc:7:
/cvmfs/cms-ib.cern.ch/nweek-02566/slc7_amd64_gcc700/lcg/root/6.12.07-pafccj/include/Rtypes.h:354:81: error: redefinition of 'int ROOT::{anonymous}::R__dummyintdefault9'
          static int _R__UNIQUE_(_NAME2_(R__dummyint,key)) __attribute__((unused)) = \                                                                                                                                          
                                                                                 ^
/cvmfs/cms-ib.cern.ch/nweek-02566/slc7_amd64_gcc700/lcg/root/6.12.07-pafccj/include/Rtypes.h:359:24: note: in expansion of macro 'ClassImpUnique'
 #define ClassImp(name) ClassImpUnique(name,default)
                        ^~~~~~~~~~~~~~
/build/dlange/CMSSW_10_6_X_2019-03-05-2300/src/Alignment/CocoaFit/src/NtupleObjects.cc:9:20: note: in expansion of macro 'ClassImp'
 ClassImp(FitParam) ClassImp(OptObject) ClassImp(Sensor2DMeas) ClassImp(DistancemeterMeas)
                    ^~~~~~~~
In file included from /cvmfs/cms-ib.cern.ch/nweek-02566/slc7_amd64_gcc700/lcg/root/6.12.07-pafccj/include/RtypesCore.h:23:0,
                 from /cvmfs/cms-ib.cern.ch/nweek-02566/slc7_amd64_gcc700/lcg/root/6.12.07-pafccj/include/Rtypes.h:23,
                 from /cvmfs/cms-ib.cern.ch/nweek-02566/slc7_amd64_gcc700/lcg/root/6.12.07-pafccj/include/TObject.h:17,
                 from /build/dlange/CMSSW_10_6_X_2019-03-05-2300/src/Alignment/CocoaFit/interface/NtupleObjects.h:11,
                 from /build/dlange/CMSSW_10_6_X_2019-03-05-2300/src/Alignment/CocoaFit/src/NtupleObjects.cc:7:
/cvmfs/cms-ib.cern.ch/nweek-02566/slc7_amd64_gcc700/lcg/root/6.12.07-pafccj/include/Rtypes.h:354:41: note: 'int ROOT::{anonymous}::R__dummyintdefault9' previously declared here
          static int _R__UNIQUE_(_NAME2_(R__dummyint,key)) __attribute__((unused)) = \                                                                                                                                          
                                         ^
/cvmfs/cms-ib.cern.ch/nweek-02566/slc7_amd64_gcc700/lcg/root/6.12.07-pafccj/include/RConfig.h:434:33: note: in definition of macro '_NAME2_'
 #   define _NAME2_(name1,name2) name1##name2
                                 ^~~~~
/cvmfs/cms-ib.cern.ch/nweek-02566/slc7_amd64_gcc700/lcg/root/6.12.07-pafccj/include/RConfig.h:455:27: note: in expansion of macro '_R__JOIN_'
 #   define _R__UNIQUE_(X) _R__JOIN_(X,__LINE__)
                           ^~~~~~~~~
/cvmfs/cms-ib.cern.ch/nweek-02566/slc7_amd64_gcc700/lcg/root/6.12.07-pafccj/include/Rtypes.h:354:21: note: in expansion of macro '_R__UNIQUE_'
          static int _R__UNIQUE_(_NAME2_(R__dummyint,key)) __attribute__((unused)) = \                                                                                                                                          
                     ^~~~~~~~~~~
/cvmfs/cms-ib.cern.ch/nweek-02566/slc7_amd64_gcc700/lcg/root/6.12.07-pafccj/include/Rtypes.h:354:33: note: in expansion of macro '_NAME2_'
          static int _R__UNIQUE_(_NAME2_(R__dummyint,key)) __attribute__((unused)) = \                                                                                                                                          
                                 ^~~~~~~
/cvmfs/cms-ib.cern.ch/nweek-02566/slc7_amd64_gcc700/lcg/root/6.12.07-pafccj/include/Rtypes.h:359:24: note: in expansion of macro 'ClassImpUnique'
 #define ClassImp(name) ClassImpUnique(name,default)
                        ^~~~~~~~~~~~~~
/build/dlange/CMSSW_10_6_X_2019-03-05-2300/src/Alignment/CocoaFit/src/NtupleObjects.cc:9:1: note: in expansion of macro 'ClassImp'
 ClassImp(FitParam) ClassImp(OptObject) ClassImp(Sensor2DMeas) ClassImp(DistancemeterMeas)
 ^~~~~~~~
/cvmfs/cms-ib.cern.ch/nweek-02566/slc7_amd64_gcc700/lcg/root/6.12.07-pafccj/include/Rtypes.h:356:42: error: redefinition of 'class ROOT::{anonymous}::R__dummyintdefault9_c'
          R__UseDummy(_R__UNIQUE_(_NAME2_(R__dummyint,key))); \                                                                                                                                                                 
                                          ^
/cvmfs/cms-ib.cern.ch/nweek-02566/slc7_amd64_gcc700/lcg/root/6.12.07-pafccj/include/RConfig.h:434:33: note: in definition of macro '_NAME2_'
 #   define _NAME2_(name1,name2) name1##name2

plus another several hundreds of lines
(cmsdev03:/build/dlange/CMSSW_10_6_X_2019-03-05-2300/go.2

**Comment by Dr15Jones** [comment] 2019-03-06 12:32
@davidlange6 what is the git diff of the file that will not compile?

**Comment by davidlange6** [comment] 2019-03-06 14:29
ah - I guess this is the problem - I guess its confused by the ClassImp lines not having a ';'?

-ClassImp(FitParam)
-ClassImp(OptObject)
-ClassImp(Sensor2DMeas)
-ClassImp(DistancemeterMeas) 
-ClassImp(Distancemeter1DimMeas)
-ClassImp(TiltmeterMeas)
-ClassImp(CopsMeas)  
+ClassImp(FitParam) ClassImp(OptObject) ClassImp(Sensor2DMeas) ClassImp(DistancemeterMeas)
+    ClassImp(Distancemeter1DimMeas) ClassImp(TiltmeterMeas) ClassImp(CopsMeas)

**Comment by davidlange6** [comment] 2019-03-06 14:46
Clang-format PRs
1) #26085 the formatting we looked at yesterday (but updated)
2) #26086  #1 but with reverting the template line break topic as brought up by Matti
3) #26087 #1 but breaking function arguments line by line.

So next steps:

Agree on which of these PRs we want - can we try to discuss in the next few days?

Commit the corresponding .clang-format to cmssw

Post hypernews with a planned migration path 

Suggestion for a potential timescale
 1) 2 weeks for anyone that wants to apply this formatting to their package / file can do it and make a PR (Fabio to facilitate the integration of theses PRs once their tests pass)
 2) Start migrating packages that have no outstanding PRs for the master branch. Make a PR per package (Fabio to facilitate the integration of theses PRs once their tests pass)
 3) Iterate on this as PRs are merged and more packages can be done
 4) At the same time (or soon after), enable clang-format in the code checks for new PRs
 5) Complete migration by running on remaining packages

**Comment by Dr15Jones** [comment] 2019-03-06 14:57
> ah - I guess this is the problem - I guess its confused by the ClassImp lines not having a ';'?

I just took a quick look at ROOT, ClassImp does allow a trailing ';' which is how ROOT actually uses it.

**Comment by davidlange6** [comment] 2019-03-06 15:40
ha - and in CMSSW we almost never have the ';'.

adding one is sufficient to make clang-format do the right thing in the example I followed.

**Comment by Dr15Jones** [comment] 2019-03-06 15:57
@davidlange6 Matti and I are finding it extremely difficult to see the effect of the various formating options. Instead of doing one giant change, could you instead

1) do a commit which is just the same as the commit '#26085'
2) change the format options and run again and make a second commit with the new format

In that way we can look at just one commit difference to see how the one formating option changes things.

**Comment by davidlange6** [comment] 2019-03-06 16:17
how about this

https://github.com/cms-sw/cmssw/commit/85a3a029e6f7aa132116516e052034450b1676d8

https://github.com/cms-sw/cmssw/commit/5c445893d31957c393047ced9ce263f852725286

**Comment by Dr15Jones** [comment] 2019-03-06 16:24
Perfect!

**Comment by makortel** [comment] 2019-03-06 16:25
@davidlange6 Thanks! I think https://github.com/cms-sw/cmssw/commit/85a3a029e6f7aa132116516e052034450b1676d8 is mostly better.

**Comment by kpedro88** [comment] 2019-03-06 17:35
I do not like 5c44589 at all - huge waste of space. If we want to have each function argument on a separate line (do we want this?), I would prefer the following approach:
```
      return GlobalContext(
        GlobalContext::Transition::kBeginLuminosityBlock,
        principal.id(),
        principal.runPrincipal().index(),
        principal.index(),
        principal.beginTime(),
        processContext
      );
```

**Comment by fabiocos** [comment] 2019-03-07 16:18
@davidlange6 your plan https://github.com/cms-sw/cmssw/issues/26082#issuecomment-470133536 looks reasonable, according to what we have discussed. My main concern is to try to avoid undoing fixes in subsequent PRs during the stages 1 - 3, that globally might last for several weeks.

**Comment by davidlange6** [comment] 2019-03-07 16:50
> On Mar 7, 2019, at 5:18 PM, Fabio Cossutti <notifications@github.com> wrote:
> 
> @davidlange6 your plan #26082 (comment) looks reasonable, according to what we have discussed. My main concern is to try to avoid undoing fixes in subsequent PRs during the stages 1 - 3, that globally might last for several weeks.
> 

imo we need to commit to pushing in these changes if we want this to work. There will be some conflicts without a doubt. We can also propose to delay any packages from the migration for a few weeks in cases where some significant development is coming

**Comment by davidlange6** [comment] 2019-03-21 13:34
coming back to this topic - i've closed #26085 as it seems #26086 is favored over it.

**Comment by davidlange6** [comment] 2019-03-21 13:39
hi @kpedro88 - i decided I don't understand your comment - as it seems to be exactly what is done in https://github.com/cms-sw/cmssw/commit/5c445893d31957c393047ced9ce263f852725286 aside from the location of the trailing ')'

**Comment by kpedro88** [comment] 2019-03-21 13:45
5c445893d31957c393047ced9ce263f852725286:
```
      return GlobalContext(GlobalContext::Transition::kBeginRun,
                           LuminosityBlockID(principal.run(), 0),
                           principal.index(),
                           LuminosityBlockIndex::invalidLuminosityBlockIndex(),
                           principal.beginTime(),
                           processContext);
```

Mine:
```
      return GlobalContext(
        GlobalContext::Transition::kBeginLuminosityBlock,
        principal.id(),
        principal.runPrincipal().index(),
        principal.index(),
        principal.beginTime(),
        processContext
      );
```

These do not look the same to me. The former has a ton of extra white space. Subordinate lines really only need to be indented once, not lined up with the leading '('.

**Comment by davidlange6** [comment] 2019-03-21 13:54
ah - got it. I personally much prefer the indentation done by clang-tidy.

**Comment by Dr15Jones** [comment] 2019-03-21 13:54
I also prefer the indentation done by clang-tidy.

**Comment by kpedro88** [comment] 2019-03-21 13:55
To me it is almost the height of ugliness (could only be worse if each line were indented differently...). This is the difficulty with aesthetics, I suppose.

**Comment by davidlange6** [comment] 2019-03-21 19:10
someone at JLab warmed me that clang-format will of course change with llvm version. I checked the clang-format output of cmssw using llvm6 vs llvm7

diff -r cmssw6 cmssw.7 | wc
    423    1795   21225

so small compared to the total...

**Comment by davidlange6** [comment] 2019-04-04 14:41
#26358 is the new proposal. please complain by tomorrow..

**Comment by fwyzard** [comment] 2019-04-04 15:05
How do I tell scram to run clang-format ?

**Comment by davidlange6** [comment] 2019-04-04 15:09
i've just been doing

find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\)' | xargs clang-format -i

**Comment by fwyzard** [comment] 2019-04-04 15:31
Yep, I ended up dong something similar.

One thing I do not like much is that it disrupts the hand-made alignment of `type     variable;`:
```diff
diff --git a/HLTrigger/Egamma/plugins/HLTEgammaDoubleEtDeltaPhiFilter.cc b/HLTrigger/Egamma/plugins/HLTEgammaDoubleEtDeltaPhiFilter.cc
index e79ce36e072..23db7c1dee9 100644
--- a/HLTrigger/Egamma/plugins/HLTEgammaDoubleEtDeltaPhiFilter.cc
+++ b/HLTrigger/Egamma/plugins/HLTEgammaDoubleEtDeltaPhiFilter.cc
@@ -19,80 +19,83 @@
 //
 // constructors and destructor
 //
-HLTEgammaDoubleEtDeltaPhiFilter::HLTEgammaDoubleEtDeltaPhiFilter(const edm::ParameterSet& iConfig) : HLTFilter(iConfig)
-{
-   inputTag_    = iConfig.getParameter< edm::InputTag > ("inputTag");
-   etcut_       = iConfig.getParameter<double> ("etcut");
-   minDeltaPhi_ = iConfig.getParameter<double> ("minDeltaPhi");
-   l1EGTag_     = iConfig.getParameter< edm::InputTag > ("l1EGCand");
-   inputToken_  = consumes<trigger::TriggerFilterObjectWithRefs> (inputTag_);
+HLTEgammaDoubleEtDeltaPhiFilter::HLTEgammaDoubleEtDeltaPhiFilter(const edm::ParameterSet& iConfig)
+    : HLTFilter(iConfig) {
+  inputTag_ = iConfig.getParameter<edm::InputTag>("inputTag");
+  etcut_ = iConfig.getParameter<double>("etcut");
+  minDeltaPhi_ = iConfig.getParameter<double>("minDeltaPhi");
+  l1EGTag_ = iConfig.getParameter<edm::InputTag>("l1EGCand");
+  inputToken_ = consumes<trigger::TriggerFilterObjectWithRefs>(inputTag_);
 }
```
though I guess that was intended.


The other is that it tends to get confused between comments and commented-out lines:
```diff
diff --git a/HLTrigger/Egamma/plugins/HLTEgammaDoubleEtDeltaPhiFilter.h b/HLTrigger/Egamma/plugins/HLTEgammaDoubleEtDeltaPhiFilter.h
index 231dd8b9c64..460132f6a84 100644
--- a/HLTrigger/Egamma/plugins/HLTEgammaDoubleEtDeltaPhiFilter.h
+++ b/HLTrigger/Egamma/plugins/HLTEgammaDoubleEtDeltaPhiFilter.h
@@ -20,20 +20,21 @@ namespace edm {
 //

 class HLTEgammaDoubleEtDeltaPhiFilter : public HLTFilter {
-
-   public:
-      explicit HLTEgammaDoubleEtDeltaPhiFilter(const edm::ParameterSet&);
-      ~HLTEgammaDoubleEtDeltaPhiFilter() override;
-      bool hltFilter(edm::Event&, const edm::EventSetup&, trigger::TriggerFilterObjectWithRefs & filterproduct) const override;
-      static void fillDescriptions(edm::ConfigurationDescriptions & descriptions);
-
-   private:
-      edm::InputTag inputTag_; // input tag identifying product contains filtered candidates
-      edm::EDGetTokenT<trigger::TriggerFilterObjectWithRefs>  inputToken_;
-      double etcut_;           // Et threshold in GeV
-      double minDeltaPhi_;    // minimum deltaPhi
- //   int    ncandcut_;        // number of egammas required
-      edm::InputTag l1EGTag_;
+public:
+  explicit HLTEgammaDoubleEtDeltaPhiFilter(const edm::ParameterSet&);
+  ~HLTEgammaDoubleEtDeltaPhiFilter() override;
+  bool hltFilter(edm::Event&,
+                 const edm::EventSetup&,
+                 trigger::TriggerFilterObjectWithRefs& filterproduct) const override;
+  static void fillDescriptions(edm::ConfigurationDescriptions& descriptions);
+
+private:
+  edm::InputTag inputTag_;  // input tag identifying product contains filtered candidates
+  edm::EDGetTokenT<trigger::TriggerFilterObjectWithRefs> inputToken_;
+  double etcut_;        // Et threshold in GeV
+  double minDeltaPhi_;  // minimum deltaPhi
+                        //   int    ncandcut_;        // number of egammas required
+  edm::InputTag l1EGTag_;
 };

-#endif //HLTEgammaDoubleEtDeltaPhiFilter_h
+#endif  //HLTEgammaDoubleEtDeltaPhiFilter_h
```
but I don't think we can do anything about it (apart from removing the commented out lines).

**Comment by davidlange6** [comment] 2019-04-09 10:23
ok #26398 should be it.

**Comment by davidlange6** [comment] 2019-04-09 10:26
I'd propose getting a slide into the joint plenary talk of Markus tomorrow to advertise that this is coming (with the additional potential clang-tidy change at the same time to be determined). Objections?

**Comment by Dr15Jones** [comment] 2019-04-09 11:40
Sounds good

**Comment by smuzaffar** [comment] 2019-09-09 15:44
@davidlange6 , can we close this now?

**Closed** 2019-11-18 22:18 UTC
Labels: pending-assignment
