### ISSUE TITLE
Build CMSSW_7_4_0_pre4

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#7172] opened 2015-01-14 19:23 UTC

**Comment by davidlange6** [comment] 2015-01-14 19:31
+1

**Comment by davidlange6** [comment] 2015-01-15 04:03
upload all



On Jan 14, 2015, at 6:58 PM, cmsbuild <notifications@github.com<mailto:notifications@github.com>> wrote:


The build has finished sucessfully for the architecture slc6_amd64_gcc491 and is ready to be uploaded.

  *   You can start the uploads by writing the comment: "upload all". I will upload all the architectures as soon as the build finishes successfully.
  *   Or you can start the upload only for slc6_amd64_gcc491 by writing: "upload slc6_amd64_gcc491".

You can see the log for the build here:
https://cmssdt.cern.ch/SDT/jenkins-artifacts/auto-build-release/CMSSW_7_4_0_pre4-slc6_amd64_gcc491/126
Some tests ( runTheMatrix.py -s ) are being run, the results will be posted when done.

**Comment by davidlange6** [comment] 2015-01-15 05:10
release-notes since CMSSW_7_4_0_pre2 slc6_amd64_gcc491

**Comment by davidlange6** [comment] 2015-01-15 05:29
@ktf - seems something is wrong here. Could you check and announce the release once its ok. (the root6 version is uploaded already)

**Comment by ktf** [comment] 2015-01-15 07:44
looking into it.

**Comment by ktf** [comment] 2015-01-15 07:54
I think the problem is that both pre4 and pre4ROOT6 needed to rebuild 
some externals (updated root to compile with clang) and they conflicted, 
with the ROOT6 version winning at upload time. It's now rebuilding the 
pre4 release resolving the conflict, so it should be done in a bit. Once 
that is done we will try to make the logic smarter (like it is now in 
the IBs).

**Comment by ktf** [comment] 2015-01-15 12:51
abort

**Closed** 2015-01-15 12:55 UTC
Labels: build-in-progress, release-notes-requested, slc6_amd64_gcc481-upload-ok, slc6_amd64_gcc491-upload-error
