### ISSUE TITLE
too many different non-versioned layouts for `pair<MuonTrackType,Ref<vector<Track>`

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmssw#37113] opened 2022-03-02 03:30 UTC
Something similar was already reported in 11_3_0_pre3 https://mattermost.web.cern.ch/cms-o-and-c/pl/dzqcc5poriy5zx5igm9bjr7npw

Here is a report mentioned in Feb 28 TRK POG meeting, in a simpler setup using interactive prompt:
(I tired in CMSSW_12_3_X_2022-02-28-1100 and in a bit older CMSSW_12_3_0_pre1)
```
FWLiteEnabler::enable();
e = new TChain("Events");
e->Add("root://cms-xrd-global.cern.ch//store/data/Commissioning2021/MinimumBias8/RECO/900GeVnomkFit_FEVT-v1/40000/aa98e17b-012c-492b-8e12-e530018cd464.root");
e->Add("root://cms-xrd-global.cern.ch//store/data/Commissioning2021/MinimumBias8/RECO/900GeVnomkFit_FEVT-v1/40000/ab71db55-c0e9-4e85-84a9-1508280782ff.root");
e->GetEntries();
```

leads to warnings
first, right after the file open
```
Warning in <TClass::Init>: no dictionary for class pair<reco::Muon::MuonTrackType,edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> > > is available
```
then a bit later
```
Warning in <TStreamerInfo::BuildCheck>:
   The class pair<reco::Muon::MuonTrackType,edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> > > transitioned from not having a specified class version
   to having a specified class version (the current class version is 1).
   However too many different non-versioned layouts of the class have been
   loaded so far.  This prevent the proper reading of objects written with
   the class layout version 2, in particular from the file:
   root://cms-xrd-global.cern.ch//store/data/Commissioning2021/MinimumBias8/RECO/900GeVnomkFit_FEVT-v1/40000/ab71db55-c0e9-4e85-84a9-1508280782ff.root.
   To work around this issue, load fewer 'old' files in the same ROOT session.
Warning in <TStreamerInfo::CompareContent>: The following data member of
the on-file layout version 2 of class 'pair<reco::Muon::MuonTrackType,edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> > >' differs from
the in-memory layout version 2:
   reco::Muon::MuonTrackType first; //
vs
   reco::Muon::MuonTrackType first; //
```

in the cmsRun jobs reading these files leads to an exception.
```
 An exception of category 'FileOpenError' occurred while
    [0] Calling InputSource::readFile_
    [1] Calling RootInputFileSequence::initTheFile()
    Additional Info:
       [a] Calling RootInputFileSequence::initTheFile(): fail to open the file with name root://gfe02.grid.hep.ph.ic.ac.uk:1097///store/data/Commissioning2021/MinimumBias8/RECO/900GeVnomkFit_FEVT-v1/40000/ab71db55-c0e9-4e85-84a9-1508280782ff.root
       [b] Input file root://cms-xrootd.gridpp.ac.uk//store/data/Commissioning2021/MinimumBias8/RECO/900GeVnomkFit_FEVT-v1/40000/ab71db55-c0e9-4e85-84a9-1508280782ff.root?tried=gfe02.grid.hep.ph.ic.ac.uk could not be opened.
       [c] Fatal Root Error: @SUB=TStreamerInfo::BuildCheck
    The class pair<reco::Muon::MuonTrackType,edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> > >  transitioned from not having a specified class version
    to having a specified class version (the current class version is 1).
    However too many different non-versioned layouts of the class have been
    loaded so far.  This prevent the proper reading of objects written with
    the class layout version 2, in particular from the file:
    root://cms-xrootd.gridpp.ac.uk//store/data/Commissioning2021/MinimumBias8/RECO/900GeVnomkFit_FEVT-v1/40000/ab71db55-c0e9-4e85-84a9-1508280782ff.root.
    To work around this issue, load fewer 'old' files in the same ROOT session.
 ----- End Fatal Exception
```

The process history for these files is
```
Processing History:
  LHC '' '"CMSSW_12_0_3_patch1"' [1]  (dd392193a5747b5c718c2371e7635ff9)
    HLT '' '"CMSSW_12_0_3_patch1"' [1]  (e49133644bc5afeef3ab479fd4e5745b)
      RECO '' '"CMSSW_12_1_1"' [1]  (99bd6b628277dec42c83d9e3e5a6dff3)

```

@pcanal

**Comment by slava77** [comment] 2022-03-02 03:31
@mmusich

**Comment by Dr15Jones** [comment] 2022-03-02 12:36
@pcanal

**Comment by pcanal** [comment] 2022-03-02 17:55
I thought I fixed the issue:
```
Warning in <TClass::Init>: no dictionary for class pair<reco::Muon::MuonTrackType,edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> > > is available
```
which should also (likely) have fixed the too-many version issue.   Which commit of ROOT are we using here?

**Comment by slava77** [comment] 2022-03-02 18:24
> I thought I fixed the issue:
> 
> ```
> Warning in <TClass::Init>: no dictionary for class pair<reco::Muon::MuonTrackType,edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> > > is available
> ```
> 
> which should also (likely) have fixed the too-many version issue. Which commit/version of ROOT are we using here?

in my test it was , according to 
https://github.com/cms-sw/cmsdist/blob/ALL/CMSSW_12_3_X_2022-02-28-1100/slc7_amd64_gcc10/root.spec

https://github.com/cms-sw/root/tree/11009abdb2a84fb354cea142c16bf27963053db6
from cms/v6-24-00-patches/292e441

**Comment by makortel** [comment] 2022-03-02 19:41
Using the same methodology for the other two releases mentioned in the issue description (@smuzaffar, is this the best way to figure out the exact version of a spec file that used in a release after the fact?)

CMSSW_12_3_0_pre1 has https://github.com/cms-sw/root/tree/5b76eded10db8060c87698bc6f34be4a72eca938 from cms/v6-22-00-patches/18c440c

CMSSW_11_3_0_pre3 has https://github.com/cms-sw/root/tree/9496c05e656f9c18c83cce6658f9f8914eaf2244 from cms/v6-22-00-patches/v6-22-06

**Comment by smuzaffar** [comment] 2022-03-02 20:52
@makortel , yes currently this is the easiest way to find the external specs. . For release one should use `REL/CMSSW_VERSION/SCRAM_ARCH` tag and for IBs `REL/CMSSW_VERSION/SCRAM_ARCH` tag of cmsdist should be used

**Comment by slava77** [comment] 2022-03-04 20:17
I tried the same test in the interactive root as in the PR description in more variants and observed the same symptoms 
- CMSSW_12_3_ROOT626_X_2022-02-28-2300, which is https://github.com/cms-sw/root/tree/cms/v6-26-00-patches/252cf52 or https://github.com/cms-sw/root/tree/a70499faadd8e9b70889b46c114b819d0a51d295
- CMSSW_12_3_ROOT6_X_2022-02-28-2300, which is https://github.com/cms-sw/root/tree/cms/master/657adad or https://github.com/cms-sw/root/tree/43b0ccf0bb687974ed680b93623a6383b196926d

**Comment by pcanal** [comment] 2022-03-04 21:23
@slava77 or @smuzaffar Could you copy the ROOT files in place accessible from cmsdev34?

**Comment by slava77** [comment] 2022-03-04 21:30
the files are on eos at CERN, but in case it helps, I made a copy at cmsdev34:/build/slava77/RawReference/MinimumBias8/Commissioning2021-900GeVnomkFit_FEVT-v1/RECO

**Comment by pcanal** [comment] 2022-03-04 21:49
It did help.  I can not reproduce the problem.  Thanks.

**Comment by pcanal** [comment] 2022-03-08 22:16
Note: one trigger of this problem is that the underlying type of the enum `reco::Muon::MuonTrackType` has some point explicitly (or maybe implicit through a CINT/Cling update) change from `int` to `unsigned int`.   Consequently the onfile layout of the type `pair<reco::Muon::MuonTrackType,edm::Ref<vector<reco::Track>, ....>` technically did change.

**Comment by makortel** [comment] 2022-03-08 22:41
I checked the history of `reco::Muon::MuonTrackType` and it has never specified explicitly the underlying type.

I'm guessing the type `pair<MuonTrackType, TrackRef>` comes from
https://github.com/cms-sw/cmssw/blob/a4ee4a972e3791a145270a47de42ccc53e4dbc96/DataFormats/MuonReco/src/classes_def.xml#L87
https://github.com/cms-sw/cmssw/blob/a4ee4a972e3791a145270a47de42ccc53e4dbc96/DataFormats/MuonReco/interface/Muon.h#L37

**Comment by pcanal** [comment] 2022-03-08 22:43
The issue is compounded with the fact that that pair "seems" to no longer be in active use in the data model (at least in the libraries autoloaded by opening the files) consequently there `TClass` for the pair stays in `emulated` mode and can 'only' guess on whether the pair class layout is 'versioned' or not 'versioned'.  

In this example, because the 2nd file ended up with the 2 versions of the class layout, the system 'guess' that it is versioned but the version '1' in the first file is different from the version '1' in the 2nd file, so it is added to the slot '2' and then it conflict with the version 'numbered 2' in the 2nd file.

**Comment by pcanal** [comment] 2022-03-09 00:31
> I'm guessing the type pair<MuonTrackType, TrackRef> comes from

It seems so.  And thus another work around is to call, before opening the files:

```
TClass::GetClass("map<reco::Muon::MuonTrackType,edm::Ref<vector<reco::Track>,reco::Track,edm::refhelper::FindUsingAdvance<vector<reco::Track>,reco::Track> > >")->GetCollectionProxy()->GetValueClass();
```

which triggers the generation of the "proper" TClass for the pair.

**Comment by makortel** [comment] 2022-03-09 19:57
> The issue is compounded with the fact that that pair "seems" to no longer be in active use in the data model (at least in the libraries autoloaded by opening the files)

Is this something that is a property of CMSSW code or ROOT code? (or some mixture of both?)

> In this example, because the 2nd file ended up with the 2 versions of the class layout, the system 'guess' that it is versioned but the version '1' in the first file is different from the version '1' in the 2nd file, so it is added to the slot '2' and then it conflict with the version 'numbered 2' in the 2nd file.

I'm very confused how this could have happened. The 2nd file is almost certainly a result of a merge job, because it contains data from two Runs. According to provenance everything was processed with the same CMSSW version (CMSSW_12_1_1 for RECO). The preceding step, HLT, used CMSSW_12_0_3_patch1, but from there the RECO job should not get anything related to `reco::Muon`. I tested the FWLite recipe in the description in 12_1_1, and it fails there in the same way.

Can the dictionary information of the `map<MuonTrackType, TrackRef>` from 12_0_3_patch1 nevertheless impact the 12_1_1 job?

Otherwise I can think of two otherwise similar job to end with with different version of this dictionary, but how?

Would adding version number for the `map<MuonTrackType, TrackRef>` dictionary declaration be of any help? (or could it break things even more?)

**Comment by pcanal** [comment] 2022-03-09 22:17
> Is this something that is a property of CMSSW code or ROOT code? (or some mixture of both?)

I was wrong, as you pointed out, it is still used but 'bring the TClass into' existence requires (usually indirectly) the execution of the code at https://github.com/cms-sw/cmssw/issues/37113#issuecomment-1062429408

**Comment by pcanal** [comment] 2022-03-09 22:21
> The 2nd file is almost certainly a result of a merge job, because it contains data from two Runs. 

That would most likely do it.  One file created before ROOT and/or Cling change the underlying type  and one file from after.

> Would adding version number for the map<MuonTrackType, TrackRef> dictionary declaration be of any help? (or could it break things even more?)

That would most certainly break things (i.e. you should not add version to the map nor the pair).

I am working on a solution (hopefully done this week) otherwise (or until then), the 'best' workaround is https://github.com/cms-sw/cmssw/issues/37113#issuecomment-1062429408

**Comment by makortel** [comment] 2022-03-10 00:45
> > The 2nd file is almost certainly a result of a merge job, because it contains data from two Runs.
> 
> That would most likely do it. One file created before ROOT and/or Cling change the underlying type and one file from after.

As far as I can tell the original files would have been produced with the same CMSSW version.

**Comment by pcanal** [comment] 2022-04-06 15:56
The issues related to this (handling of `std::pair`) have all been merged in the v6.24, v6.26 and main branches.

**Comment by makortel** [comment] 2023-04-13 14:48
+core

Looks like this issue can be closed

**Comment by makortel** [comment] 2023-04-13 14:48
@cmsbuild, please close

**Closed** 2023-04-13 14:48 UTC
Labels: core-approved, fully-signed
