### ISSUE TITLE
[DD4hep] [Simulation] [Validation]: Regions, root logical volumes and cuts

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#28398] opened 2019-11-14 10:10 UTC
* Default world region name is different

DD:
```
 "DefaultRegionForTheWorld" ,                               "OCMS" ,    10 ,     10 ,     10 ,     10 ,   mm
```
DD4hep:
```
 "DefaultRegionForTheWorld" ,                       "world_volume" ,    10 ,     10 ,     10 ,     10 ,   mm
```

* Units are off by x10

DD:
```
                "ZDCRegion" ,                                "ZDC" ,     1 ,      1 ,      1 ,      1 ,   mm
```
DD4hep:
```
                "ZDCRegion" ,                                "ZDC" ,   0.1 ,    0.1 ,    0.1 ,    0.1 ,   mm
```
* Some logical volumes contain namespace

DD:
```
        "TrackerSensRegion" ,                "TIDModule2RphiWafer" ,   0.1 ,    0.1 ,    0.1 ,    0.1 ,   mm
```
DD4hep:
```
        "TrackerSensRegion" ,     "tidmodule2:TIDModule2RphiWafer" ,  0.01 ,   0.01 ,   0.01 ,   0.01 ,   mm
```

**Comment by fabiocos** [comment] 2019-11-17 19:17
assign geometry

**Comment by civanch** [comment] 2019-11-27 22:02
@ianna , @cvuosalo , I would consider these 3 cases separately. For me the difference "OCMS" and "world_volume" should not bring any issue, we may want to return to OCMS only in order to be consistent. Other two cases are bugs to be fixed. I would avoid namespaces in the new description.

**Comment by cvuosalo** [comment] 2020-08-06 21:41
@ianna Is this issue still relevant? If so, could you please add a comment explaining how to reproduce these errors?

**Comment by ianna** [comment] 2020-08-07 08:39
yes, it should be reevaluated after we move to the new version of DD4hep where the default units are G4 ones.

**Comment by cvuosalo** [comment] 2020-08-07 21:55
@ianna What test script does one use to produce the output shown in this issue description?

**Comment by ianna** [comment] 2020-12-08 08:36
reevaluate after #32403

**Comment by ghugo83** [comment] 2021-03-24 11:04
Production cuts, comparison DDD <-> DD4hep:
- Units are properly fixed.
- World region name being different in DDD <-> DD4hep, and namespace presence in DD4hep, are independent points from production cuts.
- There were bugs in assignments of logical volumes to production cuts regions: 
Addressed in https://github.com/cms-sw/cmssw/pull/33101 (different search behavior in DD4hep over SpecPars, resulting in different prodcuts to root logical volumes assignments) + https://github.com/cms-sw/cmssw/pull/33164#event-4453572315 (reflected volumes were not taken into account for productions cuts assignemnts).

**Comment by ghugo83** [comment] 2021-03-24 11:04
Present comparison DDD <-> DD4hep:
**- NumberOfCouples   464 in both DDD and DD4hep
- Root logical volumes assignments are identical.
- Production range cuts values for all materials volumes are identical (all volumes, not only the root ones).**

Sorting and comparing all productions cuts for all materials in CMS (2021 scenario), there are only 2 small discrepancies appearing in computed energy thresholds (no issue in production range cuts):
* Material : Aluminium 2219:
DDD:
```
Range cuts        :  gamma  1 mm     e-  1 mm     e+  1 mm  proton 1 mm 
Energy thresholds :  gamma  7.73912 keV    e-  618.791 keV    e+  590.357 keV proton 100 keV
```
DD4hep:
```
Range cuts        :  gamma  1 mm     e-  1 mm     e+  1 mm  proton 1 mm 
Energy thresholds :  gamma  7.73912 keV    e-  618.791 keV    e+  586.403 keV proton 100 keV
```

* Material : Pix_Fwd_OuterBlade_AdhFilm
DDD:
```
 Range cuts        :  gamma  1 mm     e-  1 mm     e+  1 mm  proton 1 mm 
 Energy thresholds :  gamma  3.78332 keV    e-  693.679 keV    e+  670.758 keV proton 100 keV
```
DD4hep:
```
Range cuts        :  gamma  1 mm     e-  1 mm     e+  1 mm  proton 1 mm 
Energy thresholds :  gamma  3.78332 keV    e-  689.033 keV    e+  670.758 keV proton 100 keV
```

These small variations are due to slightly different materials descriptions (see https://github.com/cms-sw/cmssw/issues/28168). Hence, completely off-topic from production cuts.

Can conclude production cuts are now OK for a DDD <-> DD4hep comparison.

**Comment by civanch** [comment] 2021-06-09 14:33
+1

**Closed** 2021-06-09 14:55 UTC
Labels: fully-signed, geometry-approved
