### ISSUE TITLE
[G4VecGeom_X] Multiple relvals failed with "Stuck track"

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#37097] opened 2022-03-01 09:22 UTC
Several RelVals ([160.0](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_3_G4VECGEOM_X_2022-02-28-2300/pyRelValMatrixLogs/run/160.0_Hydjet2Q_MinBias_5020GeV_2018_ppReco+Hydjet2Q_MinBias_5020GeV_2018_ppReco+DIGIHI2018PPRECO+RECOHI2018PPRECOMB+ALCARECOHI2018PPRECO+HARVESTHI2018PPRECO/step1_Hydjet2Q_MinBias_5020GeV_2018_ppReco+Hydjet2Q_MinBias_5020GeV_2018_ppReco+DIGIHI2018PPRECO+RECOHI2018PPRECOMB+ALCARECOHI2018PPRECO+HARVESTHI2018PPRECO.log#/770-770), [1304.18](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_3_G4VECGEOM_X_2022-02-28-2300/pyRelValMatrixLogs/run/1304.18_ProdZEE_13UP18+ProdZEE_13UP18+DIGIUP18PROD1+RECOPRODUP18+MINIAODMCUP18+NANOPRODUP18/step1_ProdZEE_13UP18+ProdZEE_13UP18+DIGIUP18PROD1+RECOPRODUP18+MINIAODMCUP18+NANOPRODUP18.log#/1590-1590), [1304.181](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_3_G4VECGEOM_X_2022-02-28-2300/pyRelValMatrixLogs/run/1304.181_ProdZEE_13UP18ml+ProdZEE_13UP18ml+DIGIUP18PROD1+RECOPRODUP18+MINIAODMCUP18+NANOPRODUP18/step1_ProdZEE_13UP18ml+ProdZEE_13UP18ml+DIGIUP18PROD1+RECOPRODUP18+MINIAODMCUP18+NANOPRODUP18.log#/1773-1773), [1304.182](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_3_G4VECGEOM_X_2022-02-28-2300/pyRelValMatrixLogs/run/1304.182_ProdZEE_13UP18+ProdZEE_13UP18+DIGIUP18PROD1bParking+RECOPRODUP18bParking+MINIAODMCUP18bParking/step1_ProdZEE_13UP18+ProdZEE_13UP18+DIGIUP18PROD1bParking+RECOPRODUP18bParking+MINIAODMCUP18bParking.log#/1587-1587), [250200.118](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_3_G4VECGEOM_X_2022-02-28-2300/pyRelValMatrixLogs/run/250200.118_ProdZEE_13_pmx25ns+ProdZEE_13UP18+DIGIPRMXUP18_PROD_PU25+RECOPRMXUP18PROD_PU25+NANOEDMMC2018_PROD/step1_ProdZEE_13_pmx25ns+ProdZEE_13UP18+DIGIPRMXUP18_PROD_PU25+RECOPRMXUP18PROD_PU25+NANOEDMMC2018_PROD.log#/1575-1575), [250200.182](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_3_G4VECGEOM_X_2022-02-28-2300/pyRelValMatrixLogs/run/250200.182_ZEE_13UP18_RD+ZEE_13UP18_RD+DIGIPRMXUP18_PU25_RD+RECOPRMXUP18_PU25_L1TEgDQM_RD+HARVESTUP18_PU25_L1TEgDQM_RD/step1_ZEE_13UP18_RD+ZEE_13UP18_RD+DIGIPRMXUP18_PU25_RD+RECOPRMXUP18_PU25_L1TEgDQM_RD+HARVESTUP18_PU25_L1TEgDQM_RD.log#/1608-1608) ) failed with `Stuck Track: potential geometry or navigation problem.`

Error message:
```
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomNav0003
      issued by : G4Navigator::ComputeStep()
Stuck Track: potential geometry or navigation problem.
  Track stuck, not moving for 25 steps.
  Current  phys volume: 'PixelForwardInnerDiskCFInnerRing'
   - at position : (-3.025221731688998,36.22389584399818,-310.997522674291)
     in direction: (-0.5021349830335725,0.8473731737201923,-0.1726822610265527)
    (local position: (-3.025221731688998,36.22389584399818,1.002477325709037))
    (local direction: (-0.5021349830335725,0.8473731737201923,-0.1726822610265527)).
  Previous phys volume: 'PixelForwardDiskZminus'

  Likely geometry overlap - else navigation problem !
 Track *abandoned* due to excessive number of Zero steps. Event aborted. 


TrackID=8669 ParentID=0  pi+; Ekin(MeV)=218.227; time(ns)=7.10096; status=0
   position(mm): (-3.02522,36.2239,-310.998); direction: (-0.502135,0.847373,-0.172682)
   PhysicalVolume: PixelForwardInnerDiskCFInnerRing; material: FPix_CFSkin_InnerInnerRing
   stepNumber=383; stepLength(mm)=1e-07; weight=1 

-------- EEEE -------- G4Exception-END --------- EEEE -------
```

**Comment by Dr15Jones** [comment] 2022-03-01 13:29
Assign simulation

**Comment by iarspider** [comment] 2022-05-03 07:29
@cms-sw/simulation-l2 any progress? This still happens, e.g. [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_4_G4VECGEOM_X_2022-05-02-2300/pyRelValMatrixLogs/run/158.0_HydjetQ_B12_5020GeV_2018_ppReco+HydjetQ_B12_5020GeV_2018_ppReco+DIGIHI2018PPRECO+RECOHI2018PPRECOMB+ALCARECOHI2018PPRECO+HARVESTHI2018PPRECO/step1_HydjetQ_B12_5020GeV_2018_ppReco+HydjetQ_B12_5020GeV_2018_ppReco+DIGIHI2018PPRECO+RECOHI2018PPRECOMB+ALCARECOHI2018PPRECO+HARVESTHI2018PPRECO.log#/308-308)

**Comment by civanch** [comment] 2022-05-03 10:44
@iarspider , the problem may be reduced/fixed if we will integrate  vecgeom 1.1.20 (https://github.com/cms-sw/cmsdist/pull/7735 )

**Comment by civanch** [comment] 2022-08-23 07:30
+1

the problem is fixed now

**Comment by civanch** [comment] 2022-08-25 10:24
@iarspider , you may close this issue now.

**Closed** 2022-08-25 12:41 UTC
Labels: simulation-approved, fully-signed
