### ISSUE TITLE
Intermittent failures in DD4hep test workflow

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/cmssw#32646] opened 2021-01-12 16:48 UTC
I've seen this issue in unrelated PRs at least twice now:
https://github.com/cms-sw/cmssw/pull/32576#issuecomment-754892923
https://github.com/cms-sw/cmssw/pull/32574#issuecomment-758782363

**Comment by kpedro88** [comment] 2021-01-12 16:48
assign geometry

**Comment by cvuosalo** [comment] 2021-01-12 17:30
@civanch Could you please take a look at these errors? How might they be caused?

**Comment by cvuosalo** [comment] 2021-01-12 17:32
assign simulation

**Comment by civanch** [comment] 2021-01-12 17:39
I would guess, that this happens just now after recent PRs were merged. @cvuosalo , @hugo83, @bsunanda do you agree or it is something else?

**Comment by cvuosalo** [comment] 2021-01-12 17:54
@civanch I noticed some sporadic errors in my own tests of the workflow last month, so the instability has been present for a while. But the errors were not reproducible.

**Comment by civanch** [comment] 2021-01-15 07:14
This error has been discussed with expert in Geant4 tracking. It happens due to negative step length -1 mm, which is huge and is not related to precision lost. From my point of view, it is an indication that there is a broken geometry. Position of the initial point (-538.967161 604.098226 -167.072581), particle is e- of 6 keV.

**Comment by makortel** [comment] 2021-01-21 14:09
Here https://github.com/cms-sw/cmssw/pull/32576#issuecomment-764550520 is a different one, segfault in `__kernel_sincosl`
```
Disabling gnu++: clang has no __float128 support on this target!
PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
CompactLoader    INFO  +++ Processing compact file: /cvmfs/cms-ib.cern.ch/nweek-02664/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml with flag (null)
DD4CMS           INFO  +++ Processing the CMS detector description file:///cvmfs/cms-ib.cern.ch/nweek-02664/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/src/Geometry/CMSCommonData/data/dd4hep/cmsExtendedGeometry2021.xml

#6  0x0000100002c67f14 in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x100003590000 (LWP 118029)):
#0  0x0000100002c56df8 in poll () from /lib64/libc.so.6
#1  0x000010000878309c in full_read.constprop () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/pluginFWCoreServicesPlugins.so
#2  0x0000100008783ba8 in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/pluginFWCoreServicesPlugins.so
#3  0x00001000087850f0 in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x0000100002a373d8 in __kernel_sincosl () from /lib64/libm.so.6
#6  0x0000100002a2ffa8 in sincosl@@GLIBC_2.17 () from /lib64/libm.so.6
#7  0x0000100244ec83e8 in algorithm(dd4hep::Detector&, cms::DDParsingContext&, dd4hep::xml::Handle_t) [clone .isra.0] () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/libDD4hep_GeometryEcalCommonDataPlugins.so
#8  0x00001002415dc880 in void dd4hep::xml::Collection_t::for_each<dd4hep::Converter<dd4hep::(anonymous namespace)::DDLAlgorithm, dd4hep::xml::Handle_t> >(dd4hep::Converter<dd4hep::(anonymous namespace)::DDLAlgorithm, dd4hep::xml::Handle_t>) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/libDetectorDescriptionDD4HepPlugins.so
#9  0x00001002415ef250 in load_dddefinition(dd4hep::Detector&, dd4hep::xml::Handle_t) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/libDetectorDescriptionDD4HepPlugins.so
#10 0x00001002415f0884 in (anonymous namespace)::Factory<dd4hep::(anonymous namespace)::xml_document_DDDefinition, long (dd4hep::Detector*, dd4hep::xml::Handle_t*)>::call(dd4hep::Detector*, dd4hep::xml::Handle_t*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/libDetectorDescriptionDD4HepPlugins.so
#11 0x000010022321ab24 in dd4hep::DetectorLoad::processXMLElement(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dd4hep::xml::Handle_t const&) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/32576/12408/CMSSW_11_3_X_2021-01-20-2300/external/slc7_ppc64le_gcc9/lib/libDDCore.so.1.14
#12 0x000010022321c4fc in dd4hep::DetectorLoad::processXML(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dd4hep::xml::UriReader*) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/32576/12408/CMSSW_11_3_X_2021-01-20-2300/external/slc7_ppc64le_gcc9/lib/libDDCore.so.1.14
#13 0x000010022320c640 in non-virtual thunk to dd4hep::DetectorImp::fromCompact(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dd4hep::DetectorBuildType) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/32576/12408/CMSSW_11_3_X_2021-01-20-2300/external/slc7_ppc64le_gcc9/lib/libDDCore.so.1.14
#14 0x00001002415605c8 in (anonymous namespace)::Factory<dd4hep::(anonymous namespace)::DD4hep_CompactLoader, long (dd4hep::Detector*, int, char**)>::call(dd4hep::Detector*, int, char**) () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/32576/12408/CMSSW_11_3_X_2021-01-20-2300/external/slc7_ppc64le_gcc9/lib/libDDCorePlugins.so.1.14
#15 0x0000100223203518 in dd4hep::DetectorImp::apply(char const*, int, char**) const () from /cvmfs/cms-ci.cern.ch/week0/cms-sw/cmssw/32576/12408/CMSSW_11_3_X_2021-01-20-2300/external/slc7_ppc64le_gcc9/lib/libDDCore.so.1.14
#16 0x0000100222b364e0 in cms::DDDetector::process(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/libDetectorDescriptionDDCMS.so
#17 0x0000100222b36e44 in cms::DDDetector::DDDetector(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/libDetectorDescriptionDDCMS.so
#18 0x0000100225e65a20 in DDDetectorESProducer::produceGeom(IdealGeometryRecord const&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/pluginDetectorDescriptionPlugins.so
#19 0x0000100225e76980 in decltype ({parm#1}()) edm::convertException::wrap<edm::eventsetup::Callback<DDDetectorESProducer, std::unique_ptr<cms::DDDetector, std::default_delete<cms::DDDetector> >, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator<IdealGeometryRecord> >::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}::operator()() const::{lambda()#1}>(edm::eventsetup::Callback<DDDetectorESProducer, std::unique_ptr<cms::DDDetector, std::default_delete<cms::DDDetector> >, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator<IdealGeometryRecord> >::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}::operator()() const::{lambda()#1}) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/pluginDetectorDescriptionPlugins.so
#20 0x0000100225e76fa8 in edm::eventsetup::Callback<DDDetectorESProducer, std::unique_ptr<cms::DDDetector, std::default_delete<cms::DDDetector> >, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator<IdealGeometryRecord> >::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}::operator()() const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/pluginDetectorDescriptionPlugins.so
#21 0x0000100225e78868 in void edm::SerialTaskQueueChain::actionToRun<edm::eventsetup::Callback<DDDetectorESProducer, std::unique_ptr<cms::DDDetector, std::default_delete<cms::DDDetector> >, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator<IdealGeometryRecord> >::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}&>(edm::eventsetup::Callback<DDDetectorESProducer, std::unique_ptr<cms::DDDetector, std::default_delete<cms::DDDetector> >, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator<IdealGeometryRecord> >::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}&) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/pluginDetectorDescriptionPlugins.so
#22 0x0000100225e78928 in edm::SerialTaskQueue::QueuedTask<edm::SerialTaskQueueChain::push<edm::eventsetup::Callback<DDDetectorESProducer, std::unique_ptr<cms::DDDetector, std::default_delete<cms::DDDetector> >, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator<IdealGeometryRecord> >::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}>(edm::eventsetup::Callback<DDDetectorESProducer, std::unique_ptr<cms::DDDetector, std::default_delete<cms::DDDetector> >, IdealGeometryRecord, edm::eventsetup::CallbackSimpleDecorator<IdealGeometryRecord> >::runProducerAsync(std::__exception_ptr::exception_ptr const*, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&)::{lambda()#1}&&)::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/pluginDetectorDescriptionPlugins.so
#23 0x000010000249b4fc in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::process_bypass_loop (this=0x10000385b200, context_guard=..., t=0x100003732440, isolation=0) at ../../include/tbb/task.h:1003
#24 0x000010000249b834 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::local_wait_for_all (this=0x10000385b200, parent=..., child=<optimized out>) at ../../include/tbb/task.h:1003
#25 0x000010000249c220 in tbb::internal::custom_scheduler<tbb::internal::IntelSchedulerTraits>::wait_for_all (this=<optimized out>, parent=..., child=0x0) at ../../src/tbb/governor.h:123
#26 0x00001000001e25b4 in tbb::interface7::internal::delegated_function<edm::eventsetup::DataProxy::get(edm::eventsetup::EventSetupRecordImpl const&, edm::eventsetup::DataKey const&, bool, edm::ActivityRegistry const*, edm::EventSetupImpl const*) const::{lambda()#1} const, void>::operator()() const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#27 0x00001000024949a8 in tbb::interface7::internal::task_arena_base::internal_execute (this=0x1000004f6ca0 <edm::esTaskArena()::s_arena>, d=...) at ../../src/tbb/arena.cpp:1105
#28 0x00001000001e2908 in edm::eventsetup::DataProxy::get(edm::eventsetup::EventSetupRecordImpl const&, edm::eventsetup::DataKey const&, bool, edm::ActivityRegistry const*, edm::EventSetupImpl const*) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#29 0x000010000029ff88 in edm::eventsetup::EventSetupRecordImpl::getFromProxy(edm::eventsetup::DataKey const&, edm::eventsetup::ComponentDescription const*&, bool, edm::EventSetupImpl const*) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
#30 0x00001002388b23bc in OscarMTMasterThread::readES(edm::EventSetup const&) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/biglib/slc7_ppc64le_gcc9/pluginSimulation.so
#31 0x00001002388b30f0 in OscarMTMasterThread::beginRun(edm::EventSetup const&) const () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/biglib/slc7_ppc64le_gcc9/pluginSimulation.so
#32 0x000010023889c080 in OscarMTProducer::globalBeginRun(edm::Run const&, edm::EventSetup const&, OscarMTMasterThread const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/biglib/slc7_ppc64le_gcc9/pluginSimulation.so
#33 0x00001002388a5290 in edm::stream::ProducingModuleAdaptor<OscarMTProducer, edm::stream::EDProducerBase, edm::stream::EDProducerAdaptorBase>::doBeginRun(edm::RunTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/biglib/slc7_ppc64le_gcc9/pluginSimulation.so
#34 0x00001000003cc66c in edm::WorkerT<edm::stream::EDProducerAdaptorBase>::implDoBegin(edm::RunTransitionInfo const&, edm::ModuleCallingContext const*) () from /cvmfs/cms-ib.cern.ch/week0/slc7_ppc64le_gcc9/cms/cmssw/CMSSW_11_3_X_2021-01-20-2300/lib/slc7_ppc64le_gcc9/libFWCoreFramework.so
```

**Comment by Dr15Jones** [comment] 2021-01-21 15:36
@makortel we've been seeing the ppc related failure consistently. We really need access to a machine to attempt to debug what is happening.

**Comment by makortel** [comment] 2021-01-21 17:18
Oh, it was PPC, missed that, thanks. Nevermind then (in this issue).

**Comment by civanch** [comment] 2021-04-25 09:46
+1

This is fixed now

**Comment by silviodonato** [comment] 2021-04-29 07:17
https://github.com/cms-sw/cmssw/pull/33568

**Closed by silviodonato** 2021-04-29 07:17 UTC
Labels: fully-signed, geometry-approved, simulation-approved
