### ISSUE TITLE
ROOT files with duplicated GUIDs observed on production T0 replay workflows

### ISSUE THREAD

**Issue by khurtado** [cms-sw/cmssw#37240] opened 2022-03-14 15:06 UTC
This is related to a WMCore issue:

https://github.com/dmwm/WMCore/issues/10870

**Bug description**
When deploying T0 replays with a significant amount of jobs, one of the WMCore components fail complaining about duplicated LFNs. Our LFN patterns look like this:

```
/store/unmerged/HG2202_Val/RelValProdMinBias/GEN-SIM/HG2202_Val_OLD_Alanv4-v22/00000/2AE85F14-94A1-EC11-BBF5-FA163EC7AA59.root
````
where: `2AE85F14-94A1-EC11-BBF5-FA163EC7AA59` is the GUID extracted from the ROOT file through the framework XML job report.

So we are basically observing 2 different jobs generating files with the same GUID.
We get the GUID from the framework XML job report [here:](https://github.com/dmwm/WMCore/blob/6cab2cbec356c63f9c175ac21995dc199ea0ad5d/src/python/WMCore/FwkJobReport/FileInfo.py#L103-L110)

And since the GUID from the FW report seems to be generated here:
https://github.com/cms-sw/cmssw/blob/master/FWCore/Utilities/src/Guid.cc#L18-L28

I'm reporting the issue here.

**How to reproduce**
Deploy a Tier0 replay with a significant amount of jobs. I think @germanfgv can help with this if needed. At least one incident has been reported per week lately this year.

**Comment by makortel** [comment] 2022-03-14 15:33
@khurtado What CMSSW version was used in these tests? Was there only one GUID collision in the replay or many? Do you have any information about the hosts that produced the files whose GUIDs collided?

**Comment by makortel** [comment] 2022-03-14 15:36
The process-level GUID is created here
https://github.com/cms-sw/cmssw/blob/62d26a25201604dae1a25c3ccf434613cda1cc18/FWCore/Utilities/src/processGUID.cc#L4-L7
Notably this calls the `edm::Guid()` constructor with `usetime == false` leading to
https://github.com/cms-sw/cmssw/blob/62d26a25201604dae1a25c3ccf434613cda1cc18/FWCore/Utilities/src/Guid.cc#L21-L27
branch being taken.

**Comment by khurtado** [comment] 2022-03-14 15:54
@makortel 
They were using:
`CMSSW_12_0_2_patch1` with scram arch: `slc7_amd64_gcc900`

You can find logs of different set of jobs generating files with the same guid here:
```/afs/cern.ch/user/c/cmst0/public/JobAccountant/jobs```

Logs seem to have 2 replays, one with many incidents, involving 2 files/jobs but one of them (in `g5` directory) involves 3 files/jobs:

```
[khurtado@lxplus708 /afs/cern.ch/user/c/cmst0/public/JobAccountant/jobs]$ find . -name "dupPickles.json" -exec head -n 2 {} \;
{
  "/data/tier0/srv/wmagent/3.0.1/install/tier0/JobCreator/JobCache/Express_Run343082_StreamCalibration_Tier0_REPLAY_2021_v2110131547_211013_1547/Express/JobCollection_1_1/job_1058/Report.0.pkl": {
{
  "/data/tier0/srv/wmagent/3.0.1/install/tier0/JobCreator/JobCache/Express_Run343082_StreamCalibration_Tier0_REPLAY_2021_v2110131547_211013_1547/Express/JobCollection_1_1/job_1064/Report.0.pkl": {
{
  "/data/tier0/srv/wmagent/3.0.1/install/tier0/JobCreator/JobCache/Express_Run343082_StreamCalibration_Tier0_REPLAY_2021_v2110131547_211013_1547/Express/JobCollection_1_1/job_1038/Report.0.pkl": {
{
  "/data/tier0/srv/wmagent/3.0.1/install/tier0/JobCreator/JobCache/Express_Run343082_StreamCalibration_Tier0_REPLAY_2021_v2110131547_211013_1547/Express/JobCollection_1_0/job_527/Report.0.pkl": {
{
  "/data/tier0/srv/wmagent/3.0.1/install/tier0/JobCreator/JobCache/Express_Run344063_StreamCalibration_Tier0_REPLAY_2021_v2110131547_211013_1548/Express/JobCollection_5_1/job_4623/Report.0.pkl": {
```

The condor logfiles have information about the hosts runninig these jobs. The collisions seem to involve different condor jobs, but running in the same host:

```
[khurtado@lxplus708 /afs/cern.ch/user/c/cmst0/public/JobAccountant/jobs]$ find . -name "condor*out" -exec grep -H Hostname {} \; | sort
./g1/job_1038/condor.41731.37.out:Hostname:   b7g18p9798.cern.ch
./g1/job_1048/condor.41731.47.out:Hostname:   b7g18p9798.cern.ch
./g2/job_98/condor.41726.97.out:Hostname:   b7g18p7310.cern.ch
./g2/job_99/condor.41726.98.out:Hostname:   b7g18p7310.cern.ch
./g3/job_1137/condor.41731.136.out:Hostname:   b7g17p4406.cern.ch
./g3/job_1138/condor.41731.137.out:Hostname:   b7g17p4406.cern.ch
./g4/job_1169/condor.41731.168.out:Hostname:   b7g18p3673.cern.ch
./g4/job_1170/condor.41731.169.out:Hostname:   b7g18p3673.cern.ch
./g5/job_527/condor.41729.133.out:Hostname:   b7g10p4995.cern.ch
./g5/job_530/condor.41729.136.out:Hostname:   b7g10p4995.cern.ch
./g5/job_531/condor.41729.137.out:Hostname:   b7g10p4995.cern.ch
./g6/job_4623/condor.41780.47.out:Hostname:   b7g17p1733.cern.ch
./g6/job_4635/condor.41780.59.out:Hostname:   b7g17p1733.cern.ch
```

And they involve the same or almost the same date:

```
[khurtado@lxplus708 /afs/cern.ch/user/c/cmst0/public/JobAccountant/jobs]$ find . -name "condor*out" -exec grep -H "Local time" {} \; | sort
./g1/job_1038/condor.41731.37.out:Local time: Wed Oct 13 16:25:29 CEST 2021
./g1/job_1048/condor.41731.47.out:Local time: Wed Oct 13 16:25:29 CEST 2021
./g2/job_98/condor.41726.97.out:Local time: Wed Oct 13 15:58:51 CEST 2021
./g2/job_99/condor.41726.98.out:Local time: Wed Oct 13 15:58:53 CEST 2021
./g3/job_1137/condor.41731.136.out:Local time: Wed Oct 13 16:26:53 CEST 2021
./g3/job_1138/condor.41731.137.out:Local time: Wed Oct 13 16:26:53 CEST 2021
./g4/job_1169/condor.41731.168.out:Local time: Wed Oct 13 16:27:32 CEST 2021
./g4/job_1170/condor.41731.169.out:Local time: Wed Oct 13 16:27:31 CEST 2021
./g5/job_527/condor.41729.133.out:Local time: Wed Oct 13 16:18:54 CEST 2021
./g5/job_530/condor.41729.136.out:Local time: Wed Oct 13 16:18:54 CEST 2021
./g5/job_531/condor.41729.137.out:Local time: Wed Oct 13 16:18:54 CEST 2021
./g6/job_4623/condor.41780.47.out:Local time: Wed Oct 13 17:34:21 CEST 2021
./g6/job_4635/condor.41780.59.out:Local time: Wed Oct 13 17:34:21 CEST 2021
```

**Comment by khurtado** [comment] 2022-03-14 16:16
I unfortunately don't have direct ssh access to these machines. I can probably submit some condor jobs matching to these hosts, but I don't know how long they would take to match and run. I will check if there is anybody with direct access to them for a quick check or submit those jobs otherwise.

Do you know if `/dev/urandom` and `/proc/sys/kernel/random/entropy_avail` can vary depending on wether they run inside a singularity container or not by the way? We run these jobs inside containers in production.

**Comment by dan131riley** [comment] 2022-03-14 19:07
Am I reading the logs correctly, that the duplicates are all in the DQMIO output?  DQMIO does not use the code Matti pointed to, it calls `TFile::GetUUID()` instead:

https://github.com/cms-sw/cmssw/blob/ce4f5b212642a02e5c7ccff8403fdbf6f0306865/DQMServices/FwkIO/plugins/DQMRootOutputModule.cc#L327-L338

That UUID comes from `TUUID()`, see comments here: https://github.com/root-project/root/blob/bd7c94375627ae10a401543ac84f296f5386c874/core/base/src/TUUID.cxx#L24-L30  `TUUID()` only implements the older UUID generation algorithm that uses the system time and ethernet address.  We actually had to switch away from that algorithm to the one that uses `/dev/urandom` because we were getting duplicates in docker containers, as apparently containers don't guarantee clock monotonicity across different containers on the same system.

So, if it is just the DQMIO getting duplicates, that's not unexpected and the issue is with the DQM use of the ROOT UUID.

**Comment by makortel** [comment] 2022-03-14 19:44
> DQMIO does not use the code Matti pointed to,

On a closer look my reference to `edm::processGUID()` was incorrect anyway, `RootOutputFile` doesn't use it either but calls `edm::createGlobalIdentifier()`
https://github.com/cms-sw/cmssw/blob/ce4f5b212642a02e5c7ccff8403fdbf6f0306865/IOPool/Output/src/RootOutputFile.cc#L199
https://github.com/cms-sw/cmssw/blob/ce4f5b212642a02e5c7ccff8403fdbf6f0306865/IOPool/Output/src/RootOutputFile.cc#L230-L239

`edm::createGlobalIdentifier()` itself is just
https://github.com/cms-sw/cmssw/blob/ce4f5b212642a02e5c7ccff8403fdbf6f0306865/FWCore/Utilities/src/GlobalIdentifier.cc#L5-L8

I see I changed the DQMIO output behavior from `edm::createGlobalIdentifier()` to `TFile::GetUUID()`  in #28551 to fix inconsistency between DQMIO input and output that was reported in #28534.

Then I see #28622 removed the whole call to `edm::JobReport::inputFileOpened()` from `DQMRootSource` (?!) that used the `TFile::GetUUID()`.

So on one hand, we could easily change the `DQMRootOutputModule` to use `edm::createGlobalIdentifier()` without worrying the consistency raised in #28534, but on the other hand, should `DQMRootSource` report `inputFileOpened()`?

**Comment by khurtado** [comment] 2022-03-14 19:44
@dan131riley We do see more occurrences in DQMIO, but If you look at the json in the `g3` or or `g4` directories from the T0 folks, you will see there are other datatiers with the problem. E.g.:

``` 
  "dup_lfns": [
      "/store/unmerged/data/Tier0_REPLAY_2021/StreamCalibration/ALCARECO/Express-v2110131547/000/343/082/00001/a48e105e-4352-4d0e-a084-cb077219d1dd.root",
      "/store/unmerged/data/Tier0_REPLAY_2021/StreamCalibration/ALCARECO/Express-v2110131547/000/343/082/00001/a48e105e-4352-4d0e-a084-cb077219d1dd.root",
      "/store/unmerged/data/Tier0_REPLAY_2021/StreamCalibration/DQMIO/Express-v2110131547/000/343/082/00001/891C47F4-2C31-11EC-BA14-95C08E80BEEF.root",
      "/store/unmerged/data/Tier0_REPLAY_2021/StreamCalibration/DQMIO/Express-v2110131547/000/343/082/00001/891C47F4-2C31-11EC-BA14-95C08E80BEEF.root",
      "/store/unmerged/data/Tier0_REPLAY_2021/TestEnablesEcalHcal/RAW/Express-v2110131547/000/343/082/00001/523ec1e8-286f-47b2-b0a0-5534dbd7c492.root",
      "/store/unmerged/data/Tier0_REPLAY_2021/TestEnablesEcalHcal/RAW/Express-v2110131547/000/343/082/00001/523ec1e8-286f-47b2-b0a0-5534dbd7c492.root",
      "/store/unmerged/data/logs/prod/2021/10/13/Express_Run343082_StreamCalibration_Tier0_REPLAY_2021_v2110131547_211013_1547/Express/0001/0/Express-ac5ffd57-dc01-493f-ba17-951d97d7a523-0-logArchive.tar.gz",
      "/store/unmerged/data/logs/prod/2021/10/13/Express_Run343082_StreamCalibration_Tier0_REPLAY_2021_v2110131547_211013_1547/Express/0001/0/Express-ac5ffd57-dc01-493f-ba17-951d97d7a523-0-logArchive.tar.gz"
    ]
  },
```

(The logArchive.tar.gz are using our own `uuid` mechanism from python, so we need to fix that independently of the ROOT files).

Question: If we have this known problem with DQMIO, why can't this output type use the new UUID generation algorithm too?

**Comment by makortel** [comment] 2022-03-14 19:53
(FYI @cms-sw/dqm-l2 since we mentioned DQM modules)

**Comment by dan131riley** [comment] 2022-03-15 19:10
> @dan131riley We do see more occurrences in DQMIO, but If you look at the json in the `g3` or or `g4` directories from the T0 folks, you will see there are other datatiers with the problem.

It seems weird that the dups are either just DQMIO, or all of ALCARECO, DQMIO, RAW, and the logArchive.  The actual logs only cover the DQMIO case--can we get some logs for jobs where the whole set is duplicated?  I think we understand the DQMIO-only case, but the other case is still a mystery to me.

> Question from someone not knowledgeable on the topic: If we have this known problem with DQMIO, why can't this output type use the new UUID generation algorithm too?

It got overlooked--until I started investigating this issue, I hadn't realized `TFile::TUUID()` was using the old algorithm.

**Comment by khurtado** [comment] 2022-03-24 19:05
@dan131riley Sorry for the delay. We found a bug in the script that finds these duplicated LFNs. After fixing it, it seems the. only problem is DQMIO.

**Comment by drkovalskyi** [comment] 2022-03-29 13:14
Hi everyone. This issue affects the Tier0 operations and the detector commissioning. Is there any chance to speed it up?

**Comment by dan131riley** [comment] 2022-03-29 14:13
We will need to switch back to the `createGlobalIdentifier()`, I'm still looking into whether we can restore the DQMIO files to the input files FJR, I should have a PR tomorrow at the latest.

**Comment by drkovalskyi** [comment] 2022-03-29 14:16
Thanks Dan.

**Comment by perrotta** [comment] 2022-03-29 14:34
> Andrea, this problem is what caused Express failure last weekend. Our operators noticed it by chance (we don't normally have coverage during weekends). The risk is that it may happen again and we can be blind for a few days. If you have no strong pressure to release 12_2_2 now, let's wait for the fix. Otherwise we will need a patch release right after that.

That is exactly what I meant: if the PR is ready by tomorrow(ish), we can wait and build 12_2_2 with it.
Otherwise we build 12_2_2 now, since there are other requests for it, and another patch later on when the fix is available (not the preferred option)

**Comment by dan131riley** [comment] 2022-03-29 23:42
#37405 has the PR for master (comments and criticisms are welcome).  Backports will likely wait until tomorrow morning (US EDT).

**Comment by germanfgv** [comment] 2022-04-01 11:45
Hi @perrotta @dan131riley, thank you for you prompt actions. I see that this has been backported into `CMSSW_12_2_X`. I would like to know, when will the patch release be available? I'm guessing it will be `CMSSW_12_2_2_patch1`.

**Comment by qliphy** [comment] 2022-04-01 11:49
> Hi @perrotta @dan131riley, thank you for you prompt actions. I see that this has been backported into `CMSSW_12_2_X`. I would like to know, when will the patch release be available? I'm guessing it will be `CMSSW_12_2_2_patch1`.

@germanfgv yes, this will be included in CMSSW_12_2_2_patch1.  We are just trying to include another PR:  https://github.com/cms-sw/cmssw/pull/37417  (to be backported)        Hopefully 12_2_2_patch1 can be made in the weekend.

**Comment by makortel** [comment] 2022-04-01 12:45
I think it would be better to proceed without #37417 (even if it would lead to two separate patch releases).

**Comment by perrotta** [comment] 2022-04-01 13:07
CMSSW_12_2_3 is going to be built: https://github.com/cms-sw/cmssw/issues/37433

**Comment by germanfgv** [comment] 2022-04-01 15:46
@perrotta the release is built! how long would it be until it is updated in `/cvmfs`?

**Comment by germanfgv** [comment] 2022-04-01 15:49
ohh.. I see the process is still going on for  `slc7_amd64_gcc900`. Nvm!

**Comment by perrotta** [comment] 2022-04-01 16:37
> @perrotta the release is built! how long would it be until it is updated in `/cvmfs`?

At 3pm we said that the release will take "a few hours" and that it would have been hopefully ready before evening at Fermilab: we are still in track, I guess...

**Comment by davidlange6** [comment] 2022-04-01 16:41
Yea, sorry I missed the fact that it was full build at 3pm - seems to rely on someone working through the fnal evening to make this converge (at best). Given that no one spoke for this extra development its unfortunate that we make someone work Friday evening just for it.

**Comment by davidlange6** [comment] 2022-04-01 16:46
Probably a good reason to recover the ability to start branches in GitHub to facilitate patches in cases where the tip of the release branch has moved forward in some way. Useful for data taking.

**Comment by perrotta** [comment] 2022-04-01 16:49
@davidlange6 CMSSW_12_2_2 full build took less than six hous two days ago. That's why I asked today at the joint meeting by when it was needed, And the answer was "before this evening at Fermilab". If I am not wrong now it is almost noon at Fermilab, and I think we are perfectly in schedule for what was asked for.

**Comment by perrotta** [comment] 2022-04-01 19:19
Release CMSSW_12_2_3 is ready, see https://github.com/cms-sw/cmssw/releases/tag/CMSSW_12_2_3

**Comment by germanfgv** [comment] 2022-04-01 21:23
Thanks @perrotta. It is not in `cvmfs` yet, but we will try it as soon as it gets there.

**Comment by dan131riley** [comment] 2022-04-14 15:43
Ping…can this issue be resolved?

**Comment by makortel** [comment] 2022-04-14 15:52
@germanfgv @drkovalskyi Could you confirm that the issues with duplicated GUIDs are gone? (I'd assume so from the silence, but would like to check explicitly) Thanks!

**Comment by jhonatanamado** [comment] 2022-04-14 18:41
Hello @makortel , From Tier0 we can confirm that the issues with duplicated GUIDs are gone since CMSSW_12_2_3. Thanks.

**Comment by makortel** [comment] 2022-04-14 18:44
+1

Thanks @jhonatanamado

**Closed** 2022-04-14 23:10 UTC
Labels: core-approved, fully-signed
