### ISSUE TITLE
Look into function multiversioning on gcc

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#16675] opened 2016-11-17 14:18 UTC
The gcc compiler can build different versions of the same function and then at run time pick the one that best matches the algorithm. This is primarily intended to work with SIMD instructions:

https://gcc.gnu.org/wiki/FunctionMultiVersioning

Should we look into using this technology for the few places where we explicitly use SIMD or even cases where we know auto-vectorization works?

**Comment by Dr15Jones** [comment] 2016-11-17 14:18
@bbockelm @VinInn @davidlt Would you care to comment?

**Comment by VinInn** [comment] 2016-11-17 14:26
useless for us  (ok for libm; one library for all platforms). 
For CMSSW much better to have multiple "architecture".

And for the time being we have the problem that switching on AVX slows us down due to the clock that trottles down...  (which most probably is already hitting us on slc7 due to the use of AVX in libm and libc even if we would prefer to stick to SSE)

@fwyzard

**Comment by Dr15Jones** [comment] 2016-11-17 14:37
@VinInn I assume you are referring to something like this:
http://www.anandtech.com/show/8423/intel-xeon-e5-version-3-up-to-18-haswell-ep-cores-/5

which seems to come from the Intel's literature:
http://www.intel.com/content/dam/www/public/us/en/documents/white-papers/performance-xeon-e5-v3-advanced-vector-extensions-paper.pdf

**Comment by VinInn** [comment] 2016-11-17 14:40
and my infamous tests
https://twiki.cern.ch/twiki/bin/view/Main/VIAvxCost
that predates INTEL official announcement

**Comment by davidlt** [comment] 2016-11-17 14:41
I am currently doing that for Cloudfare zlib implementation.

Some very minimal statistics from 2015 January when I scanned WLCG with CRAB3:
```
                   SSE 4.1   SSE 4.2   AVX
CORES SUPPORT       170708    161464    90572
CORES NO SUPPORT    17714     26958     97850
```

SSE 4.2 first got available in 2008 on Core i7 CPUs. The last time I looked at the numbers for SSE4.2 and FMA, it looks like it takes about a decade before new technology in CPUs become widely available.

Low level bits, libm/glibc already used ifunc (FMV is implemented using ifunc). ifunc support depends on glibc version, 2.11.1 is the first to support it. Should work on anything above and incl. RHEL6. Our toolchain supports this.

There are some features which you cannot select via FMV, for those you need to write your own resolver and check CPUID bits. Basically FMV just generates ifunc resolver function for known arguments (they are listed on GCC documentation). Don't have information about Clang support. I think, they started pushing support  ~1 ago.

IIUC, due to thermal affects (higher power consumption) when using 256-bit vectors, there are multiple possible frequencies in cores and uncore part, aka AVX frequencies. Thus one probably needs to be efficient enough on AVX before actually use it. I think, it's gonna be hard to avoid AVX 256-bit instructions, because those could be executed on the same core not even by CMSSW, or by CMSSW but something we don't directly control (glibc).

**Comment by davidlt** [comment] 2016-11-17 14:48
There is also: https://tu-dresden.de/zih/forschung/ressourcen/dateien/laufende-projekte/firestarter/2015_hackenberg_hppac.pdf?lang=en that @VinInn pointed out last year.

> Probably the most momentous novelty comes as a conse- quence of two aspects: (1) the processor cannot continuously operate at full speed due to TDP limitations, and (2) the RAPL mechanism to enforce the TDP limitation has changed from a modeling to a measurement approach. The transpar- ent controls that set core and uncore frequencies according to TDP limitations complicate performance analysis tasks significantly. The significance of this change is tremendous: Starting with the Haswell-EP processor generation, the pre- viously observed power consumption variations will likely be replaced by uncontrollable and unpredictable performance variations, with a potentially large impact on the performance of tightly synchronized, large scale parallel applications. The newly introduced AVX frequency makes every clock speed above this level–including nominal frequency–opportunistic and unreliable. The performance of the uncore can change depending on the previous memory access patterns, making performance significantly less predictable, including increased performance at reduced clock speeds for certain workloads.

**Comment by VinInn** [comment] 2016-11-17 16:21
Btw, coming back to the original question, the code in https://twiki.cern.ch/twiki/bin/view/Main/VIAvxCost 
gives an example of "flexible" implementation that for instance can be used in
http://cmslxr.fnal.gov/source/RecoVertex/PrimaryVertexProducer/src/DAClusterizerInZ_vect.cc
to produce a Fat-library
(DAClusterizerInZ is the only place where we really gain using vectorization)
Producing a fat library for vdt for instance would require the use of OpenMP4 simd-functions
(currenlty we inline and auto-vectorize)
see https://github.com/VinInn/ctest/blob/master/floatPrec/vdtSIMD.h
and corresponding  .cc
btw due to ABI oddities OpenMP4 does not support FMA as an option (and FMA is the main gain one gets from AVX2 on intel and AMD  (but FMA is not in the generic spec of AVX2))

**Comment by bbockelm** [comment] 2016-11-17 16:38
I think I'm ready to give up on the approach of "one CMSSW compilation per CPU architecture in CVMFS".  There's too much operational machinery involved - I'd point out to the fact we've discussed it for 3-5 years but never actually gotten a demonstration done.

FMV could be used for really small targeted algorithms - after implementation, the ongoing operational machinery is relatively small.

An example case would be selectively enabling the Cloudflare fork of zlib on hosts that support SSE4.2 (and my AVX2 version of `adler32` on appropriate hosts).

In experimenting with zlib variants, I did have problems with the combination of FMV and LTO - it seems that LTO eliminated all versions except one at compile time?  Would be nice if @davidlt  could confirm

I don't think doing this CMSSW-wide makes a ton of sense.

**Comment by VinInn** [comment] 2016-11-17 17:19
> On 17 Nov, 2016, at 5:38 PM, Brian Bockelman <notifications@github.com> wrote:
> 
> In experimenting with zlib variants, I did have problems with the combination of FMV and LTO - it seems that LTO eliminated all versions except one at compile time? Would be nice if @davidlt could confirm
> 
> 
if this is the case we shall file a bug report to gcc. Please check with latest gcc version

**Comment by bbockelm** [comment] 2016-11-17 17:21
@VinInn - this was with the 6.2.0 release.  Haven't picked the issue apart further - I just disabled LTO in my zlib build and moved on.

**Comment by VinInn** [comment] 2016-11-18 11:02
in gcc 7 I see the symbols with lto as well
```
[innocent@vinavx3 ctest]$ c++ -Wall -fPIC -shared multiFunc.cpp -o multiFunc.so
[innocent@vinavx3 ctest]$ nm -C mul
multiFunc.cpp   multiFunc.so*   multiPtr.cc     multiTuple.cpp  
[innocent@vinavx3 ctest]$ nm -C multiF
multiFunc.cpp  multiFunc.so*  
[innocent@vinavx3 ctest]$ nm -C multiFunc.so
0000000000200df0 d _DYNAMIC
0000000000201000 d _GLOBAL_OFFSET_TABLE_
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
0000000000000757 T sum(float const*, float const*, float const*, int)
0000000000000787 T sum(float const*, float const*, float const*, int) [clone .arch_haswell]
00000000000007e7 T sum(float const*, float const*, float const*, int) [clone .arch_nehalem]
00000000000007b7 T sum(float const*, float const*, float const*, int) [clone .arch_sandybridge]
00000000000006bc t (anonymous namespace)::_sum0(float const*, float const*, float const*, int)
0000000000000940 r __FRAME_END__
0000000000201030 d __TMC_END__
0000000000201030 B __bss_start
                 w __cxa_finalize@@GLIBC_2.2.5
0000000000000670 t __do_global_dtors_aux
0000000000200de8 t __do_global_dtors_aux_fini_array_entry
0000000000201028 d __dso_handle
0000000000200de0 t __frame_dummy_init_array_entry
                 w __gmon_start__
0000000000201030 D _edata
0000000000201038 B _end
0000000000000818 T _fini
0000000000000588 T _init
0000000000201030 b completed.6873
00000000000005e0 t deregister_tm_clones
00000000000006b0 t frame_dummy
0000000000000620 t register_tm_clones
[innocent@vinavx3 ctest]$ c++ -Wall -fPIC -shared multiFunc.cpp -o multiFunc.so -flto
[innocent@vinavx3 ctest]$ nm -C multiFunc.so
0000000000200df0 d _DYNAMIC
0000000000201000 d _GLOBAL_OFFSET_TABLE_
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
0000000000000757 T sum(float const*, float const*, float const*, int)
0000000000000787 T sum(float const*, float const*, float const*, int) [clone .arch_haswell]
00000000000007e7 T sum(float const*, float const*, float const*, int) [clone .arch_nehalem]
00000000000007b7 T sum(float const*, float const*, float const*, int) [clone .arch_sandybridge]
00000000000006bc t (anonymous namespace)::_sum0(float const*, float const*, float const*, int)
0000000000000940 r __FRAME_END__
0000000000201030 d __TMC_END__
0000000000201030 B __bss_start
                 w __cxa_finalize@@GLIBC_2.2.5
0000000000000670 t __do_global_dtors_aux
0000000000200de8 t __do_global_dtors_aux_fini_array_entry
0000000000201028 d __dso_handle
0000000000200de0 t __frame_dummy_init_array_entry
                 w __gmon_start__
0000000000201030 D _edata
0000000000201038 B _end
0000000000000818 T _fini
0000000000000588 T _init
0000000000201030 b completed.6873
00000000000005e0 t deregister_tm_clones
00000000000006b0 t frame_dummy
0000000000000620 t register_tm_clones
```

**Comment by davidlt** [comment] 2016-11-18 12:21
Here are the tickets I managed to find about FMV.
- Bug 71990 - Function multiversioning prohibits inlining
- Bug 66295 - [5/6/7 Regression] LTO generates incorrect resolver call for function multiversioning
- Bug 68098 - Function multiversioning causes segfaults when used for member functions
- Bug 67946 - Function multiversioning ICE
- Bug 59865 - gnu multiversion calculates wrong target
- Bug 57546 - templated gnu multiversion function pointer returns wrong value
- Bug 58060 - separate compilation of gnu multiversioning gives undefined/multiple defined symbols at link time
- Bug 57561 - gnu function multiversion - resolver doesn't use isa priority according to documentation
- Bug 57378 - gnu multiversioning gives assembler error: foo.resolver is already defined
- Bug 57375 - gnu multiversioning selects different version depending on link order

What exactly blocks "one CMSSW compilation per CPU architecture in CVMFS"? Building CMSSW for Haswell, Broadwell, Skylake then getting those builds on CVMFS shouldn't be a problem.  Supporting multiple CMS architectures also doesn't sound too cumbersome. E.g., in we used to submit jobs to fc19_aarch64_gccABC from x86 machines. We also run CMSSW with non-production SCRAM arch once we need to validate CMSSW with new compiler. Your biggest problem would be validating more releases, which should be done automatic.

I think, we even used to have IBs tuned for newer Core i7 CPUs. 

It only makes sense to do this if one can achieve reasonable performance increase.

**Comment by davidlt** [comment] 2016-11-25 12:39
I just remembered I changed the why ICC builds compile half a year ago. I allowed ICC to generate functions for SSE4.1, SSE4.2, AVX, AVX2 if it finds any benefits in doing so. Thus CMSSW built with ICC is a "fat one". It contains gazillions optimised functions for various ISA extensions.

**Comment by smuzaffar** [comment] 2023-11-17 15:00
@Dr15Jones  , with SKYLAKEAVX512 type IBs/releases we have somehow implemented/tested this to see the improvements we can get.

Should we close this issue?

**Comment by Dr15Jones** [comment] 2023-11-17 15:02
I guess so.

**Closed** 2023-11-17 15:17 UTC
Labels: pending-assignment

**Comment by makortel** [comment] 2023-11-17 15:44
I agree

**Comment by makortel** [comment] 2023-11-17 15:45
assign core

**Comment by makortel** [comment] 2023-11-17 15:45
-core
