### ISSUE TITLE
Loads of python warnings in `DQMServices/Demo` unit tests 

### ISSUE THREAD

**Issue by mmusich** [cms-sw/cmssw#37724] opened 2022-04-28 10:41 UTC
When running the `DQMServices/Demo` unit tests in order to test PR https://github.com/cms-sw/cmssw/pull/37665 I encountered a lot of python warnings of the type:

```console
cvmfs/cms-ib.cern.ch/nweek-02729/slc7_amd64_gcc10/external/py3-setuptools/60.9.3-ddcab3b6a742c72fed5554de8ccaaf18/lib/python3.9/site-packages/_distutils_hack/__init__.py:17: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  warnings.warn(
/cvmfs/cms-ib.cern.ch/nweek-02729/slc7_amd64_gcc10/external/py3-setuptools/60.9.3-ddcab3b6a742c72fed5554de8ccaaf18/lib/python3.9/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
```
These are, by the way, visible also in the IB unit tests: [log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc10/CMSSW_12_4_X_2022-04-27-2300/unitTestLogs/DQMServices/Demo#/12755)

**Comment by makortel** [comment] 2022-04-28 13:11
assign dqm,core

**Comment by makortel** [comment] 2022-04-28 16:21
I tried out the command pointed out in the log, and got the following traceback for the warning message
```
Traceback (most recent call last):
  File "/build/mkortela/coresw/CMSSW_12_4_X_2022-04-26-1100/bin/slc7_amd64_gcc10/dqmiolistmes.py", line 24, in <module>
    runs = indices['Run'].array()
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-uproot/4.1.5-f3a47e6c85bc6a365ea24bf39852dd2d/lib/python3.9/site-packages/uproot/behaviors/TBranch.py", line 2095, in array
    _ranges_or_baskets_to_arrays(
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-uproot/4.1.5-f3a47e6c85bc6a365ea24bf39852dd2d/lib/python3.9/site-packages/uproot/behaviors/TBranch.py", line 3510, in _ranges_or_baskets_to_arrays
    uproot.source.futures.delayed_raise(*obj)
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-uproot/4.1.5-f3a47e6c85bc6a365ea24bf39852dd2d/lib/python3.9/site-packages/uproot/source/futures.py", line 46, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-uproot/4.1.5-f3a47e6c85bc6a365ea24bf39852dd2d/lib/python3.9/site-packages/uproot/behaviors/TBranch.py", line 3480, in basket_to_array
    arrays[branch.cache_key] = interpretation.final_array(
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-uproot/4.1.5-f3a47e6c85bc6a365ea24bf39852dd2d/lib/python3.9/site-packages/uproot/interpretation/numerical.py", line 115, in final_array
    output = library.finalize(output, branch, self, entry_start, entry_stop)
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-uproot/4.1.5-f3a47e6c85bc6a365ea24bf39852dd2d/lib/python3.9/site-packages/uproot/interpretation/library.py", line 497, in finalize
    awkward = self.imported
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-uproot/4.1.5-f3a47e6c85bc6a365ea24bf39852dd2d/lib/python3.9/site-packages/uproot/interpretation/library.py", line 494, in imported
    return uproot.extras.awkward()
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-uproot/4.1.5-f3a47e6c85bc6a365ea24bf39852dd2d/lib/python3.9/site-packages/uproot/extras.py", line 25, in awkward
    import awkward
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-awkward/1.8.0-6b23a972873c8b9d2c4e7a3fd8e9fc0e/lib/python3.9/site-packages/awkward/__init__.py", line 15, in <module>
    import awkward._v2
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-awkward/1.8.0-6b23a972873c8b9d2c4e7a3fd8e9fc0e/lib/python3.9/site-packages/awkward/_v2/__init__.py", line 15, in <module>
    import awkward._v2._util  # noqa: F401
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-awkward/1.8.0-6b23a972873c8b9d2c4e7a3fd8e9fc0e/lib/python3.9/site-packages/awkward/_v2/_util.py", line 9, in <module>
    import setuptools
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-setuptools/60.9.3-ddcab3b6a742c72fed5554de8ccaaf18/lib/python3.9/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-setuptools/60.9.3-ddcab3b6a742c72fed5554de8ccaaf18/lib/python3.9/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-setuptools/60.9.3-ddcab3b6a742c72fed5554de8ccaaf18/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 71, in do_override
    warn_distutils_present()
  File "/cvmfs/cms-ib.cern.ch/nweek-02730/slc7_amd64_gcc10/external/py3-setuptools/60.9.3-ddcab3b6a742c72fed5554de8ccaaf18/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 17, in warn_distutils_present
    warnings.warn(
UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
```

Something in how the uproot/awkward are set up? @smuzaffar

**Comment by makortel** [comment] 2022-04-28 17:18
Could actually be caused by https://github.com/scikit-hep/uproot4/issues/552

**Comment by smuzaffar** [comment] 2022-04-29 13:23
Looks like uproot is still using deprecated `distutils` and there is already a fix for this. @aandvalenzuela  is looking in to it and will update uproot4 to newer version

**Comment by smuzaffar** [comment] 2022-04-30 02:54
https://github.com/cms-sw/cmsdist/pull/7833 fixes this

**Closed** 2022-04-30 08:40 UTC
Labels: dqm-pending, core-pending, pending-signatures
