### ISSUE TITLE
SonicCallFailed exception in IB

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#38370] opened 2022-06-14 13:54 UTC
In IB CMSSW_12_5_X_2022-06-13-2300, workflow 10805.31, step3 we had the exception

```
----- Begin Fatal Exception 14-Jun-2022 05:20:40 CEST-----------------------
An exception of category 'SonicCallFailed' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 4 stream: 2
   [1] Running path 'dqmofflineOnPAT_1_step'
   [2] Prefetching for module SingleTopTChannelLeptonDQM_miniAOD/'singleTopElectronMediumDQM_miniAOD'
   [3] Prefetching for module PATElectronSlimmer/'slimmedElectrons'
   [4] Calling method for module PatPhotonDRNCorrectionProducer/'patPhotonsDRN'
Exception Message:
call failed after max 1 tries
----- End Fatal Exception -------------------------------------------------
```

there were a total of 3 exceptions, which happened on stream 0, 2 and 3. This was preceeded by the following warning on all three streams

```
%MSG-w TritonFailure:  PatPhotonDRNCorrectionProducer:patPhotonsDRN  14-Jun-2022 05:20:40 CEST Run: 1 Event: 5
An exception of category 'TritonFailure' occurred.
Exception Message:
evaluate(): unable to run and/or get result: Deadline Exceeded

%MSG
```

**Comment by Dr15Jones** [comment] 2022-06-14 13:55
assign reconstruction

**Comment by Dr15Jones** [comment] 2022-06-14 13:55
@kpedro88 FYI

**Comment by kpedro88** [comment] 2022-06-14 14:12
this was previously raised in #37767. if we're going to track it here now, can we close that one?

tagging @ssrothman here. we may need to consider some more automated handling of timeouts: in general, if we set them based on GPU performance, they could be too short for CPU performance (which tends to be slower by some factor, depending on the DNN architecture and data volume).

**Comment by ssrothman** [comment] 2022-06-14 14:31
As I mentioned in the previous issue, I still don't understand why a single call should take 10 seconds even on cpu, as the expected runtime is more like 10s of ms. @kpedro88 is this several order of magnitude timing variance normal/expected?

**Comment by kpedro88** [comment] 2022-06-14 14:42
It does seem like too much of a change to come from normal variation. Maybe the first event can be slow if the server is still loading necessary components into memory? We could think about increasing the timeout for the first event.

**Comment by ssrothman** [comment] 2022-06-14 14:45
Is the crash always on the first event?

**Comment by kpedro88** [comment] 2022-06-14 14:56
In this IB, it seems to be on the first event in each stream. It's also possible that some of our ongoing investigations into the performance of the CPU fallback server will reveal a different configuration to speed up inference and avoid this issue. For example, we're trying out a scheme that deploys one model instance per cmsRun thread, whereas the current default configuration just has one model instance for the whole job. @yongbinfeng

**Comment by ssrothman** [comment] 2022-06-14 15:18
There are no optimizations explicitly turned on in the DRN config files, although maybe there are some on by default when you use torch/torch-geometric?

**Comment by smuzaffar** [comment] 2022-10-12 21:10
this is duplicate of #37767 , lets close this and discuss it via #37767

**Closed by smuzaffar** 2022-10-12 21:10 UTC
Labels: reconstruction-pending, pending-signatures
