### ISSUE TITLE
Crash of many workflows in CMSSW_11_2_X_2020-06-01-2300

### ISSUE THREAD

**Issue by silviodonato** [cms-sw/cmssw#30074] opened 2020-06-02 08:37 UTC
Many workflows are crashing in CMSSW_11_2_X_2020-06-01-2300. At least those crashing with `ScheduleExecutionFailure` seem to be related to #29630. 
Here an example:
```
----- Begin Fatal Exception 02-Jun-2020 06:36:42 CEST-----------------------
An exception of category 'ScheduleExecutionFailure' occurred while
   [0] Calling beginJob
Exception Message:
Unrunnable schedule
Module run order problem found: 
L1Reco_step after l1extraParticles [path L1Reco_step], l1extraParticles consumes caloStage1LegacyFormatDigis, caloStage1LegacyFormatDigis after caloStage1Digis [path dqmoffline_step], caloStage1Digis after rctDigis [path dqmoffline_step], rctDigis after l1tGt [path dqmoffline_step], l1tGt after l1tGmt [path dqmoffline_step], l1tGmt after l1tRpctf [path dqmoffline_step], l1tRpctf after l1tCsctf [path dqmoffline_step], l1tCsctf after l1tDttf [path dqmoffline_step], l1tDttf after l1GtUnpack [path dqmoffline_step], l1GtUnpack after dqmProvInfo [path dqmoffline_step], dqmProvInfo after @EndPathStart [path dqmoffline_step], @EndPathStart consumes TriggerResults, TriggerResults consumes L1Reco_step
 Running in the threaded framework would lead to indeterminate results.
 Please change order of modules in mentioned Path(s) to avoid inconsistent module ordering.
----- End Fatal Exception -------------------------------------------------
```

**Comment by silviodonato** [comment] 2020-06-02 08:37
assign core

**Comment by makortel** [comment] 2020-06-02 12:49
I'm not really surprised, I'll get into it.

**Comment by makortel** [comment] 2020-06-02 17:42
Unrunnable schedule errors are fixed in https://github.com/cms-sw/cmssw/pull/30081

**Comment by makortel** [comment] 2020-06-02 21:47
The `SIGABRT` ones are fixed in https://github.com/cms-sw/cmssw/pull/30087 (and the `abort()` itself is changed to an exception in https://github.com/cms-sw/cmssw/pull/30082).

**Comment by makortel** [comment] 2020-06-03 02:00
> Unrunnable schedule errors are fixed in #30081

Second attempt is in https://github.com/cms-sw/cmssw/pull/30089

**Comment by makortel** [comment] 2020-06-03 13:31
The `ProductNotFound` errors caused by `egmElectronIsolationCITK` in 1325.X workflows are fixed in https://github.com/cms-sw/cmssw/pull/30094

**Comment by makortel** [comment] 2020-06-03 13:58
The `ProductNotFound` error in 1004.0 is fixed in https://github.com/cms-sw/cmssw/pull/30076

There should now be PRs to fix all failures caused by #29630 (unless I missed something).

**Comment by makortel** [comment] 2020-06-06 23:52
Seems that `140.55` is showing a new symptom after https://github.com/cms-sw/cmssw/pull/30089
```
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 263400 lumi: 65 event: 1036358 stream: 3
   [1] Running path 'dqmoffline_step'
   [2] Calling method for module MuonRecoOneHLT/'muonRecoOneHLT'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: edm::TriggerResults
Looking for module label: TriggerResults
Looking for productInstanceName: 
Looking for process: HLT
   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_X_2020-06-06-1100/pyRelValMatrixLogs/run/140.55_RunHI2015VR+RunHI2015VR+HYBRIDRepackHI2015VR+HYBRIDZSHI2015+RECOHID15+HARVESTDHI15/step4_RunHI2015VR+RunHI2015VR+HYBRIDRepackHI2015VR+HYBRIDZSHI2015+RECOHID15+HARVESTDHI15.log#/

**Comment by makortel** [comment] 2020-06-06 23:56
The failure in 138.1
```
An exception of category 'NoProxyException' occurred while
   [0] Processing  Event run: 334393 lumi: 576 event: 9562884 stream: 2
   [1] Running path 'dqmoffline_step'
   [2] Calling method for module SiPixelPhase1TrackClusters/'SiPixelPhase1TrackClustersAnalyzer_cosmics'
Exception Message:
No data of type "ClusterShapeHitFilter" with label "ClusterShapeHitFilter" in record "CkfComponentsRecord"
 Please add an ESSource or ESProducer to your job which can deliver this data.
```
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc820/CMSSW_11_2_X_2020-06-04-2300/pyRelValMatrixLogs/run/138.1_RunCosmics2020+RunCosmics2020+RECOCOSDRUN3+ALCACOSDRUN3+HARVESTDCRUN3/step2_RunCosmics2020+RunCosmics2020+RECOCOSDRUN3+ALCACOSDRUN3+HARVESTDCRUN3.log#/

might also be related, although it is not immediately evident why any PR merged in CMSSW_11_2_X_2020-06-04-2300 could cause it.

**Comment by makortel** [comment] 2020-06-08 00:00
The 140.55 got somehow fixed in CMSSW_11_2_X_2020-06-07-0000 (maybe because of https://github.com/cms-sw/cmssw/pull/30094?).

I'm investigating 138.1, and it does not seem to be directly caused by https://github.com/cms-sw/cmssw/pull/29630

**Comment by makortel** [comment] 2020-06-08 00:02
> I'm investigating 138.1, and it does not seem to be directly caused by #29630

I opened a new issue for it https://github.com/cms-sw/cmssw/issues/30140

**Comment by makortel** [comment] 2020-06-08 00:02
+1

**Closed** 2020-06-08 08:25 UTC
Labels: core-approved, fully-signed
