### ISSUE TITLE
MESetEcal  broken when using ROOT 6.0.12

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#21423] opened 2017-11-21 22:06 UTC
ROOT 6.12 used additional bits in `TH1::fBits` which broke the assumption in `MESetEcal`

https://github.com/cms-sw/cmssw/blob/54c17f0c102be607ddab88b6a5edcd104c0a81f7/DQM/EcalCommon/src/MESetEcal.cc#L226

This code needs to be changed to not interfere with ROOT 6.12's use of `TH1::fBits`

This problem is causing the 10_0_ROOT6_X IBs to fail.

**Comment by Dr15Jones** [comment] 2017-11-21 22:07
assign dqm

**Comment by Dr15Jones** [comment] 2017-11-21 22:07
@pcanal Though you should follow this.

**Comment by Dr15Jones** [comment] 2017-11-22 00:27
In a private email exchange, Philippe suggested
>I suspect you could use a TParameter<char> and put in the list of functions of the histogram but this might be a little heavy.
>Another choice could be to use the UniqueID field (unless you have TRef pointing to it, in which case TestBit(kIsReferenced) would be true).

**Comment by davidlange6** [comment] 2017-11-28 19:20
since this is blocking things, I'd propose to disable the setBIt lines if there is no feedback by the weekend.

**Comment by Dr15Jones** [comment] 2017-12-01 14:14
@davidlange6 any word on this?

**Comment by Dr15Jones** [comment] 2017-12-04 17:20
Worked around using #21635. With that pull request, the IB workflows are now successful.

**Comment by schneiml** [comment] 2019-01-16 09:46
@Dr15Jones , @tanmaymudholkar do the two mentioned PRs fix this for good? In that case, the issue should be closed.

**Comment by tanmaymudholkar** [comment] 2019-01-16 10:13
@schneiml : yes, the issue is fixed in ECAL DQM. Please feel free to close the issue.

**Comment by Dr15Jones** [comment] 2019-01-16 12:41
@schneiml when the DQM L2 are satisfied an issue assigned to dqm is done, you just have to make the ‘+1’ comment like in a pull request to signify the issue can be closed. The original creator of the pull request does not need to be the one to close it.

**Comment by andrius-k** [comment] 2019-01-16 15:13
+1

**Closed** 2019-04-27 21:51 UTC
Labels: dqm-approved, fully-signed
