### ISSUE TITLE
Exception on HLT_DoubleMediumDeepTauPFTauHPS35_eta2p1 Phase-2 workflow

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#42862] opened 2023-09-25 22:50 UTC
I just see relvals failure [1] from [2]. Not sure if this link to DeepTauId issue reported before in https://github.com/cms-sw/cmssw/issues/40437 and https://github.com/cms-sw/cmssw/issues/40733, as the error report looks different. I try to look on 13_1_0_preX relvals report, but I don't see this issue, so I am not clear what condition to make this exception happens.

[1]
```
An exception of category 'InvalidRun' occurred while
   [0] Processing  Event run: 1 lumi: 13 event: 648 stream: 0
   [1] Running path 'HLT_DoubleMediumDeepTauPFTauHPS35_eta2p1'
   [2] Calling method for module DeepTauId/'hltHpsPFTauDeepTauProducer'
Exception Message:
error while running session: INVALID_ARGUMENT: Incompatible shapes: [0,1,1,86] vs. [207]
	 [[{{node inner_egamma_norm_1/FusedBatchNorm_1/Mul}}]]
```

[2] 
https://cmsweb.cern.ch/couchdb/workloadsummary/_design/WorkloadSummary/_show/histogramByWorkflow/pdmvserv_RVCMSSW_13_3_0_pre2ZpToMM_m6000_14TeV__2026D98noPU_RV213_230913_122713_9881
https://cmsweb.cern.ch/couchdb/workloadsummary/_design/WorkloadSummary/_show/histogramByWorkflow/pdmvserv_RVCMSSW_13_3_0_pre2TenTau_15_500_Eta3p1__2026D98noPU_RV213_230913_122651_78

**Comment by srimanob** [comment] 2023-09-25 22:52
FYI @mmusich @rovere @SohamBhattacharya 
Not sure if this is a known issue on your side. But I just see it happens on 13_3 relvals, not 13_1 as you are focusing on.

**Comment by srimanob** [comment] 2023-09-25 22:52
assign upgrade,hlt

**Comment by mmusich** [comment] 2023-09-26 04:32
@srimanob thanks for reporting.

Fwiw, the path `HLT_DoubleMediumDeepTauPFTauHPS35_eta2p1` was introduced in master (CMSSW_13_3_X) in PR https://github.com/cms-sw/cmssw/pull/42562 and bacported in CMSSW_13_1_X in PR https://github.com/cms-sw/cmssw/pull/42649. 

@hsert FYI

**Comment by swagata87** [comment] 2023-09-26 08:11
Shouldn't one use `year=2026` instead of `2017`?
https://github.com/cms-sw/cmssw/blob/a288c8fdd1cbc6f2e0759f8ebbaa9763c76a7e70/HLTrigger/Configuration/python/HLT_75e33/modules/hltHpsPFTauDeepTauProducer_cfi.py#L14

and also [deepTau_2026v2p5_core.pb](https://github.com/cms-data/RecoTauTag-TrainingFiles/blob/master/DeepTauId/deepTau_2026v2p5_core.pb) etc files in here?
https://github.com/cms-sw/cmssw/blob/a288c8fdd1cbc6f2e0759f8ebbaa9763c76a7e70/HLTrigger/Configuration/python/HLT_75e33/modules/hltHpsPFTauDeepTauProducer_cfi.py#L10-L12

**Comment by SohamBhattacharya** [comment] 2023-09-26 08:17
> Shouldn't one use `year=2026` instead of `2017`?
> 
> https://github.com/cms-sw/cmssw/blob/a288c8fdd1cbc6f2e0759f8ebbaa9763c76a7e70/HLTrigger/Configuration/python/HLT_75e33/modules/hltHpsPFTauDeepTauProducer_cfi.py#L14
> 
> and also [deepTau_2026v2p5_core.pb](https://github.com/cms-data/RecoTauTag-TrainingFiles/blob/master/DeepTauId/deepTau_2026v2p5_core.pb) etc files in here?
> 
> https://github.com/cms-sw/cmssw/blob/a288c8fdd1cbc6f2e0759f8ebbaa9763c76a7e70/HLTrigger/Configuration/python/HLT_75e33/modules/hltHpsPFTauDeepTauProducer_cfi.py#L10-L12

I see this is also there in the 13_1 [backport](https://github.com/cms-sw/cmssw/blob/CMSSW_13_1_1/HLTrigger/Configuration/python/HLT_75e33/modules/hltHpsPFTauDeepTauProducer_cfi.py#L14).
May be @hsert can clarify.

**Comment by mmusich** [comment] 2023-09-26 08:26
> I see this is also there in the 13_1 [backport](https://github.com/cms-sw/cmssw/blob/CMSSW_13_1_1/HLTrigger/Configuration/python/HLT_75e33/modules/hltHpsPFTauDeepTauProducer_cfi.py#L14).

if this paths fire seldom enough it might be randomly failing in a 9k events relval.

**Comment by hsert** [comment] 2023-09-26 08:29
Yes, that is correct. It should be 2026. It was integrated in this way to have a preliminary version of the path. The path still requires some improvements and this is one of them.
Once we understand the performance issue that we observed, we will work on updating to a new/phase2 DeepTau training.


On 26 Sep 2023, at 11:17, SohamBhattacharya ***@***.******@***.***>> wrote:



Shouldn't one use year=2026 instead of 2017?

https://github.com/cms-sw/cmssw/blob/a288c8fdd1cbc6f2e0759f8ebbaa9763c76a7e70/HLTrigger/Configuration/python/HLT_75e33/modules/hltHpsPFTauDeepTauProducer_cfi.py#L14

and also deepTau_2026v2p5_core.pb<https://github.com/cms-data/RecoTauTag-TrainingFiles/blob/master/DeepTauId/deepTau_2026v2p5_core.pb> etc files in here?

https://github.com/cms-sw/cmssw/blob/a288c8fdd1cbc6f2e0759f8ebbaa9763c76a7e70/HLTrigger/Configuration/python/HLT_75e33/modules/hltHpsPFTauDeepTauProducer_cfi.py#L10-L12

I see this is also there in the 13_1 backport<https://github.com/cms-sw/cmssw/blob/CMSSW_13_1_1/HLTrigger/Configuration/python/HLT_75e33/modules/hltHpsPFTauDeepTauProducer_cfi.py#L14>.
May be @hsert<https://github.com/hsert> can clarify.

**Comment by mmusich** [comment] 2023-09-26 08:31
@hsert 

> Once we understand the performance issue that we observed, we will work on updating to a new/phase2 DeepTau training.

No. We can't let this randomly fail relvals (used by everyone) else. Please either fix or disable the path.

**Comment by srimanob** [comment] 2023-09-26 08:40
> > I see this is also there in the 13_1 [backport](https://github.com/cms-sw/cmssw/blob/CMSSW_13_1_1/HLTrigger/Configuration/python/HLT_75e33/modules/hltHpsPFTauDeepTauProducer_cfi.py#L14).
> 
> if this path fires seldom enough it might be randomly failing in a 9k events relval.

We don't see the failure in 13_1 because the last relvals came with CMSSW_13_1_0_pre4. The backport PR was merged in Aug, so we don't see it. I agree with @mmusich if we can't fix at this moment, we should disable the path.

**Comment by hsert** [comment] 2023-09-26 08:46
Ok, how urgent it is? I was working on updating it due to fixes needed, then focused on performance improvement since it was suggested in the Phase2 meeting. It may take some days to fix it. If it is urgent, then we can disable it.

**Comment by srimanob** [comment] 2023-09-26 08:49
To me, the next pre-release, CMSSW_13_3_0_pre4, is targeted on 2023/10/17. So if you can't fix it by, let's say, a week before (10 Oct), then please make a PR to disable it. Other may have different comments.

**Comment by SohamBhattacharya** [comment] 2023-09-26 08:57
> To me, the next pre-release, CMSSW_13_3_0_pre4, is targeted on 2023/10/17. So if you can't fix it by, let's say, a week before (10 Oct), then please make a PR to disable it. Other may have different comments.

Agreed, the path should be disabled for the time being if it crashes RelVals.
@hsert If there's no quick fix for this, can you please disable the DeepTau path?

**Comment by mmusich** [comment] 2023-09-26 08:59
> If there's no quick fix for this, can you please disable the DeepTau path?

before disabling the path, I'd just like to make sure that the fix proposed at https://github.com/cms-sw/cmssw/issues/42862#issuecomment-1735044691 is not enough.

**Comment by hsert** [comment] 2023-09-26 09:27
As shown in slide 18 of https://indico.cern.ch/event/1322372/#sc-2-5-taus, it gives some matrix incompatibility issue. I have another deadline this week, but I can focus on solving the issue next week if it is ok. If that is late, we can disable it. Is there anything that I should do for disabling the path?

**Comment by mmusich** [comment] 2023-09-26 09:28
>  Is there anything that I should do for disabling the path?

removing any reference from the menu (while keeping the configuration fragment) should be enough.

**Comment by mmusich** [comment] 2023-09-26 09:40
>  I have another deadline this week, but I can focus on solving the issue next week if it is ok

Next week should be fine. I'll check back here in one week time.

**Comment by SohamBhattacharya** [comment] 2023-09-26 09:43
> > Is there anything that I should do for disabling the path?
> 
> removing any reference from the menu (while keeping the configuration fragment) should be enough.
> 
> EDIT: to be fully explicit, remove it from here:
> 
> https://github.com/cms-sw/cmssw/blob/a288c8fdd1cbc6f2e0759f8ebbaa9763c76a7e70/HLTrigger/Configuration/python/HLT_75e33_cff.py#L293

Confirm that it's enough to remove it from `HLT_75e33_cff.py`. The Tau paths are intentionally not there in `HLT_75e33_cff_timing.py` as that's meant to measure a timing that can be compared to the TDR measurement, which does not include the tau paths.

**Comment by rovere** [comment] 2023-09-26 09:55
> > > Is there anything that I should do for disabling the path?
> > 
> > 
> > removing any reference from the menu (while keeping the configuration fragment) should be enough.
> > EDIT: to be fully explicit, remove it from here:
> > https://github.com/cms-sw/cmssw/blob/a288c8fdd1cbc6f2e0759f8ebbaa9763c76a7e70/HLTrigger/Configuration/python/HLT_75e33_cff.py#L293
> 
> Confirm that it's enough to remove it from `HLT_75e33_cff.py`. The Tau paths are intentionally not there in `HLT_75e33_cff_timing.py` as that's meant to measure a timing that can be compared to the TDR measurement, which does not include the tau paths.

Once the performance of the Tau Paths is better understood, we can hook those in the `Timing` version to have an improved baseline.

**Comment by mmusich** [comment] 2023-10-04 06:28
@hsert please update on the status of the fix. Thank you.

**Comment by hsert** [comment] 2023-10-04 08:50
I have tried several things, but couldn't figure it out yet. Probably it would be safer to disable the path. Sorry for the inconvenience.

**Comment by mmusich** [comment] 2023-10-05 14:06
> I have tried several things, but couldn't figure it out yet. Probably it would be safer to disable the path. Sorry for the inconvenience.

I have created https://github.com/cms-sw/cmssw/pull/42955, just in case. 
I am trying (unsuccessfully so far) to reproduce the failure offline (@srimanob it would be good if you could get the specs of the nodes in which the relval jobs failed, to see if there's any architecture dependence). 
If something better doesn't appear before next pre-release deadline, we can go ahead with disabling.

**Comment by srimanob** [comment] 2023-10-05 14:19
Hi @cms-sw/pdmv-l2 
Could you please help to find the spec of node which run this relvals,
https://cms-unified.web.cern.ch/cms-unified/report/pdmvserv_RVCMSSW_13_3_0_pre3DisplacedSUSY_stopToB_M_800_500mm_13__2026D98noPU_230918_064200_5200

**Comment by srimanob** [comment] 2023-10-05 14:38
I can reproduce the issue with CMSSW_13_3_0_pre3 using slc7.

cmsDriver.py step3 -s HLT:@relval2026 --conditions auto:phase2_realistic_T25 --datatier GEN-SIM-DIGI-RAW -n -1 --eventcontent FEVTDEBUGHLT --geometry Extended2026D98 --era Phase2C17I13M9 --python step_3_cfg.py --no_exec --filein file:/eos/cms/store/group/offcomp_upgrade-sw/srimanob/phase2/HLT/Tau/step2.root --fileout file:step3.root --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000

**Comment by srimanob** [comment] 2023-10-05 14:54
With CMSSW_13_3_0_pre3, I see we more failure in relvals, i.e. with [CMSSW_13_3_0_pre3DisplacedSUSY](https://cms-unified.web.cern.ch/cms-unified/report/pdmvserv_RVCMSSW_13_3_0_pre3DisplacedSUSY_stopToB_M_800_500mm_13__2026D98noPU_230918_064200_5200)

3 jobs from 20 jobs fail with this issue.

**Comment by mmusich** [comment] 2023-10-05 15:37
> I can reproduce the issue with CMSSW_13_3_0_pre3 using `slc7_amd64_gcc11` arch.

I can reproduce the issue in these conditions. Interestingly when I run in `CMSSW_13_3_X_2023-10-05-1100` on `el8_amd64_gcc11` it does NOT reproduce.
Even more interestingly at the beginning of the job there is a set of tensorflow warnings which differs in the two architectures:

On `el8_amd64_gcc11`:
```
023-10-05 17:25:29.050172: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-05 17:25:29.050519: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: UNKNOWN ERROR (34)
2023-10-05 17:25:29.070838: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:353] MLIR V1 optimization pass is not enabled
```

on `slc7_amd64_gcc11 arch`:

```
2023-10-05 17:29:55.090388: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-10-05 17:30:19.307018: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-05 17:30:19.308508: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: UNKNOWN ERROR (34)
2023-10-05 17:30:19.352316: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:353] MLIR V1 optimization pass is not enabled
```

this is indeed slightly reminiscent of https://github.com/cms-sw/cmssw/issues/40437 and https://github.com/cms-sw/cmssw/issues/40733.

@cms-sw/tau-pog-l2 and @VinInn FYI.

**Comment by mmusich** [comment] 2023-10-05 15:47
> Here is what I get from el8, with CMSSW_13_3_0_pre3:

for me on `lxplus806` also this combination runs OK. Not sure how to tell the cpu microarchitecture from the lxplus node.

**Comment by mmusich** [comment] 2023-10-05 16:38
> Not sure how to tell the cpu microarchitecture from the lxplus node.

OK, for the record it can be obtained running `cmsRun -e step_3_cfg.py` and then inspecting the `FrameworkJobReport.xml`.
On `lxplus806`, **in which the job succeeds**  ( in `CMSSW_13_3_0_pre3` with `el8_amd64_gcc11`):

    <Metric Name="CPUModels" Value="Intel Core Processor (Broadwell, IBRS)"/>

On `lxplus761`, **in which the job fails** ( in `CMSSW_13_3_0_pre3` with `slc7_amd64_gcc11` ) :

    <Metric Name="CPUModels" Value="Intel Xeon Processor (Skylake, IBRS)"/>

**Comment by makortel** [comment] 2023-10-05 17:45
Just to make sure, I'd like to rule out the dependence on `SCRAM_ARCH`. Could you check what happens on either
* el8 node in `cmssw-cc7` container (`slc7_amd64_gcc11`), or
* slc7 node in `cmssw-el8` container (`el8_amd64_gcc11`)

?

**Comment by mmusich** [comment] 2023-10-05 18:15
>  Could you check what happens on either

sure.

> el8 node in cmssw-cc7 container (slc7_amd64_gcc11)

the job succeeds.

> slc7 node in cmssw-el8 container (el8_amd64_gcc11)

the job fails.

So it seems to be independent of the `SCRAM_ARCH`.

**Comment by mmusich** [comment] 2023-10-05 18:31
type tau

**Comment by srimanob** [comment] 2023-10-05 19:06
I confirm the observation on CPU model

**lxplus805.cern.ch: Job fail**

CPU model:
`<Metric Name="CPUModels" Value="Intel Xeon Processor (Skylake, IBRS)"/>`

TensorFlow:
```
2023-10-05 20:59:32.468228: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-05 20:59:32.470515: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: UNKNOWN ERROR (34)
2023-10-05 20:59:32.520719: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:353] MLIR V1 optimization pass is not enabled
```

**lxplus806.cern.ch: Job Success**

CPU model:
`<Metric Name="CPUModels" Value="Intel Core Processor (Broadwell, IBRS)"/>`

TensorFlow:
```
2023-10-05 21:02:48.630734: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-05 21:02:48.631423: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: UNKNOWN ERROR (34)
2023-10-05 21:02:48.658306: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:353] MLIR V1 optimization pass is not enabled
```

**Comment by makortel** [comment] 2023-10-05 19:27
Thanks @mmusich for the test. So it looks like somehow the `AVX512F AVX512_VNNI` trigger the problem. The error message message looks quite serious to be caused by the wider vector instruction set, so I'd _guess_ TensorFlow has some very different code path for AVX-512 compared to AVX2.

**Comment by mmusich** [comment] 2024-02-04 17:58
@cms-sw/core-l2 do you have suggestions on how to test the proposed solution at https://github.com/cms-sw/cmssw/pull/43855 (i.e. how can I access a node that will guarantee me to get `AVX512F AVX512_VNNI`) ?

**Comment by mmusich** [comment] 2024-02-04 18:52
> do you have suggestions on how to test the proposed solution at https://github.com/cms-sw/cmssw/pull/43855 (i.e. how can I access a node that will guarantee me to get AVX512F AVX512_VNNI) ?

answering to myself, I found a `lxplus-gpu` node (i.e. `lxplus921`) that has:
```
<Metric Name="CPUModels" Value="Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz"/>
```
that enables the `AVX512F AVX512_VNNI` instructions.

**Comment by mmusich** [comment] 2024-02-07 15:51
+hlt
   * https://github.com/cms-sw/cmssw/pull/43855 fixes the problem of this issue.

**Comment by mmusich** [comment] 2024-02-07 16:06
@cmsbuild, ping? seems stuck

**Comment by valsdav** [comment] 2024-03-13 21:07
This is happening due to a `num_valid_cells()==0`, aka empty input tensor in https://github.com/cms-sw/cmssw/blob/619b1aa756a2181a5d946f22b4bba8c96c57b84d/RecoTauTag/RecoTau/plugins/DeepTauId.cc#L1123

See discussion in https://github.com/cms-sw/cmssw/issues/44333#issuecomment-1995813985

**Comment by valsdav** [comment] 2024-03-13 21:07
assign ml

(to get updates)

**Comment by mmusich** [comment] 2024-03-13 21:09
> (to get updates)

technically this is issue is solved by https://github.com/cms-sw/cmssw/pull/43855. 

@cms-sw/upgrade-l2 do you have objections to close ?

**Comment by valsdav** [comment] 2024-03-13 21:34
Hi @mmusich,   I don't think  #43855 is protecting us against empty tensors. 

I'm not a expert of the DeepTau code but the problem is related to evaluating the model over an empty CellGrid. I don't know why the grid used in the producer is empty in the events that are crashing the run.. maybe @hsert may have an idea? 

```
<DeepTauId::createConvFeatures (is_inner = 1)>:
number of valid cells = 0  --> output added by me locally

processing ( eta = -5, phi = -5 )
 skipping creation of inputs, because ( eta = -5, phi = -5 ) is not in the grid !!
processing ( eta = -5, phi = -4 )
 skipping creation of inputs, because ( eta = -5, phi = -4 ) is not in the grid !!
processing ( eta = -5, phi = -3 )
[....all same output not in the grid...]
 skipping creation of inputs, because ( eta = 5, phi = 3 ) is not in the grid !!
processing ( eta = 5, phi = 4 )
 skipping creation of inputs, because ( eta = 5, phi = 4 ) is not in the grid !!
processing ( eta = 5, phi = 5 )
 skipping creation of inputs, because ( eta = 5, phi = 5 ) is not in the grid !!

 no valid cells found, empty tensors to inference engine  --> output added by me locally
```

**Comment by mmusich** [comment] 2024-03-13 21:36
@valsdav 

> I don't think https://github.com/cms-sw/cmssw/pull/43855 is protecting us against empty tensors.

as far as I could test, the exceptions reported here are gone with that PR, see https://github.com/cms-sw/cmssw/pull/43855#issuecomment-1925882340

**Comment by valsdav** [comment] 2024-03-13 21:49
Your test in https://github.com/cms-sw/cmssw/pull/43855#issuecomment-1925882340 is quite clear.

I think this depends on the model version.  #43855 is  indeed using a different model than the other issue #44333. Maybe the new models is not giving empty cells?  It would be interesting to understand what changes.. 

I think implementing a guard against empty inputs  would at least make the issue clearer

**Comment by mmusich** [comment] 2024-03-13 21:52
> I think implementing a guard against empty inputs would at least make the issue clearer

I agree, but I would not mix different issues (it is fine to lik https://github.com/cms-sw/cmssw/issues/44333 to this one, but this one is technically resolved), I would continue the discussion in the main one.

**Comment by mmusich** [comment] 2024-03-20 08:47
for record, these add an extra layer of protection:
   * https://github.com/cms-sw/cmssw/pull/44455 (master)
   * https://github.com/cms-sw/cmssw/pull/44456 (14.0.X)

**Comment by srimanob** [comment] 2024-03-20 08:48
+Upgrade

**Comment by makortel** [comment] 2024-03-20 13:12
@cmsbuild, please close

**Closed** 2024-03-20 13:13 UTC
Labels: hlt-approved, fully-signed, upgrade-approved, tau, ml-approved
