### ISSUE TITLE
Peculiar $CMSSW_BASE path in latest CMSSW_12_0_X release

### ISSUE THREAD

**Issue by colizz** [cms-sw/cmssw#33607] opened 2021-05-03 12:29 UTC
The following environment setup commands run on lxplus report an error:
```bash
export SCRAM_ARCH=slc7_amd64_gcc900
cmsrel CMSSW_12_0_X_2021-05-02-2300
cd CMSSW_12_0_X_2021-05-02-2300/src
cmsenv
git cms-init
```
Error message:
```
fatal: destination path '/cvmfs/cms-ib.cern.ch/nweek-02679/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-05-02-2300/src' already exists and is not an empty directory.
```

Checking `$CMSSW_BASE`, it's still pointing to the cvmfs path
`/cvmfs/cms-ib.cern.ch/nweek-02679/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-05-02-2300` instead of the working dir.

The older version e.g. `CMSSW_12_0_X_2021-04-29-1100` does not encounter the problem.

Besides, working on lxplus under `/tmp` seems to be fine.

Thanks a lot for your investigation.

**Comment by silviodonato** [comment] 2021-05-03 12:37
Thanks a lot for reporting this.
I noticed that this error appeared since `CMSSW_12_0_X_2021-04-29-2300`. So I suspected it was from 
https://github.com/cms-sw/cmsdist/pull/6849

and indeed I see the error in `CMSSW_12_0_SCRAMV3_X_2021-04-29-1100` and no error in `CMSSW_12_0_X_2021-04-29-1100`

**Comment by silviodonato** [comment] 2021-05-03 12:37
assign core, externals

**Comment by silviodonato** [comment] 2021-05-03 12:43
@colizz meanwhile you can fix this using
```
export SCRAM_ARCH=slc7_amd64_gcc900
cmsrel CMSSW_12_0_X_2021-05-02-2300
cd CMSSW_12_0_X_2021-05-02-2300/src
cmsenv
CMSSW_BASE=$PWD/..
git cms-init
```

**Comment by smuzaffar** [comment] 2021-05-03 12:56
@colizz  @silviodonato I am not able to reproduce it. Can you please try in a fresh shell and see it you get this error? Can you please share your env before running these commands (send me an mail with the env output instead of posting it here)

**Comment by colizz** [comment] 2021-05-03 12:56
> @colizz meanwhile you can fix this using
> 
> ```
> export SCRAM_ARCH=slc7_amd64_gcc900
> cmsrel CMSSW_12_0_X_2021-05-02-2300
> cd CMSSW_12_0_X_2021-05-02-2300/src
> cmsenv
> CMSSW_BASE=$PWD/..
> git cms-init
> ```

Thanks, indeed. But there is another error later doing `scram b`:
```
**** ERROR: You have moved/renamed this project area "/afs/cern.ch/work/c/coli/multithread/test/CMSSW_12_0_X_2021-05-02-2300" from "/cvmfs/cms-ib.cern.ch/nweek-02679/slc7_amd64_gcc900/cms/cmssw-patch/CMSSW_12_0_X_2021-05-02-2300"
config/SCRAM/GMake/Makefile.rules:1391: *** Please first run \"scramv1 b ProjectRename\".  Stop.
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2
```
Seems there is a conflict between the two directories anyhow.

**Comment by colizz** [comment] 2021-05-03 12:59
> @colizz @silviodonato I am not able to reproduce it. Can you please try in a fresh shell and see it you get this error? Can you please share your env before running these commands (send me an mail with the env output instead of posting it here)

Thanks. I'll send you the email (it happened that I was meeting this issue on afs dir, but it's fine in e.g. `/tmp`, maybe it's related to this.)

**Comment by smuzaffar** [comment] 2021-05-03 13:24
I confirm thatI can re-produce it on AFS. I am checking

**Comment by smuzaffar** [comment] 2021-05-03 13:26
we have moved to SCRAM V3 for CMSSW_12_0_X and it might be related to that, I am checking

**Comment by smuzaffar** [comment] 2021-05-03 14:21
https://github.com/cms-sw/cmsdist/pull/6868 (once merged and integrated in IB) should fix the issue

**Comment by colizz** [comment] 2021-05-03 15:59
@smuzaffar Thanks a lot!

**Comment by smuzaffar** [comment] 2021-05-04 07:55
this is fixed now

**Closed by smuzaffar** 2021-05-04 07:55 UTC
Labels: core-pending, externals-pending, pending-signatures
