### ISSUE TITLE
[GCC12] Missing dictionary for __pair_base in many workflows

### ISSUE THREAD

**Issue by makortel** [cms-sw/cmssw#41865] opened 2023-06-05 07:15 UTC
Many el8_amd64_gcc12 workflows (that are able to get run despite of the build failures) fail with an exception along
```
----- Begin Fatal Exception 03-Jun-2023 17:13:23 CEST-----------------------
An exception of category 'DictionaryNotFound' occurred while
   [0] Constructing the EventProcessor
   [1] Calling ProductRegistry::initializeLookupTables
Exception Message:
No data dictionary found for the following classes:

  __pair_base<csc::L1Track,MuonDigiCollection<CSCDetId,CSCCorrelatedLCTDigi> >
  __pair_base<int,bitset<6> >

Most likely each dictionary was never generated, but it may
be that it was generated in the wrong package. Please add
(or move) the specification '<class name="whatever"/>' to
the appropriate classes_def.xml file along with any other
information needed there. For example, if this class has any
transient members, you need to specify them in classes_def.xml.
Also include the class header in classes.h

A type listed above might or might not be the same as a
type stored in the Event (or Lumi or Run). Instead it might
be the type of a data member, base class, wrapped type, or
other object needed by a stored type. Below is some additional
information which lists the stored types associated with the
types whose dictionaries were not found:

  std::vector<std::pair<csc::L1Track,MuonDigiCollection<CSCDetId,CSCCorrelatedLCTDigi> > > (produced in current process)
  std::vector<std::pair<int,std::bitset<6> > > (produced in current process)

Missing dictionaries are associated with these branch names:

  cscL1TrackCSCDetIdCSCCorrelatedLCTDigiMuonDigiCollectionstdpairs_simCsctfTrackDigis__HLT.
  int6stdbitsetstdpairs_mix_AffectedAPVList_HLT.

If you do not need these branches and they are not produced
in the current process, an alternate solution to adding
dictionaries is to drop these branches on input using the
inputCommands parameter of the PoolSource.
----- End Fatal Exception -------------------------------------------------
```
(e.g. https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_13_2_X_2023-06-03-1100/pyRelValMatrixLogs/run/3.0_ProdQCD_Pt_3000_3500/step2_ProdQCD_Pt_3000_3500.log#/)

**Comment by makortel** [comment] 2023-06-05 07:15
assign core

**Comment by makortel** [comment] 2023-06-05 07:15
FYI @pcanal

**Comment by makortel** [comment] 2023-06-05 07:27
The dictionaries relevant to `__pair_base<csc::L1Track,MuonDigiCollection<CSCDetId,CSCCorrelatedLCTDigi> >` are defined in
https://github.com/cms-sw/cmssw/blob/b2104010566f44c0bb808f4b0159df0239e4885a/DataFormats/L1CSCTrackFinder/src/classes_def.xml#L28
https://github.com/cms-sw/cmssw/blob/b2104010566f44c0bb808f4b0159df0239e4885a/DataFormats/L1CSCTrackFinder/src/classes_def.xml#L35
https://github.com/cms-sw/cmssw/blob/b2104010566f44c0bb808f4b0159df0239e4885a/DataFormats/L1CSCTrackFinder/src/classes_def.xml#L39

and to `__pair_base<int,bitset<6> >` in
https://github.com/cms-sw/cmssw/blob/b2104010566f44c0bb808f4b0159df0239e4885a/DataFormats/StdDictionaries/src/classes_def_vector.xml#L48-L49
https://github.com/cms-sw/cmssw/blob/b2104010566f44c0bb808f4b0159df0239e4885a/DataFormats/WrappedStdDictionaries/src/classes_def.xml#L56

@pcanal These errors are specific to GCC 12 compiler. The ROOT version in 6.26 (more specifically https://github.com/cms-sw/root/commit/fe824a0d8806a5484c3cc1530d60107774c59257 in https://github.com/cms-sw/root/commits/cms/v6-26-00-patches/a25c523160). Not sure if it is relevant for this issue, but I recall you've said earlier that the `std::pair<X, Y>` dictionaries would not need to be explicit defined anymore (https://github.com/cms-sw/cmssw/issues/32444, and no, we did not get to any clean up yet).

**Comment by pcanal** [comment] 2023-06-05 22:11
I had a vague recollection that we had fixed this.   Do we happen to have a test of the same code with v6.28?

**Comment by makortel** [comment] 2023-06-06 06:23
@smuzaffar Would it be feasible to have (in one way or another) a single build with GCC12 and ROOT 6.28 to check if these errors occur there?

**Comment by smuzaffar** [comment] 2023-06-06 06:38
@makortel , I already have start ROOT628 with GCC12 build [here](https://cmssdt.cern.ch/jenkins/job/build-any-ib/155934/console)

**Comment by smuzaffar** [comment] 2023-06-06 12:38
looks like this is not fixed in ROOT 6.28 too see [log](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_13_2_ROOT628_X_2023-06-05-2300/addOnTests/logs/cmsDriver-pat1_step1.log#/)

**Comment by smuzaffar** [comment] 2023-06-06 12:46
ROOT 6.28 is build in debug mode and it shows bit more errors e.g.
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc12/CMSSW_13_2_ROOT628_X_2023-06-05-2300/addOnTests/logs/cmsDriver-pat1_step1.log#/46-50
```
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-e30fb68be5dbc9ad534ab5b10ba8ea7c/include/c++/12.3.1/bits/stl_iterator_base_types.h:127:12: note: 'iterator<std::random_access_iterator_tag, edm::Ptr<reco::Jet>, long, edm::Ptr<reco::Jet> *, edm::Ptr<reco::Jet> &>' has been explicitly marked deprecated here
    struct _GLIBCXX17_DEPRECATED iterator
           ^
/data/cmsbld/jenkins/workspace/build-any-ib/w/el8_amd64_gcc12/external/gcc/12.3.1-e30fb68be5dbc9ad534ab5b10ba8ea7c/include/c++/12.3.1/x86_64-redhat-linux-gnu/bits/c++config.h:119:34: note: expanded from macro '_GLIBCXX17_DEPRECATED'
# define _GLIBCXX17_DEPRECATED [[__deprecated__]]
```

**Comment by pcanal** [comment] 2023-06-06 16:58
So far I am unable to reproduce the issue with gcc 12.2 and thus it might also be related to the OS.  @makortel Can you send me a recipe to reproduce with el8?

**Comment by makortel** [comment] 2023-06-09 08:46
Thanks @pcanal, I created a PR with your patch https://github.com/cms-sw/cmssw/pull/41908

**Closed** 2023-06-12 14:43 UTC
Labels: core-pending, pending-signatures
