### ISSUE TITLE
VIDElectronSelector does not work for FWLite with CMSSW 8_2_X and above

### ISSUE THREAD

**Issue by karavdin** [cms-sw/cmssw#23803] opened 2018-07-16 16:05 UTC
VIDElectronSelector stopped working with FWLite since CMSSW version 8_2_X and above. 
The error message:
TypeError: none of the 2 overloaded methods succeeded. Full details:
  VersionedSelector<edm::Ptr<reco::GsfElectron> > MakeVersionedSelector<reco::GsfElectron>::operator()(const string& pset, const string& which_config) =>
    An exception of category 'BadPluginName' occurred.
Exception Message:
The requested cut: MinPtCut is not available!
 (C++ exception of type cms::Exception)
  VersionedSelector<edm::Ptr<reco::GsfElectron> > MakeVersionedSelector<reco::GsfElectron>::operator()() =>
    takes at most 0 arguments (2 given)

The issue can be reproduced with [1]. For more detailed discussion see [2]. 
We need it in 9_4_X (for DAS school exercise, as soon as possible) and potentially in 10_2_X (for future editions of DAS schools).
 
[1] https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/SelectorUtils/test/pyfwlite_test.py
[2] https://hypernews.cern.ch/HyperNews/CMS/get/egamma/2091/1/1/1/1/1.html

**Comment by kpedro88** [comment] 2018-07-16 16:07
assign reconstruction

**Comment by guitargeek** [comment] 2018-07-16 18:00
Hi, I opened an issue about that a month ago, with a few ideas what the problem could be:
https://github.com/cms-sw/cmssw/issues/23676

**Comment by smuzaffar** [comment] 2020-05-28 19:26
closing as its a duplicate of #23676

**Closed by smuzaffar** 2020-05-28 19:26 UTC
Labels: pending-signatures, reconstruction-rejected
