### ISSUE TITLE
[GPU_X] Parameter 'pulseOffsets' not found.

### ISSUE THREAD

**Issue by iarspider** [cms-sw/cmssw#42913] opened 2023-09-29 12:59 UTC
Multiple ( [Relval 141.008506 step 2](http://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_3_GPU_X_2023-09-28-2300/pyRelValMatrixLogs/run/141.008506_Run3-2023_JetMET2023B_RecoPixelOnlyTripletsGPU/step2_Run3-2023_JetMET2023B_RecoPixelOnlyTripletsGPU.log), [Relval 141.008506 step 2](http://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_3_GPU_X_2023-09-28-2300/pyRelValMatrixLogs/run/141.008506_Run3-2023_JetMET2023B_RecoPixelOnlyTripletsGPU/step2_Run3-2023_JetMET2023B_RecoPixelOnlyTripletsGPU.log), ... - all 141.x, 12434.x, 12450.x) RelVals failed in CMSSW_13_3_GPU_X_2023-09-28-2300 due to Configuration error `Parameter 'pulseOffsets' not found.`

Some of the RelVals failed gracefuly:
```
----- Begin Fatal Exception 29-Sep-2023 04:12:05 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Processing  Event run: 366727 lumi: 89 event: 132359457 stream: 2
   [1] Running path 'MC_Run3_PFScoutingPixelTracking_v22'
   [2] Prefetching for module HBHERecHitProducerGPU/'hltHbherecoGPU'
   [3] Calling method for EventSetup module HcalMahiPulseOffsetsGPUESProducer/'hcalMahiPulseOffsetsGPUESProducer'
Exception Message:
MissingParameter: Parameter 'pulseOffsets' not found.
----- End Fatal Exception -------------------------------------------------
```

but some did segmentation violation, e.g. [link](https://cmssdt.cern.ch/SDT/cgi-bin/logreader/el8_amd64_gcc11/CMSSW_13_3_GPU_X_2023-09-28-2300/pyRelValMatrixLogs/run/141.008512_Run3-2023_JetMET2023B_RecoECALOnlyGPU/step2_Run3-2023_JetMET2023B_RecoECALOnlyGPU.log#/):
```
Thread 1 (Thread 0x2b919abaffc0 (LWP 20880) "cmsRun"):
#0  0x00002b9199e68f41 in poll () from /lib64/libc.so.6
#1  0x00002b919ea47d0f in full_read.constprop () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#2  0x00002b919ea0f8ec in edm::service::InitRootHandlers::stacktraceFromThread() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#3  0x00002b919ea1034b in sig_dostack_then_abort () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/pluginFWCoreServicesPlugins.so
#4  <signal handler called>
#5  0x00002b919747b921 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, edm::Entry>, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, edm::Entry> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, edm::Entry> > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreParameterSet.so
#6  0x00002b91974731be in edm::ParameterSet::retrieve(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreParameterSet.so
#7  0x00002b9197473239 in edm::ParameterSet::retrieve(char const*) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreParameterSet.so
#8  0x00002b9197475c50 in std::vector<int, std::allocator<int> > edm::ParameterSet::getParameter<std::vector<int, std::allocator<int> > >(char const*) const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreParameterSet.so
#9  0x00002b923073fe7e in HcalMahiPulseOffsetsGPU::HcalMahiPulseOffsetsGPU(edm::ParameterSet const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/libRecoLocalCaloHcalRecAlgos.so
#10 0x00002b92309aa3c7 in HcalMahiPulseOffsetsGPUESProducer::produce(JobConfigurationGPURecord const&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/pluginRecoLocalCaloHcalRecProducers.so
#11 0x00002b92309b5807 in edm::eventsetup::CallbackBase<edm::ESProducer, edm::ESProducer::setWhatProduced<HcalMahiPulseOffsetsGPUESProducer, std::unique_ptr<HcalMahiPulseOffsetsGPU, std::default_delete<HcalMahiPulseOffsetsGPU> >, JobConfigurationGPURecord, edm::eventsetup::CallbackSimpleDecorator<JobConfigurationGPURecord> >(HcalMahiPulseOffsetsGPUESProducer*, std::unique_ptr<HcalMahiPulseOffsetsGPU, std::default_delete<HcalMahiPulseOffsetsGPU> > (HcalMahiPulseOffsetsGPUESProducer::*)(JobConfigurationGPURecord const&), edm::eventsetup::CallbackSimpleDecorator<JobConfigurationGPURecord> const&, edm::es::Label const&)::{lambda(JobConfigurationGPURecord const&)#1}, std::unique_ptr<HcalMahiPulseOffsetsGPU, std::default_delete<HcalMahiPulseOffsetsGPU> >, JobConfigurationGPURecord, edm::eventsetup::CallbackSimpleDecorator<JobConfigurationGPURecord> >::makeProduceTask<edm::eventsetup::Callback<edm::ESProducer, edm::ESProducer::setWhatProduced<HcalMahiPulseOffsetsGPUESProducer, std::unique_ptr<HcalMahiPulseOffsetsGPU, std::default_delete<HcalMahiPulseOffsetsGPU> >, JobConfigurationGPURecord, edm::eventsetup::CallbackSimpleDecorator<JobConfigurationGPURecord> >(HcalMahiPulseOffsetsGPUESProducer*, std::unique_ptr<HcalMahiPulseOffsetsGPU, std::default_delete<HcalMahiPulseOffsetsGPU> > (HcalMahiPulseOffsetsGPUESProducer::*)(JobConfigurationGPURecord const&), edm::eventsetup::CallbackSimpleDecorator<JobConfigurationGPURecord> const&, edm::es::Label const&)::{lambda(JobConfigurationGPURecord const&)#1}, std::unique_ptr<HcalMahiPulseOffsetsGPU, std::default_delete<HcalMahiPulseOffsetsGPU> >, JobConfigurationGPURecord, edm::eventsetup::CallbackSimpleDecorator<JobConfigurationGPURecord> >::prefetchAsync(edm::WaitingTaskHolder, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&, edm::ESParentContext const&)::{lambda(auto:1&&, auto:2&&, auto:3&&, auto:4&&)#1}::operator()<tbb::detail::d1::task_group*&, edm::ServiceWeakToken&, edm::eventsetup::EventSetupRecordImpl const*&, edm::EventSetupImpl const*&>(tbb::detail::d1::task_group*&, edm::ServiceWeakToken&, edm::eventsetup::EventSetupRecordImpl const*&, edm::EventSetupImpl const*&) const::{lambda(JobConfigurationGPURecord const&)#1}>(tbb::detail::d1::task_group*, edm::ServiceWeakToken const&, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, bool, tbb::detail::d1::task_group*&)::{lambda(std::__exception_ptr::exception_ptr const*)#1}::operator()(std::__exception_ptr::exception_ptr const*) const::{lambda()#2}::operator()() const () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/pluginRecoLocalCaloHcalRecProducers.so
#12 0x00002b92309b5b68 in edm::SerialTaskQueue::QueuedTask<edm::SerialTaskQueueChain::push<edm::eventsetup::CallbackBase<edm::ESProducer, edm::ESProducer::setWhatProduced<HcalMahiPulseOffsetsGPUESProducer, std::unique_ptr<HcalMahiPulseOffsetsGPU, std::default_delete<HcalMahiPulseOffsetsGPU> >, JobConfigurationGPURecord, edm::eventsetup::CallbackSimpleDecorator<JobConfigurationGPURecord> >(HcalMahiPulseOffsetsGPUESProducer*, std::unique_ptr<HcalMahiPulseOffsetsGPU, std::default_delete<HcalMahiPulseOffsetsGPU> > (HcalMahiPulseOffsetsGPUESProducer::*)(JobConfigurationGPURecord const&), edm::eventsetup::CallbackSimpleDecorator<JobConfigurationGPURecord> const&, edm::es::Label const&)::{lambda(JobConfigurationGPURecord const&)#1}, std::unique_ptr<HcalMahiPulseOffsetsGPU, std::default_delete<HcalMahiPulseOffsetsGPU> >, JobConfigurationGPURecord, edm::eventsetup::CallbackSimpleDecorator<JobConfigurationGPURecord> >::makeProduceTask<edm::eventsetup::Callback<edm::ESProducer, edm::ESProducer::setWhatProduced<HcalMahiPulseOffsetsGPUESProducer, std::unique_ptr<HcalMahiPulseOffsetsGPU, std::default_delete<HcalMahiPulseOffsetsGPU> >, JobConfigurationGPURecord, edm::eventsetup::CallbackSimpleDecorator<JobConfigurationGPURecord> >(HcalMahiPulseOffsetsGPUESProducer*, std::unique_ptr<HcalMahiPulseOffsetsGPU, std::default_delete<HcalMahiPulseOffsetsGPU> > (HcalMahiPulseOffsetsGPUESProducer::*)(JobConfigurationGPURecord const&), edm::eventsetup::CallbackSimpleDecorator<JobConfigurationGPURecord> const&, edm::es::Label const&)::{lambda(JobConfigurationGPURecord const&)#1}, std::unique_ptr<HcalMahiPulseOffsetsGPU, std::default_delete<HcalMahiPulseOffsetsGPU> >, JobConfigurationGPURecord, edm::eventsetup::CallbackSimpleDecorator<JobConfigurationGPURecord> >::prefetchAsync(edm::WaitingTaskHolder, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, edm::ServiceToken const&, edm::ESParentContext const&)::{lambda(auto:1&&, auto:2&&, auto:3&&, auto:4&&)#1}::operator()<tbb::detail::d1::task_group*&, edm::ServiceWeakToken&, edm::eventsetup::EventSetupRecordImpl const*&, edm::EventSetupImpl const*&>(tbb::detail::d1::task_group*&, edm::ServiceWeakToken&, edm::eventsetup::EventSetupRecordImpl const*&, edm::EventSetupImpl const*&) const::{lambda(JobConfigurationGPURecord const&)#1}>(tbb::detail::d1::task_group*, edm::ServiceWeakToken const&, edm::eventsetup::EventSetupRecordImpl const*, edm::EventSetupImpl const*, bool, tbb::detail::d1::task_group*&)::{lambda(std::__exception_ptr::exception_ptr const*)#1}::operator()(std::__exception_ptr::exception_ptr const*) const::{lambda()#2}>(tbb::detail::d1::task_group&, tbb::detail::d1::task_group*&)::{lambda()#1}>::execute() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/pluginRecoLocalCaloHcalRecProducers.so
#13 0x00002b91974f5099 in tbb::detail::d1::function_task<edm::SerialTaskQueue::spawn(edm::SerialTaskQueue::TaskBase&)::{lambda()#1}>::execute(tbb::detail::d1::execution_data&) () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreConcurrency.so
#14 0x00002b9198e8ca6d in tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::external_waiter> (waiter=..., t=0x2b92ffa9cb00, this=0x2b919b87e880) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc11/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-5caec19d753f5e33a53af823382dc5ea/tbb-v2021.9.0/src/tbb/task_dispatcher.h:322
#15 tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::external_waiter> (waiter=..., t=<optimized out>, this=0x2b919b87e880) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc11/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-5caec19d753f5e33a53af823382dc5ea/tbb-v2021.9.0/src/tbb/task_dispatcher.h:458
#16 tbb::detail::r1::task_dispatcher::execute_and_wait (t=<optimized out>, wait_ctx=..., w_ctx=...) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc11/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-5caec19d753f5e33a53af823382dc5ea/tbb-v2021.9.0/src/tbb/task_dispatcher.cpp:168
#17 0x00002b919764042d in edm::FinalWaitingTask::wait() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#18 0x00002b919764df21 in edm::EventProcessor::processRuns() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#19 0x00002b919764e4b1 in edm::EventProcessor::runToCompletion() () from /cvmfs/cms-ib.cern.ch/sw/x86_64/nweek-02804/el8_amd64_gcc11/cms/cmssw/CMSSW_13_3_GPU_X_2023-09-28-2300/lib/el8_amd64_gcc11/libFWCoreFramework.so
#20 0x000000000040c272 in tbb::detail::d1::task_arena_function<main::{lambda()#1}::operator()() const::{lambda()#1}, void>::operator()() const ()
#21 0x00002b9198e79877 in tbb::detail::r1::task_arena_impl::execute (ta=..., d=...) at /data/cmsbld/jenkins/workspace/auto-builds/CMSSW_13_3_0_pre3-el8_amd64_gcc11/build/CMSSW_13_3_0_pre3-build/BUILD/el8_amd64_gcc11/external/tbb/v2021.9.0-5caec19d753f5e33a53af823382dc5ea/tbb-v2021.9.0/src/tbb/arena.cpp:688
#22 0x0000000000410360 in main::{lambda()#1}::operator()() const ()
#23 0x0000000000407dfc in main ()
```

**Comment by makortel** [comment] 2023-09-29 13:24
Very likely caused by https://github.com/cms-sw/cmssw/pull/42503

**Comment by makortel** [comment] 2023-09-29 15:46
assign heterogeneous

**Comment by makortel** [comment] 2023-09-29 15:46
Fixed in https://github.com/cms-sw/cmssw/pull/42916

**Closed** 2023-10-02 13:44 UTC
Labels: reconstruction-pending, pending-signatures, heterogeneous-pending
