### ISSUE TITLE
OscarMTMasterThread does not handle failures properly

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/cmssw#14273] opened 2016-04-27 16:05 UTC
If an exception is thrown in the framework during the module construction phase and after OscarMTProducer has been constructed, then when the framework deletes OscarMTProducer before any beginRun is called, it will cause the error such as

```
%MSG-e OscarMTMasterThread:  AfterModConstruction 27-Apr-2016 16:39:01 CEST  pre-events
OscarMTMasterThread::stopThread() has not been called to stop Geant4 and join the master thread
%MSG
terminate called without an active exception
Abort
```

This us caused because `OscarMTMasterThread` has a member variable that is an `std::thread` and it is destructed before it was `join`ed. Therefore `OscarMTMasterThread` needs a a mechanism to stop its thread gracefully in its destructor.

**Comment by Dr15Jones** [comment] 2016-04-27 16:06
assign simulation

**Comment by civanch** [comment] 2016-04-28 09:24
#14289 is created to address the issue, @Dr15Jones , please, have a look.

**Comment by Dr15Jones** [comment] 2016-04-28 13:53
@makortel please give us your opinion on the changes.

**Comment by makortel** [comment] 2016-04-28 14:09
After trying to remind myself of the details and taking a cursory look on #14289 and the code, I think too that #14289 does not solve the problem. I think (without testing) that the problem could be solved with
```
if(!m_stopped)
  stopThread();
```
in https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/SimG4Core/Application/src/OscarMTMasterThread.cc#L119

The poor-man's state machine in https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/SimG4Core/Application/src/OscarMTMasterThread.cc#L59 looks like it would properly handle destruction without any beginRun-endRun cycles (and still throws if the thread would be destructed without explicitly stopping Geant4 first).

If the suggestion above works and we do it, then maybe we should remove the call to `OscarMTMasterThread::stopThread()` from `OscarMTProducer::globalEndJob()` https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/SimG4Core/Application/plugins/OscarMTProducer.cc#L155 and rely fully on the destructor? Then we could also remove the `OscarMTMasterThread::m_stopped` altogether and make `stopThread()` private (if still kept separate from destructor).

**Comment by kpedro88** [comment] 2016-05-05 21:07
I confirm that #14289 does not solve the problem. Here is a recipe to reproduce it in the latest IB and some thoughts about the possible cause:
```
cmsrel CMSSW_8_1_X_2016-05-05-1100
cd CMSSW_8_1_X_2016-05-05-1100/src
cmsenv
xrdcp root://cmsxrootd.fnal.gov//store/relval/CMSSW_8_1_0_pre2/RelValMinBias_13/GEN-SIM/80X_mcRun2_asymptotic_v10_gs810pre2-v1/00000/1A23AEF4-C6FD-E511-98A1-0CC47A4C8F26.root RelValMinBias_13_GEN-SIM_80X_mcRun2_asymptotic_v10_gs810pre2-v1_0.root
runTheMatrix.py -l 250199.0 --command '--pileup_input RelValMinBias_13_GEN-SIM_80X_mcRun2_asymptotic_v10_gs810pre2-v1_0.root'
```

Here, I'm setting `process.mix.input.fileNames` (in a GEN-SIM-DIGIPREMIX workflow, so `process.source = cms.Source("EmptySource"`) to a local file *without* the "file:" prefix. Usually, CMSSW points out this mistake gracefully, e.g. if I try it with a standard PoolSource:
```
Exception Message:
RootFileSequenceBase::initTheFile()
Logical file name 'step2_SIM.root' was not found in the file catalog.
If you wanted a local file, you forgot the 'file:' prefix
before the file name in your configuration file.
```

However, process.mix.input is a `cms.SecSource("EmbeddedRootSource"`. Either this type of source does not handle the missing "file:" issue gracefully, or there is still some problem with OscarMTMasterThread when an exception occurs elsewhere. Here is the output I get:
```
%MSG-e OscarMTMasterThread:  AfterModConstruction 05-May-2016 15:59:13 CDT  pre-events
OscarMTMasterThread::stopThread() has not been called to stop Geant4 and join the master thread
%MSG
terminate called without an active exception
```

**Comment by civanch** [comment] 2016-10-04 16:04
The issue is resolved by #14405

**Comment by Dr15Jones** [comment] 2016-10-04 17:35
You can give this issue a '+1' to mark it as completed

**Comment by civanch** [comment] 2016-10-08 14:30
+1

**Closed** 2017-01-12 15:50 UTC
Labels: fully-signed, simulation-approved
