### ISSUE TITLE
Timeout in communication between the main and external channels in ExternalGeneratorFilter

### ISSUE THREAD

**Issue by srimanob** [cms-sw/cmssw#31426] opened 2020-09-10 14:33 UTC
When testing ExternalGeneratorFilter using
https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_test/PPD-MultiValidationUL17GEN-00004

I've found the issue on specific event:
----- Begin Fatal Exception 10-Sep-2020 11:46:29 CEST-----------------------
An exception of category 'ExternalFailed' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 1 stream: 0
   [1] Running path 'generation_step'
   [2] Calling method for module ExternalGeneratorFilter/'generator'
Exception Message:
failed waiting for external process

@colizz helps to investigate and it seems to come from the time to producing this event (~3.5 min) exceeds the max limit for communication between the main and external channels, which is set to be 60 sec in FWCore/SharedMemory.

From event point of view, it seems to be a good event, just spending longer in pythia. Is extending timeout limit is the only way to do to avoid this issue?

**Comment by Dr15Jones** [comment] 2020-09-10 14:55
assign generator, core

**Comment by Dr15Jones** [comment] 2020-09-10 15:01
From a quick look at the code, we should be able to make the timeout amount be configurable.

**Comment by Dr15Jones** [comment] 2020-09-10 15:13
assign generators

**Comment by agrohsje** [comment] 2020-09-11 12:10
I would be in favour of the proposal by @colizz and increase the allowed time. Let me add @smrenna , maybe he can comment on the P8 side, i.e. about skipping the event.

**Comment by smrenna** [comment] 2020-09-11 13:34
Are you saying that Pythia spends 3.5minutes trying to generate an event?
If so, there is something terribly wrong.

**Comment by agrohsje** [comment] 2020-09-11 14:21
Could it be related to PS weights, i.e. maybe it is not a problem with the actual parton shower. @srimanob maybe has all info to reproduce using the seed of the event.

**Comment by smrenna** [comment] 2020-09-11 15:16
What type of an event is/was it?

Also, is there any way that seed can be used for an external run of Pythia8?

Steve

**Comment by Dr15Jones** [comment] 2020-09-11 15:31
@smrenna 
> Also, is there any way that seed can be used for an external run of Pythia8?

Do you mean external to CMSSW?

**Comment by smrenna** [comment] 2020-09-11 15:48
Yes.   If it is a Pythia issue, it will be easier to debug outside of CMSSW.

**Comment by davidlange6** [comment] 2020-09-11 15:53
Was this 3.5 minutes reproducible? I tried on a slowish node and failed to see an event taking > 1 minute (let alone 3)

On Sep 11, 2020, at 2:10 PM, agrohsje <notifications@github.com<mailto:notifications@github.com>> wrote:



I would be in favour of the proposal by @colizz<https://github.com/colizz> and increase the allowed time. Let me add @smrenna<https://github.com/smrenna> , maybe he can comment on the P8 side, i.e. about skipping the event.

**Comment by agrohsje** [comment] 2020-09-11 17:17
@colizz could reproduce. He can comment more on the seed.

**Comment by colizz** [comment] 2020-09-11 20:08
Hi,

sorry I was out for a while. With the original request this actually happens in the 7677th event. We found this particular event takes the seed shown in [0]. (Pythia is using an external random engine CLHEP::HepRandomEngine here)

In fact the issue can be reproduced with the test script of [PPD-MultiValidationUL17GEN-00004](https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_test/PPD-MultiValidationUL17GEN-00004) plus an additional patch [0] applied to cmssw. This way the particular seed is imposed, so that one sees the long time response by Pythia.

Pythia would print out a warning/error for this event, although it is finally produced:
>  PYTHIA Warning in SimpleSpaceShower::pT2nextQCD: small daughter PDF  
 PYTHIA Error in BeamRemnants::setKinematics: kinematics construction failed  

That may provide a clue for us to continue digging out the mechanism (which I haven't done yet).

[0] https://gist.github.com/colizz/9278337879721663c2c3438cc6ca29bc

Many thanks, Congqiao

**Comment by colizz** [comment] 2020-09-11 20:10
Here goes the full recipe:
```
export SCRAM_ARCH=slc7_amd64_gcc700
cmsrel CMSSW_10_6_16
cd CMSSW_10_6_16/src
cmsenv

git cms-addpkg GeneratorInterface/Core
curl -s https://gist.githubusercontent.com/colizz/9278337879721663c2c3438cc6ca29bc/raw/c2adb8f79f6ab7892e9820df179e33bc88fcce4f/GeneratorFilter_h.patch | patch -p1
git cms-checkdeps -a
curl -s --insecure https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/PPD-MultiValidationUL17GEN-00004 --retry 2 --create-dirs -o Configuration/GenProduction/python/PPD-MultiValidationUL17GEN-00004-fragment.py 
scram b -j8
cd ../../

cmsDriver.py Configuration/GenProduction/python/PPD-MultiValidationUL17GEN-00004-fragment.py --fileout file:PPD-MultiValidationUL17GEN-00004.root --mc --eventcontent RAWSIM --datatier GEN --conditions 106X_mc2017_realistic_v6 --beamspot Realistic25ns13TeVEarly2017Collision --step GEN --geometry DB:Extended --era Run2_2017 --python_filename PPD-MultiValidationUL17GEN-00004_1_cfg.py --no_exec --customise Configuration/DataProcessing/Utils.addMonitoring -n 2814
cmsRun -e -j PPD-MultiValidationUL17GEN-00004_rt.xml PPD-MultiValidationUL17GEN-00004_1_cfg.py
```

> In fact the issue can be reproduced with the test script of PPD-MultiValidationUL17GEN-00004 plus an additional patch [0] applied to cmssw. This way the particular seed is imposed, so that one sees the long time response by Pythia.

**Comment by smrenna** [comment] 2020-09-11 20:34
Can we figure out what is the type of physics event that is being processed.
Is it some LHE file?

Steve

**Comment by colizz** [comment] 2020-09-11 20:51
hi @smrenna: It is the ZZ process produced by Pythia (using process `WeakDoubleBoson:ffbar2gmZgmZ    = on`, cms [fragment](https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/PPD-MultiValidationUL17GEN-00004/0) here). The output should be the gen-level hepmc file yet in the root format.

**Comment by colizz** [comment] 2020-09-11 20:57
By the way, I upload the full output for this buggy event here [1] as a reference, with the Pythia event list included.
[1] https://coli.web.cern.ch/coli/tmp/.200911-225455_enternalGenFilter/pythia.log

**Comment by Dr15Jones** [comment] 2020-09-11 21:13
See #31441

**Comment by smrenna** [comment] 2020-09-11 22:09
Awesome.   It looks like this is coming from b bbar -> Z Z.

There is probably some funny interplay with the b parton distribution in the NNLO pdf function.

Steve

**Comment by smrenna** [comment] 2020-09-16 14:40
Hi,

What exactly is the random number generator that is used here?
I should be able to attach it to my standalone version of Pythia to debug exactly this event.
I am having a hard time getting an event that takes so long to process.

Best,
Steve

**Comment by smrenna** [comment] 2020-09-16 16:21
Hi,
I am confused about the random number state to reproduce this event.
The link you sent (https://gist.github.com/colizz/9278337879721663c2c3438cc6ca29bc)
had a seed and a vector of 38 longs.

For the HepJamesRandom generator, you need to specify a lot more than that (97 longs).
Where is that info?

Steve

**Comment by colizz** [comment] 2020-09-16 16:25
Hi @smrenna ,

Thanks for testing! I am not so sure, but I found it seems to use the CLHEP::MixMaxRng engine, with the random seed 123456789 (which indeed matches with what I observed). Does this match with the vector length?

Best, Congqiao

**Comment by smrenna** [comment] 2020-09-16 17:46
Hi, then we are running MixMax with N=38?

**Comment by colizz** [comment] 2020-09-16 18:00
Hi @smrenna , 
I just look into the MinMax code and see it is using N=17 as default. Perhaps this is the case?

**Comment by smrenna** [comment] 2020-09-16 18:12
That is what I see too.   But, then, what is the state that you gave me (with 38 long ints)?

**Comment by smrenna** [comment] 2020-09-16 18:14
engine.setSeed(123456789L, 0);
engine.get({2888826676L, 4222204286L, 239210476L, 2844405951L, 35428347L, 354167893L, 78655686L, 2729890738L, 145928944L, 2854232373L, 8374007L, 604295913L, 98961718L, 3463364680L, 217399053L, 1172894265L, 476173365L, 581365486L, 87742339L, 3794171095L, 467348746L, 1977749280L, 374460165L, 3619523079L, 300465183L, 67791381L, 415197038L, 4104105407L, 109639045L, 2293915619L, 218460587L, 782512343L, 520213210L, 3314195479L, 228207194L, 4L, 126079611L, 263768728L});


The vector inside of {} seems to be too long.

**Comment by colizz** [comment] 2020-09-16 18:25
Hi, I see that there is a `VECTOR_STATE_SIZE`defined as 2*N+4
https://gitlab.cern.ch/CLHEP/CLHEP/-/blob/master/Random/Random/MixMaxRng.h#L120
which is 38 and matches the length of the vector. Bingo!

I think we can still use the get() function to input our state vector, here it checked that the length must be 38:
https://gitlab.cern.ch/CLHEP/CLHEP/-/blob/master/Random/src/MixMaxRng.cc#L450

**Comment by smrenna** [comment] 2020-09-17 03:42
Hi,

I made some good progress today.   I know how to take the 38 long int input to the MixMax engine, and I get the exact same
hard event, but the rest of the development is different.

Can you tell me two things?


  1.  Which version of CMSSW did you run in that had pythia8240?
  2.  Were there any patches applied to this version of pythia8240?

Steve

P.S.  This is good news for the future.  It means that, given the seed from a CMSSW Pythia8 event, I can reproduce that
event standalone!

**Comment by srimanob** [comment] 2020-09-17 05:28
Hi @smrenna 
Thanks very much. We are using CMSSW_10_6_16 out-of-box.

**Comment by agrohsje** [comment] 2020-09-17 14:38
Hi @smrenna . Patches are here: https://github.com/cms-externals/pythia8/commits/cms/240 .

**Comment by smrenna** [comment] 2020-09-17 15:32
Hi, Phat implied that it was out-of-the-box pythia8.

Sadly, I can’t quite get the initialization of my stand-alone Pythia8 to match what is going on
in CMSSW.

I probably need a CMSSW expert to figure this out.

I can get exactly the same hard-event (before the parton shower and MPI), but then
things diverge.   Already from the start, I see that the MPI cross section is slightly different.

When you start a run in the middle, you must have exactly the same initialization, and then
you fast forward to your given event.     This is telling me that already the initialization for the MPI
Is somewhat different.

I will have to go back to my old brute force way of using print statements ;(.

Steve

**Comment by smrenna** [comment] 2020-09-21 19:38
Hi,

What are the compiler settings used for building this version of Pythia8.

On my laptop, I can reproduce this event up to a point, but then there is a divergence deep in the event
(i.e. there is something accepted in the CMSSW version that is rejected in the standalone version).

This led me to think that maybe it was something different between clang and gcc.

I built my code on lxplus and in CMSSW_10_6_16, but I see the same effect as in my standalone version.

However, then I built my same executable, but linked to the pre-build Pythia8 library that I found
using scram tool info pythia8.    THEN, I do reproduce the effect.

This leads me to believe that there might be different options in the Makefile.

Thanks,
Steve

**Comment by agrohsje** [comment] 2020-09-22 12:18
Hi @smrenna. What about the PR: https://github.com/cms-externals/pythia8/commits/cms/240
Did you include them in your standalone version?

**Comment by smrenna** [comment] 2020-09-22 12:52
I concluded that they didn’t make a difference.
However, it is simple enough to add them in, now that I have the random number issue
sorted out.
At the same time, I would like to know the specific compiler options used in building the library.

Best,
Steve

**Comment by makortel** [comment] 2020-09-22 13:00
> At the same time, I would like to know the specific compiler options used in building the library.

i believe the build options for pythia8 are here
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/master/pythia8.spec

@smuzaffar @mrodozov Please confirm.

**Comment by mrodozov** [comment] 2020-09-22 13:13
> > At the same time, I would like to know the specific compiler options used in building the library.
> 
> i believe the build options for pythia8 are here
> https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/master/pythia8.spec
> 
> @smuzaffar @mrodozov Please confirm.

yes that's it.

**Comment by smrenna** [comment] 2020-09-22 13:19
Oh, but what is the compiler (gcc 8.3.1?) and are there CMS specific CXX options?

**Comment by smuzaffar** [comment] 2020-09-22 13:26
GCC is 8.4.0  ( https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/master/gcc.spec ) and as you can see in https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/master/pythia8.spec we do not pass any cms specific options
```
./configure --prefix=%i --enable-shared --with-hepmc2=${HEPMC_ROOT} --with-lhapdf6=${LHAPDF_ROOT}
make -j N
```

**Comment by mrodozov** [comment] 2020-09-22 13:28
> Oh, but what is the compiler (gcc 8.3.1?) and are there CMS specific CXX options?

the compiler is this: 
https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_2_X/master/gcc.spec
its 8.4.0 . Where did you get the 8.3.1 from ?

**Comment by smuzaffar** [comment] 2020-09-22 13:30
by the way, we used to build pythia8 from https://github.com/cms-externals/pythia8/commits/cms/243 (where we have some patches on top of version 243). I see that @mkirsano requested to update it to version 302 which we take from http://home.thep.lu.se/~torbjorn/pythia8/%{n}%{realversion}.tgz . Are we missing any pacthes on top of version 302?

**Comment by smrenna** [comment] 2020-09-22 13:38
Hi,
I am on lxplus, and in CMSSW release 10_6_16.
After executing “cmsenv”, I then type “gcc -v”.
I get 8.3.1.
Is that wrong?

Steve

**Comment by mrodozov** [comment] 2020-09-22 13:48
> Is that wrong?


no its not but we gave you the gcc version for 11_2. 
For 10_6 is 8.3.1 https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_6_X/gcc820/gcc.spec

**Comment by smuzaffar** [comment] 2020-09-22 13:49
ah this is for 10.6.X release cycle. Yes for that GCC version of 8.3.1 but production architecture for 10.6.X is slc7_amd64_gcc700.
For 10.6.16 , we are using pythia8 240 ( https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_10_6_X/gcc820/pythia8.spec ) from https://github.com/cms-externals/pythia8/commits/cms/240

**Comment by colizz** [comment] 2020-09-22 14:20
Hi, I happened to find something new and is related to this.

Using the pythia8 in CMSSW_10_6_16 out-of-the-box with the [above recipe](https://github.com/cms-sw/cmssw/issues/31426#issuecomment-691290707), we face this low-response issue, and here's the event output as shown before:
(1) https://coli.web.cern.ch/coli/tmp/.200911-225455_enternalGenFilter/pythia.log

However, using the same module ExternalGeneratorFilter and configuration, but to set `--nThreads 2`, same phenomena occur as @smrenna mentions -- **the hard-event keeps the same but the following diverges.**
Here is the output
(2) https://coli.web.cern.ch/coli/tmp/.200911-225455_enternalGenFilter/pythia-th2.log

Techiqucally, using `--nThreads 2` in ExternalGeneratorFilter means to launch the generator step in two separate external processes. And, as we manually impose the random state and seed, the output of (1) and (2) should really be the same -- but it is not.

Is there any subtle difference in the pythia8 env for (1) and (2)?

**Comment by agrohsje** [comment] 2020-09-22 16:57
@colizz  but output is already because of nthread option before we impose the seed:
 |    pT0 =  1.44 gives sigmaInteraction =   461.63 mb: accepted    | 
 |    pT0 =  1.44 gives sigmaInteraction =   464.40 mb: accepted    |

**Comment by colizz** [comment] 2020-09-22 17:10
@agrohsje thanks! So that might be the cause. The random state during the pythia initializing period should also affect event output. We need to acquire that state also.

**Comment by colizz** [comment] 2020-09-22 18:08
Hi, after imposing another set of random state before initializing Pythia, we finally reproduce the same event. Here is the patch: https://github.com/colizz/cmssw/commit/fb04accb9d86a6188a6ed8cbfe238d7a0f08f44f. (the second imposed state is for initializing)
The initializing procedure may include Pythia settings defined [here](https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_16/GeneratorInterface/Pythia8Interface/plugins/Pythia8Hadronizer.cc#L329).
I guess this is the key to reproduce the same event in the stand-alone Pythia. Many thanks for the following test!

**Comment by smrenna** [comment] 2020-09-22 18:36
Hi,

After emailing with experts at FNAL, it might be that initialization needs to be done with seed+1.
I have confirmed this explicitly in my stand-alone version of Pythia8.
So, it seems that 123456790 is used for initializing Pythia8.
The seed 123456789 is used for a second random number generator.

Steve

**Comment by smrenna** [comment] 2020-09-22 21:35
Hi,
Success on reproducing the long event outside of CMSSW.
The reasons why it was tricky:

  1.  The seed used is actually 123456789+1 = 123456790
  2.  The last patch in cmssw/pythia8 is NOT in this build.    I know this because I explicitly rebuilt
Pythia8Interface with and without the change to SimpleTimeShower, and only the version
without the ‘reverted’ patch reproduces the event within CMSSW.
I am too exhausted with this now to actually debug, but I suspect that it might have something
to do with the high multiplicity bug.

Steve

**Comment by makortel** [comment] 2021-01-06 15:34
+1

I think the `core` part was addressed by making the timeout configurable in https://github.com/cms-sw/cmssw/pull/31441

**Comment by colizz** [comment] 2021-08-05 15:12
Hello,
I would like to raise this issue again as we continuously meet the timeout issue in ExternalGeneratorFilter, please see
https://its.cern.ch/jira/browse/CMSCOMPPR-20017
https://its.cern.ch/jira/browse/CMSCOMPPR-20020
and also https://github.com/cms-sw/cmssw/pull/34710#issuecomment-893523281

I am thinking of a way to get rid of the timeout issue. When there is a timeout, I think it is possible to monitor whether the worker instance is dead or not (by e.g. sharing another memory spacer). If the controller knows the worker is still alive then we can wait for multiple iterations of the period, until it finishes its task.

@Dr15Jones  Do you think this is possible? Not sure whether or not extra implementation is needed in SharedMemory. Looking forward to your suggestions.
Many thanks.

**Comment by Dr15Jones** [comment] 2021-08-06 21:14
I hope #34815 will better handle timeouts. I think our problem stem from my lack of understanding about exactly how the timeouts occured.

**Comment by colizz** [comment] 2021-08-09 04:47
@Dr15Jones Many thanks! I test the new `retry` method in ExternalGeneratorFilter and it works as expected. Will make a PR to ExternalGeneratorFilter.

**Comment by Dr15Jones** [comment] 2021-08-09 11:45
@colizz I first suggest seeing if the retry is even necessary. Try running the job without any modification to ExternalGeneratorFilter but with the new version of FWCore/SharedMemory. I fixed how the non-retry code handles timeouts as well.

**Comment by colizz** [comment] 2021-08-09 12:14
> @colizz I first suggest seeing if the retry is even necessary. Try running the job without any modification to ExternalGeneratorFilter but with the new version of FWCore/SharedMemory. I fixed how the non-retry code handles timeouts as well.

Thanks, but in the non-retry mode we have to set "very large waitTime" to allow some events that took a particularly long time to proceed. This way, we'll have to risk that the worker instance breaks accidentally, and the controller waits a "long time" before recognizing that the worker is dead. 
(This is the original reason we propose the retry method to "keep the waitTime small" while letting the long-time events pass)

**Comment by colizz** [comment] 2021-08-09 12:23
I see the change in the "non-retry" mode is on how the worker notify the controller in https://github.com/cms-sw/cmssw/pull/34815/files#diff-0ddbc2396a91fcad561341136b1ca917ee0da4d59e449c1e351316490e6f02a9R95-R96. But it won't make a difference dealing with the above puzzle.

My idea is to use `setupWorkerWithRetry` and `doTransitionWithRetry` with the custom `iRetry` function set as monitoring if the external process has dead (via its PID) - if not, returns True. Does this look fine?

**Comment by Dr15Jones** [comment] 2021-08-09 12:47
> Thanks, but in the non-retry mode we have to set "very large waitTime" to allow some events that took a particularly long time to proceed. This way, we'll have to risk that the worker instance breaks accidentally, and the controller waits a "long time" before recognizing that the worker is dead.

With the change to the non-retry mode, you can also set shorter wait times. The reason is what 'wait times' means on the `boost::semaphore` we are using isn't what I thought it was. So here is what a 'wait with a time out' actually does.
1. releases the lock being held by the controller
2. the worker code is waiting so will immediately take the lock
3. if the controller times out, it then tries to take the lock back from the worker
4. the worker only releases the lock after the worker has finished doing its work

The problem before my code change was the worker would finish its work fine but because the timeout happened the controller thought the worker did not start work and therefore stopped the program. With my recent change, if there was a timeout, the controller now check to see if the worker did actually complete the work and if so, it ignores the timeout.

So you can still have a short timeout since the only timeout that can cause the job to actually fail would be if the worker process takes way to long to initially startup. While actually processing events I couldn't find a non fatal way to cause the timeout to matter after my recent code change.

This is why I suggest testing out the existing code with the new FWCore/SharedMemory to see if the non-retry (with a shorter timeout) will already do what you need.

If the test fails, you can always use the retry interface (I added that as a possible backup plan if we ever needed it).

**Comment by Dr15Jones** [comment] 2021-08-09 14:00
@colizz do you know to which releases we would need to backport the change?

**Comment by colizz** [comment] 2021-08-09 14:28
Hi @Dr15Jones It's 10_6_X that will be used for ultra legacy processing

**Comment by colizz** [comment] 2021-08-09 14:50
And thanks for the detailed explanation! For

> So you can still have a short timeout since the only timeout that can cause the job to actually fail would be if the worker process takes way to long to initially startup. While actually processing events I couldn't find a non fatal way to cause the timeout to matter after my recent code change.

I understand your idea. But the recent test with Pythia indicate that the concern lies in the timeout in event processing step" The change you introduced
> if there was a timeout, the controller now check to see if the worker did actually complete the work and if so, it ignores the timeout.

may not quite help. I'll have further investigation in e.g. https://its.cern.ch/jira/browse/CMSCOMPPR-20017 because here shows the picture that if we generate a *very huge* number of events, it is possible that we continuously hit the maximum time/event records (maybe it's a feature in this version of Pythia), that forces us to set a larger waitTime.

**Comment by Dr15Jones** [comment] 2021-08-09 15:02
@colizz 'timeout' doesn't mean what you think it means (I was wrong about it before I changed the code this weekend). After the code change, the timeout does not mean 'the event must complete within this time frame else the job will fail' (which was the previous behavior). Now the timeout is the longest amount of time before cmsRun notices that the Worker has crashed.

This new test illustrates that
https://github.com/cms-sw/cmssw/blob/master/FWCore/SharedMemory/test/test_channels_okTimeout.cc

https://github.com/cms-sw/cmssw/blob/f620d9e86017731ccac322fc28bf4af9d02ae4ac/FWCore/SharedMemory/test/worker.h#L38-L40

the timeout in the Controller is only 5 seconds. While the worker waits 20 seconds just after the worker starts and waits 20 seconds each time 'handleTransitions' is called (which is what is called in ExternalGeneratorFilter each Event). So even though the 'timeout' technically happens, the new code says "the worker finished its work so I'll ignore the fact that we technically timed out". The unit test exists to make sure that behavior works.

**Comment by Dr15Jones** [comment] 2021-08-09 15:18
See #34822 for backport.

**Comment by colizz** [comment] 2021-08-09 15:18
ah i see! I think now I understand the concept - I'll launch more test

**Comment by colizz** [comment] 2021-08-11 11:38
Hi @Dr15Jones, the ExternalGeneratorFilter works well with the new code! There is no need to modify the ExternalGeneratorFilter code.

PS. 
I now understand the exact meaning of these steps (it's convoluted and I wasn't realize to this extend)
> 1. releases the lock being held by the controller
> 2. the worker code is waiting so will immediately take the lock
> 3. if the controller times out, it then tries to take the lock back from the worker
> 4. the worker only releases the lock after the worker has finished doing its work

In previous code, step 3 means that the controller still waits even the time exceeds the waitTime limit, until the worker finishes its work after a "long time". The controller waits because it needs the worker to release the lock. Then the controller takes the lock, and reports the error due to the timeout.
The new code check if the worker completes its work when a timeout occurs. If the worker really finishes the work, the controller ignores the timeout. Otherwise it means the worker just abort in the midway, so the controller reports the error.

Thanks a lot for all this fix, and I think we now fully resolve the timeout issue.

**Comment by Dr15Jones** [comment] 2021-08-11 13:41
@colizz thanks for doing the leg work on this!

**Closed** 2023-03-06 05:58 UTC
Labels: generators-pending, core-approved, pending-signatures
