### ISSUE TITLE
LHERunInfoProduct headers missing in externalLHEProducer?

### ISSUE THREAD

**Issue by kdlong** [cms-sw/cmssw#33690] opened 2021-05-11 12:10 UTC
Testing in CMSSW_12_0_0_pre1 (and some nightly builds) the LHE header of externalLHEProducer does not seem to be filled. In particular, I take a DY sample (or a Z' sample) and generate LHE events, then just read the product with FWLite, and runInfo.headers_size() gives zero. 

Hopefully someone can verify this, but I see that there are some recent changes to ExternalLHEProducer. Could this issue have slipped through validation? Having the LHE header info is very important for the NanoAOD production and any use of LHE weight info.

@agrohsje

**Comment by qliphy** [comment] 2021-05-11 12:30
assign generators

**Comment by qliphy** [comment] 2021-05-11 12:32
adding also @justinasr    

@kdlong  Not sure whether #33674 can fix this, but it will be included in next nightly build, and you may check then again.

**Comment by agrohsje** [comment] 2021-05-11 12:38
Hi @qliphy @Dr15Jones, could it be caused by this PR: 
https://github.com/cms-sw/cmssw/commit/b3d43f277097d61e247c4c8c327ab515f64acd2d#diff-655dfc6de4acb390723e3869d0d1bfeab1c79f0366e980abb256483f7cc393c4 ?

**Comment by justinasr** [comment] 2021-05-11 12:57
> adding also @justinasr

I don't think I did anything dangerous, essence of my PR is to add an `if` around `throw Exception`. Code check shuffled `#includes` a little, could that cause issues? I mean, `tbb/task_arena.h` and `tbb/task_group.h` [1].

[1] https://github.com/cms-sw/cmssw/pull/33624/files

**Comment by Dr15Jones** [comment] 2021-05-11 13:17
> Hi @qliphy @Dr15Jones, could it be caused by this PR:
b3d43f2#diff-655dfc6de4acb390723e3869d0d1bfeab1c79f0366e980abb256483f7cc393c4 ?

It certainly could. In that change the 'extra' call to `put` that data at end run was removed since it was interfering with the `put` of that data at begin run. However, the put at the begin run does have an 'if' block around it so it has the posibility to not do the `put`.

**Comment by kdlong** [comment] 2021-05-11 14:04
@davidlange6 the NanoGen workflows should show it, 546-548, as the missing header will ruin the weight storage (this is how I found this, but not through DQM). These variables should be empty:  https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/NanoAOD/python/nanoDQM_cfi.py#L420-L433

I don't think they are run unless requested, but it could be useful to run them for all GEN changes as it really helps to notice changes that affect Gen info in Nano before we produce GEN samples.

**Comment by Dr15Jones** [comment] 2021-05-11 14:56
It appears to me that the following needs to be done

1. reproduce the problem
2. create unit tests to avoid the problem happening again
3. understand why the LHE file format did not have the Run information as part of its header

once that is done then one will know what the fix has to be.

**Comment by kdlong** [comment] 2021-05-11 16:10
@Dr15Jones I'm confused by some of this.

2) It's not really a unit test, but the NanoGen workflows already show if the LHEHeader is invalid. One could also add something like LHERunInfoProduct.headers_size() > 0 to the validation plots

3) I don't follow this. There's nothing wrong with the LHE files. What do you mean by "the LHE file format" then?

**Comment by colizz** [comment] 2021-05-25 15:38
Yes this happens to be the fix - just notice the issue.

**Comment by agrohsje** [comment] 2021-05-25 16:08
fix working. let's close this.

**Comment by agrohsje** [comment] 2021-05-25 16:08
+generators

**Closed** 2021-05-26 00:03 UTC
Labels: fully-signed, generators-approved
