### ISSUE TITLE
Fatal exception thrown while running data WFs

### ISSUE THREAD

**Issue by sunilUIET** [cms-sw/cmssw#39453] opened 2022-09-20 12:10 UTC
Dear All

  We are observing a fatal exception error (exceeding array size) while running data WFs

https://cms-unified.web.cern.ch/cms-unified/showlog/?search=CMSSW_12_6_0_pre2__AUTOMATED_Data-RunBTagMu2022C-00001

This error is also reproducible locally. Please have a look for the fix. 

Sunil for pdmV (@bbilin @kskovpen )

**Comment by makortel** [comment] 2022-09-20 13:09
The exception is
```
----- Begin Fatal Exception 15-Sep-2022 02:15:35 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 356531 lumi: 11 event: 9968011 stream: 4
   [1] Running path 'HLTAnalyzerEndpath'
   [2] Prefetching for module L1TRawToDigi/'hltGtStage2Digis'
   [3] Prefetching for module RawDataCollectorByLabel/'rawDataCollector'
   [4] Calling method for module L1TDigiToRaw/'packGmtStage2'
Exception Message:
A std::exception was thrown.
array::at: __n (which is 6) >= _Nm (which is 6)
----- End Fatal Exception -------------------------------------------------
```
https://cms-unified.web.cern.ch/cms-unified/joblogs/pdmvserv_RVCMSSW_12_6_0_pre2RunBTagMu2022C__RelVal_2022C_220914_102620_781/8002/HLTRUN3/46ee1bee-994f-42ce-94f7-743f6331103a-1-3-logArchive/job/WMTaskSpace/cmsRun1/cmsRun1-stdout.log

**Comment by makortel** [comment] 2022-09-20 13:09
assign l1

**Comment by cecilecaillol** [comment] 2022-09-23 09:28
@sunilUIET What is the command to reproduce the error locally? Thanks!

**Comment by sunilUIET** [comment] 2022-09-23 13:10
@cecilecaillol you can copy config file which can be run with CMSSW_12_6_0_pre2
/afs/cern.ch/user/s/subansal/public/step_2_cfg.py

**Comment by cecilecaillol** [comment] 2022-10-27 08:05
Fixed in https://github.com/cms-sw/cmssw/pull/39624

**Comment by cecilecaillol** [comment] 2022-10-27 08:05
+l1

**Comment by perrotta** [comment] 2022-11-02 06:49
Close it, as it looks like it has been fixed

**Closed by perrotta** 2022-11-02 06:49 UTC
Labels: l1-approved, fully-signed
