### ISSUE TITLE
tk alignmen fix for overlap validation

### ISSUE THREAD

**Issue by venturana** [cms-sw/cmssw#39031] opened 2022-08-11 12:03 UTC
Hello,

When running TkAlOverlapValidation.py, this problem pops up:

```
plot("/afs/cern.ch/cms/CAF/CMSALCA/ALCA_TRACKERALIGN2/data/commonValidation/results/venturaa/Collisions2022/overlap/OverlapValidationPlots/",subdet_ids,module_directions,overlap_directions,profile_directions,("root://eoscms.cern.ch//eos/cms/store/group/alca_trackeralign/AlignmentValidation/AlignmentValidation/Collisions2022/overlap/OverlapValidation_collisions_PCL_alignment.root", "PCL alignment", 1, 2001),
  File "/afs/cern.ch/cms/CAF/CMSALCA/ALCA_TRACKERALIGN/data/commonValidation/CMSSW_12_4_3/python/Alignment/OfflineValidation/overlapValidationPlot.py", line 202, in plot
    h = hist(files,files.replace("/",""),subdet_ids,module_directions,overlap_directions,profile_directions)
  File "/afs/cern.ch/cms/CAF/CMSALCA/ALCA_TRACKERALIGN/data/commonValidation/CMSSW_12_4_3/python/Alignment/OfflineValidation/overlapValidationPlot.py", line 29, in hist
    if subdetConditon(subdet,module,overlap):
NameError: name 'subdetConditon' is not defined
```

**Comment by venturana** [comment] 2022-08-11 12:03
the configuration file is

```import FWCore.ParameterSet.Config as cms

process = cms.Process("overlap")

process.load("Alignment.OfflineValidation.Dataset_Validation_StreamExpress_Run2022B-TkAlMinBias-Express-v1_ALCARECO_180722_cff")
process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(int(100000 / 1))
)
process.source.skipEvents=cms.untracked.uint32(int(0*100000/1))

process.options = cms.untracked.PSet(
   wantSummary = cms.untracked.bool(False),
   Rethrow = cms.untracked.vstring("ProductNotFound"), # make this exception fatal
   fileMode  =  cms.untracked.string('NOMERGE') # no ordering needed, but calls endRun/beginRun etc. at file boundaries
)

process.load("FWCore.MessageLogger.MessageLogger_cfi")
process.MessageLogger.cerr.FwkReport.reportEvery = 1000
process.MessageLogger.cout.enableStatistics = cms.untracked.bool(True)


process.load("RecoVertex.BeamSpotProducer.BeamSpot_cff")
process.load("Configuration.Geometry.GeometryDB_cff")
process.load('Configuration.StandardSequences.Services_cff')
process.load("Configuration.StandardSequences.MagneticField_cff")


import Alignment.CommonAlignment.tools.trackselectionRefitting as trackselRefit
process.seqTrackselRefit = trackselRefit.getSequence(process, 'ALCARECOTkAlMinBias',
                                                     isPVValidation=False, 
                                                     TTRHBuilder='WithAngleAndTemplate',
                                                     usePixelQualityFlag=True,
                                                     openMassWindow=False,
                                                     cosmicsDecoMode=True,
                                                     cosmicsZeroTesla=False,
                                                     momentumConstraint=None,
                                                     cosmicTrackSplitting=False,
                                                     use_d0cut=True,
                                                    )




#Global tag
process.load("Configuration.StandardSequences.FrontierConditions_GlobalTag_cff")
from Configuration.AlCa.GlobalTag import GlobalTag
process.GlobalTag = GlobalTag(process.GlobalTag,"124X_dataRun3_Express_v4")


import CalibTracker.Configuration.Common.PoolDBESSource_cfi

process.conditionsInTrackerAlignmentRcd = CalibTracker.Configuration.Common.PoolDBESSource_cfi.poolDBESSource.clone(
     connect = cms.string('frontier://FrontierProd/CMS_CONDITIONS'),
     toGet = cms.VPSet(cms.PSet(record = cms.string('TrackerAlignmentRcd'),
                               tag = cms.string('TrackerAlignment_HGPCL_ForComparison2022_v1')
                               )
                      )
    )
process.prefer_conditionsInTrackerAlignmentRcd = cms.ESPrefer("PoolDBESSource", "conditionsInTrackerAlignmentRcd")


# Use compressions settings of TFile
# see https://root.cern.ch/root/html534/TFile.html#TFile:SetCompressionSettings
# settings = 100 * algorithm + level
# level is from 1 (small) to 9 (large compression)
# algo: 1 (ZLIB), 2 (LMZA)
# see more about compression & performance: https://root.cern.ch/root/html534/guides/users-guide/InputOutput.html#compression-and-performance
compressionSettings = 207
process.analysis = cms.EDAnalyzer("OverlapValidation",
    usePXB = cms.bool(True),
    usePXF = cms.bool(True),
    useTIB = cms.bool(True),
    useTOB = cms.bool(True),
    useTID = cms.bool(True),
    useTEC = cms.bool(True),
    compressionSettings = cms.untracked.int32(compressionSettings),
    ROUList = cms.vstring('TrackerHitsTIBLowTof',
        'TrackerHitsTIBHighTof',
        'TrackerHitsTOBLowTof',
        'TrackerHitsTOBHighTof'),
    trajectories = cms.InputTag("FinalTrackRefitter"),
    associatePixel = cms.bool(False),
    associateStrip = cms.bool(False),
    associateRecoTracks = cms.bool(False),
    tracks = cms.InputTag("FinalTrackRefitter"),
    barrelOnly = cms.bool(False)
)



process.TFileService = cms.Service("TFileService",
    fileName = cms.string('OverlapValidation_collisions_PCL_alignment.root')
)



process.p = cms.Path(
process.seqTrackselRefit*process.analysis)


print("Done")
```

**Comment by venturana** [comment] 2022-08-11 12:04
and you can find the dataset used in /afs/cern.ch/cms/CAF/CMSALCA/ALCA_TRACKERALIGN/data/commonValidation/CMSSW_12_4_3/src/Alignment/OfflineValidation/python/Dataset_Validation_StreamExpress_Run2022B-TkAlMinBias-Express-v1_ALCARECO_180722_cff.py

**Comment by mmusich** [comment] 2022-08-11 12:51
assign alca, trk-dpg

**Comment by tvami** [comment] 2022-08-11 12:53
@venturana please include in the title that this is for the tracker alignment, thanks

**Comment by tvami** [comment] 2022-08-11 12:56
Looking at the history I found this commit: https://github.com/cms-sw/cmssw/commit/843303816dffa2100495248594d0503e0b1f4909

**Comment by tvami** [comment] 2022-08-11 13:01
So it's a type: `subdetConditon`vs `subdetCondition` ...

**Comment by tvami** [comment] 2022-08-11 21:26
+alca
 * resolved in https://github.com/cms-sw/cmssw/pull/39035

**Comment by tvami** [comment] 2022-08-11 21:28
> So it's a typo: `subdetConditon`vs `subdetCondition` ...

If I may point out, not only the issue is about a typo but the title of the issue has one too ;)

**Closed** 2022-08-12 00:59 UTC
Labels: alca-approved, pending-signatures, trk-dpg-pending

**Comment by mmusich** [comment] 2022-08-12 06:13
+1
   * resolved in https://github.com/cms-sw/cmssw/pull/39035
