### ISSUE TITLE
CMSSW changes requested for spring re-reco of 2016 data

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmssw#17603] opened 2017-02-22 14:16 UTC
As proposed in the 21 February ORP, this issue is for your requests for CMSSW changes for the "legacy" re-reco. Please add your requests here for discussion in the 28 February ORP.

Essential information includes:
 - Feature description
 - 80x PR or expected date of completion
 - Is this change in the development release cycle already? if so, approximately when did it enter (for validation bookkeeping
 - What is the impact of this change on MC? (as we are not re-doing the MC)

**Comment by davidlange6** [comment] 2017-02-22 14:17
assign reconstruction, alca, db, dqm, pdmv

**Comment by slava77** [comment] 2017-02-22 14:54
On 2/22/17 6:16 AM, David Lange wrote:
> # What is the impact of this change on MC? (as we are not re-doing the MC)

Are we planning to redo miniAOD for MC?

**Comment by davidlange6** [comment] 2017-02-22 15:05
I’m not aware of a concrete plan for that, but others may know more than me. It can be useful to track things that need “only” a re-miniaod of the MC to be consistent.

**Comment by boudoul** [comment] 2017-02-28 15:07
Greetings, I asked @dmitrijus to put here this PR  #17592 , but since the ORP is in less than 1 hour, i'm doing myself (as Tracker DPG ). 
Answering here the questions raised in  the description of this issue : 
This PR is just adding some monitoring strip plots which could be useful for the re-reco - fully signed (but ORP ) 
Backport of the same code from the already merged a month ago PR in 90X : #17304

**Comment by slava77** [comment] 2017-02-28 15:22
RECO-related PRs and features (I intend to edit this post once new contributions show up or the available ones change):

Affects RECO only
- ECAL ES dead plane treatment
    - https://github.com/cms-sw/cmssw/pull/17219
    - will need a GT; the part handled in PPD
- ECAL EB multifit using max-sample for gain-switched rechits
    - https://github.com/cms-sw/cmssw/pull/17259
    - This PR doesn't enable the change itself; will need an update or use of customise command in cmsDriver at submission.
    - Further updates are expected to #17259 based on https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1501/1/1.html
- CTPPS diamond hit and track reconstruction
    - 90X PR in 900pre5 #17535; no 80X PR yet
- CTPPS miniAOD
    - 90X PR #17650; 80X PR after will come after the merge in 90X and backport of diamond rechit reco #17535 
- Tracking muon outside-in iteration HIP un-mitigation
    - proposed in the XPF Feb 21 https://indico.cern.ch/event/614937/. This will supposedly be applied only to B-F (SiStrip VFP30 period)
    - No PR yet.

The following will also require MC re-miniAOD
- BTV DNN taggers
    - https://github.com/cms-sw/cmssw/pull/17584 additional switches will be needed to enable the taggers with jetupdate tools
- BTV AK8 jets double b-tagger update from v3 to v4
    - https://github.com/cms-sw/cmssw/pull/17609
    - tested already in 90X since pre4
- MET: puppi MET and MET significance fixes
    - https://github.com/cms-sw/cmssw/pull/16174
    - 90X PR is not yet signed off https://github.com/cms-sw/cmssw/pull/17524
- miniAOD/MET related to bad muons
    - something to replace what went to 03Feb2017 re-miniAOD; unclear if a PR will be made since muon reco fixes may render a replacement unnecessary.
- EGamma 80X-based regression
    - to be likely based on the "analysis" code from https://github.com/cms-sw/cmssw/pull/17508 and applied as modifiers to miniAOD objects
    - https://hypernews.cern.ch/HyperNews/CMS/get/recoDevelopment/1501/1/2.html

**Comment by slava77** [comment] 2017-02-28 16:39
From reco: I added Tau PR #17292 in https://github.com/cms-sw/cmssw/issues/17603#issuecomment-283068710

**Comment by slava77** [comment] 2017-03-04 17:31
@davidlange6 

just to clarify: some of the reco/miniAOD changes are not configurable and will change the default behavior once integrated.

**Comment by gkasieczka** [comment] 2017-03-10 10:22
I would like to add from the JMAR side:
Backport of JetID functor (#17875)

**Comment by forthommel** [comment] 2017-03-30 11:01
Depending on the merging status of #17817 onto `9_1_X` and #17815 onto `8_0_X` a backport of the earlier would be good.

**Comment by mmusich** [comment] 2017-03-30 13:53
Strips offline would appreciate merging of https://github.com/cms-sw/cmssw/pull/18062

**Comment by slava77** [comment] 2017-04-05 09:28
PRs for the legacy and miniAOD v1:

RECO part
- CTPPS strip updates, diamond reco up to rechits and  strip miniAOD #17815
    - all relevant algorithms are enabled by default
- ECAL multifit updates #17259
    - current implementation implies that production is run with ```--customise_command "process.ecalMultiFitUncalibRecHit.algoPSet.gainSwitchEBMaxSample = cms.bool(True)"```
- ES dead plane calibration #17219
    - new behavior is enabled with a corresponding GT; default/old payloads lead to no changes in behavior


miniAODv1:
- deep flavor tags #17584
    - this adds new tags to miniAOD jets. This can technically just go to v2 because it will become useful only once MC has this.
- new MET filters #17968 [THIS IS NOT SIGNED YET]
    - the filters are most useful for data and because of this it is appropriate for v1
    - the filters can be rerun from miniAOD

Analysis level changes (no effect on production workflows):
- Egamma tag-and-probe updates #17940
- Reject 0 pt Puppi candidates in jet-track association #17642

**Comment by davidlange6** [comment] 2017-04-06 07:09
Status update

Merged in 04-05-2300
#17219, #17259, #17584, #17592, #17609, #17642, #17815, #17875, #17940, #18062

Merged in 04-06-1100
#17292 [except this should have been for miniaodv2 per @slava77 

Other requests pending and/or mentioned in this issue
#17968 - not in 91x (or signed), so not in the re-reco
#16174 - not in 91x (or signed), so not in the re-reco

**Comment by slava77** [comment] 2017-04-06 07:29
@davidlange6 for rereco and mini v1 please use https://github.com/cms-sw/cmssw/issues/17603#issuecomment-291805776
I was trying to make the text rather clear, but apparently not clear enough.

**Comment by slava77** [comment] 2017-04-06 07:41
@davidlange6 
I have now updated https://github.com/cms-sw/cmssw/issues/17603#issuecomment-291805776 to reflect the merged PRs status and added muon tracking HIP un-mitigation #18218 (to be signed some time today).

**Comment by davidlange6** [comment] 2017-04-06 07:51
ok, #17292 is reverted. we can merge #18235 when we need it again.

**Comment by slava77** [comment] 2017-04-06 12:26
I added #18240  to https://github.com/cms-sw/cmssw/issues/17603#issuecomment-291805776

**Comment by slava77** [comment] 2017-04-09 21:16
I have updated https://github.com/cms-sw/cmssw/issues/17603#issuecomment-291805776
- already merged #18240 is added to the list
- recently signed #18218 has an updated description and is ready to be merged (with a caveat that the 91X code is not merged yet)
- recently signed #17968 is ready to be merged (with a caveat that the 91X code update, which has a 10% relative impact on what's already in 91X and was not in sync with this PR, is not merged yet).

The last two are the only remaining features needed for rereco/miniAODv1

**Comment by davidlange6** [comment] 2017-04-10 13:23
#17968 looks too late to consider here. the much bigger 91x code change in #18165  is somehow finally catching up to the last-moment-reminiaod changes from months ago?

**Comment by davidlange6** [comment] 2017-04-10 13:23
#18218 is now merged.

**Comment by slava77** [comment] 2017-04-10 17:12
I have updated https://github.com/cms-sw/cmssw/issues/17603#issuecomment-291805776
- added CTPPS diamonds tracking #18238
- marked  #18218 as merged

**Comment by slava77** [comment] 2017-06-28 18:07
+1

the legacy rereco is essentially over for the "RECO" step.
It's probably time to close this issue.
@davidlange6

**Comment by slava77** [comment] 2018-10-20 15:13
@davidlange6 
this can be closed now

**Closed** 2018-10-23 09:32 UTC
Labels: alca-pending, db-pending, dqm-pending, pdmv-pending, pending-signatures, reconstruction-approved
