### ISSUE TITLE
Wrong formula for percentual difference in profiling

### ISSUE THREAD

**Issue by felicepantaleo** [cms-sw/cmssw#46578] opened 2024-11-01 11:56 UTC
It is calculated as `(PR-baseline)/PR` while it should be calculated as `(PR-baseline)/baseline`. It is wrong in all the columns `cpu time percent diff`, `allocated memory percent diff`, `deallocated memory percent diff`

From a PR: https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-d4760a/42504/profiling/29834.21/diff-step3_cpu.resources.json.html
I see:
![image](https://github.com/user-attachments/assets/835a9db7-f8ab-49a1-a24e-ac5993628dda)

**Comment by smuzaffar** [comment] 2024-11-01 17:06
assign core

**Comment by smuzaffar** [comment] 2024-11-01 17:07
@gartung , can you please look in to this?

**Comment by gartung** [comment] 2024-11-04 15:58
@smuzaffar can profiling be run on the baseline release. Part of the problem is that the "baseline" in this instance is the profiling for the last IB.

**Comment by smuzaffar** [comment] 2024-11-04 16:04
sorry @gartung , I did not get your point ? PR profiling job should use the same IB for which the the PR tests were run.

**Comment by gartung** [comment] 2024-11-04 16:11
I need to set the number of events to 100 and I wanted to avoid running that many for every IB.

**Comment by gartung** [comment] 2024-11-04 16:20
Step 1 and step 2 are run for each job so technically the input for step3 RECO is different. On average the results should be the same but not with the limited stats of 10 events.

**Comment by smuzaffar** [comment] 2024-11-04 16:21
ah ok, I thought we were doign it already. Aren't we downloading baseline results during the PR profiling job here https://github.com/cms-sw/cms-bot/blob/master/pr_testing/run-pr-profiling.sh#L50-L54 ?

**Comment by gartung** [comment] 2024-11-04 16:23
No, it is pulling the data from the IB.

**Comment by smuzaffar** [comment] 2024-11-04 16:29
sorry, can you please explain with an example e.g for `PR1` if we have used `IBa` then `IBa` is `baseline` and profiling comparison should use the profiling data from `IBa` ... right?  Are you saying that we use `IBa` for PR tests but downloaded profiling data for `IBb` ?

**Comment by smuzaffar** [comment] 2024-11-04 16:31
shouldn't we just change https://github.com/cms-sw/cms-bot/blob/master/comparisons/resources-diff.py#L18-L19
```
        if not data[metric] == 0.0:
            pdmetric = 100 * dmetric / data[metric]
```

**Comment by gartung** [comment] 2024-11-04 16:38
Yes. I made that change and will submit a PR.

**Comment by gartung** [comment] 2024-11-04 16:56
https://github.com/cms-sw/cms-bot/pull/2365
It's failing black checks for code not touched by this PR.

**Comment by smuzaffar** [comment] 2024-11-04 17:03
https://github.com/cms-sw/cms-bot/pull/2365 is merged now. @gartung , please open a separate issue for https://github.com/cms-sw/cmssw/issues/46578#issuecomment-2455090939

**Comment by makortel** [comment] 2024-11-08 22:43
+core

**Comment by makortel** [comment] 2024-11-08 22:43
@cmsbuild, please close

**Closed** 2024-11-08 22:44 UTC
Labels: core-pending, pending-signatures
