### ISSUE TITLE
Problem with plugin for RPC Trigger Primitive

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssw#27491] opened 2019-07-11 08:29 UTC
The integration of #26967 has caused a massive failure in the IB CMSSW_11_0_X_2019-07-10-1100 due to a misconfiguration of plugins that was not caught in the initial test phase. According to the comment by @Dr15Jones there are two factories registered under two different names but with identical signature. @maseguracern @rekovic this needs to be fixed in order to reintegrate again this code, that for the time being has been reverted for clarity.

On top of this there is the question @smuzaffar @Dr15Jones : why was this failure missed 1) in the PR test and 2) in the first IB where the PR was merged CMSSW_11_0_X_2019-07-09-2300 ? This behaviour is easily reproducible in standalone tests using 136.85 .

**Comment by fabiocos** [comment] 2019-07-11 08:30
assign l1

**Comment by Dr15Jones** [comment] 2019-07-11 13:49
> On top of this there is the question @smuzaffar @Dr15Jones : why was this failure missed 1) in the PR test and 2) in the first IB where the PR was merged CMSSW_11_0_X_2019-07-09-2300 ? This behaviour is easily reproducible in standalone tests using 136.85 .

This is only a guess. The problem is essentially a _one definition rule_ type violation. For such violation, the exact order in which a symbol is loaded into a job will dictate the behavior. So I'm guessing we just happen to load the shared libraries in a different order.

**Comment by fabiocos** [comment] 2021-05-12 09:27
@silviodonato @qliphy not sure whether this is issue is still there

**Comment by silviodonato** [comment] 2021-05-12 14:34
The issue was "solved" by reverting #27491(#27481), but the code of the RPC TriggerPrimitives was never merged.
@cms-sw/l1-l2 do you know what is the plan about this?
Let me also add in cc @folguera, author of #30344 (DT TPG)

**Comment by fabiocos** [comment] 2021-05-12 14:56
@silviodonato more than a solution that was the temporarily protection. I see that the new package proposed in #26967 is not there, so the problem is not there, at least in the original form, but it is unclear to me what is the follow-up (if any).

Unless you have a good reason to keep this issue open, I would close it.

**Comment by silviodonato** [comment] 2021-05-12 15:33
I agree let's close the issue. @rekovic @cecilecaillol be aware that the RPC TriggerPrimitives are not merged yet (after 2 year since #26967)

**Closed by silviodonato** 2021-05-12 15:33 UTC
Labels: l1-pending, pending-signatures
