### ISSUE TITLE
FWCore/Integration: Duplicate geneabted CFI files

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/cmssw#25057] opened 2018-10-30 16:19 UTC
@Dr15Jones , we have duplicate generated cfi files[a]. With new build rules this will generate a build error.

[a]
https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/FWCore/Integration/test/OtherThingAnalyzer.cc#L310

https://github.com/cms-sw/cmssw/blob/02d4198c0b6615287fd88e9a8ff650aea994412e/FWCore/Integration/test/ThingWithMergeProducer.cc#L191

**Comment by smuzaffar** [comment] 2018-10-30 16:20
assign core

**Comment by Dr15Jones** [comment] 2018-10-30 16:40
@wddgit could you fix this?

**Comment by wddgit** [comment] 2018-10-30 16:46
Yes. I will take a look now.

**Comment by wddgit** [comment] 2018-10-30 18:10
PR #25060 should fix this and this issue can be closed.

**Comment by Dr15Jones** [comment] 2018-11-17 13:46
+1

**Comment by Dr15Jones** [comment] 2018-11-17 13:46
@smuzaffar please close this one if the problem is now gone.

**Closed** 2018-11-19 08:29 UTC
Labels: core-approved, fully-signed
