### ISSUE TITLE
DQMRootSource and DQMRootOutputModule don't use the same file ID

### ISSUE THREAD

**Issue by nsmith-** [cms-sw/cmssw#28534] opened 2019-12-03 19:49 UTC
Since the DQM file type is not using the standard RootFile IO, it doesn't have the `edm::createGlobalIdentifier()` embedded in a `MetaData` tree.
Rather, it uses the method `TFile::GetUUID` to read the file ID out of input files in:
https://github.com/cms-sw/cmssw/blob/81e12a9da6b3864a9d1aac5d433c7147f578fd2a/DQMServices/FwkIO/plugins/DQMRootSource.cc#L641

The DQMRootOutputModule should then correspondingly report the correct UUID from `m_file->GetUUID()` rather than creating an unrelated ID and passing it to the job report:
https://github.com/cms-sw/cmssw/blob/81e12a9da6b3864a9d1aac5d433c7147f578fd2a/DQMServices/FwkIO/plugins/DQMRootOutputModule.cc#L337

**Comment by makortel** [comment] 2019-12-04 15:52
@nsmith- Below is my understanding of the chain of actions, could you confirm whether it is correct or not?

* Production runs `cmsRun` to produce a DQMIO file with some temporary file name.
* `cmsRun` (in `DQMRootOutputModule`) reports an GUID from `edm::createGlobalIdentifier()` in the job report
* Production renames the DQMIO file according to the GUID from the job report
* Production runs another `cmsRun` job to read the aforementioned DQMIO file
* `cmsRun` reads the file and reports `TFile::GetUUID()` in the job report
  * The problem is that the `TFile::GetUUID()` is not consistent with the GUID in the file name

Easiest fix would be to use `TFile::GetUUID()` also in the `DQMRootOutputModule`. But that won't fix the inconsistency with the existing DQMIO files, i.e. only files written after the fix will have consistent file name and GUID in the job report.

In a quick test the `TFile::GetUUID()` seems to give the GUID in lower case (e.g. `1a37a3f8-113d-11ea-91c0-211fb8bcbeef`), is that ok for computing?

**Comment by makortel** [comment] 2019-12-04 17:49
> Easiest fix would be to use `TFile::GetUUID()` also in the `DQMRootOutputModule`.

Done in #28551.

**Comment by nsmith-** [comment] 2019-12-04 18:49
Yeah the fix you've done is exactly what I was thinking to do.  Lowercase is not an issue in principle (since already that is how its reported in the inputfile jobreport) but while you're there having it uppercase would be nice for consistency.

Indeed there is no practical way to fix the existing files.

**Comment by makortel** [comment] 2019-12-04 20:22
> but while you're there having it uppercase would be nice for consistency.

Ok, updated #28551 accordingly.

**Closed** 2019-12-05 21:11 UTC
Labels: pending-assignment
