### ISSUE TITLE
Bug in HLTrigger/HLTfilters/plugins/HLTDoubletDZ.cc

### ISSUE THREAD

**Issue by XL-Seb-Yan** [cms-sw/cmssw#40615] opened 2023-01-25 16:47 UTC
Hello experts,

We noticed a potential bug in the HLTDoubletDZ filter: https://github.com/cmssw/cmssw/blob/master/HLTrigger/HLTfilters/plugins/HLTDoubletDZ.cc#L348

Here the validity of electron gsfTrack is not checked before accessing it, and it would cause the code to crash when the electron does not have a valid gsfTrack.

Adding a line to check the validity of gsfTrack would be a solution for this.

**Comment by makortel** [comment] 2023-01-25 16:48
assign hlt

**Comment by missirol** [comment] 2023-01-25 17:59
@XL-Seb-Yan, thanks for reporting. If you encountered the crash, and have a recipe to reproduce it, it would be useful.

(The correct link is https://github.com/cms-sw/cmssw/blob/master/HLTrigger/HLTfilters/plugins/HLTDoubletDZ.cc#L348)

I can prepare a fix in time for `CMSSW_13_0_0_pre4` (Feb 7) (if nobody does it earlier). Looks like there are a few more things to improve in that function (e.g. it does not return if [the handle is invalid](https://github.com/cms-sw/cmssw/blob/97697ab73e8dd02f8965b9a9e896ab075497425f/HLTrigger/HLTfilters/plugins/HLTDoubletDZ.cc#L336)).

Afaiu, an appropriate check would be `gsfTrack().isNonnull() and gsfTrack().isAvailable()`, but please let me know if that's not the case.

**Comment by swagata87** [comment] 2023-01-27 16:38
A way to see the crash can be this:

From `CMSSW_12_6_2`, 

`hltGetConfiguration /dev/CMSSW_12_6_0/GRun --globaltag auto:phase1_2022_realistic_postEE --mc --unprescale --output minimal --max-events -1 --eras Run3 --l1-emulator FullMC --l1 L1Menu_Collisions2022_v1_4_0-d1_xml --input /store/mc/Run3Summer22EEDR/QCD_Pt-120To170_TuneCP5_13p6TeV-pythia8/GEN-SIM-RAW/Poisson70KeepRAW_124X_mcRun3_2022_realistic_postEE_v1-v1/80000/55194757-7f7a-4fac-83b2-fc6e0b5fe7f5.root --paths HLT_DoubleEle6_eta1p22_mMax6_dz0p8_v1 > hlt_bparking_dz.py`

At this point, if we run `hlt_bparking_dz.py`, no crash is encountered.
But then open the config file and change `MinPixHitsForDZ` from 0 to 3 in `hltDoubleEle6eta1p22mMax6DZFilter`. 
Now it will crash. 

The fix that you have proposed should work. 

We never discovered this issue before because in dielectron paths, DZ filter has always used  `MinPixHitsForDZ=0`, so the problematic line[1] is never activated. 

[1]
https://github.com/cms-sw/cmssw/blob/338d63c616c621afd28f277d431a067c222d7389/HLTrigger/HLTfilters/plugins/HLTDoubletDZ.cc#L405-L406

**Comment by missirol** [comment] 2023-02-02 11:28
+hlt

Fixed in #40648. Improvements could be considered for 13_1_X (see https://github.com/cms-sw/cmssw/pull/40648#issuecomment-1413434811).

Thanks again for reporting the issue!

**Comment by missirol** [comment] 2023-02-02 11:28
please close

**Closed** 2023-02-02 11:29 UTC
Labels: hlt-approved, fully-signed
