### ISSUE TITLE
[Geometry] Non-planar Trapezoids in a 2021 v4 Yoke Description

### ISSUE THREAD

**Issue by ianna** [cms-sw/cmssw#31824] opened 2020-10-16 11:55 UTC
@slomeo, @civanch, @cvuosalo - FYI

Reported by Evgueni from his recent analysis of 2021 GDML:
```
-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : GeomSolids0002
      issued by : G4Trap::MakePlanes()
Side face ~-X is not planar for solid: YB2_w1_m50x7fd9eb80be80
Discrepancy: -0.025 mm
-----------------------------------------------------------
    *** Dump for solid: YB2_w1_m50x7fd9eb80be80 ***
    ===================================================
 Solid type: G4Trap
 Parameters:
    half length Z: 194.9 mm
    half length Y, face -Dz: 224.9 mm
    half length X, face -Dz, side -Dy1: 513.1 mm
    half length X, face -Dz, side +Dy1: 573.4 mm
    half length Y, face +Dz: 224.9 mm
    half length X, face +Dz, side -Dy2: 513.2 mm
    half length X, face +Dz, side +Dy2: 573.4 mm
    theta: 0°
    phi: 0°
    alpha, face -Dz: 7.632170099999999°
    alpha, face +Dz: 7.632170099999999°
-----------------------------------------------------------

*** Fatal Exception *** core dump ***
 **** Track information is not available at this moment
 **** Step information is not available at this moment

-------- EEEE -------- G4Exception-END --------- EEEE -------

```

**Comment by ianna** [comment] 2020-10-16 11:59
assign geometry

**Comment by slomeo** [comment] 2020-10-16 12:06
@ianna please tell me how can I reproduce the warning? which tool do I have to use?

**Comment by etcherniaev** [comment] 2020-10-16 13:00
@slomeo this warning message appears if to use pure Geant4 without VecGeom. To fix the problem in this particular case, it should be sufficient to set both X half length at -Dy1 & -Dy2 to 513.1 (or 513.2).

**Comment by slomeo** [comment] 2020-10-16 14:05
@etcherniaev are you talking about three traps (i.e YB2_w1_m1 _m5 _m6) defined in Geometry/MuonCommonData/data/muonYoke/2021/v4/muonYoke.xml ?

**Comment by slomeo** [comment] 2020-10-16 14:11
@etcherniaev : For YB2_w1_m1 we have: bl1=bl2="0.5132*m -0.1*mm" 
                         For YB2_w1_m5 we have: bl1="0.5132*m -0.1*mm"  and  bl2="0.5132*m" 
                         For YB2_w1_m5 bl1 and bl2 are not 0.5132*m
So the only discrepancy, between bl1 and bl2, is for YB2_w1_m5
Is this the problem?

**Comment by etcherniaev** [comment] 2020-10-16 14:16
@slomeo yes, the problem is that _YB2_w1_m5_ is twisted, its lateral surfaces are not planar

**Comment by slomeo** [comment] 2020-10-16 14:25
@etcherniaev : 👍 , I'll change it putting bl1=bl2 for YB2_w1_m5 (then I'll check overlaps) but how can I know if the issue will be fixed in order to submit a PR?

**Comment by etcherniaev** [comment] 2020-10-16 14:39
@slomeo try to upload you geometry in pure Geant4, it does not accept twisted G4Trap solids. You can use the attached routine to adjust the parameters of a G4Trap solid to make lateral faces planar
[TrapParamsAdjustment.cc.txt](https://github.com/cms-sw/cmssw/files/5392355/TrapParamsAdjustment.cc.txt)

**Comment by slomeo** [comment] 2020-10-16 15:11
@etcherniaev : in lxplus (after a cmsenv) I have to compile your routine, is it so?

**Comment by etcherniaev** [comment] 2020-10-16 16:00
@slomeo have you renamed it from `TrapParamsAdjustment.cc.txt` to `TrapParamsAdjustment.cc`? it is an ordinary c++ code and should compile on any system, i've just checked it with g++

**Comment by slomeo** [comment] 2020-10-16 16:06
@etcherniaev : Yes, I renamed it but in my laptop I see:

g++ TrapParamsAdjustment.cc -o TrapParamsAdjustment.exe

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
and so on... 
I think that I'll work on lxplus

**Comment by slomeo** [comment] 2020-10-23 13:17
@ianna : as PR #31839  is merged, I think that you can close this PR.

**Comment by cvuosalo** [comment] 2020-10-23 22:23
+1

**Closed** 2020-10-24 00:53 UTC
Labels: fully-signed, geometry-approved
