### ISSUE TITLE
[PPC] Unit test failure in FWCore/Concurrency

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/cmssw#32086] opened 2020-11-10 20:58 UTC
Unit test:
testFWCoreConcurrency fails
with 
`Running ............./bin/sh: line 1: 91746 Floating point exception(core dumped) testFWCoreConcurrency`
on powerpc. It doesn's say anything else, so I guess  disassembling the test which includes all .ccpunit. files.

**Comment by makortel** [comment] 2020-11-10 21:05
assign core

**Comment by makortel** [comment] 2020-11-10 21:44
I wonder if the problem has the same origin as in https://github.com/cms-sw/cmssw/pull/32049#issuecomment-724055451 as the cause is floating point exception.

**Comment by dan131riley** [comment] 2020-11-13 14:42
> I wonder if the problem has the same origin as in [#32049 (comment)](https://github.com/cms-sw/cmssw/pull/32049#issuecomment-724055451) as the cause is floating point exception.

Maybe?  That crash looks like the floating point exception state is getting reset from a state saved by TBB after the saved state has been invalidated, probably because the object holding the saved state has been freed.  I have a vague theory that Chris's changes to the MessageLogger somehow exposed a bug in our use of TBB, and this is a manifestation of the same issue, but that's just a hand-wavy theory.

**Comment by Dr15Jones** [comment] 2020-11-13 14:47
>  I have a vague theory that Chris's changes to the MessageLogger somehow exposed a bug in our use of TBB, and this is a manifestation of the same issue, but that's just a hand-wavy theory.

I hold the same supposition.

**Comment by mrodozov** [comment] 2020-11-14 11:05
this failure is not present anymore, I'll guess fixed by https://github.com/cms-sw/cmssw/pull/32117

**Comment by dan131riley** [comment] 2020-11-15 16:24
> this failure is not present anymore, I guess fixed by #32117

Still there.  It's intermittent, has been all along.  I'd have been very surprised if #32117 fixed it, the FWCore/Concurrency tests are at a much lower level than the IOV issue fixed in that PR, though it may be that they share some underlying issue that #32117 works around.

**Comment by mrodozov** [comment] 2020-11-15 16:37
the problem

**Comment by dan131riley** [comment] 2021-01-12 15:52
We're also seeing testFWCoreConcurrency failing on slc7_aarch64_gcc9

```
===== Test "testFWCoreConcurrency" ====
Running ............./bin/sh: line 1: 241557 Segmentation fault      testFWCoreConcurrency
```

**Comment by dan131riley** [comment] 2021-01-12 17:55
We're also seeing intermittent crashes in InputTag_t on slc7_aarch64_gcc9, which is how #32649 came about (I don't expect the PR to fix the unit test, but it at least simplifies things a bit).
```
===== Test "InputTag_t" ====
/bin/sh: line 1: 31127 Segmentation fault      InputTag_t
```

**Comment by makortel** [comment] 2024-09-16 19:15
Given that we have dropped PPC I would close this issue

**Comment by makortel** [comment] 2024-09-16 19:15
-core

**Comment by makortel** [comment] 2024-09-16 19:15
@cmsbuild, please close

**Closed by makortel** 2024-09-16 19:15 UTC
Labels: core-pending, pending-signatures
