### ISSUE TITLE
FactorizedJetCorrector returns incorrect JEC

### ISSUE THREAD

**Issue by aperloff** [cms-sw/cmssw#13889] opened 2016-04-01 20:15 UTC
Hi,

I have noticed that the FactorizedJetCorrector is not returning the correct JEC factors since CMSSW_7_6_0. I have tested the code in CMSSW version 741, 750, 758_patch1, 760, 763, and 801. In the first three, the code returns the exact value we would expect, but in the last three releases the code returns some other number.

As far as I can tell the FactorizedJetCorrector relies on FactorizedJetCorrectorCalculator, which in turn uses the SimpleJetCorrector. This was updated by [1] and I think it was first integrated into CMSSW_7_6_0_pre7. The purpose was to move from TFormula to reco::FormulaEvaluator ([2]) in an effort to make the code thread safe.

To test the code I used the L2Relative JEC text file Spring16_25nsV1_MC_L2Relative_AK4PFl1.txt located at [3] and compared the value returned by the FactorizedJetCorrector for a jet of 10 GeV and eta 3.4. The value should be 1.25124, but was not after 76X. Instead 801 returned 5.72194. The ROOT file containing the original functions and their parameters (l2.root) can also be found at [3]. The exact sequence of commands I used can be found in [4].

If what I'm seeing is correct then this effects everyone who is correcting jets on-the-fly. Hopefully someone knows why this is happening and how to fix it.

Cheers,
Alexx Perloff

[1]
https://github.com/cms-sw/cmssw/commit/83aa62173a5849fad32fd05ee9f0d7c773a27ca2

[2]
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/CommonTools/Utils/interface/FormulaEvaluator.h

[3]
http://people.physics.tamu.edu/aperloff/CMS_JEC/forGitHubIssue/

[4]

```
root
JetCorrectorParameters * jcPar = new JetCorrectorParameters("Spring16_25nsV1_MC_L2Relative_AK4PFl1.txt")
vector<JetCorrectorParameters> vPar
vPar.push_back(*jcPar)
FactorizedJetCorrector* jcor = new FactorizedJetCorrector(vPar)
jcor->setJetPt(10)
jcor->setJetEta(3.4)
cout << jcor->getCorrection() << endl
```

**Comment by blinkseb** [comment] 2016-04-01 20:38
I can confirm the issue which is directly tracked down to `FormulaEvaluator`. I added this code snippet to `CommonTools/Utils/test/testFormulaEvaluator.cc`

```c++
{
    reco::FormulaEvaluator f("max(0.0001,[0]+[1]/(pow(log10(x),2)+[2])+[3]*exp([4]*(log10(x)-[5])*(log10(x)-[5])))");

    std::vector<double> x = {10.};

    std::vector<double> v = {0.88524, 28.4947, 4.89135, -19.0245, 0.0227809, -6.97308};
    std::vector<double> xValues = {10.};


    auto func =[&v](double x) {return std::max(0.0001,v[0]+v[1]/(std::pow(std::log(x)/std::log(10), 2)+v[2])+v[3]*std::exp(-1*v[4]*(std::log(x)/std::log(10)-v[5])*(std::log(x)/std::log(10)-v[5]))); };

    for(auto const xv: xValues) {
      x[0] = xv;
      std::cout << f.evaluate(x, v) << " =?= " << func(x[0]) << std::endl;
      
      CPPUNIT_ASSERT(compare(f.evaluate(x, v), func(x[0])));
    }
  }
```

C++ code returns `1.25124`, while `reco::FormulaEvaluator` returns `5.72194` (same numbers seen by Alexx).

Interestingly, `5.72194` corresponds to the first part of the formula, `std::max(0.0001,v[0]+v[1]/(std::pow(std::log(x)/std::log(10), 2)+v[2]))`. It seems like the parser ignore the last part of the formula.

Hope this helps

**Comment by slava77** [comment] 2016-04-01 20:43
@aperloff 
Is only the on-the-fly setup affected or do we get wrong corrections using jet corrector modules in CMSSW cmsRun jobs?
please clarify

I thought that the same FormulaEvaluator is used.

**Comment by blinkseb** [comment] 2016-04-01 20:52
@slava77 I'm afraid the whole JEC code is affected by this issue, since all the module basically ends using the FormulaEvaluator to evalue the formula.

It seems we get lucky in the past always using formula compatible with the FormulaEvaluator, but this one seems to trigger an incorrect behavior.

**Comment by slava77** [comment] 2016-04-01 20:57
@blinkseb 
Do I understand correctly, that at least this version of corrections was not yet used in miniAOD production?
(The one that corresponds to Spring16_25nsV1_MC_L2Relative_AK4PFl1.txt or the explicit implementation discussed here)

**Comment by blinkseb** [comment] 2016-04-01 20:59
Exactly, it's not used anywhere for the moment. It's in development for the new miniaod production, and the bug was found by @aperloff during validation.

**Comment by slava77** [comment] 2016-04-01 21:00
On 4/1/16 1:59 PM, Sébastien Brochet wrote:
> Exactly, it's not used anywhere for the moment. It's in development for
> the new miniaod production, and the bug was found by @aperloff
> <https://github.com/aperloff> during validation.
> 

OK, that's clear.
Disaster averted ;)

**Comment by Dr15Jones** [comment] 2016-04-01 22:38
I'm sure that you probably found a bug, however, the formula you passed to FormulaEvaluator is not the same one you evaluated with C++.  The C++ had
```
std::exp(-1*v[4]*(std::log(x)/std::log(10)-v[5])*(std::log(x)/std::log(10)-v[5])
```
but the formula evaluator was given
```
exp([4]*(log10(x)-[5])*(log10(x)-[5]))
```

Notice the missing '-1*' for the FormulaEvaluator. What is the actual formula that wasn't working?

**Comment by aperloff** [comment] 2016-04-01 22:41
The formula at the top of the text file ([1]) is:
max(0.0001,[0]+[1]/(pow(log10(x),2)+[2])+[3]*exp(-[4]*(log10(x)-[5])*(log10(x)-[5])))

[1]
http://people.physics.tamu.edu/aperloff/CMS_JEC/forGitHubIssue/Spring16_25nsV1_MC_L2Relative_AK4PFl1.txt

**Comment by Dr15Jones** [comment] 2016-04-02 03:00
assign core

**Comment by Dr15Jones** [comment] 2016-04-02 03:01
Fixed in #13890

**Comment by slava77** [comment] 2018-10-20 15:16
@aperloff @Dr15Jones 
this can be close now
(just to cleanup still open issues somewhat remotely related to reco).

**Comment by smuzaffar** [comment] 2019-04-27 22:35
+1

**Closed by smuzaffar** 2019-04-27 22:35 UTC
Labels: core-pending, pending-signatures
