### ISSUE TITLE
Wrong getNbins function in Utilities/RelMon

### ISSUE THREAD

**Issue by peruzzim** [cms-sw/cmssw#26496] opened 2019-04-18 12:30 UTC
The getNbins function in Utilities/RelMon/python/utils.py seems wrongly defined or used:

https://github.com/cms-sw/cmssw/blob/8c0b3deb7bf6fc4d0a30a6696fb3b0944316d0c4/Utilities/RelMon/python/utils.py#L92-L97

https://github.com/cms-sw/cmssw/blob/8c0b3deb7bf6fc4d0a30a6696fb3b0944316d0c4/Utilities/RelMon/python/utils.py#L330-L334

In this case, for instance, a 1-D histogram defined with N bins (excluding under/overflow) would give getNbins = N+1, and then range(0,N+3) which results in calling GetBinContent(N+2).

This breaks statistical tests in the same package (e.g. a file does not compare ok to itself using the BinToBin test). If you agree I can submit a PR to fix it.

**Comment by Dr15Jones** [comment] 2019-04-18 13:15
assign reconstruction

**Comment by slava77** [comment] 2019-04-18 13:20
reco is not really using relmon.
If someone will provide a fix, we'll review and sign.

**Comment by fabiocos** [comment] 2019-04-29 16:27
@peruzzim you seem to refer to the printout (nok vs ntot), not the final summary right? For what I can see the problem is in ```nbin+2```, that should be just nbin...

**Comment by fabiocos** [comment] 2019-04-30 14:48
@peruzzim the issue looks to me more complex, looking inside the code it seems to me that there is an inconsistent treatment of ranges. The second value in a range() function is the upper limit of the range *not included in the sequence* . So if we want to use 0 for the underflow and GetNbinsX()+1 for the overflow, the count of ok and total bins as it is now seems to me wrong. I am having a look at what to fix, but it seems to me there are several lines that should be modified...

**Comment by davidlange6** [comment] 2019-04-30 14:53
maybe @dpiparo still remembers this code?

**Comment by fabiocos** [comment] 2019-05-02 07:35
@davidlange6 looking at the function I think it is a matter to go systematically through the places where number of bins are used in loops and have all of them treated coherently. I am preparing a PR for this

**Comment by perrotta** [comment] 2019-05-10 05:18
+1
- Fixed with #26593

**Comment by dpiparo** [comment] 2019-05-10 06:39
@davidlange6 , saw this too late. Thanks for pinging me.

**Comment by fabiocos** [comment] 2019-05-10 07:30
@dpiparo in case have a look, I think that now the textual report is more consistent, while the histogram comparison should not be affected.

**Comment by dpiparo** [comment] 2019-05-21 15:31
@fabiocos , for me the changes are good to go (not following closely this repo yet, again, apologies for the delay in answering)

**Comment by fabiocos** [comment] 2019-05-23 07:27
@dpiparo thanks, as far as I can see this fix has removed a long list of warnings in the textual report.

**Closed** 2019-11-13 09:35 UTC
Labels: fully-signed, reconstruction-approved
