### ISSUE TITLE
`EgammaV/ConversionValidator` DQM ouptut is unstable in workflow 11634

### ISSUE THREAD

**Issue by schneiml** [cms-sw/cmssw#28072] opened 2019-09-26 11:01 UTC
While validating  #28042 I noticed that many plots in the `EgammaV/ConversionValidator` hierarchy are unstable in the PR tests. This seems to only affect workflow 11634, while the same plots seem stable in WF 11624 (which *only* exists in 10_6, while 11634 is *only* in 11?).

We could blacklist it, but this might point to a deeper problem somewhere else.

```
# voms-proxy-init required
WF=11634
ME=EgammaV/ConversionValidator/ConversionInfo/convEtaAss
curl -E /tmp/x509up_u$(id -u) https://cmsweb.cern.ch/dqm/dev/data/json/samples | python -m json.tool  | grep -o '"[^"]*'$WF'.*"' | tr -d '"' > datasets
echo "Got $(wc -l datasets)."
for d in $(cat datasets); do 
  echo -n $d ';'
  curl -E /tmp/x509up_u$(id -u) https://cmsweb.cern.ch/dqm/dev/jsonfairy/archive/1$d/$ME ; echo
done > mes
echo "ME did not change in (at least) $(grep -c unsupported mes) tests"
echo "ME did change in $(grep -c title mes) tests"
```

Says:
```
ME did not change in (at least) 703 tests
ME did change in 36 tests
```
for wf 11624, but 
```
ME did not change in (at least) 101 tests
ME did change in 54 tests
``` 
for wf 11634.

**Comment by Dr15Jones** [comment] 2019-09-26 11:46
assign dqm, reconstruction

**Comment by fabiocos** [comment] 2019-10-11 14:39
I believe that the first appearance of the issue in a merged PR is for #28011 , so I would say that the problem is present already in 11_0_0_pre9

**Comment by jfernan2** [comment] 2020-03-11 18:28
Hi, I believe this issue has been solved

**Comment by slava77** [comment] 2020-05-01 12:57
> Hi, I believe this issue has been solved

@jfernan2 
do you happen to know the origin of the fix?

**Comment by slava77** [comment] 2020-05-01 12:58
+1

this is apparently resolved, likely not related to reco in the end

**Comment by smuzaffar** [comment] 2020-06-03 09:06
this has been resolved

**Closed by smuzaffar** 2020-06-03 09:06 UTC
Labels: dqm-pending, pending-signatures, reconstruction-approved
