### ISSUE TITLE
Code still consumes CASTOR tags in Run-3 

### ISSUE THREAD

**Issue by tvami** [cms-sw/cmssw#36944] opened 2022-02-11 23:01 UTC
In https://github.com/cms-sw/cmssw/pull/36940
we discovered that the there is still some code that consumes CASTOR tags in Run-3.

https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-0f9c0d/22366/unitTests/src/DQM/Integration/test/TestDQMOnlineClient-ecal_dqm_sourceclient/testing.log
and
https://cmssdt.cern.ch/SDT/jenkins-artifacts/pull-request-integration/PR-0f9c0d/22366/unitTests/src/DQM/Integration/test/TestDQMOnlineClient-hlt_dqm_sourceclient/testing.log

```
----- Begin Fatal Exception 11-Feb-2022 22:50:25 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing global begin Run run: 344518
   [1] Prefetching for module EcalDQMonitorClient/'ecalMonitorClient'
   [2] Prefetching for EventSetup module CaloGeometryBuilder/''
   [3] Calling method for EventSetup module CastorGeometryFromDBEP/''
   [4] While getting dependent Record from Record CastorGeometryRecord
Exception Message:
No "PCastorRcd" record found in the EventSetup.

 Please add an ESSource or ESProducer that delivers such a record.
```

and
```
----- Begin Fatal Exception 11-Feb-2022 22:50:59 CET-----------------------
An exception of category 'NoRecord' occurred while
   [0] Processing global begin Run run: 344518
   [1] Prefetching for module HcalRecHitsAnalyzer/'hltHCALRecHitsAnalyzer'
   [2] Prefetching for EventSetup module CaloGeometryBuilder/''
   [3] Calling method for EventSetup module CastorGeometryFromDBEP/''
   [4] While getting dependent Record from Record CastorGeometryRecord
Exception Message:
No "PCastorRcd" record found in the EventSetup.

 Please add an ESSource or ESProducer that delivers such a record.
----- End Fatal Exception -------------------------------------------------
```

**Comment by tvami** [comment] 2022-02-11 23:02
assign dqm

**Comment by mmusich** [comment] 2022-02-12 08:15
isn't this a duplicate of the first part of https://github.com/cms-sw/cmssw/issues/36806#issue-1114945807 ?

**Comment by tvami** [comment] 2022-02-12 14:00
> isn't this a duplicate of the first part of [#36806 (comment)](https://github.com/cms-sw/cmssw/issues/36806#issue-1114945807) ?
> 
> seems to me something like:
> 
> ```diff
> diff --git a/DQM/Integration/python/clients/ecal_dqm_sourceclient-live_cfg.py b/DQM/Integration/python/clients/ecal_dqm_sourceclient-live_cfg.py
> index 43bf00c57aa..d2ccb842dd8 100644
> --- a/DQM/Integration/python/clients/ecal_dqm_sourceclient-live_cfg.py
> +++ b/DQM/Integration/python/clients/ecal_dqm_sourceclient-live_cfg.py
> @@ -3,7 +3,8 @@ import FWCore.ParameterSet.Config as cms
>  from EventFilter.OnlineMetaDataRawToDigi.tcdsRawToDigi_cfi import * # To monitor LHC status, e.g. to mask trigger primitives quality alarm during Cosmics
>  import sys
>  
> -process = cms.Process("process")
> +from Configuration.Eras.Era_Run3_cff import Run3
> +process = cms.Process("process", Run3)
>  
>  unitTest = False
>  if 'unitTest=True' in sys.argv:
> diff --git a/DQM/Integration/python/clients/hlt_dqm_sourceclient-live_cfg.py b/DQM/Integration/python/clients/hlt_dqm_sourceclient-live_cfg.py
> index 19d4a18a757..26462d10dbd 100644
> --- a/DQM/Integration/python/clients/hlt_dqm_sourceclient-live_cfg.py
> +++ b/DQM/Integration/python/clients/hlt_dqm_sourceclient-live_cfg.py
> @@ -1,8 +1,8 @@
>  import FWCore.ParameterSet.Config as cms
>  
>  import sys
> -from Configuration.ProcessModifiers.run2_HECollapse_2018_cff import run2_HECollapse_2018
> -process = cms.Process("DQM", run2_HECollapse_2018)
> +from Configuration.Eras.Era_Run3_cff import Run3
> +process = cms.Process("DQM", Run3)
>  
>  unitTest = False
>  if 'unitTest=True' in sys.argv:
> ```
> 
> on top of #36940 should solve.

Thanks Marco, I submitted this in this PR https://github.com/cms-sw/cmssw/pull/36946

**Comment by mmusich** [comment] 2022-02-12 14:08
> This error came up also in the Tier0 replay https://github.com/dmwm/T0/pull/4644#issuecomment-1037176514
with error:

I think a possible way of investigation is https://github.com/dmwm/T0/pull/4644#issuecomment-1037234924. 

This smells again like a stale era definition in the T0 configuration, given then Tamas' PR actually tests positively, setting a side the online DQM

**Closed** 2022-02-12 21:50 UTC
Labels: dqm-pending, pending-signatures

**Comment by jfernan2** [comment] 2022-02-13 15:42
+1
For the records
